### ISSUE TITLE
IntelliJ IDEA import fails with extra resolvers

### ISSUE THREAD

**Issue by benwaffle** [coursier/coursier#1001]
When IntelliJ runs 'dump project structure from sbt, it downloads all the libraryDependencies. When using sbt-coursier, it does not check extra repos defined with `resolvers in ThisBuild += "Jfrog" at "https://myorganization.jfrog.io/myorg/libs-release/"`. Coursier throws a `coursier.ResolutionException`.

**Comment by benwaffle** [comment]
also filed https://youtrack.jetbrains.com/issue/SCL-14810

**Comment by alexarchambault** [comment]
Closing for now. Feel free to re-open with more details. A reproduction solely from sbt (`sbt update`), and the detailed error message would help.
