### ISSUE TITLE
Rework the code to limit the probability to be blacklisted on central

### ISSUE THREAD

**Issue by rmannibucau** [coursier/coursier#1003]
Maven Central has some cleverness to blacklist crawlers. One of the detection part is the regular usage of directory listing. Since coursier uses it on a regular base it is quite easy to be blacklisted on central.

Goal of this issue is to align coursier usage on maven one (direct files + configurable caching with a default to "day") to ensure central is not that easily blacklisted due to coursier based builds.

See https://central.sonatype.org/articles/2018/Sep/06/403-forbidden-error-from-central/

**Comment by alexarchambault** [comment]
Recent versions of coursier shouldn't rely on directory listings anymore since https://github.com/coursier/coursier/commit/08d0375f7e0e413867b831414b0298146095dda2 (coursier `>= 1.1.0-M8`).

**Comment by rmannibucau** [comment]
What about https://github.com/coursier/coursier/blob/8c20ed54bf8df66bb7dc26a05d78667fe07f7072/modules/core/shared/src/main/scala/coursier/maven/MavenRepository.scala#L162 ? Can be replaced by metadata read I think.

**Comment by alexarchambault** [comment]
That particular are is very very seldom used. It's [only used](https://github.com/coursier/coursier/blob/8c20ed54bf8df66bb7dc26a05d78667fe07f7072/modules/core/shared/src/main/scala/coursier/maven/MavenRepository.scala#L355-L356) when depending on a version interval of an sbt plugin, so I don't think it can really lead to blacklisting on its own…

**Comment by rmannibucau** [comment]
Is it logged somehow? I didn't find where it is but if so it is ok for me.

**Comment by alexarchambault** [comment]
Yes:
```bash
$ coursier launch io.get-coursier:coursier-cli_2.12:1.1.0-M8 -- \
    fetch com.github.alexarchambault:case-app_2.12:2.0.0-M5 \
      --mode force </dev/null 2>&1 | grep '\/$'
$ coursier launch io.get-coursier:coursier-cli_2.12:1.1.0-M7 -- \
    fetch com.github.alexarchambault:case-app_2.12:2.0.0-M5 \
      --mode force </dev/null 2>&1 | grep '\/$'
Downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app_2.12/2.0.0-M5/
Downloaded https://repo1.maven.org/maven2/com/github/alexarchambault/case-app_2.12/2.0.0-M5/
Downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-util_2.12/2.0.0-M5/
Downloaded https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-util_2.12/2.0.0-M5/
Downloading https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/
Downloaded https://repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.7/
Downloading https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M5/
Downloaded https://repo1.maven.org/maven2/com/github/alexarchambault/case-app-annotations_2.12/2.0.0-M5/
Downloading https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.3/
Downloaded https://repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.3/
Downloading https://repo1.maven.org/maven2/org/typelevel/macro-compat_2.12/1.1.1/
Downloaded https://repo1.maven.org/maven2/org/typelevel/macro-compat_2.12/1.1.1/
```

**Comment by rmannibucau** [comment]
I was more looking for a WARN or something letting the user know he can be in a bad shape but maybe it requires to check it is targetting central cause not all repos have these blacklisting rules. Wdyt?

**Comment by alexarchambault** [comment]
Closing this. Directory listings are very seldomly relied upon now. Feel free to upon a PR or discuss further enhancements if you'd like.
