### ISSUE TITLE
Retrieving older or newer artifact than specified version

### ISSUE THREAD

**Issue by Sciss** [coursier/coursier#1016]
How can I resolve a dependency when I have a nominal version `x`, but there is no published artifact for that version, only an older version `y < x` or a newer version `y > x`. Is there a way to use something similar to those version ranges notation in Ivy?

**Comment by alexarchambault** [comment]
Yes, version ranges are supported, like
```
$ coursier resolve 'com.chuusai:shapeless_2.12:2.3+'
$ coursier resolve 'com.chuusai:shapeless_2.12:[2.3,2.4)' # only works with the current master, wait for 1.1.0-M14-4 or 1.1.0-M15
```
