### ISSUE TITLE
Broken link on get-coursier.io page

### ISSUE THREAD

**Issue by atisvagyok** [coursier/coursier#1019]
I just noticed there is a broken link in the footer of https://get-coursier.io. 'Quick start' points to https://get-coursier.io/docs/intro.html but it's a 404.

https://github.com/coursier/coursier/blob/23ccd4763325223633fccb80ab983303bd1bad65/doc/website/core/Footer.js#L37

I guess that should be something like ```<a href={this.docUrl('overview')}>```

**Comment by alexarchambault** [comment]
Indeed, thanks!
