### ISSUE TITLE
coursier binary in root directory not updated

### ISSUE THREAD

**Issue by kiendang** [coursier/coursier#1033]
Looks like the `coursier` binary in root directory hasn't been updated to v1.1.0-M10 yet, making v1.1.0-M10 not available through homebrew.

**Comment by alexarchambault** [comment]
Its location [just changed](https://get-coursier.io/blog/index.html#new-launcher-url). I'm going to have the launcher embed the completions, so that referencing the main git repository isn't needed in the brew formula.

**Comment by kiendang** [comment]
I see. Thank you!
