### ISSUE TITLE
Support for authentication with ivy repositories

### ISSUE THREAD

**Issue by jgogstad** [coursier/coursier#1050]
Hi,

I'm trying to use a private ivy repository with `coursier bootstrap`, is authentication supported yet?

I'm able to work around it by embedding the credentials in the URL, but it's unideal as it shows up in the console.

```
$ coursier bootstrap --native mygroup:app_native0.3_2.11:0.1.7 -r ivy2local -r ivy:https://nexus.example.com/repository/aggregate/ -o app
Error:
  mygroup:app_native0.3_2.11:0.1.7
    No fallback URL found
    not found: userhome/.ivy2/local/mygroup/app_native0.3_2.11/0.1.7/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/mygroup/app_native0.3_2.11/0.1.7/app_native0.3_2.11-0.1.7.pom
    not found: userhome/.ivy2/local/mygroup/app_native0.3_2.11/0.1.7/ivys/ivy.xml
    unauthorized: https://nexus.example.com/repository/aggregate/
```

The last "unauthorized" line makes me think coursier doesn't pick up the credentials in `~/.ivy2/.credentials`. Is that correct?

**Comment by alexarchambault** [comment]
coursier doesn't read `~/.ivy2/.credentials`, yes. For now, you can pass credentials on the command line, like
```
$ coursier bootstrap -r ivy:https://user:pass@nexus.example.com/repository/aggregate
```

There's also a new way to pass those in master (without putting them in a URL), about to be documented.
