### ISSUE TITLE
Passing properties trough java opts breaks bootstrap

### ISSUE THREAD

**Issue by voidcontext** [coursier/coursier#1056]
Passing a `--java-opt` breaks bootstrap on the current master branch, after `sbt clean cli/pack`:

Example behaviour:

```zsh
λ gaborpihaj [Workspace/private/coursier] at master
→ modules/cli/target/pack/bin/coursier bootstrap io.get-coursier:echo:1.0.1 -o echo
λ gaborpihaj [Workspace/private/coursier] at master
→ ls -l echo
-rwxr-xr-x  1 gaborpihaj  staff    18K 11 Feb 18:43 echo                                                                                                                             
```

Broken behaviour:

```zsh
→ modules/cli/target/pack/bin/coursier bootstrap --java-opt -Dfoo=bar io.get-coursier:echo:1.0.1 -o echo

Cannot find default main class. Specify one with -M or --main.
```

**Comment by alexarchambault** [comment]
That originates from https://github.com/xerial/sbt-pack/pull/118/files, that makes the sbt-pack based launcher pass the `-D` options to Java rather than the launched application. The coursier launcher itself, once packaged, is fine.

**Comment by voidcontext** [comment]
Indeed, after publishing the package locally and assembling it with the stable coursier it started working. @alexarchambault thanks for the help!
