### ISSUE TITLE
ResolutionException when building mesosphere marathon using artifactory proxy -- ${packaging.type} 

### ISSUE THREAD

**Issue by fikovnik** [coursier/coursier#1063]
I have set up an artifactory proxy at our lab (available at `prl4:8081`). When I try to build [mesosphere marathon](https://github.com/mesosphere/marathon) (it uses coursier 1.0.3) I get the following error:

```
[error] coursier.ResolutionException: 1 download error
[error]     Caught java.io.IOException: Server returned HTTP response code: 400 for URL: http://prl4:8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type} (Server returned HTTP response code: 400 for URL: http://prl4:8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}) while downloading http://prl4:8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}
[error] (update) coursier.ResolutionException: 1 download error
[error]     Caught java.io.IOException: Server returned HTTP response code: 400 for URL: http://prl4:8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type} (Server returned HTTP response code: 400 for URL: http://prl4:8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}) while downloading http://prl4:8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}
```

If I build it without the proxy it works.

When I look at what the coursier fetches in the two cases I see that in the case of without artifactory, it additionally creates the following file:

```
$ ls /home/krikava/.cache/coursier/v1/https/repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1
...
.javax.ws.rs-api-2.1.%24{packaging.type}.error
...
```

If I copy that file into the local coursier cache for artifactory:
```
/home/krikava/.cache/coursier/v1/http/prl4%3A8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1
```
it continues to work.

I double checked, but both requests:

- https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.$%7Bpackaging.type%7D
- http://prl4:8081/artifactory/mvn-releases/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.$%7Bpackaging.type%7D

do return HTTP 404. Why does coursier report HTTP 400?

Is there something I need to set up specifically in artifactory?

**Comment by alexarchambault** [comment]
Did you try with the latest sbt-coursier (`1.1.0-M11`)?

I'm not sure about the 400 error code, but the `${packaging.type}` in URLs don't look good… (and related things changed in more recent versions of coursier).

**Comment by fikovnik** [comment]
I cannot really change the build definition. I simply clone projects and then attempt to build them extracting data from Scala compiler. The weird thing is the `.javax.ws.rs-api-2.1.%24{packaging.type}.error` file - simply creating it in the coursier cache directory makes it work.

**Comment by 2m** [comment]
I get a similar error:
```
sbt:alpakka-kafka> tests/Test/compile
[error] java.net.URISyntaxException: Illegal character in path at index 88: https://repo1.maven.org/maven2/javax/ws/rs/javax.ws.rs-api/2.1.1/javax.ws.rs-api-2.1.1.${packaging.type}
[error]         at java.base/java.net.URI$Parser.fail(URI.java:2915)
[error]         at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
[error]         at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
```

when trying to compile tests in the current https://github.com/akka/alpakka-kafka/ master

Using latest sbt-coursier plugin `1.1.0-M14-4`

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/1213 should fix that (thanks for the repro, @2m!)

**Comment by 2m** [comment]
Thank you for fixing this so quickly. How would it be possible to use coursier with this fix in sbt?

**Comment by 2m** [comment]
I was able to release sbt-coursier locally and it works great! :)
