### ISSUE TITLE
ResolutionException for dynamic versions for major = 0

### ISSUE THREAD

**Issue by dvirf1** [coursier/coursier#1069]
Following a gitter message, this is probably a better place.

I was playing around with coursier and stumbled on a weird behavior:
After creating a toy project with `sbt new scala/scala-seed.g8` and adding `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M11")` to a `project/plugins.sbt` file, I added two libraries to my build.sbt (just to play around):

```
libraryDependencies += "com.softwaremill.macwire" %% "macros" % "2.+"
libraryDependencies += "com.github.pureconfig" %% "pureconfig" % "0.+"
```

When I enter the sbt shell and execute update I get a ResolutionException (will post in the end of this message).

The weird thing is that it seems that I only get it for libraries with major version 0.

e.g I get this error for `"com.github.pureconfig" %% "pureconfig" % "0.+"`, but when I comment it out and only bring macwire everything works.

If I specify some minor version for pureconfig, everything works too. e.g:
```
libraryDependencies += "com.softwaremill.macwire" %% "macros" % "2.+"
libraryDependencies += "com.github.pureconfig" %% "pureconfig" % "0.10.+"
```

Here is the error with the ResolutionException:
> sbt:Scala Seed Project> update
[info] Updating root
[info] Resolved root dependencies
[error] coursier.lmcoursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error] com.github.pureconfig:pureconfig_2.12:[0,1-a1):
[error] not found:
[error] /Users/dvir/.ivy2/local/com.github.pureconfig/pureconfig_2.12/[0,1-a1)/ivys/ivy.xml
[error] https://repo1.maven.org/maven2/com/github/pureconfig/pureconfig_2.12/%5B0,1-a1)/pureconfig_2.12-%5B0,1-a1).pom
[error] (coursierResolutions) coursier.lmcoursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error] com.github.pureconfig:pureconfig_2.12:[0,1-a1):
[error] not found:
[error] /Users/dvir/.ivy2/local/com.github.pureconfig/pureconfig_2.12/[0,1-a1)/ivys/ivy.xml
[error] https://repo1.maven.org/maven2/com/github/pureconfig/pureconfig_2.12/%5B0,1-a1)/pureconfig_2.12-%5B0,1-a1).pom
[error] Total time: 3 s, completed Feb 19, 2019 6:53:40 PM

**Comment by alexarchambault** [comment]
Closing this, related things were fixed recently, and this now seems to work fine with sbt-coursier `1.1.0-M14-3`. Re-open if that's not fixed on your end.
