### ISSUE TITLE
COURSIER_TTL environment variable and SNAPSHOTs

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [coursier/coursier#1095]
I don't want my snapshots dependencies to be automatically re-fetched, because untested.
I'm an Ammonite script user.
Ammonite brings dependencies through Coursier.

I'm doing this:
```
$ export COURSIER_TTL=Inf
$ amm
Welcome to the Ammonite Repl 1.3.3
(Scala 2.12.7 Java 1.8.0_201)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ interp.repositories() ++= Seq(coursier.MavenRepository("https://oss.sonatype.org/content/repositories/snapshots")) 

@ import $ivy.`com.sikulix:sikulixapi:1.1.4-SNAPSHOT` 
https://oss.sonatype.org/content/repositories/snapshots/com/sikulix/sikulixapi/1.1.4-SNAPSHOT/maven-metadata.xml
  100.0% [##########] 1.5 KiB (3.6 KiB / s)
https://oss.sonatype.org/content/repositories/snapshots/com/sikulix/sikulixapi/1.1.4-SNAPSHOT/sikulixapi-1.1.4-2019032?
  100.0% [##########] 5.4 KiB (26.4 KiB / s)
.....
```
It downloads the newer version, even though it has cached earlier version in `~/.cache/coursier`.
The `COURSIER_TTL` environment variable seems not to work.
Is this a bug?
How can I avoid redownloading snapshots?

[Associated doc](https://get-coursier.io/docs/ttl).

BTW, the documentation is missing the use of the Java system property called `coursier.ttl`for setting TTL default value.

**Comment by DavidPerezIngeniero** [comment]
Contents of `IvyThing.scala` in `Ammonite`:
```coursier.Fetch()
      .addDependencies(dependencies: _*)
      .withRepositories(repositories)
      .withCache(
        FileCache()
          .withLogger(if (verbose) RefreshLogger.create() else CacheLogger.nop)
      )
      .withMainArtifacts()
      .addClassifiers(Classifier.sources)
```
It controls how Coursier is used.

**Comment by DavidPerezIngeniero** [comment]
Is this a bug or a misinterpretation?

**Comment by alexarchambault** [comment]
Seems it works fine / as expected with recent Ammonite versions (`1.6.8`, maybe earlier too). Re-open if that's not fixed for you.

**Comment by DavidPerezIngeniero** [comment]
I had found a workaround.
I'll try it and let you know, because the `COURSIER_TTL` solution is cleaner.

**Comment by DavidPerezIngeniero** [comment]
Tried Ammonite version 1.6.8 and it doesn't try to redonwload `sikulixapi:1.1.4-SNAPSHOT`.  It only redownloads `https://oss.sonatype.org/content/repositories/snapshots/com/sikulix/sikulix2tigervnc/2.0....`

This is much better behavior than before.
