### ISSUE TITLE
excludeDependencies doesn't prevent graph expansion?

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1128]
## steps

I found this during sbt's `scripted watch/dynamic-inputs`, but likely any build using recent sbt 1.3.0 nightly.

Putting the following to `project/plugins.sbt` may show some evidence.

```scala
Compile / scalacOptions += "-Ylog-classpath"
```

In `develop` branch of sbt, the meta build excludes the resolution of sbt itself to avoid double resolution of sbt artifacts.

## problem

I see sbt modules resolved as transitive dependency of the plugin.

## expectation

sbt modules are excluded from the graph.

## notes

This might be related to https://github.com/coursier/coursier/issues/1122 and https://github.com/coursier/coursier/issues/853.

**Comment by eed3si9n** [comment]
Using `allExcludeDependencies` didn't help for my case. I do have an odd situation where sbt is included as a direct dependency (so it will be in the POM or `ivy.xml`), but I am trying to exclude it during resolution.

A simple reproduction is as follows using CLI:

```
$ coursier resolve -t com.chuusai:shapeless_2.12:2.3.3 -E com.chuusai:shapeless_2.12
  Result:
└─ com.chuusai:shapeless_2.12:2.3.3
   ├─ org.scala-lang:scala-library:2.12.4
   └─ org.typelevel:macro-compat_2.12:1.1.1
      └─ org.scala-lang:scala-library:2.12.0 -> 2.12.4
```

**Comment by alexarchambault** [comment]
@eed3si9n https://github.com/coursier/coursier/pull/1151 (plus using it from the sbt-coursier repo) should fix that.

**Comment by eed3si9n** [comment]
@alexarchambault Nice. Looking forward to trying that out.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/1151 I think.

**Comment by eed3si9n** [comment]
```
$ coursier --help
Coursier 2.0.0-RC3-4
Usage: coursier [options] [command] [command-options]

Available commands: bootstrap, complete, fetch, install, install-path, launch, publish, resolve, sonatype, spark-submit, update

Type  coursier command --help  for help on an individual command
$ coursier resolve -t com.chuusai:shapeless_2.12:2.3.3 -E com.chuusai:shapeless_2.12
  Result:
└─ com.chuusai:shapeless_2.12:2.3.3
   ├─ org.scala-lang:scala-library:2.12.4
   └─ org.typelevel:macro-compat_2.12:1.1.1
      └─ org.scala-lang:scala-library:2.12.0 -> 2.12.4
```

It looks like shapeless is still being resolved even though I am telling it to exclude it from graph expansion.
