### ISSUE TITLE
Add integration tests for the SBT plugin

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#114]
Try to build and run the tests of a few projects (cats, http4s, refined, circe, Ammonite, ...) with the plugin enabled globally.

**Comment by benmccann** [comment]
You're probably already aware, but just in case... Most sbt plugins use "scripted" for integration tests: http://eed3si9n.com/testing-sbt-plugins

**Comment by alexarchambault** [comment]
@benmccann Yeah, so does coursier: https://github.com/alexarchambault/coursier/tree/master/plugin/src/sbt-test/sbt-coursier ;-)

That issue is for more high level integration tests, where existing projects out there would be checked against the coursier sbt plugin from master.

**Comment by alexarchambault** [comment]
The various scripted unit tests seem to actually have been enough…
