### ISSUE TITLE
Expose bootstrap command-line options for native linking 

### ISSUE THREAD

**Issue by olafurpg** [coursier/coursier#1146]
Currently, the `bootstrap --native` flag uses the `nativeMode := "release"` and `nativeCompileOptions := sn.Discover.compileOptions()` by default. It would be nice if it was possible to configure these values from the command-line with a syntax like this
```
coursier bootstrap <artifact> --native --native-mode debug --native-compile-options "-O2|foobar"
```

The `|` separated format for multiple compile options could be replaced with something better.

Related code: https://github.com/coursier/coursier/blob/889d3bb8241f2e357fbb94faa91fee43924d6986/modules/cli/src/main/scala-2.12/coursier/cli/util/Native.scala#L31

Motivation: the Scalafmt cli links with the latest Scala Native 0.3.9 but the performance is slower with `nativeMode := "release"` compared to debug.

**Comment by alexarchambault** [comment]
With the current state of https://github.com/coursier/coursier/pull/1147, that would be
```bash
$ coursier bootstrap <artifact> --native \
    --native-mode debug \
    --native-compile-option -O2 \
    --native-compile-option foobar
```
