### ISSUE TITLE
sbt.librarymanagement.ResolveException: unresolved dependency: io.get-coursier#sbt-coursier;1.1.0-M14-3: not found

### ISSUE THREAD

**Issue by antonkulaga** [coursier/coursier#1148]
For some reasons adding
```
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M14-3")
```
cannot resolve coursier

**Comment by alexarchambault** [comment]
I think that was because the versions of the sbt plugins of coursier, and those of coursier itself, don't necessarily correspond one-to-one. See [this page](https://github.com/coursier/sbt-coursier/releases) for the actual sbt plugin versions.
