### ISSUE TITLE
sbt-dependency-graph not working with sbt-lm-coursier

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1170]
Repro:
```bash
$ git clone https://github.com/scalacommunitybuild/akka-persistence-jdbc.git
$ cd akka-persistence-jdbc
$ git checkout 35977c34
$ mkdir -p project/project
$ cat > project/project/plugins.sbt << EOF
addSbtPlugin("io.get-coursier" % "sbt-lm-coursier" % "1.1.0-M14-2")
EOF
$ cat >> project/plugins.sbt << EOF
addSbtPlugin("net.virtual-void" % "sbt-dependency-graph" % "0.9.2")
addSbtCoursier
EOF
$ rm -rf $(find . -type d -name target)
$ sbt dependencyTree
…
[info] com.github.dnvriend:akka-persistence-jdbc_2.12:3.6.0-SNAPSHOT
[success] Total time: 0 s, completed …
```

It seems to work fine with `sbt-coursier` instead of `sbt-lm-coursier` (and when having neither sbt-coursier nor sbt-lm-coursier).

**Comment by alexarchambault** [comment]
The repro uses akka-persistence-jdbc (from https://github.com/coursier/sbt-launcher/issues/38), but it seems to happen for any project.

**Comment by alexarchambault** [comment]
This could be an issue with the [sbt support in sbt](https://github.com/sbt/sbt/pull/4614) (that relies on similar keys as sbt-lm-coursier).

**Comment by dwijnand** [comment]
> the [sbt support in sbt](https://github.com/sbt/sbt/pull/4614)

(😆)

**Comment by eed3si9n** [comment]
See also
- https://github.com/jrudolph/sbt-dependency-graph/issues/178
- https://github.com/sbt/sbt/issues/4706

> So the remaining problem with eviction is that it is not reported any more it seems
