### ISSUE TITLE
sbt-related tasks

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1174]
List of things that ought to be done before sbt `1.3.0` final

- [ ] add mima to the sbt-coursier repo, to prevent binary breakages for the `lm-coursier-shaded` module (that sbt depends on)
- [ ] allow to replace `lm-coursier-shaded` by `lm-coursier` in the [coursier-based sbt launcher](https://github.com/coursier/sbt-launcher), so that one can safely add sbt-coursier in sbt 1.3.x

**Comment by alexarchambault** [comment]
FYI @eed3si9n (don't release sbt 1.3.0 final until this is done, and sbt depends on a version of lm-coursier-shaded with that).

**Comment by eed3si9n** [comment]
What should we do about MiMa? coursier/sbt-coursier#69 and coursier/sbt-coursier#73 are merged, but it won't actually run MiMa until there's a non-milestone build. https://github.com/coursier/sbt-coursier/blob/bed2d2dd28056558404e153247a37fa28809f15f/project/Mima.scala#L9-L13

On Gitter you said:

> once coursier/sbt-coursier#73 is in a release (next release of the sbt-coursier repo), this should be  fine to depend on from a sbt stable release

**Comment by alexarchambault** [comment]
Yes, that issue can be closed. @eed3si9n Want me to cut a release with https://github.com/coursier/sbt-coursier/pull/73?

**Comment by eed3si9n** [comment]
That would be awesome.

**Comment by alexarchambault** [comment]
Ok, I just tagged [`1.1.0-M14-4`](https://github.com/coursier/sbt-coursier/releases/tag/v1.1.0-M14-4). It should be released from [there](https://travis-ci.org/coursier/sbt-coursier/builds/538858452). Feel free to re-start any of its tasks yourself, if you think any failed because of transient errors.
