### ISSUE TITLE
pom files of dependencies in the local .m2 repo gets deleted

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1178]
This was reported by @felher originally as https://github.com/sbt/sbt/issues/4709.

The report uses sbt 1.3.0-RC1, but I was also able to reproduce the issue using sbt 1.2.8 combined with 

```scala
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.1.0-M13-4")
```

in `project/plugins.sbt` as well.

### steps
I attached a zip containing three things:
- a folder with a mini project, configured to show the problem
- a folder containing sample dependencies
- a docker file setting up a minimal, fresh system to show the problem (of course, you don't have to use the docker file. You can do everything locally, too)

I'm sorry the file is 17MB big, but I wanted to use the real dependencies I used and within in the folder were a few other dependencies.

To test it with a docker file, do the following in the root of demo folder after unzipping:
```
docker build -t felher/sbtrep:latest . # build the test system image
docker run --rm -ti felher/sbtrep:latest /bin/bash # start into the test system
ll /root/.m2/repository/de/uniwuerzburg/informatik/is/juriparser/juriparser/1.0/juriparser-1.0.pom #make sure the pom file is still there
cd /tmp/miniproject/ # change to the miniproject folder
sbt compile # start sbt and compile it. This takes a while, being a fresh install and all
ll /root/.m2/repository/de/uniwuerzburg/informatik/is/juriparser/juriparser/1.0/juriparser-1.0.pom  # now the pom file is gone.
```
You can also try it without using docker. Just unzip the file, copy the dependency folder to `~/.m2/repository/de/` and change into the miniproject folder and call `sbt compile` there.

### problem
After failing resolving the dependency, the .pom file got deleted.

### expectation
The dependency should have been found and the pom should not have been deleted.

### notes

sbt version: *1.3.0-RC1*. I also tried 1.0.1 and 1.2.8. Neither of them show this problem.
[sbtrep.zip](https://github.com/sbt/sbt/files/3195158/sbtrep.zip)

**Comment by alexarchambault** [comment]
Can be reproduced from the command-line, like
```bash
$ coursier
```

That originates from `sbtrep/uniwuerzburg/informatik/is/juriparser/juriparser/1.0/juriparser-1.0.pom` and its `.sha1` file not matching. [These lines](https://github.com/coursier/coursier/blob/cd2e83566091f98fa4558930192fd44ceacd8111/modules/cache/jvm/src/main/scala/coursier/cache/FileCache.scala#L725-L726) are then supposed to remove those (only the first one in released versions of coursier, both now in master).

Fix is just that the cache shouldn't delete files that aren't in its cache.
