### ISSUE TITLE
sbt-lm-coursier breaks the dotty build, seems to produce broken UpdateReports in some cases

### ISSUE THREAD

**Issue by smarter** [coursier/coursier#1181]
Discovered when testing sbt 1.3.0-RC1 but can be reproduced by adding:
```scala
addSbtPlugin("io.get-coursier" % "sbt-lm-coursier" % "1.1.0-M14-2")
```
To https://github.com/lampepfl/dotty/blob/master/project/plugins.sbt

```scala
> show dotty-compiler/scalaInstance
[error] java.lang.AssertionError: assertion failed: There should only be one ExactFilter(dotty-library_0.14) jar but found: Vector()
[error]         at scala.Predef$.assert(Predef.scala:219)
[error]         at dotty.tools.sbtplugin.DottyPlugin$.getJar(DottyPlugin.scala:388)
[error]         at dotty.tools.sbtplugin.DottyPlugin$.$anonfun$projectSettings$16(DottyPlugin.scala:282)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error]         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error]         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error]         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error]         at java.lang.Thread.run(Thread.java:748)
[error] (dotty-compiler / scalaInstance) java.lang.AssertionError: assertion failed: There should only be one ExactFilter(dotty-library_0.14) jar but found: Vector()
```

`getJar` is failing because the `UpdateReport` we got for `dottty-doc_0.14` is missing `dotty-library_0.14` (this is an artifact available on maven: https://repo1.maven.org/maven2/ch/epfl/lamp/dotty-doc_0.14/0.14.0-RC1/), the relevant code is:
https://github.com/lampepfl/dotty/blob/2b6c757adb3bba7d3eebfa0ac2e216ba63640698/sbt-dotty/src/dotty/tools/sbtplugin/DottyPlugin.scala#L267-L281

What's weird is that `dotty-library/scalaInstance` succeeds, and it should be running the exact same code asking for the UpdateReport of the same artifact, but somehow we get two different UpdateReports.

Working UpdateReport: https://gist.githubusercontent.com/smarter/35d3f854a0d1ca83ea219e1af15e2d7b/raw/a8977006eaab704a2b15439831beb0db58915342/working.txt
Broken UpdateReport: https://gist.githubusercontent.com/smarter/35d3f854a0d1ca83ea219e1af15e2d7b/raw/a8977006eaab704a2b15439831beb0db58915342/broken.txt

**Comment by alexarchambault** [comment]
A bisect gives https://github.com/lampepfl/dotty/commit/3db70e6f27966c2a954d5d944a2885c501fd380f as the first commit where it breaks.

**Comment by smarter** [comment]
Yes, because from that point on Dotty became a "regular" dotty project that uses the previous published version of dotty to compile itself, using sbt-dotty to get the correct scalaInstance.

**Comment by alexarchambault** [comment]
And simple projects with sbt-dotty `0.3.0` seem fine though (see [this scripted test](https://github.com/coursier/sbt-coursier/tree/master/modules/sbt-coursier/src/sbt-test/shared-1/dotty)).

**Comment by alexarchambault** [comment]
Paging @eed3si9n, who should know more about the way `dependencyResolver` is wired to the rest…

Basically, it works with the default ivy resolver, it works with sbt-coursier, but not with sbt-lm-coursier or sbt 1.3.0-RC1.

**Comment by smarter** [comment]
It seems that `dependencyResolver` is per-project, the `dotty-compiler` project depends on the `dotty-library` project, so maybe that has something to do with why trying to resolve `dotty-doc_0.14` using the dependencyResolver from `dotty-compiler` skips `dotty-library_0.14` somehow ? Is it possible to get a "clean" `dependencyResolver` that doesn't depend on whatever the current project is ?

**Comment by smarter** [comment]
I'm also happy to replace the use of dependencyResolver by some less crazy happy that doesn't require ten lines of boilerplate, but I'd rather not add other sbt plugins as dependencies to the sbt-dotty plugin.

**Comment by alexarchambault** [comment]
Ah yeah, `dependencyResolver` is tied to the current project for sure, with coursier (for `autoScalaLibrary`, `scalaModuleInfo`, `excludes`, …)

You can always create your own `CoursierDependencyResolution` (`lmcoursier.CoursierDependencyResolution(conf)`, with `conf: lmcoursier.CoursierConfiguration`), and use that.

**Comment by smarter** [comment]
Does that work in sbt 1.3 without plugins ?

**Comment by alexarchambault** [comment]
You mean `1.2`? You'll have to depend on `io.get-coursier::lm-coursier-shaded:1.1.0-M14-2`, which should be fine whatever the sbt version.

**Comment by alexarchambault** [comment]
`io.get-coursier::lm-coursier-shaded:1.1.0-M14-2` is around. It shades some coursier stuff internally, but that's it.

**Comment by smarter** [comment]
Hmm, so doesn't that mean that sbt plugins using the lmcoursier api in 1.3 will break if the user build also has the plugin for an incompatible version of lm-coursier enabled ?

**Comment by smarter** [comment]
For the record, when using sbt-lm-coursier, I can get the result I want (that is, the same behavior that I get without lm-coursier in sbt 1.2) by using `lmcoursier.CoursierDependencyResolution(coursierConfiguration.value..withInterProjectDependencies(Vector.empty))`.

**Comment by alexarchambault** [comment]
@smarter I'm about to enforce strict bin compat with mima for `lm-coursier-shaded`. Its surface area should be rather small. (Although beware I may change some of the classes it defines right before enforcing bin compat, precisely to make it easier to maintain bin compat later on.)

**Comment by smarter** [comment]
OK, then my main remaining problem is accessing `coursierConfiguration.value` from an sbt 1.3 plugin without adding a dependency. Could this task (https://github.com/coursier/sbt-coursier/blob/745894efc581e379ada1d8d7b6e62dcacd80b4a1/modules/sbt-lm-coursier/src/main/scala/coursier/sbtlmcoursier/LmCoursierPlugin.scala#L20) be moved to the `lmcoursier` package ?

**Comment by smarter** [comment]
> (Although beware I may change some of the classes it defines right before enforcing bin compat, precisely to make it easier to maintain bin compat later on.) 

As long as a bin compat version ships with sbt 1.3.0 I'm fine with that ;)

**Comment by alexarchambault** [comment]
Couldn't make your own `CoursierConfiguration` (like done [here](https://github.com/coursier/sbt-coursier/blob/745894efc581e379ada1d8d7b6e62dcacd80b4a1/modules/sbt-lm-coursier/src/main/scala/coursier/sbtlmcoursier/LmCoursierPlugin.scala#L109-L135)) be a solution? sbt 1.3 doesn't ship with sbt-lm-coursier, so that key isn't around (I guess it creates that configuration itself one way or another).

**Comment by smarter** [comment]
> Couldn't making your own CoursierConfiguration (like done here) be a solution?

Yes, but it's a lot of lines of code and sbt-dotty is too complicated already :p

> sbt 1.3 doesn't ship with sbt-lm-coursier, so that key isn't around (I guess it creates that configuration itself too, one way or another).

Thanks for the hint, indeed there is https://github.com/sbt/sbt/blob/a021528af43cf2af0235dade22dac333e1cca4b6/main/src/main/scala/sbt/Keys.scala#L329 but it's `private[sbt]` :(. And all of https://github.com/sbt/sbt/blob/develop/main/src/main/scala/sbt/internal/LMCoursier.scala is too. @eed3si9n, is there a reason for making all this stuff private ?

**Comment by eed3si9n** [comment]
> is there a reason for making all this stuff private ?

@smarter learning the lesson from the Ivy situation, I thought I should hide as much underlying implementations like third-party types from the plugin authors. If sbt goes the sbt-big route, all these might get re-shaded.

**Comment by smarter** [comment]
OK, but you're not actually hiding any type I care about here since everything from the lmcoursier package is available, instead you're hiding keys for tasks, and some of these tasks are important for dependency resolution (that's why they exist in  sbt-lm-coursier after all), so this is pretty unfortunate.

**Comment by eed3si9n** [comment]
This sounds kind of similar to a funny bug I had in sbt 1.3.0-M3 where I couldn't compile the compiler bridge for 2.11 only on sbt/zinc repository (https://github.com/sbt/sbt/issues/4669), and my fix was also to remove the inter-project resolver - https://github.com/sbt/sbt/pull/4670

**Comment by smarter** [comment]
Either `lmcoursier` is public API of sbt and it needs to be treated as such (bincompat, customizable via various keys), or it's private API and it needs to be shaded like the rest of coursier, and some other mechanism needs to be avaiable to customize dependency resolution. It seems that the current situation is an incomfortable middle-ground between those two things.

**Comment by eed3si9n** [comment]
bincompat seems to be coming soon according to https://github.com/coursier/coursier/issues/1174

Assuming that, I'd be happy to open up more knobs so we can allow plugin authors to create their own `dependencyResolution` instance like `LibraryManagement.dependencyResolutionTask.value` scoped to a task etc, and accompanying settings to change the resolvers, also scoped to a task etc.

**Comment by smarter** [comment]
Cool, I opened https://github.com/sbt/sbt/pull/4713.

**Comment by alexarchambault** [comment]
Seems we can close this, right?

**Comment by smarter** [comment]
In theory I should be able to work around the issue now (haven't had time to check this yet), but there's still a difference between sbt 1.2 and 1.3 behavior, I'll let you decide if that's worth investigating more.

**Comment by smarter** [comment]
Thanks! Can this get into sbt 1.3.0 ?
