### ISSUE TITLE
concurrent runs intermittently cause locking failures: java.io.FileNotFoundException

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1185]
This was originally reported by @SethTisue as https://github.com/sbt/sbt/issues/4723

I was running two instances of the Scala community build at the same time on my laptop, and in both runs, I had several projects fail with this error:

```
[akka] [error] java.io.FileNotFoundException: /Users/tisue/Library/Caches/Coursier/v1/.structure.lock (No such file or directory)
[akka] [error] 	at java.io.FileOutputStream.open0(Native Method)
[akka] [error] 	at java.io.FileOutputStream.open(FileOutputStream.java:270)
[akka] [error] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
[akka] [error] 	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
[akka] [error] 	at lmcoursier.internal.shaded.coursier.paths.CachePath.withStructureLock(CachePath.java:112)
[akka] [error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withStructureLock(CacheLocks.scala:20)
[akka] [error] 	at lmcoursier.internal.shaded.coursier.cache.CacheLocks$.withLockOr(CacheLocks.scala:34)
[akka] [error] 	at lmcoursier.internal.shaded.coursier.cache.FileCache.$anonfun$download$25(FileCache.scala:429)
[akka] [error] 	at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:658)
[akka] [error] 	at scala.util.Success.$anonfun$map$1(Try.scala:255)
[akka] [error] 	at scala.util.Success.map(Try.scala:213)
[akka] [error] 	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
[akka] [error] 	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
[akka] [error] 	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
[akka] [error] 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
[akka] [error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[akka] [error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[akka] [error] 	at java.lang.Thread.run(Thread.java:748)
[akka] [error] (update) java.io.FileNotFoundException: /Users/tisue/Library/Caches/Coursier/v1/.structure.lock (No such file or directory)
[akka] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

the affected projects were airframe, akka, coursier, github4s

log of the entire run: https://gist.github.com/SethTisue/af4544a5aa6eb263eef5a954a7777466

**Comment by alexarchambault** [comment]
I think I found the origin of the issue… Giving some details for the record.

That seems to be a (slightly more intricate) re-occurrence of https://github.com/coursier/coursier/issues/187, where the same kind of `FileNotFoundException` was seen, but for per-file locks (like `COURSIER_CACHE/v1/https/repo1.maven.org/maven2/org/scala-library/2.12.8/.scala-library-2.12.8.jar.lock`).

I wasn't really sure what was going on at the time of #187, but I now think it was [this race condition in `File.mkdirs`](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4742723). Two threads or processes where trying to create a directory, and one of the calls to `mkdirs` was returning early (before the directory even existed) as it found one of the parent as non existing, but couldn't create it either (as the other process just did concurrently). It seems `java.nio.file.Files.createDirectories` doesn't suffer this limitation.

The [initial fix](https://github.com/coursier/coursier/commit/83a08d172cffa85e23fefb9fa6c5fb1c9e59eca5) for #187 consisted in introducing a global lock, via `COURSIER_CACHE/v1/.structure.lock`, which was only held when creating sub-directories and lock files in the cache. But the directory of that lock (root of the coursier cache directory) needs itself to be created. Up to now, `mkdirs` was called for that, hence the error here. I guess most people must cache the coursier cache between CI runs, so the directory already exists, and we're only seeing this issue now.

**Comment by alexarchambault** [comment]
That said, if it happens several times in a row, it could also just mean it's a permission issue.

**Comment by alexarchambault** [comment]
Creating `/Users/tisue/Library/Caches/Coursier/v1` before running sbt could solve the issue (provided there's no permission issues either).

**Comment by alexarchambault** [comment]
Closing this for now. Re-open if the recent fixes ended up not addressing that.

**Comment by eatkins** [comment]
@alexarchambault I'm still seeing this with sbt 1.3.0-RC3. Here is a CI job that failed: https://travis-ci.org/eatkins/io/jobs/560269334.

**Comment by eatkins** [comment]
Oh, I think this is a different issue. I’ll open a new one.
