### ISSUE TITLE
Fails on Windows if powershell isn't available

### ISSUE THREAD

**Issue by hmemcpy** [coursier/coursier#1208]
I encountered a strange issue on Windows while trying to use metals-vscode: coursier would fail to download, terminating with a strange error I outlined in https://github.com/scalameta/metals-vscode/issues/116.

I was able to figure out and fix the issue - metals-vscode used the `spawn` API to launch a coursier command without passing it all of the environment variables.

Upon further investigation, it seems that a library coursier uses, directories-jvm, is [using powershell on Windows](https://github.com/coursier/directories-jvm/blob/35940596f53e04180c5e18b52ecc8aea6b8c85f4/src/main/java/io/github/soc/directories/Util.java#L117-L119) to try and detect Known Folder locations (specifically, Local and Roaming AppData dirs). 

It seems that powershell fails to fully start if some environment variables are missing, returning some warnings instead of the known folder paths (which explains the odd message I got in the metals-vscode issue).

Any reason to use powershell and not a native API, like e.g. JNA, to get the known folder locations?

**Comment by alexarchambault** [comment]
AFAIK, using jna would require adding some dependencies to directories-jvm. For now, as it's dependency-free, directories-jvm is embedded as is in the launchers that coursier generates via the `bootstrap` command. That includes the coursier launcher that can be downloaded at `https://git.io/coursier-cli`.

Depending on jna stuff would break that, or make the launchers much more heavyweight.

Don't know if that's the reason @soc went down this path, but it has advantages and works well this way for me.

**Comment by alexarchambault** [comment]
Wiping the env seems to have been the issue here. I'm not shocked that this breaks things somehow.

**Comment by hmemcpy** [comment]
Sure, this was just an idea. If it were really a problem, I'm sure this would have raised issues by now.
I'll close this.
