### ISSUE TITLE
Let user choose whether to use `-noverify` / consider changing default

### ISSUE THREAD

**Issue by retronym** [coursier/coursier#1244]
The coursier script currently [starts the JVM](https://github.com/coursier/coursier/blob/33873e769d3828255c4821269c4268486c2557ec/scripts/generate-launcher.sh#L18). with `-noverify`. I assume this is done to shave a little time off startup.

When this JVM is use for `launch`, this seems like an unsafe default to me -- unknown JARs really should be verified to avoid the risk of undefined behaviour at runtime.

I'd suggest making this configurable, and changing the default mode to leave the verifier enabled.

**Comment by alexarchambault** [comment]
This was required when a proguarded version of the cli module was published (for some time at least, not too sure right before that JAR stopped being published). But that proguarded JAR isn't published anymore, so this flag can be removed.
