### ISSUE TITLE
Standalone releases for v2.0.0+

### ISSUE THREAD

**Issue by jin** [coursier/coursier#1265]
`rules_jvm_external` makes use of the standalone jar for `v1.1.0`: https://github.com/bazelbuild/rules_jvm_external/blob/master/private/versions.bzl

However, it looks like the standalone jars aren't published for v2.0.0 onwards. Could they be published again please? It would greatly simplify `rules_jvm_external`'s coursier integration.

**Comment by alexarchambault** [comment]
There used to have a proguarded JAR of the cli being pushed to Central, but https://github.com/coursier/coursier/commit/089d5520581663eed7b47dbcaadd72024716ac85 discontinued it (using proguard could trigger its own class of bugs, so it kind of needed to be tested on the CI, but generating it there was taking around 10 minutes).

But a simple assembly could always be pushed there as a substitute. It's a bit more heavyweight (around 28 MB now), but generating it has very little overhead, so it would be fine generating it and testing it on the CI.

**Comment by jin** [comment]
I see, thank you for the explanation! An unproguarded binary is fine. From Bazel's perspective, this standalone binary can also be fetched from GitHub releases, so it doesn't need to be on Maven Central.

**Comment by jin** [comment]
Will this be available for the next 2.0.0 RC?

**Comment by alexarchambault** [comment]
@jin Would [GitHub release](https://github.com/coursier/coursier/releases) assets work fine for you? I'm planning on pushing more stuff there (graalvm launchers in particular), an assembly could be pushed along them.

**Comment by jin** [comment]
Yes, that'll work equally well. We're just downloading the standalone jar off a URL

**Comment by jin** [comment]
Woohoo thank you! We're now using v2.0.0-RC3. https://github.com/bazelbuild/rules_jvm_external/pull/215

**Comment by alexarchambault** [comment]
@jin FYI, I'm seeing some regressions with `2.0.0-RC3` and `2.0.0-RC3-1` (that https://github.com/coursier/coursier/pull/1305 should fix)… You may want to be cautious with those versions of the CLI. `2.0.0-RC3-2` is on its way.

**Comment by jin** [comment]
Thanks for the heads up. Are the standalone artifacts expected to be listed in [this release](https://github.com/coursier/coursier/releases/tag/v2.0.0-RC3-2)

**Comment by alexarchambault** [comment]
Yes, as soon as the CI is done building them.
