### ISSUE TITLE
What is the best way to call Coursier from Java code?

### ISSUE THREAD

**Issue by oferb** [coursier/coursier#1279]
<removed>

**Comment by alexarchambault** [comment]
@oferb I assume you found https://github.com/coursier/interface?

**Comment by oferb** [comment]
Nope, I just figured I can call Scala classes from Java code (I've never written any scala code, and this is the closest I've ever come to it :-) ).

What is `coursierapi`? I didn't see it in https://get-coursier.io/docs/api.
Looking at https://mvnrepository.com/artifact/io.get-coursier/interface, looks like it's a new addition from this year? :-)

**Comment by oferb** [comment]
Update: it's working for me :+1:
