### ISSUE TITLE
SCM info is missing in definitions

### ISSUE THREAD

**Issue by exoego** [coursier/coursier#1288]
I am working on https://github.com/fthomas/scala-steward/issues/82 to include a link to the upgraded project in the Scala Steward's PR.
I am using `coursier` to extract URLs of dependencies .

IIUC, `coursier` extracts `homePage` from `pom.xml`, but does not extract [SCM infos](https://maven.apache.org/scm/maven-scm-plugin/usage.html) currently.
https://github.com/coursier/coursier/blob/39d54c266db155a55eef11e2c1bac409d4ef1c1e/modules/core/shared/src/main/scala/coursier/core/Definitions.scala#L255-L261

`homePage` may be enough, but I think SCM info (URL to repository) is more useful, since it may use `Releases` pages that contain release note.

If adding SCM infos is acceptable, I am happy to open a PR.

**Comment by alexarchambault** [comment]
@exoego Sure, go ahead!
