### ISSUE TITLE
2.0.0-RC3 global credentials not used / unauthorized

### ISSUE THREAD

**Issue by francisdb** [coursier/coursier#1319]
upgraded sbt-coursier `1.0.2` to `2.0.0-RC3-2`

otherwise no changes to our build
credentials defined in `~/.sbt/1.0/global.sbt`

```
coursier.error.ResolutionError$CantDownloadModule: Error downloading com.my.company:jvm-metrics_2.12:2.9.2
[error]   Not found
[error]   Not found
...
[error]   unauthorized: https://nexus.server.host/repository/maven-releases/.../jvm-metrics_2.12/2.9.2/jvm-metrics_2.12-2.9.2.pom
```

**Comment by sbrunk** [comment]
I'm seeing the same behaviour. When upgrading from a working `1.1.0-M12` to `2.0.0-RC3-2`, I'm getting `unauthorized` errors from our private Nexus.

**Comment by alexarchambault** [comment]
@francisdb @sbrunk Are you able to reproduce that error from command-line? (see the examples [around here](https://get-coursier.io/docs/other-credentials)) That would help to know if the problems originates from coursier itself, or from its wiring with sbt.

**Comment by sbrunk** [comment]
@alexarchambault I'm getting `unauthorized` errors when using the coursier CLI as well. I tried with `COURSIER_CREDENTIALS` and a properties file without success.

Interestingly, it seems to work using the legacy method of specifying credentials as part of the host:
```bash
$ coursier fetch -r https://user:password@artifacts.foo.com/maven...
```

**Comment by jin** [comment]
+1, I can reproduce this in rules_jvm_external from the CLI.

**Comment by francisdb** [comment]
For a repo to test with see instructions here:
https://github.com/francisdb/sbt-plugin-test
(from linked sbt issue)

**Comment by leonardehrenfried** [comment]
I'm seeing this issue, too.

It worked in sbt 1.3.0-RC2 but not any version after that.

**Comment by leonardehrenfried** [comment]
I've been able to narrow down the versions where this problem started appearing.

The last working version of the sbt plugin was `1.1.0-M14`.

From version `2.0.0-RC2` onwards this problem appears.

If you look at the what happened [between those two tags](https://github.com/coursier/coursier/compare/v1.1.0-M14...v2.0.0-RC2) there are indeed a few commits that deal with credentials.

Could they be the problem?

**Comment by francisdb** [comment]
hehe, looks like @jsoref is beating me on this one. It's indeed the `WWW-Authenticate` header regex that does not match on the nexus header

https://github.com/coursier/coursier/blob/85f1fae0409cedff0d2f417c34d2103550de66c9/modules/cache/jvm/src/main/scala/coursier/cache/CacheUrl.scala#L384-L390

`BASIC realm="Sonatype Nexus Repository Manager"`

**Comment by hvesalai** [comment]
#1436 

Also seeing this

**Comment by pshirshov** [comment]
Same here on 2.0.0-RC5-2 and 2.0.0-RC5-6. Very annoying problem.

**Comment by dcsobral** [comment]
Oh, and I thought it was a github packages issue. I'm seeing this too: legacy mode works, nothing else does. With and without realm.
