### ISSUE TITLE
Can't set a custom repository

### ISSUE THREAD

**Issue by zoltanctoth** [coursier/coursier#1341]
Hi, 

I'm behind a firewall and have a maven mirror under `http://x.com/artifactory/maven`.
I am trying to run coursier, but right after downloading it it tries to connect to `repo1.maven.org`. That's cool, so I'm changing the repos the following way, but neither of these work:

```
COURSIER_REPOSITORIES="ivy2Local|http://x.com/artifactory/maven" ./coursier --no-default -r http://x.com/artifactory/maven help

cat ~/.config/coursier/mirror.properties
jcenter.from=https://repo1.maven.org/maven2
jcenter.to=http:/x.com/artifactory/maven
```

Any idea why this isn't working?

**Comment by zoltanctoth** [comment]
I've gotten an answer on gitter:
> that's the issue with the smaller coursier bootstrap usually. It only downloads coursier to start working. You need the full jar to make it working. Not sure where it is though.

**Comment by jin** [comment]
@zoltanctoth you can get the standalone jars in https://github.com/coursier/coursier/releases/tag/v2.0.0-RC3-3
