### ISSUE TITLE
dependencyOverrides still reported as evicted

### ISSUE THREAD

**Issue by jrduncans** [coursier/coursier#1342]
Related to #1278, tested using sbt-1.3.0-RC5. dependencyOverrides are taken into account in resolution, but are still being reported as evicted. See https://github.com/sbt/sbt/issues/5008

**Comment by dogonthehorizon** [comment]
I'm seeing this behavior with `sbt 1.3.3`

**Comment by anthonyemerson** [comment]
and 1.3.5
