### ISSUE TITLE
Some class not shaded in lm-coursier-shaded ?

### ISSUE THREAD

**Issue by chikei** [coursier/coursier#1393]
Exploring the jar of lm-coursier-shaded 2.0.0-RC3-4, the classes defined in lm-coursier module seems not getting shaded (class under `lmcoursier`, `lmcouriser.definitions`, etc.).

I don't know if this is intended, but since sbt-coursier plugin depends on lm-coursier, this could be the cause of https://github.com/sbt/sbt/issues/5144, https://github.com/sbt/sbt/issues/5040.

**Comment by alexarchambault** [comment]
Yes, that's intended. The shaded stuff are under `lmcoursier.internal.shaded`
