### ISSUE TITLE
System-wide sbt/Intellij IDEA cannot import coursier's sbt project

### ISSUE THREAD

**Issue by exoego** [coursier/coursier#1396]
It seems that current branch 0dde4226fad737ea0fa98f799c252db700e5fd50 cannot be compiled <del>on some environment</del> if system-wide installed sbt used.
`NoSuchMethodError` on every sbt sub projects.
```
[error] (bootstrap-launcher / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (okhttp / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (cacheJVM / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
[error] (utilJVM / coursierResolutions) java.lang.NoSuchMethodError: lmcoursier.definitions.ToCoursier$.project(Llmcoursier/definitions/Project;)Lcoursier/core/Project;
... all sub project
```

* Ubuntu
* JDK: JDK 1.8.0_222, 11.0.3

Due to this, Intelij IDEA also fails to import the sbt project.
I think this makes it difficult for Intellij users to contribute.

**Comment by fthomas** [comment]
I get the same errors when I'm using the system-wide installed sbt but it works fine when I'm using the sbt runner that is in the root directory of this repo.

**Comment by exoego** [comment]
Ah, correct.
I actually used system-wide installed sbt.
If I used the launcher, it worked !!

I think this is confusing, so I will make a PR to improve.

**Comment by exoego** [comment]
Addressed in #1406

**Comment by joprice** [comment]
I just hit the same thing, then tried the checked-in launcher, but got the error 

```
[error] Expected ';'
[error] -Xms512m
[error]
```

**Comment by joprice** [comment]
Looks like this has something to do with my `SBT_OPTS` env var, which starts with "-Xms512m". Not quite sure where the bash quoting goes wrong...
