### ISSUE TITLE
Windows 8: cache directory resolves to null/Coursier/v1 with system/virtual account

### ISSUE THREAD

**Issue by nigredo-tori** [coursier/coursier#1438]
This is a tricky one to minimize... This happens when building an SBT (1.3.3, coursier 2.0.0-RC3-4, AFAICT) project via a gitlab-runner (12.4.1) on Windows 8 under the system (`NT Authority\LocalSystem`) or virtual (`NT Service\gitlab-runner`) account. Coursier attempts to store its cache in `null/Coursier/v1` subfolder of the build folder, instead of `AppData/Local` for the corresponding account.

**Comment by nigredo-tori** [comment]
The account thing seems to be a red herring. The same thing seems to happen with a "vanilla" account. I've ran `sbt` in an empty project (with only a `project` folder), and it downloaded all the dependencies to the `null` folder.

**Comment by nightscape** [comment]
Same thing started happening for me on Windows 10 on an ordinary user account (not system/virtual).

**Comment by nigredo-tori** [comment]
This was earlier reported in the SBT repository: https://github.com/sbt/sbt/issues/5206.

**Comment by OlegYch** [comment]
it looks like this is caused by some change in jre - sbt works correctly under 8u131 but fails to use proper cache folder using 8u231

**Comment by eed3si9n** [comment]
See also https://github.com/soc/directories-jvm/issues/26

**Comment by OlegYch** [comment]
just a note - this also affects current scalafmt and scalafix, which surprisingly don't use coursier provided by sbt, even if used from it
