### ISSUE TITLE
Change in classpath ordering compared to Ivy

### ISSUE THREAD

**Issue by dwijnand** [coursier/coursier#1466]
I have a little sbt project reproducer that upgrading from sbt 1.2.8 to sbt 1.3.5 (and, therefore, to Coursier) changes the order of the dependencies, which in turn breaks the project.

**build.sbt**
```scala
scalaVersion in ThisBuild := "2.13.1"

libraryDependencies += "com.typesafe.play" %% "play-test" % "2.8.0-RC1" % Test
libraryDependencies += "org.scalatest"     %% "scalatest" % "3.0.8"     % Test
```

**src/test/scala/t/UnitSpec.scala**
```scala
import com.typesafe.config.ConfigFactory
import org.scalatest.{ MustMatchers, WordSpec }

class UnitSpec extends WordSpec with MustMatchers {
  def conf = ConfigFactory.defaultReference()

  "Config" should {
    "return Akka HTTP server provider" in {
      val serverProvider = conf.getString("play.server.provider")
      serverProvider mustBe "play.core.server.AkkaHttpServerProvider"
    }

    "be able to load Netty settings" in {
      val nettyTransport = conf.getString("play.server.netty.transport")
      nettyTransport mustBe "jdk"
    }
  }
}
```

Using sbt 1.2.8, all works as expected:

```
17:36:22 $ sbtx -Dsbt.version=1.2.8 test
[warn] sbt version mismatch, current: 1.2.8, in build.properties: "1.3.5", use 'reboot' to use the new value.
[info] Loading settings for project global-plugins from global-plugins.sbt ...
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/1.0/plugins
[info] Loading project definition from /s/t-sbt-cp-order/project
[info] Loading settings for project t-sbt-cp-order from build.sbt ...
[info] Set current project to t-sbt-cp-order (in build file:/s/t-sbt-cp-order/)
[info] UnitSpec:
[info] Config
[info] - should return Akka HTTP server provider
[info] - should be able to load Netty settings
[info] ScalaTest
[info] Run completed in 483 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 2 s, completed 17-Dec-2019 17:36:33
```

Using sbt 1.3.5, it fails:

```
17:37:11 $ sbtx -Dsbt.version=1.3.5 test
[info] Loading settings for project global-plugins from global-plugins.sbt ...
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/1.0/plugins
[info] Loading project definition from /s/t-sbt-cp-order/project
[info] Loading settings for project t-sbt-cp-order from build.sbt ...
[info] Set current project to t-sbt-cp-order (in build file:/s/t-sbt-cp-order/)
[info] UnitSpec:
[info] Config
[info] - should return Akka HTTP server provider *** FAILED ***
[info]   "play.core.server.[Netty]ServerProvider" was not equal to "play.core.server.[AkkaHttp]ServerProvider" (UnitSpec.scala:12)
[info] - should be able to load Netty settings
[info] ScalaTest
[info] Run completed in 480 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 1, failed 1, canceled 0, ignored 0, pending 0
[info] *** 1 TEST FAILED ***
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
[error] Failed tests:
[error] 	UnitSpec
[error] (Test / test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 2 s, completed 17-Dec-2019 17:37:21
```

Using sbt 1.3.5 without Coursier succeeds again:

```
17:37:46 $ sbtx -Dsbt.version=1.3.5 -Dsbt.coursier=false test
[info] Loading settings for project global-plugins from global-plugins.sbt ...
[info] Loading global plugins from /Users/dnw/.dotfiles/.sbt/1.0/plugins
[info] Loading project definition from /s/t-sbt-cp-order/project
[info] Loading settings for project t-sbt-cp-order from build.sbt ...
[info] Set current project to t-sbt-cp-order (in build file:/s/t-sbt-cp-order/)
[info] UnitSpec:
[info] Config
[info] - should return Akka HTTP server provider
[info] - should be able to load Netty settings
[info] ScalaTest
[info] Run completed in 441 milliseconds.
[info] Total number of tests run: 2
[info] Suites: completed 1, aborted 0
[info] Tests: succeeded 2, failed 0, canceled 0, ignored 0, pending 0
[info] All tests passed.
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2
[success] Total time: 2 s, completed 17-Dec-2019 17:37:56
```

Originally opened against sbt as https://github.com/sbt/sbt/issues/5282.

**Comment by alexarchambault** [comment]
Maybe it's time to [enable classpath ordering in lm-coursier](https://github.com/coursier/sbt-coursier/blob/a6c06c32aa9cff9e141b5b5fd2ee6397139393ad/modules/lm-coursier/src/main/scala/lmcoursier/internal/ArtifactsRun.scala#L38). Or to make that flag configurable.

I initially disabled it, when classpath ordering was still new, but it should be better now (the tests in coursier were migrated to it in particular).

**Comment by dwijnand** [comment]
Sounds good to me!

**Comment by dwijnand** [comment]
Shall I PR lm-coursier and just switch it?

**Comment by alexarchambault** [comment]
@dwijnand If you feel like sending a PR, go ahead. I was thinking of maybe adding a field for it in [`CoursierConfiguration`](https://github.com/coursier/sbt-coursier/blob/master/modules/lm-coursier/src/main/scala/lmcoursier/CoursierConfiguration.scala), defaulting to `true` I guess.

**Comment by dwijnand** [comment]
I should try to get this fix in before 2.0.0 comes out of RC cycle!!  (I wouldn't want 2.0.0 to be "stable" and this change not to be acceptable.)  Should I consider this urgent?  Do you have an idea of a timeline for 2.0.0?

**Comment by alexarchambault** [comment]
> Do you have an idea of a timeline for 2.0.0?

I'd like to cut `2.0.0` final this month.

**Comment by eed3si9n** [comment]
I think the most severe backward compatibility issue is https://github.com/coursier/coursier/issues/1382 where `Test` configuration can bleed into published `Compile` artifacts.

**Comment by dwijnand** [comment]
Tried a local sbt build with coursier/sbt-coursier#174, and this hasn't been fixed. 😢

@alexarchambault any advice on how to convert the reproduction into a test in sbt-coursier?

**Comment by alexarchambault** [comment]
@dwijnand The scripted tests of sbt-coursier live under [this directory](https://github.com/coursier/sbt-coursier/tree/master/modules/sbt-coursier/src/sbt-test). I guess this can be put there. I usually copy the `plugins.sbt` of [`shared-2/simple`](https://github.com/coursier/sbt-coursier/blob/master/modules/sbt-coursier/src/sbt-test/shared-2/simple/project/plugins.sbt) in new tests.

**Comment by alexarchambault** [comment]
These scripted tests are run by both sbt-coursier (the legacy plugin) and sbt-lm-coursier (using `dependencyResolution`, so closer to the coursier support of sbt).

**Comment by dwijnand** [comment]
OK.  Here's a variable I hadn't taken into account: the Scala version.

I've re-created my reproduction, but this time using sbt 1.3.7 (which includes my "classpath ordering" change - coursier/sbt-coursier#174) instead of a local build, and I eventually noticed that it:

* ✅ passed on 2.13 🎉 
* ❌ fails on 2.12 💩 

No idea why.  @alexarchambault any ideas why that would happen?  Differences in how `withClasspathOrder` is used or applied or something?  😖

**Comment by dwijnand** [comment]
Ran with Typesafe Config's `-Dconfig.trace=loads` and the distilled output is:

```
> +test
[info] Forcing Scala version to 2.12.10 on all projects.
Loading config from resource 'reference.conf' URL jar:file:/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-akka-http-server_2.12/2.8.0-RC1/play-akka-http-server_2.12-2.8.0-RC1.jar!/reference.conf from class loader sbt.internal.LayeredClassLoader@156c9734
Loading config from resource 'reference.conf' URL jar:file:/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.12/2.8.0-RC1/play-netty-server_2.12-2.8.0-RC1.jar!/reference.conf from class loader sbt.internal.LayeredClassLoader@156c9734
[info] Passed: Total 2, Failed 0, Errors 0, Passed 2

[info] Forcing Scala version to 2.13.1 on all projects.
Loading config from resource 'reference.conf' URL jar:file:/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.13/2.8.0-RC1/play-netty-server_2.13-2.8.0-RC1.jar!/reference.conf from class loader sbt.internal.LayeredClassLoader@1633f873
Loading config from resource 'reference.conf' URL jar:file:/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-akka-http-server_2.13/2.8.0-RC1/play-akka-http-server_2.13-2.8.0-RC1.jar!/reference.conf from class loader sbt.internal.LayeredClassLoader@1633f873
[info] Config
[info] - should return Akka HTTP server provider *** FAILED ***
[info]   "play.core.server.[Netty]ServerProvider" was not equal to "play.core.server.[AkkaHttp]ServerProvider" (UnitSpec.scala:12)
[error] Failed: Total 2, Failed 1, Errors 0, Passed 1
```

So it looks like the classloader is getting the resources in different orders.

I also took the outputs of:

* `cs fetch com.typesafe.play:play-test_2.12:2.8.0-RC1`
* `cs fetch com.typesafe.play:play-test_2.13:2.8.0-RC1`
* `cs fetch --classpath-order com.typesafe.play:play-test_2.12:2.8.0-RC1` and
* `cs fetch --classpath-order com.typesafe.play:play-test_2.13:2.8.0-RC1`

And the results are that only when using `--classpath-order` is the order the same.  Which leads me to believe that in sbt (even v1.3.7) it's not using "classpath order"?  I'll try to confirm.

**Comment by dwijnand** [comment]
Yeah the order without `--classpath-order` matches the order that `config.loads` gives:

```
##############
# Contents of: 2.12.no-cp-order.txt
##############
/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-akka-http-server_2.12/2.8.0-RC1/play-akka-http-server_2.12-2.8.0-RC1.jar
/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.12/2.8.0-RC1/play-netty-server_2.12-2.8.0-RC1.jar

##############
# Contents of: 2.13.no-cp-order.txt
##############
/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.13/2.8.0-RC1/play-netty-server_2.13-2.8.0-RC1.jar
/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-akka-http-server_2.13/2.8.0-RC1/play-akka-http-server_2.13-2.8.0-RC1.jar
```

So, again, it looks like sbt's not using "classpath ordering".

**Comment by dwijnand** [comment]
Another confirmation, from `fullClasspath`:

```
> +show Test/fullClasspath
[info] Forcing Scala version to 2.12.10 on all projects.
[info] * Attributed(/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-akka-http-server_2.12/2.8.0-RC1/play-akka-http-server_2.12-2.8.0-RC1.jar)
[info] * Attributed(/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.12/2.8.0-RC1/play-netty-server_2.12-2.8.0-RC1.jar)

[info] Forcing Scala version to 2.13.1 on all projects.
[info] * Attributed(/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-netty-server_2.13/2.8.0-RC1/play-netty-server_2.13-2.8.0-RC1.jar)
[info] * Attributed(/Users/dnw/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/typesafe/play/play-akka-http-server_2.13/2.8.0-RC1/play-akka-http-server_2.13-2.8.0-RC1.jar)
```

**Comment by alexarchambault** [comment]
Something I wanted to look at last time I looked at this issue is whether the logic in lm-coursier itself preserves the order that coursier gives it, when it generates the `UpdateReport`.

**Comment by dwijnand** [comment]
Yeah, I reached the same conclusion: https://github.com/coursier/sbt-coursier/blob/ab4fb3df0dd66c8fe7612f66352917c99be1afb3/modules/lm-coursier/src/main/scala/lmcoursier/internal/UpdateRun.scala#L60

It's using the order of resolution (`params.res`), ignoring the carefully preserved order of artifacts (`params.artifacts`/`params.artifactFileOpt`).

**Comment by dwijnand** [comment]
@alexarchambault I spent, like, 2 hours staring and navigating the code and couldn't figure out how this should be fixed.  Any pointers would be very welcome as they might unblock me to continue investigating and maybe even a fix.  Thanks!

**Comment by alexarchambault** [comment]
I think the problem lies in [`SbtUpdateReport.scala`](https://github.com/coursier/sbt-coursier/blob/64a0e6d2654251f0dcab3749c556d546fe4428f4/modules/lm-coursier/src/main/scala/lmcoursier/internal/SbtUpdateReport.scala). In particular, the [`moduleReports`](https://github.com/coursier/sbt-coursier/blob/64a0e6d2654251f0dcab3749c556d546fe4428f4/modules/lm-coursier/src/main/scala/lmcoursier/internal/SbtUpdateReport.scala#L133) method, that currently returns an `Iterable[ModuleReport]`, should return a `Seq[ModuleReport]` or a `Vector[ModuleReport]`, and not lose the order it gets from [calling](https://github.com/coursier/sbt-coursier/blob/64a0e6d2654251f0dcab3749c556d546fe4428f4/modules/lm-coursier/src/main/scala/lmcoursier/internal/SbtUpdateReport.scala#L144) `Resolution.dependencyArtifacts`. It should pass `classpathOrder = true` to it when needed too.

Then with classpath order, I think [`reports0` here](https://github.com/coursier/sbt-coursier/blob/64a0e6d2654251f0dcab3749c556d546fe4428f4/modules/lm-coursier/src/main/scala/lmcoursier/internal/SbtUpdateReport.scala#L286) is unnecessary (we'll always the right module upfront now).

And I don't know if we should manage to keep the order in [`details`](https://github.com/coursier/sbt-coursier/blob/64a0e6d2654251f0dcab3749c556d546fe4428f4/modules/lm-coursier/src/main/scala/lmcoursier/internal/SbtUpdateReport.scala#L330) too.

I can have a look at this later if you wish.

**Comment by dwijnand** [comment]
Ah, I see now.  Both lm-coursier's `ArtifactsRun` / coursier's `Artifacts` and lm-coursier's `SbtUpdateReport` use coursier's `Resolution`, but in `SbtUpdateReport` it's using the `false` default for `classpathOrder`.

I'll see if I can piece together something to fix this, thank you very much for the insights.

> I can have a look at this later if you wish.

But I might still need your help here if I get stuck. 😄

**Comment by alexarchambault** [comment]
Quick update about 
> I'd like to cut 2.0.0 final this month.

I think I will cut `2.0.0` next week, in spite of a few issues in lm-coursier (problems with `dependencyOverrides`, dependencies in the test configuration bumping versions in compile, etc.) The issues in lm-coursier can be addressed later / independently of what happens in the repository here. I think they shouldn't need changes in this repository in particular.

**Comment by dwijnand** [comment]
Good news: I release a local version of lm-coursier-shaded and a local version of sbt 1.3.x using it, and this is now fixed.

I learnt that `update`'s caching doesn't track lm-coursier-shaded's version, which is why it was initially looking still unfixed.

Thanks for your help, Alex!!
