### ISSUE TITLE
Unify cache directory across all OSes

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1483]
Ref https://github.com/coursier/coursier/issues/1438 / https://github.com/sbt/sbt/issues/5206
Ref https://github.com/sbt/sbt/issues/5120

## steps

Where's Coursier's cache?

## problem 

"It depends..."

## expectation

Let's change the default Coursier cache once and for all to a single location: **`$HOME/.cache/coursier/v1`**. For all operating systems.

(In my original description I had `$HOME/.coursier/cache/`. I meant the new `$HOME/.cache/coursier/`)

## notes

In theory, using something like directories-jvm and following the directory standard is a good idea, but it's messy in practice. If we _really_ want, I'd say only respect `$XDG_CACHE_HOME` nothing else.

**Comment by soc** [comment]
> only respect `$XDG_CACHE_HOME` nothing else

How would that work vs. `$HOME/.coursier/cache/v1`? You can't have both.

**Comment by eed3si9n** [comment]
@soc here's my proposal - https://github.com/coursier/coursier/pull/1484

**Comment by eed3si9n** [comment]
I just realized I typo'ed in the original proposal. I meant `$XDG_CACHE_HOME/coursier/v1` otherwise `$HOME/.cache/coursier/v1`.

**Comment by yanns** [comment]
I'd also agree to pick a single place.
I was testing on mac, and have not realized that the path was depending on the OS.
As a result, the cache was wrongly configured on the CI system.

**Comment by soc** [comment]
@eed3si9n I think any app ignoring operating system rules is being a really poor citizen and people are rightfully annoyed. (Just search for "XDG" on GitHub and read the hundreds of issues of users being annoyed of XDG being ignored, now add to that the people annoyed by ignoring macOS conventions and the people annoyed by ignoring Windows conventions).

All that said, dumping dotfiles in users' home folders on Windows is not nice, but doable (I actually only know of applications that stopped doing this. SBT would be the first that actively made things worse).

I would be more concerned about not following Apple's rules to be honest: I wouldn't take it for granted that applications can still indiscriminately dump their files all over the place in a few years.

To be honest, I don't really see the point in the change: the paths will still differ across operating systems even after this, and it just makes coursier a worse citizen on 2 of the 3 main platforms it runs on.

**Comment by dwijnand** [comment]
> but it's messy in practice

It's messy on Windows.  Or, maybe, on the JVM on Windows.  We should seek to improving that (e.g. https://github.com/soc/directories-jvm/pull/27), but I don't think we should use https://github.com/soc/directories-jvm/issues/26 as an excuse for going back to not following the OS's conventions.

Oh... @soc just posted roughly the same thing ^

**Comment by eed3si9n** [comment]
@soc @dwijnand I think it's a nature of writing an app on JVM. Supposedly the program is written against the Virtual Machine that abstracts all things OS, but we will also make various deals with the devil to get native things like putting color on the terminal or making IPC calls for the sake of improvements. In general respecting directory standards etc I think is a good thing.

For Coursier cache, though, I personally find it inconvenient that the location is not only OS-dependent it is "have you ran an older version" dependent because it will use `$HOME/.coursier/cache/`. As I do go back and forth between macOS, Linux, and Windows fairly frequently, I personally wish that the Coursier cache was in a single spot across all machines.

> I would be more concerned about not following Apple's rules to be honest: I wouldn't take it for granted that applications can still indiscriminately dump their files all over the place in a few years.

Coursier currently uses `$HOME/.cache` anyway. If we followed Apple's rules it should use `$HOME/Library/Caches` (or `$HOME/Library/Application Support` maybe?), but I can't imagine anyone wanting that.

Maybe the difference in the expectations comes from the word "cache." It is a cached data from the repositories, but unlike browser cache etc you actually don't want that to be cleared automatically (Debian says cache can [live in tmpfs](https://wiki.debian.org/XDGBaseDirectorySpecification)), and from the build's point of view they are part of the classpath. In terms of XDG, `XDG_DOWNLOAD_DIR` or `XDG_DATA_HOME` might have been a better fit.

**Comment by eed3si9n** [comment]
For the record
- sbt - https://github.com/sbt/sbt/issues/3681
- Gradle - https://github.com/gradle/gradle/issues/8262
  > We need to provide a familiar experience across all major platforms (Linux, macOS, Windows). ~/.gradle (GRADLE_USER_HOME) does that for the most part.
- Maven - http://mail-archives.apache.org/mod_mbox/maven-dev/201703.mbox/%3c1490317166.3170386.921692584.444C7705@webmail.messagingengine.com%3e
- Cargo - https://github.com/rust-lang/rfcs/pull/1615 (too long did not read, but looks interesting)

**Comment by soc** [comment]
> Coursier currently uses $HOME/.cache anyway. If we followed Apple's rules it should use $HOME/Library/Caches [...]

If Coursier hasn't added custom code special-casing macOS, that's exactly what's happening.

> you actually don't want that to be cleared automatically

I think you are mixing up XDG_CACHE_HOME with XDG_RUNTIME_DIR.

The former is the correct place for everything retrieved from remote repositories.
(Ideally locally published artifacts would be put in XDG_DATA_HOME.)

The latter would be the ideal place for things like the sbt lock file.

**Comment by dwijnand** [comment]
> > Coursier currently uses $HOME/.cache anyway. If we followed Apple's rules it should use $HOME/Library/Caches [...]
> 
> If Coursier hasn't added custom code special-casing macOS, that's exactly what's happening.

Indeed.  See https://get-coursier.io/docs/cache.html#default-location, it uses `~/Library/Caches/Coursier/1` on macOS.

The "have you ran an older version" thing I can see was done so early Coursier users could avoid having to redownload everything again.  I don't see it as a great problem, but I'd be in favour of finding a way to complete that transition.

> As I do go back and forth between macOS, Linux, and Windows fairly frequently, I personally wish that the Coursier cache was in a single spot across all machines.

Yeah, that's the rub: you can either follow platform standards or have the same path.

**Comment by alexarchambault** [comment]
I agree that the support for `~/.coursier` is confusing at this point. I think I'm going to just remove it, and maybe add a command to help migrate it to the new location(s).

After that, the default location will only be the current OS-dependent one. I agree with @dwijnand and @soc's points, there's no reason to rollback now that we have proper OS-specific support. XDG conventions don't really make sense on Windows, and macOS locations are more likely future-proof.

The only drawback is with macOS CIs, yes, as @yanns says. I've been bitten by that too :) It's not reason enough to switch to XDG on macOS IMO. (OS-specific directories make us a better citizen on macOS.)

**Comment by alexarchambault** [comment]
About https://github.com/gradle/gradle/issues/8262, it seems they don't use OS-specific locations because: they want to retain support for a single gradle "home" directory, and cost of migration. Both of these points don't apply for us.

About https://github.com/rust-lang/rfcs/pull/1615, it seems [there's no opposition of principle to OS-specific directories](https://github.com/rust-lang/cargo/pull/5183#issuecomment-513337833). It just needs more work, to make the migration easier in particular.

**Comment by soc** [comment]
> About rust-lang/rfcs#1615, it seems there's no opposition of principle to OS-specific directories. It just needs more work, to make the migration easier in particular.

You are right. It's partially my fault (see https://github.com/rust-lang/cargo/pull/5183#issuecomment-478336916), but in Rust's case the change really needs some maintainer-level buy-in as it affects a lot of components where the change would need to be applied in lock-step.

**Comment by eed3si9n** [comment]
I read through most of the Cargo RFC comments last night. It seems like the majority of the users are into it while the technical concern was more to do with where to install things and how multiple programs coordinate during transition? I had no idea @soc was involved the implementation effort.

> XDG conventions don't really make sense on Windows, and macOS locations are more likely future-proof.

Lots of people use sbt or coursier from Bash for Git, Cygwin, and Windows Subsystem for Linux. Aren't these basically Un*x/GNU environment on Windows?

**Comment by olafurpg** [comment]
If the goal is to simplify caching in CI, would it be an acceptable workaround to ask users to set the environment variable `COURSIER_CACHE=$HOME/.cache/coursier`?

**Comment by ScalaWilliam** [comment]
Sorry to chime in so late @alexarchambault , wouldn't it be easiest if there was a command to just **get** the location of the cache straight from the command line rather than having to go to the docs? It might be there but I didn't see it in the docs.

**Comment by alexarchambault** [comment]
@ScalaWilliam It'd be great to have such an option, yes. Maybe the current [`get`](https://github.com/coursier/coursier/blob/bbc251e2b5be3dca415cbc335ff9c848256c7438/modules/cli/src/main/scala/coursier/cli/get/Get.scala) could be renamed to `cache`, and a `--location` option added.

I can give slightly more detailed instructions, if you're interested in taking a cut at it.

**Comment by ScalaWilliam** [comment]
@alexarchambault  I did this one - https://github.com/coursier/coursier/pull/2012

Learned that the option already exists in SBT, and given that most of the issue gets pointed out by users is from those using SBT, it is good to at least document it so I can refer them to it.
