### ISSUE TITLE
Filenames for cached jar files are not compatible with classpath jars

### ISSUE THREAD

**Issue by rivashin** [coursier/coursier#1507]
When Coursier generates a filename for the cached jar it replaces certain illegal characters with URL encoding. E.g. it replaces colon a `:` with `%3a`. Unfortunately this doesn't seem to be compatible with classpath jars - these are the jars that are used to run java app when the classpath is too long to specify in a command line. These jars use `Class-Path` attribute in `MANIFEST.MF` file to specify the actual classpath. I found that any paths in that attribute containing `%` will be ignored by java, resulting in an NoClassDefFoundError. See a little demo project [here](https://github.com/rivashin/jar-classpath-bug).

This affects both Windows and Linux. 
Maybe this is a java bug? I couldn't find any specification prohibiting `%` in manifest files. 

In my case Coursier generates these characters because I'm specifying a username and a port in a repository url: `https://username:password@server.com:8080`. So I get file paths like this: `https/username%40server.com%3a8080/foo.jar`.

So this issue must be affecting any project that specifies a username OR a port in the repository URL and has long enough classpath so that a classpath jar must be used.

Using a different character instead of `%` (e.g. an underscore `_`) is a possible fix.

**Comment by alexarchambault** [comment]
@rivashin Are you aware that the `Class-Path` entries of the manifest [seem to be decoded as URLs](https://stackoverflow.com/questions/18659774/how-do-i-handle-files-with-spaces-in-the-classpath-in-manifest-mf)? Maybe these `%` need more escaping (like `%` should be replaced by `%25`).

**Comment by rivashin** [comment]
Now that you've mentioned it, it does make sense. I've checked and URL-encoded `Class-Path` works fine.
So the problem is then in Bazel that doesn't encode the `Class-Path` correctly. I'll raise an issue with them.

Closing this issue - thanks for the quick response @alexarchambault.
