### ISSUE TITLE
"unsupported classloader" running cs on JDK 11

### ISSUE THREAD

**Issue by dwijnand** [coursier/coursier#1572]
I was having a look at https://scalameta.org/docs/semanticdb/guide.html#installation, but using `cs` instead of `coursier` and I found a behavioral difference between them when using JDK 11:

```bash
$ coursier launch org.scalameta:metac_2.13.1:4.3.0 -- -cp $(cs fetch -p org.scala-lang:scala-library:2.13.1) Test.scala
$ cs launch org.scalameta:metac_2.13.1:4.3.0 -- -cp $(cs fetch -p org.scala-lang:scala-library:2.13.1) Test.scala
Exception in thread "main" java.lang.RuntimeException: unsupported classloader: jdk.internal.loader.ClassLoaders$AppClassLoader@6ff3c5b5
	at scala.sys.package$.error(package.scala:27)
	at scala.meta.internal.metac.Main.process(Main.scala:23)
	at scala.meta.cli.Metac$.process(Metac.scala:36)
	at scala.meta.cli.Metac$.process(Metac.scala:27)
	at scala.meta.cli.Metac$.main(Metac.scala:10)
	at scala.meta.cli.Metac.main(Metac.scala)
```

**Comment by alexarchambault** [comment]
I think the problem originates from scalameta not handling [changes in the application classloader in Java 9 onwards](https://blog.codefx.org/java/java-11-migration-guide/#Casting-To-URL-Class-Loader) (it expects a `URLClassLoader`, and the application classloader isn't one anymore).

**Comment by alexarchambault** [comment]
I had missed the first command…

The difference originates from the second command doing actually less magic. The scalameta classpath is loaded by the JVM itself in the second case, in the application classloader which isn't a URLClassLoader anymore.

Passing `--fork` to the first command should make it fail too.

**Comment by dwijnand** [comment]
Ah, found it: https://github.com/scalameta/scalameta/blob/232d56a457f92582ca2cc1ac5a8f96780a8415f4/semanticdb/metac/src/main/scala/scala/meta/internal/metac/Main.scala#L23

Sorry about that, Alex.

**Comment by alexarchambault** [comment]
np!
