### ISSUE TITLE
excludeDependencies does not work (but does in sbt) [includes reproducer]

### ISSUE THREAD

**Issue by mkurz** [coursier/coursier#1590]
Using sbt 1.3.8 with coursier enabled by default.
A very simple reproducer can be found [here](https://github.com/mkurz/coursier-excludedependencies-sbtplugin).

Adding an sbt plugin that has dependencies e.g. Playframework to `project/plugins.sbt`
```sbt
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.8.1")
```

In `build.sbt` I enable the `PlayWeb` plugin, but want to exclude a dependency that plugin pulls in, namely `play-akka-http-server`:

```sbt
lazy val root = (project in file("."))
  .enablePlugins(PlayWeb)
  .settings(
    name := "coursier-excludeDependencies-sbtPlugin",
    version := "1.0-SNAPSHOT",
    scalaVersion := "2.13.1",
    excludeDependencies ++= Seq(
      "com.typesafe.play" %% "play-akka-http-server"
      // or:
      //ExclusionRule("com.typesafe.play", "play-akka-http-server_2.13")
    )
  )
```

Using [sbt-dependency-graph](https://github.com/jrudolph/sbt-dependency-graph)
- with coursier enabled, `play-akka-http-server` still is present:
```
[coursier-excludeDependencies-sbtPlugin] $ dependencyTree
...
  +-com.typesafe.play:play-akka-http-server_2.13:2.8.1
  | +-com.typesafe.akka:akka-http-core_2.13:10.1.11
  | | +-com.typesafe.akka:akka-parsing_2.13:10.1.11
...
```
- with coursier disabled, `play-akka-http-server` is (correctly) excluded from the dependencies.

Same behaviour no matter if `ExclusionRule` is used or not.

**Comment by mkurz** [comment]
This might be a problem with sbt-dependency-graph and not with coursier, but not sure yet, will investigate further.

**Comment by mkurz** [comment]
Alright, this is **definitely a bug in coursier**.
Check out the latest version of my reproducer: https://github.com/mkurz/coursier-excludedependencies-sbtplugin. I added a java file to access the `play.core.server.AkkaHttpServer` class which should however be excluded by the build.
Now if you run:
```
reload; clean; compile
```
it will compile in with coursier enabled (which I guess is wrong).
However if you disable coursier it will _not_ compile (which I guess is correct).

**Comment by mkurz** [comment]
Ref https://github.com/sbt/sbt/issues/5170

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/coursier/sbt-coursier/pull/235 (to be included in the upcoming release).
