### ISSUE TITLE
Scala.js runtime error: require is not a function

### ISSUE THREAD

**Issue by MaximeKjaer** [coursier/coursier#1618]
## Problem

In Scala.js, Coursier's NPM dependencies are loaded through `js.Dynamic.global.require("...")`. This is problematic for two reasons:

- Incompatibility with ES modules. 
  
  Scala.js projects depending on Coursier should have the choice between generating ES module `import`s or CommonJS `require`s, but the current implementation of Coursier contains hard-coded calls to `require`. This means that Scala.js  projects targeting ES modules will also generate `require` calls, which won't work in the browser (unless the bundle is passed through a bundler like Webpack).
  
- `global.require` may be `undefined` depending on how the JS code is loaded.
  
  For instance, running `console.log(global.require)` prints `undefined` in a JS file (loaded using `node test.js`) but prints the `require` function in a Node.js REPL. See [this StackOverflow question](https://stackoverflow.com/q/34566343/918389).

These two reasons both lead to the same runtime error: `TypeError: $g.require is not a function`. 

## Solution

There are two possible solutions for this:

1. Use `@JSImport` over `js.Dynamic.global.require`.
2. Update to Scala.js 1.x and use `@JSGlobal` to access `require` instead of `global.require`.

I think solution 1 is probably preferable to solution 2, as Scala.js projects can then target the module system they need. While I think Coursier should eventually move to Scala.js 1.x, solution 2 requires getting all of Coursier's dependencies to switch to 1.x, which may take time.

## Workaround until the solution is implemented

If anyone else needs to work around the issue for now, the hack I've found is to use Webpack to bundle my Scala.js output with a JS file containing `eval("global.require = require")`. Note that you should then very carefully determine if the Coursier dependencies (xhr2, cheerio, xmldom and sax) should be bundled too (for the Web) or just be available in `node_modules` (for Node.js).

**Comment by alexarchambault** [comment]
Thanks for opening this! I agree solution 1. is fine.

About Scala.JS 1.0, we're only waiting for [scalajs-react](https://github.com/japgolly/scalajs-react) to support it to switch to it.

About bundling dependencies or not, `xhr2`, `cheerio`, `xmldom`, and `sax` are all only needed / used from Node.

**Comment by alexarchambault** [comment]
If you feel like fixing this @MaximeKjaer, go ahead!

**Comment by MaximeKjaer** [comment]
I'm up for it! I'll give it a try.

**Comment by MaximeKjaer** [comment]
I haven't submitted a PR for this yet, because I wasn't really satisfied with any of the solutions.

The offending calls to `require` are all pretty much runtime polyfills for things that are available in the browser, but not in Node.js; for instance, we call `require('xhr2')` if `XMLHttpRequest` isn't available in the global scope. I think this is the only way to write code that works both on Node and in the browser; a runtime check to load a polyfill *is* how to support both.

As such, I don't think solution 1 I outlined above will work, the only valid solution is solution 2. This issue can only be fixed by upgrading to Scala.js 1.x.

A temporary workaround is the deprecated Scala.js 0.6-only [`scalaJSOutputWrapper`](https://github.com/scala-js/scala-js/blob/647eda4470f0facd3139814403be9a46b1eefb81/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSPlugin.scala#L433-L439) sbt setting:

```scala
scalaJSOutputWrapper := ("if (typeof global !== \"undefined\") global.require = require;", "")
```

However, seeing that this is an option for generating `.js` files, and that dependencies are distributed as `.sjsir` files, this option cannot be set in Coursier, it must be set by users.

**Comment by alexarchambault** [comment]
Thanks for the update @MaximeKjaer. Hopefully, we'll be able to switch to Scala.JS 1.0 soon (https://github.com/japgolly/scalajs-react/issues/599).

In the mean time, I don't rely mind, setting `scalaJSOutputWrapper` could be ok I guess…

**Comment by MaximeKjaer** [comment]
Seems like Scala.js 1.0 support in scalajs-react may be coming quite soon, seeing the update in the linked issue! :tada: 

I'm fine with `scalaJSOutputWrapper` as well, and I'm happy to submit a PR for it. However, it would be a documentation update, not an update to coursier's build, since the `scalaJSOutputWrapper` setting isn't applied to projects depending on coursier. Would you like me to submit that as a PR? 

Otherwise, since scalajs-react will very soon be releasing for 1.0, it may also be acceptable to just let this issue be the documentation for the workaround in the meantime, and solve the issue by upgrading to 1.0.

**Comment by alexarchambault** [comment]
> Otherwise, since scalajs-react will very soon be releasing for 1.0, it may also be acceptable to just let this issue be the documentation for the workaround in the meantime, and solve the issue by upgrading to 1.0.

Let's do this for now then. I don't really know how many people depend on / use coursier via its Scala.JS artifacts, they'll find this issue if needed, yes.

**Comment by MaximeKjaer** [comment]
Update: scalajs-react 1.7.0 has been released with Scala.js 1.0 support! :tada:

**Comment by alexarchambault** [comment]
> Update: scalajs-react 1.7.0 has been released with Scala.js 1.0 support!

Cool, looking into it! (unless you'd like to?)

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/1715 bumps Scala.JS to 1.0, and scalajs-react to 1.7.0.

**Comment by MaximeKjaer** [comment]
I updated my project to Scala.js 1.1.0 and Coursier v2.0.0-RC6-21, and can confirm that #1715 fixes the problem. I'll be closing this issue -- thank you!
