### ISSUE TITLE
Publish GPG public key(s) for coursier binaries

### ISSUE THREAD

**Issue by bsolomon1124** [coursier/coursier#1644]
Since one recommended way of installing is by downloading from `https://git.io/coursier-cli`, it would be helpful to be able to verify the signature of the resulting executable.

**Comment by alexarchambault** [comment]
I didn't create short links for signatures, but the signatures are actually generated and pushed alongside the binaries.

The `git.io/coursier-…` short links redirect to the launchers pushed in the [coursier/launchers repository](https://github.com/coursier/launchers). The signatures can be found there.

Binaries are signed with [this key](https://keyserver.ubuntu.com/pks/lookup?search=0x8011fd49dc1749cd64137af3cd1b9d8dc84eca56&fingerprint=on&exact=on&op=index).

**Comment by bsolomon1124** [comment]
@alexarchambault Cool, thanks!
