### ISSUE TITLE
Coursier could cache jar validation more agressively

### ISSUE THREAD

**Issue by jtjeferreira** [coursier/coursier#1675]
Related to https://github.com/sbt/sbt/issues/5508 where I described a problem with sbt+coursier in a multi module scenario. Basically running `sbt update` in a multi module project takes a lot of time because coursier is validating the same dependencies several times (once per module AFAICT)

One of the approaches to fix this problem would be to cache this more aggressively in courier and skip validation of already validated files...

**Comment by alexarchambault** [comment]
We should cache checksum validations somehow, yes. I've been wanting to find a way not to move a file to its final destination in cache if it has invalid checksums for some time, but couldn't find a convenient way to do it.

Writing somewhere that we validated a checksum could work, or better, persist our calculated checksums, and only compare those to the downloaded ones. So that we only do the comparison later on, not recomputing the checksum itself.

**Comment by oyvindberg** [comment]
So if I want to try my hand at this, where does it make sense to put the files? side by side with the downloaded files? or in a parallel hierarchy within `$COURSIER_CACHE`?

**Comment by alexarchambault** [comment]
@oyvindberg There's already a concept of ["auxiliary files"](https://github.com/coursier/coursier/blob/84d20de788ffc09b3cac2f491e213c48c97bea9a/modules/cache/jvm/src/main/scala/coursier/cache/FileCache.scala#L953) in `FileCache`, which correspond to files kept alongside another one. For example, if we get a SHA-1 via an HTTP header when downloading `foo/name`, it's kept in `foo/.name.sha1`. This particular auxiliary file is written around [here](https://github.com/coursier/coursier/blob/84d20de788ffc09b3cac2f491e213c48c97bea9a/modules/cache/jvm/src/main/scala/coursier/cache/FileCache.scala#L399). When a changing artifact (snapshots typically) is re-downloaded, its auxiliary files are [wiped](https://github.com/coursier/coursier/blob/84d20de788ffc09b3cac2f491e213c48c97bea9a/modules/cache/jvm/src/main/scala/coursier/cache/FileCache.scala#L943) .

Checksums are currently computed around [here](https://github.com/coursier/coursier/blob/84d20de788ffc09b3cac2f491e213c48c97bea9a/modules/cache/jvm/src/main/scala/coursier/cache/FileCache.scala#L685-L693). You may want to write an auxiliary file here (with an extension along the lines of `.sha1.computed` for example), or read an existing one.

One thing to pay attention to is concurrency. You need to [hold a lock](https://github.com/coursier/coursier/blob/84d20de788ffc09b3cac2f491e213c48c97bea9a/modules/cache/jvm/src/main/scala/coursier/cache/FileCache.scala#L997) on the main file when writing an auxiliary file.

**Comment by alexarchambault** [comment]
@oyvindberg Don't know if you tried that already. I can take a stab at it else.

**Comment by oyvindberg** [comment]
Oh yeah sorry, I haven't had as much time as I anticipated. I implemented this but wanted to run some benchmarks before I PRed it, especially with different locking mechanisms. I'll PR it so you can have a look

**Comment by alexarchambault** [comment]
Don't hesitate to open a PR, the risk of perf regression for this is quite low… In the happy path (all files already downloaded and all checksums already written in cache), there should be no file locks involved at all.

It's a point I wanted to clarify above: a principle followed with the cache is that if a file exists there, it can be used straightaway, without needing to acquire any kind of lock. This is made possible by writing files in a `.part` file in the same directory while holding the lock, then moving it atomically to its final destination (while still holding the lock). That way, if the destination file exists, it is always in a valid state, and can be read straightaway, without needing a lock.

The only case when this model fails I think is for "changing" files (like file listings, or version listings such as [this one](https://repo1.maven.org/maven2/io/get-coursier/coursier-cli_2.12/maven-metadata.xml), but also all files related to a snapshot version), that may be deleted after another thread or process saw the file. I'm not sure this has been a problem in practice. Users of snapshots can always retry things if anything goes wrong, and version listings are only used / read for very short period of times…
