### ISSUE TITLE
https://git.io/coursier-cli-linux returning 5xx status

### ISSUE THREAD

**Issue by bsolomon1124** [coursier/coursier#1679]
As of Tue Apr 21 16:04:18 UTC 2020:

```bash
$ curl -Lo /opt/coursier https://git.io/coursier-cli-linux
$ cat /opt/coursier
<html><body><h1>504 Gateway Time-out</h1>
The server didn't respond in time.
</body></html>
```

Also seeing a `500` in other cases.  Have tried from several different containers, from several different source IPs.

**Comment by alexarchambault** [comment]
This download goes though GitHub. I think that's related to https://www.githubstatus.com/incidents/dsf2qtzh4jpz.

**Comment by alexarchambault** [comment]
Maybe we should add `-f` to the `curl` commands in the doc…

**Comment by bsolomon1124** [comment]
Seems to be resolved as of now, closing.

> Maybe we should add -f to the curl commands in the doc…

Yeah, maybe `--fail` or `--fail-early`.  Personally, I have found curl to have a mixed record when it comes to properly raising from 4xx or 5xx errors, and `wget` to be much more consistent at that.
