### ISSUE TITLE
I suspect of coursier bug downloading from nexus

### ISSUE THREAD

**Issue by DavidPerezIngeniero** [coursier/coursier#1689]
I do this test with:

- Ammonite 2.0.4, 
- Scala 2.12, 
- Java 11, 
- Linux 64 bits:

```
@ interp.repositories() ++= Seq(coursierapi.IvyRepository.of("https://repo.osgeo.org/repository/Geoserver-releases/"))

@ import $ivy.`org.geotools:gt-swing:21.0` 
Failed to resolve ivy dependencies:Error downloading org.geotools:gt-swing:21.0
  not found: /home/jenkins/.ivy2/local/org.geotools/gt-swing/21.0/ivys/ivy.xml
  not found: https://repo1.maven.org/maven2/org/geotools/gt-swing/21.0/gt-swing-21.0.pom
  org.xml.sax.SAXParseException; lineNumber: 20; columnNumber: 3; The element type "meta" must be terminated by the matching end-tag "</meta>". (The element type "meta" must be terminated by the matching end-tag "</meta>".)

```

But the corresponding pom file is a well-formed XML file:
https://repo.osgeo.org/#browse/search/maven=attributes.maven2.artifactId%3Dgt-swing:21031dfaf45e5b5894f0a2f996c71fb3:d6e4a50aba3c8a19f45726bf54c25e7f

I think this is a bug in Coursier.

**Comment by DavidPerezIngeniero** [comment]
Tried with latest Ammonite 2.1.1 and Scala 2.13.2, and it keeps failing.

**Comment by DavidPerezIngeniero** [comment]
When using SBT 1.3.10 (which also uses Coursier), I cannot download it either.
But the error message is different:

```
download error: Caught javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching repo.osgeo.org found. (No subject alternative DNS name matching repo.osgeo.org found.) while downloading 
```

Googling a little I've found [this](https://support.sonatype.com/hc/en-us/articles/360018652593-How-to-resolve-CertificateException-No-subject-alternative-DNS-name-matching-for-LDAP-secure-connections).

Previously, I could donwload these dependencies.  If I preserve `~/.cache/coursier`, then no error is shown.

**Comment by alexarchambault** [comment]
`https://repo.osgeo.org/repository/Geoserver-releases` is a Maven repository, you should add it with
```scala
interp.repositories() ++= Seq(coursierapi.MavenRepository.of("https://repo.osgeo.org/repository/Geoserver-releases"))
```
It then resolves (but some more dependencies are missing down-the-line after that).

**Comment by alexarchambault** [comment]
I'm not sure the SSL exception you're seeing is related to coursier…

**Comment by DavidPerezIngeniero** [comment]
Thankjs.  I've checked that Maven is able to process ok the dependencies.

**Comment by DavidPerezIngeniero** [comment]
I will open another bug....
