### ISSUE TITLE
Seems like coursier doesn't override `evicted`

### ISSUE THREAD

**Issue by nafg** [coursier/coursier#170]
When I run evicted, it causes regular sbt artifact download (even though coursier already downloaded them)

**Comment by alexarchambault** [comment]
Looks like this one has to be overridden too...

**Comment by alexarchambault** [comment]
Implementing that one should basically "just" be a matter of adding an implementation for the `evicted` task of sbt (around [here](https://github.com/alexarchambault/coursier/blob/14f297b4f7ad8cf83abfe030825cd5b51bee64e3/sbt-coursier/src/main/scala-2.10/coursier/CoursierPlugin.scala#L101), calling a new method in `Tasks.scala` or a new `Evicted.scala` file, say).

This task should rely on the value of the [`coursierResolution` key](https://github.com/alexarchambault/coursier/blob/14f297b4f7ad8cf83abfe030825cd5b51bee64e3/sbt-coursier/src/main/scala-2.10/coursier/Keys.scala#L43). The corresponding `Resolution` knows the whole dependency graph (`dependencies` lists... the dependencies, `rootDependencies` the root ones, `finalDependencies` gives the dependencies of a module - the dependency graph can be walked / explored with these methods). Evicted versions can be identified this way.

**Comment by alexarchambault** [comment]
Closing this. `evicted` should work fine with `sbt-lm-coursier` (`addSbtPlugin("io.get-coursier" % "sbt-lm-coursier" % "2.0.0-RC3-1")`), that can be substituted to `sbt-coursier`. It should also work in the coming releases of sbt 1.3 (`> 1.3.0-RC3`).
