### ISSUE TITLE
Increase TTL when launching apps

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#1738]
When starting applications using `cs launch`, binary cross-versioned dependencies `::` are used most of the time in app descriptors. Currently, these need directory listings and some `maven-metadata.xml` files. These end up being downloaded periodically because of the TTL, which is annoying.

Applications should just start with an infinite TTL (except when starting a snapshot version maybe). If all their artifacts are in cache, the network should not be hit at all, the app should be started straightaway.

**Comment by dwijnand** [comment]
Fixed in #1788
