### ISSUE TITLE
How to include custom channels by default?

### ISSUE THREAD

**Issue by olafurpg** [coursier/coursier#1745]
Currently, users need to manually include non-default channels for every `cs install` command. Would it be possible to somehow allow users to install a custom channel once and have it included by default after that? This could work similarly to homebrew `tap`. It would be nice to be able to also have commands to list and remove installed channels.

Example usage:
```
$ coursier channel-list
default
$ coursier install fastpass
# Error because it's not available in default channel
$ coursier channel-install org.scalameta:tools
$ coursier install fastpass # available via `org.scalameta:tools` channel
$ coursier channel-list
default
org.scalameta:tools
$ coursier channel-remove org.scalameta:tools(
$ coursier channel-list
default
```

**Comment by alexarchambault** [comment]
@olafurpg The `--add-channel` option of `cs install` is supposed to do that. I haven't been using it much, I don't know if it works fine.

**Comment by alexarchambault** [comment]
Actually, it seems it works locally…

**Comment by olafurpg** [comment]
That’s great! I didn’t find a mention of this in the website document. Thank you!
