### ISSUE TITLE
Support ivy metadata pattern for Ivy in COURSIER_REPOSITORIES 

### ISSUE THREAD

**Issue by aishfenton** [coursier/coursier#1802]
Currently you can provide a separate artifact and metadata pattern to Courier by separating them with a `-r artifact-pattern|metadata-pattern`. But this appears not to be supported in the COURSIER_REPOSITORIES environment variable (which itself uses pipe as a separator).

**Comment by alexarchambault** [comment]
That's unfortunate… I'll see if we can add another syntax for these repositories, or maybe another separator for `COURSIER_REPOSITORIES` (like space characters).

**Comment by ob** [comment]
I'm not sure this is working? I tried doing this:

```
export COURSIER_REPOSITORIES='ivy:http://my-ivy-server.com/artifactory/release/[orgPath]/[module]/[revision]/[artifact]-[revision](-[classifier])(.[ext]) http://my-ivy-server.com/artifactory/release/[orgPath]/[module]/[revision]/[module]-[revision].ivy'
```

and then 

```
$ cs resolve --tree org.apache.httpcomponents:httpcore:4.4.13
Resolution error: Error downloading org.apache.httpcomponents:httpcore:4.4.13
  not found: http://my-ivy-server.com/artifactory/release/org/apache/httpcomponents/httpcore/4.4.13/ivy-4.4.13.xml
  not found: http://my-ivy-server.com/artifactory/release/[orgPath]/[module]/[revision]/[module]-[revision].ivy/org/apache/httpcomponents/httpcore/4.4.13/httpcore-4.4.13.pom
```

However, if I pass the same string using the `--repository` flag, and changing the space to a `|`, it does seem to work.

```
$ cs version
2.1.5
```

**Comment by Buzz-Lightyear** [comment]
@alexarchambault Should [this line](https://github.com/coursier/coursier/pull/1810/files#diff-4a3cf1b52fe0c3a4e95d4924b0585c5234885753f26eff8f5c9f7d727a8077eaR21) instead be `"\s+".r`? I couldn't get the space separator to work either.
