### ISSUE TITLE
Directories submodule needs update

### ISSUE THREAD

**Issue by eatkins** [coursier/coursier#1847]
The latest version of https://github.com/dirs-dev/directories-jvm contains a fix for https://github.com/sbt/sbt/issues/5386#issuecomment-690519281. I'm not exactly sure how to update the submodule myself so I opened an issue rather than a PR.

**Comment by alexarchambault** [comment]
It's just a matter of bumping a git sub-module. https://github.com/coursier/coursier/pull/1848 takes care of it.
