### ISSUE TITLE
Launching sbt Ignores .sbtopts and .jvmopts

### ISSUE THREAD

**Issue by mrt181** [coursier/coursier#1867]
Launching sbt through coursier completely ignores the  `.sbtopts` and `.jvmopts` files.

I have to use the jar version because it supports proxy settings.

.sbtopts
```properties
-Dsbt.override.build.repos=true
-Dsbt.repository.config=.repositories
```
.jvmopts
```properties
-Xss8m
-Dhttps.proxyHost=localhost
-Dhttps.proxyPort=8080
```
This ignores those settings and tries to download from mavent central or fails compilation (circe needs more stack)
```
> ./couriser launch sbt
```

It's possible to pass the values to the launcher like this:
```
> ./couriser launch sbt -J-Dsbt.override.build.repos=true -J-Dsbt.repository.config=.repositories -J-Xss8m
```

**Comment by julienrf** [comment]
I think this issue is fixed?
