### ISSUE TITLE
Coursier using ivy "conf" where "classifier" should be used 

### ISSUE THREAD

**Issue by aishfenton** [coursier/coursier#1869]
When I'm fetching an artifact from our Ivy repo Coursier appears to be using the artifact's ivy "conf", rather than it's classifier to resolve the artifact. 

Example:

Here's what we have in our `ixy.xml` file.

```json
<configurations>
<conf name="foo" visibility="public"/>
<conf name="sources" visibility="public" />
</configurations>
...
<publications>
<artifact xmlns:m="http://ant.apache.org/ivy/maven" name="my-project_2.11" type="sources" ext="jar" conf="sources" m:classifier="sources"/>
<artifact xmlns:m="http://ant.apache.org/ivy/maven" name="my-project_2.11" type="jar" ext="jar" conf="foo" m:classifier="all"/>
</publications>
```

When I fetch this with `myorg:my-project_2.11:1.0:all` it doesn't work as expected. Instead I need to use `myorg.my-project_2.11:1.0:foo` (note: `foo`, which if the conf name, instead of `all`, which is the classifier). When I fetch the same artifact using other tools, such as Gradle, it works as expected, so does appear to be Coursier which is handling this differently.

PS. Not sure if needed, but the Ivy pattern we use is:
`ivy:https://artifacts.netflix.com/nfrepo-everything/[orgPath]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[module]-[revision]-[classifier].[ext]|https://artifacts.netflix.com/nfrepo-everything/[orgPath]/[module]/(scala_[scalaVersion]/)(sbt_[sbtVersion]/)[revision]/[module]-[revision](-[type])(-[classifier]).[ext]`

**Comment by alexarchambault** [comment]
@aishfenton That's expected (given how dependencies are [currently parsed](https://github.com/coursier/coursier/blob/cdc0051b50450f7526886a8f4d883e6e65415651/modules/coursier/shared/src/main/scala/coursier/parse/DependencyParser.scala)). A classifier can be passed like this:
```text
myorg:my-project_2.11:1.0,classifier=all
```

**Comment by aishfenton** [comment]
Ohh, good to know @alexarchambault. Thank you ! 

Curious, is this the standard way for a maven coordinate to work? Or is this specific to Coursier? I get the impression from our other tools that they treat the last `:foo` as a classifier. But then again, it's not like anyone has ever documented what the maven coordinate standard really is  😄

**Comment by aishfenton** [comment]
Asking around, it sounds like `:classifier` is just a made up gradle convention. Hadn't realized that. Sorry !

**Comment by alexarchambault** [comment]
No problem, I wasn't sure initially, but I think I had derived the convention in coursier from how it's done in sbt. In sbt, the component after the version is an optional configuration, `"org" % "name" % "ver" % "conf"`. And classifiers are accepted with things like `"org" % "name" % "ver" classifier "classifier"`, which doesn't differ much from how coursier does it.

**Comment by lefou** [comment]
Yeah, I agree in general. But the price pays the user. Wouldn't it be better to print out some big fat warning when we retry. That way, you can still see all issue but users don't end up with broken workflows. Some users reported these kind of issues for years, so I'd rather not mess with their user experience.
