### ISSUE TITLE
Unexpected eviction of sbt artifacts in metabuild

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#1877]
## steps

This is showing up in different ways using sbt 1.4.0-RC2 (using lm-coursier-shaded 2.0.0-RC6-9, which uses Coursier 2.0.0-RC6-26)

- https://github.com/sbt/sbt/issues/5915
- https://github.com/sbt/sbt/issues/5750

## problem

In case of Play it looks like:

```
[info] loading project definition from /Users/ethanatkins/work/oss/scala/play/framework/project                                         
[error] /Users/ethanatkins/work/oss/scala/play/framework/project/BuildSettings.scala:6:8: Symbol 'type sbt.io.IOSyntax' is missing from the classpath.      
```

for sbt/sbt,

```
ThisBuild / usePipelining := true
            ^
[error] Type error in expression
[warn] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? (default: r)
```

In Play's case IO that should be part of sbt 1.4.0-RC2 was not showing up in the dependency graph, and instead an older one introduced by a plugin was used. That resulted in a strange error. I'm guessing similar thing was happening with sbt/sbt.

## expectation

The latest version of the JARs are selected.

## notes

In both cases, putting `ThisBuild / useCoursier := false` in `project/plugins.sbt` fixed the issue.

**Comment by eed3si9n** [comment]
@alexarchambault I haven't really spent time looking into this myself, but if this remains I'm thinking of rolling back sbt to Coursier 2.0.0-RC6-26 since it creates a bug that's likely difficult to debug for sbt and Play users, and not a great UX.

**Comment by eatkins** [comment]
@eed3si9n are you sure the issue doesn't date back further? I changed the lm-coursier-shaded version to `2.0.0-RC6-8` and I could still reproduce the eviction issue.

**Comment by eed3si9n** [comment]
Interesting. I did not think of the possibility that it has regressed earlier than we noticed with `usePipelining` but it's totally possible.

**Comment by eatkins** [comment]
I made a minimal repro project here: https://github.com/eatkins/coursier-sbt-eviction-issue

**Comment by eatkins** [comment]
I went pretty far back in the history until it became onerous to fix compilation bugs. I can't remember how far back I went but at least to 2.0.0-RC5-3.

**Comment by eed3si9n** [comment]
If we use Play documentation (https://github.com/playframework/playframework/blob/977354813a4b7cd312c699419061d9113b5bb486/documentation/project/build.properties) as indication, this bug didn't exist in sbt 1.3.13. If so lm-coursier-shaded 2.0.0-RC6-4 should be ok.

**Comment by eatkins** [comment]
I went to https://github.com/sbt/sbt/commit/f850a9c9660dc9b72719fd79f881036b2a43132f and bisected lm-coursier-shaded versions until I determined that 2.0.0-RC6-8 introduced the regression. From this, I think that https://github.com/coursier/sbt-coursier/commit/02016e9f218763999681066049d4f491dafe15ef is the commit that introduced the regression.

**Comment by eed3si9n** [comment]
I still feel confident about the commit (https://github.com/coursier/sbt-coursier/pull/262), so maybe Coursier resolution of `provided` is doing its job, but sbt is not _providing_ sbt JARs in the classpath.

**Comment by eatkins** [comment]
As someone who has not touched coursier and lm, I have no idea myself about the correctness of that commit. I just observed that if I bumped the coursier version to the version used in 2.0.0-RC6-7, the regression did not appear. There were only two commits between 2.0.0-RC6-7 and 2.0.0-RC6-8, so that left the provided commit as the one that caused the regression.

**Comment by eatkins** [comment]
To your point though about providing the jars, that's exactly what my comment in https://github.com/sbt/sbt/issues/5750#issuecomment-723238334 does.

**Comment by eed3si9n** [comment]
I'm going to close this for now, and treat this as sbt issue.
