### ISSUE TITLE
Adapt forceScalaVersion to Scala 3

### ISSUE THREAD

**Issue by adpi2** [coursier/coursier#1933]
`forceScalaVersion` does not work well with Scala 3 because Coursier does not override the versions of Scala 3 artifacts and instead it tries to resolve `scala-library:3.0.0-M3` which does not exist.

The current logic of `forceScalaVersion` is:
https://github.com/coursier/coursier/blob/68ef902004474731445665ef86908d79a31f842e/modules/coursier/shared/src/main/scala/coursier/Resolve.scala#L213-L225

**Comment by SethTisue** [comment]
related: #1926

**Comment by przemek-pokrywka** [comment]
It is fixed in 2.0.14
