### ISSUE TITLE
Coursier dosen't respect ```COURSIER_CACHE``` envirnoment variable or ```--cache``` CLI argument

### ISSUE THREAD

**Issue by qbouvet** [coursier/coursier#1955]
I discovered the issue when building a package with coursier. Coursier will set its cache in ~/.cache/coursier regardless of the ```COURSIER_CACHE``` environment variable or the ```--cache``` CLI argument. 

It is benign when running as a user, but very problematic when running ```coursier``` in ```fakeroot```, for instance when building packages with ```coursier```. 

## System

    $ uname
      # Linux
    $ uname -r
      # 5.4.92-1-lts
    $ coursier --version
      # 2.0.7

## Reproduce the issue

1/ Remove artifacts from previous runs: 

    $ export COURSIER_CACHE=/home/quentin/almond/coursiercache
    $ rm -rf $COURSIER_CACHE                # cache should go here
    $ rm -rf /home/quentin/.cache/coursier  # but it goes here

2/ Run coursier with ```COURSIER_CACHE``` environment variable set and/or ```--cache``` argument: 

    $ echo "COURSIER_CACHE=$COURSIER_CACHE"
      # COURSIER_CACHE=/home/quentin/almond/coursiercache
    $ coursier bootstrap \
      --cache "$COURSIER_CACHE" \
      -r jitpack \
      -i user -I user:sh.almond:scala-kernel-api_2.13.1:0.9.1 sh.almond:scala-kernel_2.13.1:0.9.1 \
      -o almond

3/ Check where the cache was created: 

    $ ls $COURSIER_CACHE
      # ls: cannot access '/home/quentin/almond/coursiercache': No such file or directory
    $ ls /home/quentin/.cache/coursier
      # jvm v1

Note that removing the ```--cache``` argument and using only the ```COURSIER_CACHE``` environment variable yields the same results. 

## Why it's a problem

This is especially problematic when building packages with ```coursier```, because ```coursier``` is then invoked in ```fakeroot```. In that case, ```coursier``` tries to use ```/root/.cache/coursier``` as cache, while not having root privileges, resulting in an exception: 

    Exception in thread "main" java.nio.file.AccessDeniedException: /root/.cache/coursier
            [...]
            at java.base/sun.nio.fs.UnixFileSystemProvider.checkAccess(UnixFileSystemProvider.java:313)
            at java.base/java.nio.file.Files.createDirectories(Files.java:761)
            at coursier.paths.Util.createDirectories(Util.java:80)
            at coursier.paths.CoursierPaths.computeCacheDirectory(CoursierPaths.java:56)
            [...]
            at coursier.cli.bootstrap.BootstrapSpecificParams$.$anonfun$apply$19(BootstrapSpecificParams.scala:124)
            [...]
            at coursier.bootstrap.launcher.ResourcesLauncher.main(Unknown Source)

For instance, almond [almond](https://aur.archlinux.org/packages/almond/) fails to build because coursier is called in ```package()``` in the PKGBUILD (a script that builds the package - can be a bit cryptic if you are not used to it - sorry).

This specific issue can be worked around by building outside of fakeroot (which some other packages do), but ```coursier``` cache behaviour doesn't seem normal. Could something be done to address it ? 

Best,
Quentin

**Comment by qbouvet** [comment]
You're in luck, because I found the solution to this a few days ago. It turns out there's a second cache that coursier ends up writing to, the [coursier JVM cache](https://get-coursier.io/docs/cli-java#managed-jvm-directory). I don't remember exactly how I found out about this, but essentially by chance.

You can change the directory of that cache with the COURSIER_JVM_CACHE variable. You can find an example [here](https://github.com/qbouvet/pkgbuilds-almond/blob/6f9415ba7f920f02c0afe6a926fcdc83376b9cc2/PKGBUILD),

**Comment by scalavision** [comment]
Thanks @qbouvet , I will try this out!
