### ISSUE TITLE
Unifying the sbt launcher with the original sbt launcher

### ISSUE THREAD

**Issue by julienrf** [coursier/coursier#1957]
This issue is a meta-issue around the problems caused by the fact that the sbt launcher installed by `cs setup` is not the same as the original sbt launcher. I’ve noticed that there are already a few issues that seem to be related to this: #1696, #1755, #1867. Maybe some more? See also sbt/sbt#6314, on the sbt side.

What is the best way to fix the root problem? Is it possible to use the same launcher as the original sbt launcher?

**Comment by SethTisue** [comment]
This claimed another victim today. from Discord:

> Was trying to troubleshooting re: the coursier sbt-launcher. I don't think it's loading .sbtopts
> Uff, I went to so much effort to get new developers to use coursier
> ( on my team )

**Comment by SethTisue** [comment]
Is this blocked waiting for something else to happen?

**Comment by julienrf** [comment]
@SethTisue It is not blocked as far as I know. The Scala Center plans to work on this issue, but we have been slowed down by the summer holidays. I expect to report some progress soon.

**Comment by sjrd** [comment]
PR here: https://github.com/coursier/apps/pull/119, but it requires a new release of coursier itself before we can merge it.

**Comment by julienrf** [comment]
Related: #2334

**Comment by SethTisue** [comment]
Hey, I'm super glad this was addressed. Kudos 👏
