### ISSUE TITLE
[sbt-coursier] SbtCoursierCache resolutionsCache leak

### ISSUE THREAD

**Issue by jtjeferreira** [coursier/coursier#1964]
Hi!

From time to time I have out of memory errors when running long sbt sessions and doing `reload`s and recompiling. I managed to capture an heapdump when this happens and can see `SbtCoursierCache$.resolutionsCache` occupying 458M.

![image](https://user-images.githubusercontent.com/943051/107810300-62ff7c80-6d64-11eb-92fc-694d49fd3eec.png)

I suspect this is exacerbated because I use [sbt-dynver](https://github.com/dwijnand/sbt-dynver), and the version of my artifacts keeps changing on every reload because it is based on a timestamp...

Ideas to fix this: 
* change the cache to use soft references
* clear the cache whenever a reload is done

**Comment by jtjeferreira** [comment]
A similar problem seems to exist in `SbtUpdateReport#moduleReport` but "only" using 218M...

![image](https://user-images.githubusercontent.com/943051/107810594-d86b4d00-6d64-11eb-9ee3-8faea5d3a999.png)

**Comment by alexarchambault** [comment]
> - change the cache to use soft references
> - clear the cache whenever a reload is done

Both options are fine to me. About soft references, my only fear would be that these may release their data too early, leading to unnecessary re-computations…
