### ISSUE TITLE
Build for ppc64le architecture

### ISSUE THREAD

**Issue by carlosedp** [coursier/coursier#1985]
Is it possible to add ppc64le architecture to the build matrix and published binaries?

**Comment by alexarchambault** [comment]
The binaries are generated by GraalVM native-image, so we are constrained by the platforms it supports (for now Linux / macOS / Windows on x86_64, and Linux on ARM64).

**Comment by carlosedp** [comment]
Yea, true.
Just for future reference: https://www.graalvm.org/docs/introduction/#graalvm-distributions

Hope soon GraalVM supports additional architectures.
Thanks @alexarchambault and sorry about the noise.
