### ISSUE TITLE
list of applications

### ISSUE THREAD

**Issue by xhudik** [coursier/coursier#1993]
Hi there, I'm wondering the only way how to get a list of installable apps is via:
```
unzip -l "$(cs fetch io.get-coursier:apps:1.0.7)"
```   

If so, wouldn't be good to add a command line option that can display this list? I mean a newbie (or even a user that do not use `cs` on daily basis) will not remember `unzip -l "$(cs fetch io.get-coursier:apps:1.0.7)"` (not very user friendly)

**Comment by alexarchambault** [comment]
I agree it'd be nice to allow to list install-able applications. Maybe a new dedicated command, such as `cs search`, could list those.

I can give you more directions if you'd like to try implementing it.

**Comment by xhudik** [comment]
sure, give a basic direction please and me (if i have some extra time), or somebody else might try to do it
