### ISSUE TITLE
coursier docs is not working

### ISSUE THREAD

**Issue by abhishekvaidprophecy** [coursier/coursier#1998]
Keep running into this when I access [](https://get-coursier.io/docs/overview) 

<img width="1267" alt="Screenshot 2021-03-10 at 12 32 54 AM" src="https://user-images.githubusercontent.com/75244584/110523486-2a22af80-8138-11eb-93a4-969ce57aa4fe.png">

**Comment by alexarchambault** [comment]
It works fine for me. I guess that was a transient glitch from GitHub pages?

**Comment by abhishekvaidprophecy** [comment]
Yes. It was an intermittent issue with github.
