### ISSUE TITLE
"concurrent download" even with a single repository

### ISSUE THREAD

**Issue by eed3si9n** [coursier/coursier#2022]
## steps

I don't have public reproduction. I'm basically using Coursier to resolve hundreds of dependencies concurrently (4 or 12) both in terms doing running multiple resolve, or by passing a fixed thread pool to `FileCache()`. Also the cache is wiped out beforehand to emulate fresh deployment.

## problem

I'm getting many "concurrent download" error:

```
[E2] error: Error downloading com.google:google:5
  concurrent download: https://some-artifactory/something-repo/com/google/google/5/google-5.pom
```

Based on how the dependencies are sorted, it's possible that there is a concurrent resolving that transitively download https://some-artifactory/something-repo/com/google/google/5/google-5.pom.

## expectation

No errors.

## notes

I don't know what the root cause is but if it is the Downloader, it should try to manage concurrent read.

https://github.com/coursier/coursier/blob/d2e1b696de1642178cdad432956216eb6996bb95/modules/cache/jvm/src/main/scala/coursier/cache/internal/Downloader.scala#L381-L392

https://github.com/coursier/coursier/blob/d2e1b696de1642178cdad432956216eb6996bb95/modules/cache/jvm/src/main/scala/coursier/cache/internal/Downloader.scala#L681-L691

**Comment by eed3si9n** [comment]
If anyone is resolving hundreds of dependencies concurrently on an empty cache, here's my workaround using the trampoline monad:

```scala
import coursier.core.Resolution
import coursier.util.Task

def retry(m: Int) = Task.tailRecM[Int, Resolution](m) { (n: Int) =>
  if (n <= 0) resolve.io.map(Right(_))
  else
    resolve.io.attempt map {
      case Right(r) => Right(r)
      case Left(e) if e.getMessage.contains("concurrent download") =>
        Thread.sleep(100)
        Left(n - 1)
      case Left(e) => throw e
    }
}
retry(5)
```

Running the program again would usually fix this because the first thread would hydrate the local cache.

**Comment by alexarchambault** [comment]
@eed3si9n What version of coursier were you using while you were getting those errors?

**Comment by eed3si9n** [comment]
https://github.com/twitter/bazel-multiversion/blob/4282989efda2406956a8e3022aedf10ccc43f1c8/build.sbt#L56

```scala
      "io.get-coursier" %% "coursier" % "2.0.0",
```

I think.
