### ISSUE TITLE
UX: Launch a REPL with libraries in the classpath in a single command

### ISSUE THREAD

**Issue by BalmungSan** [coursier/coursier#2032]
It would be great if **coursier** could launch a REPL with some libraries in the classpath in a single command, something like:

> cs repl -v 2.13.5 -l 'org.typelevel::cats-core:2.6.0'

It probably should also support setting `scalac` and `jvm` flags... but I think most people would be more than ok with just setting the version of the REPL and adding some libraries.

Note that as of today this is possible but requires multiple manual steps like installing the REPL and setting the classpath.

**Comment by alexarchambault** [comment]
It's already possible to do that kind of things using the `launch` command, and passing either the `scala` or `ammonite` applications first, like
```text
$ cs launch ammonite org.typelevel::cats-core:2.6.0
Loading...
Welcome to the Ammonite Repl 2.3.8-65-0f0d597f (Scala 2.13.5 Java 11.0.7)
@ import cats._
import cats._

@ Bye!

$ cs launch scala org.typelevel::cats-core:2.6.0
Welcome to Scala 2.13.4 (OpenJDK 64-Bit Server VM, Java 11.0.7).
Type in expressions for evaluation. Or try :help.

scala> import cats._
import cats._

scala>
:quit
```

Both commands accept an explicit Scala version, using the `--scala` option, like `--scala 2.13.5`.

**Comment by BalmungSan** [comment]
@alexarchambault **coursier** never ceases to amaze me. 😮
Thanks for the pointer and for the amazing tool!

May I just say that this example should be in the docs? I think many people would also benefit from it.

**Comment by alexarchambault** [comment]
> May I just say that this example should be in the docs? I think many people would also benefit from it.

Definitely. Feel free to add it, in a new "Examples" page under "Command-line" for example.
