### ISSUE TITLE
coursier doesn't respect the HOME environment variable and still writes into /home/{user}/.cache/coursier

### ISSUE THREAD

**Issue by yurivict** [coursier/coursier#2036]
It downloads jars into that directory.

For the purpose of package building cache directory should be unique for each build so that they wouldn't conflict through cache.

**Comment by lefou** [comment]
Related: https://github.com/coursier/coursier/pull/1484

**Comment by yurivict** [comment]
It doesn't work in a way described in https://github.com/coursier/coursier/pull/1484: I don't have ```XDG_CACHE_HOME``` set and my ```HOME``` is not ```/home/{user}```, but it still writes into ```/home/{user}/.cache/coursier```

```/home/{user}``` is not mentioned in my environment either, so it probably concatenates ```/home/``` and ```{user}``` strings.

**Comment by lefou** [comment]
@yurivict #1484 isn't merged yet.

**Comment by yurivict** [comment]
Ok, thanks!

**Comment by alexarchambault** [comment]
@yurivict coursier doesn't read the `HOME` environment variable, but the `user.home` Java property. From what I remember from having run Java apps in weird cloud environments, this property isn't based on HOME (I'm not sure, but Java might read `/etc/passwd` itself, or do fancier things).

If you want to change the home dir as seen from a Java app (such as mill), you should run it with `-Duser.home="$HOME"`.

**Comment by alexarchambault** [comment]
We should already respect `XDG_*` env vars on Linux, thanks to the [directories-jvm](https://github.com/dirs-dev/directories-jvm) library. https://github.com/coursier/coursier/pull/1484 is about respecting them on macOS too, it won't be merged I think.

**Comment by yurivict** [comment]
> coursier should already respect XDG_* env vars on Linux, 

```XDG_CACHE_HOME``` works - it sets the cache ditectory.
