### ISSUE TITLE
cs java --jvm zulu:1.11.0-10 should download aarch64 on m1 mac insted of x64

### ISSUE THREAD

**Issue by suliatis** [coursier/coursier#2042]
It would be nice if cs could detect system architecture and download the corresponding jvm if available

Example:
```
❯ eval "$(cs java --jvm zulu:1.11.0-10 --env)"
Downloading https://cdn.azul.com/zulu/bin/zulu11.45.27-ca-jdk11.0.10-macosx_x64.tar.gz
Still downloading:
https://cdn.azul.com/zulu/bin/zulu11.45.27-ca-jdk11.0.10-macosx_x64.tar.gz (37.99 %, 74113055 / 195105665)

Still downloading:
https://cdn.azul.com/zulu/bin/zulu11.45.27-ca-jdk11.0.10-macosx_x64.tar.gz (81.69 %, 159375391 / 195105665)

Downloaded https://cdn.azul.com/zulu/bin/zulu11.45.27-ca-jdk11.0.10-macosx_x64.tar.gz
Extracting
  /Users/suliatis/Library/Caches/Coursier/v1/https/cdn.azul.com/zulu/bin/zulu11.45.27-ca-jdk11.0.10-macosx_x64.tar.gz
in
  /Users/suliatis/Library/Caches/Coursier/jvm/zulu@1.11.0-10
Done
```

**Comment by megri** [comment]
Is there any way to override this with cli flags? I just switched to using coursier to install my dependencies and also noticed it installs the x64 binary instead of aarch64

**Comment by alexarchambault** [comment]
> Is there any way to override this with cli flags?

`--architecture`, added in https://github.com/coursier/coursier/pull/2489, should do just that I think.

**Comment by suliatis** [comment]
@alexarchambault yes, using `--architecture arm64` flag solves this problem, but it must be specified otherwise coursier installs the x64 even on arm by default.
