### ISSUE TITLE
cs setup fails on MacOS since it defaults to a non-existing GraalVM version

### ISSUE THREAD

**Issue by danielRicardo** [coursier/coursier#2065]
When running `cs setup` on MacOS, you get the following error:
```
Exception in thread "main" coursier.cache.ArtifactError$NotFound: not found: https://github.com/graalvm/graalvm-ce-builds/releases/download/vm-19.3.6/graalvm-ce-java8-darwin-amd64-19.3.6.tar.gz
```
This is because GraalVM 19.3.6 doesn't have a Java 8 based release for MacOS, as can be seen [here](https://github.com/graalvm/graalvm-ce-builds/releases?after=vm-20.0.1).

We need to either change the default to Java11 on MacOS, or change to another version of GraalVM.

Versions used:
* MacOS Catalina 10.15.7
* Coursier 2.0.13, installed from homebrew

**Comment by bishabosha** [comment]
I also came upon this

**Comment by ironfish** [comment]
any update on this?

**Comment by jorhett** [comment]
Setup runs fine on m1s when I tried today https://github.com/coursier/coursier/issues/2335#issuecomment-1029486466

**Comment by SethTisue** [comment]
still not working for me:

```
% coursier setup
Checking if a JVM is installed
Found a JVM installed under /Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home.

Checking if ~/Library/Application Support/Coursier/bin is in PATH

Checking if the standard Scala applications are installed
  Installed ammonite
JVM graalvm:19.3 not found in index: JVM graalvm not found
```

**Comment by SethTisue** [comment]
I found a way to get this working, on my machine anyway:

    brew uninstall coursier     # removes 2.1.0-M5
    brew install coursier/formulas/coursier   # installs 2.1.0-M6
    coursier setup

https://get-coursier.io/docs/cli-installation does currently recommend `brew install coursier/formulas/coursier` rather than the shorter `brew install coursier`, but it isn't clear to me why there would be a difference.

**Comment by kammoh** [comment]
> https://get-coursier.io/docs/cli-installation does currently recommend `brew install coursier/formulas/coursier` rather than the shorter `brew install coursier`, but it isn't clear to me why there would be a difference.
They are two different formulas. [`coursier`](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/coursier.rb) (maintained by homebrew) installs a fat jar version, while [`coursier/formulas/coursier`](https://github.com/coursier/homebrew-formulas/blob/master/coursier.rb) (from coursier team) installs an **x86** binary, even on arm64. This causes a lot of issues if you happen to use any JNI/JNA/FFI native loading on arm64.
It's a very sad situation for coursier (and all tools depending on I, e.g. bloop) for macos/arm64 user, despite graalvm has been releasing stable darwin-arm64 builds for months now.

**Comment by alexarchambault** [comment]
FYI, the release assets of https://github.com/VirtusLab/coursier-m1 now offer M1 launchers of coursier. If anyone wants to update the brew formula to get those on M1, feel free to do so.
