### ISSUE TITLE
coursier on Apple Silicon M1 macOS

### ISSUE THREAD

**Issue by ncihnegn** [coursier/coursier#2069]
Related issues:
#2042
 #2065

**Comment by jorhett** [comment]
WFM as shown here https://github.com/coursier/coursier/issues/2335#issuecomment-1029486466

**Comment by SethTisue** [comment]
Maybe this one should be closed, even though it's older, because #2335 has more discussion on it?

**Comment by kevinsjoberg** [comment]
Could we close this to avoid tracking similar issues?

**Comment by alexarchambault** [comment]
FYI there are now M1 coursier launchers in the GitHub release assets of [VirtusLab/coursier-m1](https://github.com/VirtusLab/coursier-m1).

**Comment by alexarchambault** [comment]
Closing in favor of https://github.com/coursier/coursier/issues/2335.
