### ISSUE TITLE
Support for latest.release

### ISSUE THREAD

**Issue by darkfrog26** [coursier/coursier#209]
In Ivy and Maven there is a concept of "latest.release" and "latest.integration" that would be incredibly useful for looking up the latest version of a dependency.  It doesn't appear there is any support to determine the latest version available for a dependency in coursier unless I've missed something?

**Comment by alexarchambault** [comment]
There's a support for version ranges in coursier, like `[2.2.0,2.3.0)` (Maven syntax) or `2.2.+` (Ivy syntax). It could be straightforwardly extended to support `latest.integration`.

Note that this would only work for artifacts from Maven repositories for now. Support for listing the available versions of a given artifact is not implemented for Ivy repositories - yet (this would involve crawling the repository it seems, whereas Maven repositories have specific metadata for that).

There's also a notion of statuses (http://ant.apache.org/ivy/history/latest-milestone/ivyfile/dependency.html) which would need to be added to support `latest.release` and `latest.milestone`.

**Comment by darkfrog26** [comment]
@alexarchambault thanks for the response.  Is there a way in coursier to list out the available versions of a dependency?

**Comment by denis-pyshev** [comment]
Sorry for bumping up old issue, but it'd be really nice to have this feature.

**Comment by darkfrog26** [comment]
@denis-pyshev I created a somewhat hacky solution that works surprisingly well in my situation: https://github.com/outr/jefe/blob/master/manager/src/main/scala/com/outr/jefe/repo/MavenRepository.scala#L21

**Comment by betehess** [comment]
> There's a support for version ranges in coursier, like [2.2.0,2.3.0) (Maven syntax) or 2.2.+ (Ivy syntax).

Is there a way to specify that on the command-line? It seems like "com.example::foobar:2.2.+"` is not supported.

**Comment by alexarchambault** [comment]
@betehess It seems to work:
```
$ coursier fetch com.chuusai:shapeless_2.12:2.3.+
~/.coursier/cache/v1/https/repo1.maven.org/maven2/com/chuusai/shapeless_2.12/2.3.3/shapeless_2.12-2.3.3.jar
~/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.4/scala-library-2.12.4.jar
~/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/macro-compat_2.12/1.1.1/macro-compat_2.12-1.1.1.jar
```
(same with `2.3+`, and replacing central with Nexus mirrors).

**Comment by betehess** [comment]
@alexarchambault I think I found the issue. For some reason, the resolution mechanism doesn't seem to work for 0.* versions (which is actually my case).

Works fine: `coursier fetch "org.typelevel:cats-core_2.12:1.+"`
Does not work: `coursier fetch "org.typelevel:cats-core_2.12:0.+"` (should at least find `0.9.0`).

Do you want me to open a separate issue to track this?

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/1138/ added support for `latest.release` and `latest.integration`, and fixed `0+` related issues.

**Comment by vito-c** [comment]
Was this back ported into 1.0.x? for us legacy sbt users :D

**Comment by einnocent** [comment]
@vito-c I recommend that your organization upgrade their sbt version. It is up to 1.2.1 by now.

**Comment by kongjiellx** [comment]
I have some sub dependencies use "RELEASE" as maven version, like description in https://stackoverflow.com/questions/30571/how-do-i-tell-maven-to-use-the-latest-version-of-a-dependency
Are there any ways to deal with my situation？
@alexarchambault
