### ISSUE TITLE
coursier enters fail state if interrupted in dirty way

### ISSUE THREAD

**Issue by luksow** [coursier/coursier#226]
Hi,

Today I was downloading dependencies using coursier when there was a power black out. After reboot I was constantly getting errors such as
`Unrecognized SHA-1 checksum format in $HOME/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/cats-core_2.11/0.4.1/cats-core_2.11-0.4.1.pom.sha1`. Mentioned file was just empty (probably due to disk error recovery), manual deleting solved problems. Maybe, in such situation, coursier could retry downloading checksum file?

**Comment by alexarchambault** [comment]
There are already some mechanisms to prevent unfinished downloads (e.g. file in `org/name/file.ext` is downloaded under `org/name/.file.ext.part`, then moved to `org/name/file.ext` once the download is done). That allows to resume partial downloads in particular. What version of coursier are you using? Do you have more context on how you ended up with this flawed file?

**Comment by luksow** [comment]
My version is `1.0.0-M10`. Possible explaination:

1. coursier downloaded and moved files
2. file descriptors were still in the working set (ex. were open)
3. blackout occured
4. inodes were corrupted due to ex. yet unclosed files
5. fsck truncated their contents during repair

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/1157 should fix that I think (it removes possibly corrupts checksum files).
