### ISSUE TITLE
Stay on scala-xml 1.x for 2.12.x

### ISSUE THREAD

**Issue by ckipp01** [coursier/coursier#2273]
Would it be possible for coursier to stick to scala-xml 1.x for 2.12. There was a recent discussion about this in [scala/scala](https://github.com/scala/scala/pull/9743) and the consensus was sort of to stay on 1.0.6, and therefore a lot of other libraries are doing the same when they publish for 2.12 in order to not cause all 2.12 users to hit on this if they are using coursier, since the version of scala-xml is incompatible with that of the actual scala compiler.

```
[error]         * org.scala-lang.modules:scala-xml_2.12:2.0.1 (early-semver) is selected over {1.2.0, 1.0.6}
[error]             +- io.get-coursier:coursier-core_2.12:2.1.0-M1        (depends on 2.0.1)
[error]             +- org.scala-lang:scala-compiler:2.12.15              (depends on 1.0.6)
```

**Comment by alexarchambault** [comment]
Thanks @ckipp01! Just fixed that prior to cutting a new lm-coursier release (in the sbt-coursier repo) for sbt.
