### ISSUE TITLE
cs setup ammonite not working

### ISSUE THREAD

**Issue by mavericksy** [coursier/coursier#2282]
After running `cs setup` and appending to PATH, amm returns

`> cs launch ammonite
Error: Main method not found in class ammonite.Main, please define the main method as:
   public static void main(String[] args)
or a JavaFX application class must extend javafx.application.Application
`
as well as:

` ~/.local/share/coursier/bin/amm
Error: main method not found in class ammonite.Main
`

Normal ammonite install script works.

**Comment by alexarchambault** [comment]
I can reproduce that. It seems the main class in Ammonite changed recently… When Ammonite will switch to Mill > `0.10.0` (with https://github.com/com-lihaoyi/mill/pull/1451), its JARs should come up with a manifest specifying the correct main class, which should fix that.

**Comment by alexarchambault** [comment]
In the mean time, as a workaround, you can manually install a previous version of Ammonite with
```bash
$ cs install ammonite:2.4.1
```

**Comment by mavericksy** [comment]
Fantastic. Work-around solves the problem.
Much appreciated and great work with coursier. 
Thanks
