### ISSUE TITLE
Unable to download snapshot dependencies with 2.1.0-M1

### ISSUE THREAD

**Issue by hmemcpy** [coursier/coursier#2287]
I initially reported this as an [sbt issue](https://github.com/sbt/sbt/issues/6737) , as it seems that the latest upgrade cannot resolve snapshot dependencies from sonatype.

I managed to manually reproduce this with just coursier. I had an older v2.0.7 installed, and it fetches the snapshot dependency just fine:

```
> cs fetch --no-default -r central -r sonatype:snapshots org.zeromq:jeromq:0.5.3-SNAPSHOT
https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
  100.0% [##########] 1.2 KiB (111B / s)
https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.pom
  100.0% [##########] 16.7 KiB (42.8 KiB / s)
https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.jar
  100.0% [##########] 506.2 KiB (467.4 KiB / s)
/Users/hmemcpy/Library/Caches/Coursier/v1/https/oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-20211128.145727-50.jar
/Users/hmemcpy/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/eu/neilalexander/jnacl/1.0.0/jnacl-1.0.0.jar
```

However, upgrading to the latest coursier 2.1.0-M1-1 fails to resolve this:

```
> ll $(which cs)
lrwxr-xr-x  1 hmemcpy  admin    36B Dec  6 10:08 /usr/local/bin/cs -> ../Cellar/coursier/2.1.0-M1-1/bin/cs
> cs fetch --no-default -r central -r sonatype:snapshots org.zeromq:jeromq:0.5.3-SNAPSHOT
https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
  100.0% [##########] 353B (680B / s)
https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml
  100.0% [##########] 353B (1.8 KiB / s)
Resolution error: Error downloading org.zeromq:jeromq:0.5.3-SNAPSHOT
  not found: https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
  not found: https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
```

This issue seems to affect sbt 1.6.0-RC1 as well, since it now depends on cs 2.1.0.

Am I holding this wrong, or does it seem like a bug?

**Comment by hmemcpy** [comment]
Found the culprit! I downloaded a bunch of cs binaries from the Releases page and found the problem was introduced between https://github.com/coursier/coursier/compare/v2.0.16-169-g194ebc55c...v2.0.16-200-ge888c6dea.

Bisecting, running `./mill -i nativeTests` at every step to ease building the native binary I was able to find the PR that broke this. It was #2246, interestingly enough commenting that sending an empty User Agent string sometimes breaks sonatype repos.

I don't know right away how to fix this, perhaps it's worth sending a custom, coursier-specific user agent? Or mimic e.g. Chrome?

Paging @julienrf and @alexarchambault for additional input.

**Comment by julienrf** [comment]
Hey, I’m sorry to see that that PR did break your usecase. It’s a pity that so many things are based on the User Agent…

I share with you a workaround that lets you override the User-Agent from within sbt:

~~~ scala
val customUserAgent =
  lmcoursier.definitions.Authentication(Seq("User-Agent" -> "Coursier"))
csrConfiguration ~= (_.addRepositoryAuthentication("sonatype-snapshots", customUserAgent))
~~~

**Comment by eed3si9n** [comment]
@julienrf Thanks for the workaround.

**Comment by hmemcpy** [comment]
Hey @julienrf, thanks for the workaround, but I'm afraid it didn't work (unless I did something wrong):

```scala
ThisBuild / scalaVersion := "2.13.7"

val customUserAgent =
  lmcoursier.definitions.Authentication(Seq("User-Agent" -> "Coursier"))
csrConfiguration ~= (_.addRepositoryAuthentication("sonatype-snapshots", customUserAgent))

lazy val root = (project in file("."))
  .settings(
    name := "sbt-problem",
    resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
    libraryDependencies ++= Seq(
      "org.zeromq" % "jeromq" % "0.5.3-SNAPSHOT"
    )
  )
```
(this is using sbt 1.6.0-RC1)

I'm still getting the same error:
```
[error] (ssExtractDependencies) sbt.librarymanagement.ResolveException: Error downloading org.zeromq:jeromq:0.5.3-SNAPSHOT
[error]   Not found
[error]   Not found
[error]   not found: C:\Users\hmemcpy\.ivy2\localorg.zeromq\jeromq\0.5.3-SNAPSHOT\ivys\ivy.xml
[error]   not found: https://repo1.maven.org/maven2/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
[error]   not found: https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/jeromq-0.5.3-SNAPSHOT.pom
```

It seems that it has an issue following/redirecting to the latest version described in the [maven-metadata.xml](https://oss.sonatype.org/content/repositories/snapshots/org/zeromq/jeromq/0.5.3-SNAPSHOT/maven-metadata.xml). I'm not sure how or why the User Agent affects it...

**Comment by eed3si9n** [comment]
For the interest of unblocking sbt 1.6.0, could we revert https://github.com/coursier/coursier/pull/2246 and release a new version of Coursier please? And we can try another fix later.

**Comment by alexarchambault** [comment]
Going to revert that commit for now. I'm wondering whether [the workaround](https://github.com/coursier/coursier/issues/2287#issuecomment-990719044) suggested by @julienrf could be used by users having issues with the empty user agent.

**Comment by alexarchambault** [comment]
Will probably set the user agent to `Coursier` later on.

**Comment by hmemcpy** [comment]
Great! Thank you so much @alexarchambault! The wording on the comment of your old commit is spot on - this is FUCKING CRAZY! :)

I just checked with the user agent `Coursier` and it seems to work, so that's possibly the best solution for this now!

Thank you for the revert, this should unblock sbt 1.6.0 as well!

**Comment by jtjeferreira** [comment]
I think this explains it https://issues.sonatype.org/browse/NEXUS-6171

**Comment by hmemcpy** [comment]
Oh wow, closed "by design" bugs are my favorite... 😕 Thanks!

**Comment by julienrf** [comment]
@hmemcpy about the workaround, you need to reuse the same “resolver name”:

~~~ scala
val customUserAgent =
  lmcoursier.definitions.Authentication(Seq("User-Agent" -> "Coursier"))
csrConfiguration ~= (_.addRepositoryAuthentication("Sonatype OSS Snapshots", customUserAgent))

resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots",
~~~

The resolver name I gave you was the one sbt creates when you do:

~~~
resolvers += Resolver.sonatype("snapshots")
~~~

Last, in your example you need to scope the setting `csrConfiguration` to the project that uses snapshot libraries.

**Comment by hmemcpy** [comment]
@julienrf ah, of course... scopes. Keep getting tripped over them ;)
Yeah, definitely makes sense. Let's hope this helps the next person who stumbles on a similar issue! Thanks again!

**Comment by hmemcpy** [comment]
Anyway, thanks again everyone for your answers, and thanks @alexarchambault for the revert. I am closing this issue as resolved!
