### ISSUE TITLE
Unrecognized option: --installed

### ISSUE THREAD

**Issue by mbovel** [coursier/coursier#2300]
Hello!

This might just be a problem with my setup, but I can't figure out why `cs java --installed` fails. Any idea?

```
$ brew info coursier
coursier/formulas/coursier: stable 2.1.0-M2-1
Launcher for Coursier
https://get-coursier.io
/usr/local/Cellar/coursier/2.1.0-M2-1 (5 files, 60.4MB) *
  Built from source on 2021-12-15 at 17:56:45
From: https://github.com/coursier/homebrew-formulas/blob/HEAD/coursier.rb
==> Dependencies
Required: openjdk ✔
...
$ cs java --version
openjdk 17 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)
$ cs java --available
adopt:1.8.0-181
adopt:1.8.0-192
adopt:1.8.0-202
adopt:1.8.0-212
...
$ cs java --installed
Unrecognized option: --installed
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
```

**Comment by pnadon** [comment]
Same, no idea

**Comment by okouyad** [comment]
Try to find a way to install the version of the doc 2.0.13
https://cmichel.io/how-to-install-an-old-package-version-with-brew/
I had problems with this last version, and reverting to the version of the doc helped

**Comment by jneira** [comment]
Same here, it seems it has some logic to recognize coursier specific options starting with `--` but that "list" does not include `--installed` (but `--available` is)

**Comment by jneira** [comment]
Afaics the cli module isnot handling the `--installed` option at all:

https://github.com/coursier/coursier/blob/34af89c14c839b7cd56d1e7bd1250abf5e501046/modules/cli/src/main/scala/coursier/cli/jvm/Java.scala#L24-L29

https://github.com/coursier/coursier/blob/34af89c14c839b7cd56d1e7bd1250abf5e501046/modules/cli/src/main/scala/coursier/cli/jvm/Java.scala#L51

**Comment by jneira** [comment]
the feature was removed by https://github.com/coursier/coursier/commit/d2b2fc730df4d810c2f000f62fd02274e9d5c29a#diff-2bc0761270e33c078cbf5153efeb0b70d652a5a51b0c3149b4da7ed110064010

**Comment by jneira** [comment]
I recently open a wip pr restoring it where i asked that question and previously i did it in the original pr which removed it: https://github.com/coursier/coursier/pull/2188#issuecomment-1079935827
