### ISSUE TITLE
Error: main method not found in class ammonite.Main

### ISSUE THREAD

**Issue by wandyirawan** [coursier/coursier#2319]
OS: Manjaro

after install ./cs setup and run
$ amm
show error: 
Error: main method not found in class ammonite.Main

**Comment by ckipp01** [comment]
Hey @wandyirawan, thanks for the report. There is actually a PR to fix this here: https://github.com/coursier/apps/pull/125 since the fix is in the apps repository.

**Comment by alexarchambault** [comment]
Closing as this should be fixed by https://github.com/coursier/apps/pull/125, with recent coursier versions for sure. Feel free to re-open if that's not the case for you.
