### ISSUE TITLE
Multiply repositories flag - parsing error or incorrect documentation

### ISSUE THREAD

**Issue by dos65** [coursier/coursier#2342]
Section about `-r` in `cs resolve --help` notices that there is an option to specify multiply repositories using comma:

> Repository - for multiple repositories, separate with comma and/or add this option multiple times (e.g. -r central,ivy2local -r sonatype:snapshots, or equivalently -r central,ivy2local,sonatype:snapshots

However, the example from doc - `-r central,ivy2local,sonatype:snapshots` doesn't work:
```
$ cs resolve -r central,ivy2local,sonatype:snapshots  "org.scalameta:metals_2.12:0.11+"
Error parsing URL central,ivy2local,sonatype:snapshots (no protocol: central,ivy2local,sonatype:snapshots)
```

**Comment by alexarchambault** [comment]
This used to work in early coursier versions. I'm not sure when support for this was dropped (possibly inadvertently…), but I'm not sure either we really need it after all.

https://github.com/coursier/coursier/pull/2361 should clarify that help message.
