### ISSUE TITLE
Add a way to tell the current version of cs

### ISSUE THREAD

**Issue by ckipp01** [coursier/coursier#2343]
There is currently no way (as far as I can tell) to check the actual version of cs that you have installed. All the logical ones that a user would think of:

```
cs --version
cs -version
cs about
cs version
```
All just return the help which also doesn't include the version. It'd be helpful to be able to get the actual version of cs that is installed using cs.

**Comment by alexarchambault** [comment]
I agree these need to be added back. I might add it myself soon, but as always, contributions welcome!

**Comment by ckipp01** [comment]
You can now get this with `cs version`.
