### ISSUE TITLE
LinkageError when launching 'scala' or 'scalac' on Windows with JDK 11

### ISSUE THREAD

**Issue by sjrd** [coursier/coursier#2354]
I have a Windows machine with Adoptium JDK 11. After entirely removing `AppData\Coursier\data\bin`, I reinstalled `cs` using the latest download instructions, which seems to have installed the newer `cs` 2.1.0-something. (Yeah!) Running `cs` or `sbt` works fine, but launching `scala` or `scalac` fails with
```
C:\Users\sjrdo\Documents\Projets\scalajs>scala
Erreur : LinkageError lors du chargement de la classe principale coursier.bootstrap.launcher.Launcher
        java.lang.UnsupportedClassVersionError: coursier/bootstrap/launcher/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0

C:\Users\sjrdo\Documents\Projets\scalajs>scalac -version
Erreur : LinkageError lors du chargement de la classe principale coursier.bootstrap.launcher.Launcher
        java.lang.UnsupportedClassVersionError: coursier/bootstrap/launcher/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
This is the case
* right after installation
* after `cs install scala:2.13.8`, and
* after `cs install scala:3.1.1`

Launching `scala` with `cs launch scala` *successfully* opens up the REPL.

**Comment by alexarchambault** [comment]
So https://github.com/coursier/coursier/pull/2355 should fix that. Installing Java 17 on your Windows machine should also work (by running `cs java --setup --jvm temurin:17` for example).
