### ISSUE TITLE
Problem while installing sbt on a windows machine

### ISSUE THREAD

**Issue by hamzaremmal** [coursier/coursier#2376]
An error occurred while trying to install sbt via coursier.  A NoSuchElementException was raised while trying to find the executable file  in the sbt zip file. I've tried to debug the code quickly and found that a commit was recently pushed on February 1st in the repo related to the installation of sbt on windows.

PS : I tried an old release of coursier prior to the date of the mentioned commit and it did install sbt successfully.
![Coursier error](https://user-images.githubusercontent.com/56235032/155598032-2c53ba64-70a4-43cd-bf27-5d5ff64a8562.png)

**Comment by sjrd** [comment]
What commit was that?

(It should find the `.bat` file, not a `.exe`. 🤔)

**Comment by hamzaremmal** [comment]
After a deep check, it seems that the version I installed was 2.0.13 and when I installed the last release directly from github, it worked perfectly. However, I just installed coursier yesterday following this link : https://git.io/coursier-cli-windows-exe and using this command on cmd : ``bitsadmin /transfer cs-cli https://git.io/coursier-cli-windows-exe "%cd%\cs.exe"``.
So the problem was in version 2.0.13 and was fixed now, but the link still points the previous version.

**Comment by sjrd** [comment]
Ah. Unfortunately, the https://git.io/ service was shut down and became immutable, so we cannot update it anymore. :( Would you mind sharing where you found that link? We should replace it with https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-win32.zip everywhere it was used.

**Comment by hamzaremmal** [comment]
The link was in the setup instructions given by one of the courses I follow this semester. I informed the head TA and he changed the instructions so we follow the instructions in the coursier website.
