### ISSUE TITLE
`--scala-version 3` returns 2.13 artefacts

### ISSUE THREAD

**Issue by smarter** [coursier/coursier#2407]
Using Coursier 2.1.0-M5-18-gfebf9838c :
```shell
% cs fetch --scala-version 3 'org.scalacheck::scalacheck:1.16.0'
/home/smarter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scalacheck/scalacheck_2.13/1.16.0/scalacheck_2.13-1.16.0.jar
/home/smarter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.8/scala-library-2.13.8.jar
/home/smarter/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-sbt/test-interface/1.0/test-interface-1.0.jar
```
(Also IMO it's time to change the default to scala 3 from scala 2.13 now that `cs launch scala` starts Scala 3).

**Comment by alexarchambault** [comment]
I think some more work is required for 3.x to work fine when passed via `--scala-version`. Relatedly, I think cs can't infer a Scala 3 version when passed Scala dependencies like `org::name:ver`.
