### ISSUE TITLE
Make cs setup install scala-cli

### ISSUE THREAD

**Issue by bjornregnell** [coursier/coursier#2416]
It would be really nice if `cs setup` also installed `scala-cli`
See https://github.com/VirtusLab/scala-cli/issues/904

Including scala-cli in cs setup can be done prior to the potential/eventual promotion of scala-cli to scala. With both the traditional scala runner and scala-cli on path more people can start to play with scala-cli as soon as they have installed the currently official `scala` via the Coursier installers, without having to go to the scala-cli install page.

**Comment by julienrf** [comment]
@alexarchambault What is the process that defines which applications are installed? In the [documentation](https://get-coursier.io/docs/cli-setup) it says that it installs a number of applications, but there is no link to the exhaustive list. It would be useful to know which applications are installed, and several stakeholders should be consulted to update that list of apps.

**Comment by julienrf** [comment]
Probably, this is covered by #2415 ?

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/2415, yep.

**Comment by bjornregnell** [comment]
:tada: :rocket: :heart:
