### ISSUE TITLE
lots of logging when resolving

### ISSUE THREAD

**Issue by fommil** [coursier/coursier#244]
We are still noticing a lot of logging in ensime when using coursier. I'll dig out some details of the exact strings later, but to see it yourelf just run `sbt ensimeConfig` on `ensime-server` itself and see a few pages of logging.

Also, the logs are really messing inside emacs. When the `INSIDE_EMACS` environment variable is defined, the console should be assumed to be a dumb console.

**Comment by alexarchambault** [comment]
That's javadoc and sources artifacts not found in `updateClassifiers`. I though I limited this output some time ago, but didn't actually. Not hard to do.

**Comment by fommil** [comment]
it would be good if doing an `ensimeConfig` on `ensime-server` didn't have any of these lines:

```
Resolving org.ensime:api_2.11:0.9.10-SNAPSHOT
Resolution done
Fetching artifacts
Fetching artifacts: done
```

**Comment by fommil** [comment]
I'm pretty sure this is coming from standard `update` not `updateClassifiers`.

**Comment by fommil** [comment]
one more type of logging is that we see it like this in emacs when downloading anything (really noisy).

You can detect that you are in Emacs by looking for the `INSIDE_EMACS` environment variable, but also you should probably avoid doing this kind of printing if the sbt `jline` doesn't support it.

```
https://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   64.0% [######    ] 215.4 KiB (25.9 KiB / s)
[2A[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-javadoc.jar
   99.8% [######### ] 1.1 MiB (137.1 KiB / s)
https://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   64.0% [######    ] 215.4 KiB (25.8 KiB / s)
[2A[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-javadoc.jar
  100.0% [##########] 1.1 MiB (137.1 KiB / s)
https://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   64.0% [######    ] 215.4 KiB (25.7 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   68.7% [######    ] 231.4 KiB (27.6 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   73.5% [#######   ] 247.4 KiB (29.4 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   78.2% [#######   ] 263.4 KiB (31.2 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   83.0% [########  ] 279.4 KiB (32.9 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   87.7% [########  ] 295.4 KiB (34.6 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   92.5% [######### ] 311.4 KiB (36.1 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
   97.2% [######### ] 327.4 KiB (37.8 KiB / s)
[2A[10000Dhttps://repo1.maven.org/maven2/org/codehaus/janino/janino/2.7.8/janino-2.7.8-sources.jar
```

**Comment by alexarchambault** [comment]
The progress bars are automatically disabled when the SBT process has no stdin (run with `< /dev/null`, or with the `-batch` option if using the sbt-extras launcher). Can you run SBT this way from ensime? (I could look at `INSIDE_EMACS` or `CI`, but this way seems quite general already.)

**Comment by fommil** [comment]
SBT definitely needs a stdin when run in Emacs, otherwise it wouldn't be possible to send it information.

**Comment by alexarchambault** [comment]
https://github.com/alexarchambault/coursier/pull/257/commits/527b1eca96f42b35640f8f9bbfa47fcb589eaf79 from https://github.com/alexarchambault/coursier/pull/257 will disable progress bars by default if the env var `INSIDE_EMACS` or `CI` are set. That will be included in `1.0.0-M12-1` to come.

**Comment by fommil** [comment]
:-) thank you!!

**Comment by fommil** [comment]
M12 is looking good! (not sure what M12-1 is) But still seeing this noise for internal dependencies...

```
...
[info] Fetched artifacts of org.ensime:ensime_2.11:2.0.0-SNAPSHOT
[info] Fetching artifacts of org.ensime:monkeys_2.11:2.0.0-SNAPSHOT
[info] Fetched artifacts of org.ensime:monkeys_2.11:2.0.0-SNAPSHOT
[info] Fetching artifacts of org.ensime:testingempty_2.11:2.0.0-SNAPSHOT
[info] Fetched artifacts of org.ensime:testingempty_2.11:2.0.0-SNAPSHOT
...
```

**Comment by fommil** [comment]
oh I see it, using it now.

Also this logging

```
...
[info] Updating org.ensime:monkeys_2.11:2.0.0-SNAPSHOT
[info] Resolved org.ensime:monkeys_2.11:2.0.0-SNAPSHOT dependencies
[info] Updating org.ensime:core_2.11:2.0.0-SNAPSHOT
[info] Resolved org.ensime:core_2.11:2.0.0-SNAPSHOT dependencies
[info] Updating org.ensime:testingsimple_2.11:2.0.0-SNAPSHOT
...
```

**Comment by alexarchambault** [comment]
The progress bars should still be there in `1.0.0-M12` for things that are not in cache. `INSIDE_EMACS` is only taken into account since `1.0.0-M12-1` (that I just pushed release notes for :-).

**Comment by alexarchambault** [comment]
I'll see what I can do for the extra logging. Maybe lower the verbosity level under some conditions.

**Comment by fommil** [comment]
basically I only ever want to see a log message when it hits the network, otherwise silence is golden.

**Comment by fommil** [comment]
@alexarchambault is this going to make it for 1.0.0? I keep watching milestone releases in anticipation :smile: if you point me at the file that does this I can send a PR

**Comment by alexarchambault** [comment]
@fommil Yep, this is still planned for 1.0.0.

The `Updating` / `Resolved` / `Fetching` / `Fetched` messages could easily be printed only when some downloading did happen, as you suggest.

I would see that implemented by having [`TermDisplay`](https://github.com/alexarchambault/coursier/blob/master/cache/src/main/scala/coursier/TermDisplay.scala) print a first message if any download happens, and an exit message when `stop` is called, only so if some download happened. Then printing of the four messages above should be delegated to it via this mechanism.

If you feel like giving it a try, please do :-)

**Comment by fommil** [comment]
seems to be https://github.com/alexarchambault/coursier/blob/master/plugin/src/main/scala-2.10/coursier/Tasks.scala#L837 and https://github.com/alexarchambault/coursier/blob/master/plugin/src/main/scala-2.10/coursier/Tasks.scala#L853

seems like I just need to change `verbosityLevel := 1`

**Comment by fommil** [comment]
(but I think you probably want to change the check to `>1` instead of `>=1`)

**Comment by schmitch** [comment]
actually I came here since we are trying to use coursier inside our CI. however the logging make's our CI system also way slower. So it would be great to just have a way to say: Download Dependencies -> Done / Failure. Without the explicit dependencies in between. That would be really great.
