### ISSUE TITLE
Support File Based Parameter For fetch

### ISSUE THREAD

**Issue by cjohnstoniv** [coursier/coursier#2443]
In regards to a limitation with Bazel's usage of Coursier, for projects that have 100's of artifacts that they depend on this results in too large of a command line when running on Windows.

Some info here: https://github.com/bazelbuild/rules_jvm_external/issues/623

Is it possible to add support to Coursier such that instead of passing all of the artifacts via the command line, optionally a file can be used insted?

**Comment by cjohnstoniv** [comment]
Any thoughts on if this is possible? I don't mind contributing that change but knowing nothing about how coursier actually is designed, it would be nice to get some idea from the maintainers if this is feasible/acceptable.

**Comment by jkciesluk** [comment]
Hi, I would like to help with this issue if nobody is working on it.

**Comment by cjohnstoniv** [comment]
I am not working on this at the moment, would be great to have someone pick this up that knows Scala :). I've been procrastinating it a bit admittedly.
