### ISSUE TITLE
Feature request: setting JVM version for install/bootstrap

### ISSUE THREAD

**Issue by marktsuchida** [coursier/coursier#2449]
As far as I can tell, the only ways to run an application with a specific JVM version is to use `cs launch` or to set `JAVA_HOME` at the time of running.

It would be convenient if a JVM version could (optionally) be selected when installing or bootstrapping, so that the resulting executable always runs using that specific JVM. Currently, both `cs install` and `cs bootstrap` appear to produce executables that use the JVM set by `JAVA_HOME` (even if `--jvm` is given to `cs install`).

Use case: I'm trying to set up linting in a pre-commit hook for a Java 8 project, but the linter (CheckStyle) requires Java 11. It would be nice to keep `JAVA_HOME` pointing at JDK 8 but have the linter "just work" once set up.

**Comment by alexarchambault** [comment]
An issue with this is that bootstraps are Java apps themselves, with a shell preamble though. So setting the right JVM should be handled from the preamble. The most convenient way to achieve that would be by assuming that `cs` is available, and use it like `eval "$(cs java --env --jvm 17)"` to set the JVM right before starting the bootstrap with `java`. But that would somehow trump a benefit of bootstraps: that their only requirement is only `java` being in the `PATH` (or `JAVA_HOME` being set maybe).

**Comment by marktsuchida** [comment]
Interesting, I hadn't thought about that circularity.

I ended up implementing a different solution to my problem (not involving Coursier), by the way, so please feel free to close this if no one else is interested.

**Comment by alexarchambault** [comment]
Closing this for now, then.
