### ISSUE TITLE
Multiple assets missing for `v2.1.0-M6-28-gbad85693f`?

### ISSUE THREAD

**Issue by dzx-dzx** [coursier/coursier#2450]
I'm a newcomer to Scala so correct me if I'm wrong, but I'm afraid this has caused [coursier CLI launchers](https://github.com/coursier/launchers) to malfunction, which is preventing me from [installing Scala](https://www.scala-lang.org/download/).
> Error downloading https://github.com/coursier/coursier/releases/download/v2.1.0-M6-28-gbad85693f/cs-x86_64-pc-linux.gz

**Comment by quelgar** [comment]
Same on Mac

```
Error downloading gz+https://github.com/coursier/coursier/releases/download/v2.1.0-M6-28-gbad85693f/cs-x86_64-apple-darwin.gz
```

**Comment by dzx-dzx** [comment]
Seems added.
