### ISSUE TITLE
'cs complete' fails with strange error message

### ISSUE THREAD

**Issue by mtk** [coursier/coursier#2452]
a random example:

% cs complete dev.zio
Usage: /home/mtk/.local/share/coursier/bin/.cs.aux List(complete) format index ...args...

or an example from the doc:

% cs complete org.scala-lang
Usage: /home/mtk/.local/share/coursier/bin/.cs.aux List(complete) format index ...args...

**Comment by note** [comment]
@mtk Try `cs complete-dep org.scala-lang` instead. I've opened a PR accommodating to that change in the docs.

**Comment by mtk** [comment]
and thanks.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/2476.
