### ISSUE TITLE
COURSIER_JVM_CACHE not respected on Windows

### ISSUE THREAD

**Issue by s5bug** [coursier/coursier#2454]
![image](https://user-images.githubusercontent.com/7751296/177267183-bb0ff2bb-b8b0-4426-851f-aff46c45452e.png)

No JVMs are listed as installed:

![image](https://user-images.githubusercontent.com/7751296/177267328-2892a964-cbbb-4de0-8d98-908985589bd4.png)

And new JVMs are downloaded to a weird cache folder:

![image](https://user-images.githubusercontent.com/7751296/177267695-fae3b73b-485e-43e5-90e3-f007afbbc82d.png)

This is a _regression_, but I don't know from how long ago as I very rarely use CS to manage my Java installations.

**Comment by alexarchambault** [comment]
That looks like a bug, yes. If anyone wants to investigate, the JVM cache location is computed around [here](https://github.com/coursier/coursier/blob/ff26f8e393cdf1266e47a31d2dcbb01f1fe2b382/modules/paths/src/main/java/coursier/paths/CoursierPaths.java#L47).

**Comment by s5bug** [comment]
I don't think the JVM cache is even _used_. It looks like the Archive cache is used (by the `arc` in the path).

**Comment by alexarchambault** [comment]
Of course, that's because `COURSIER_JVM_CACHE` isn't used anymore! `COURSIER_ARCHIVE_CACHE` should be used instead.

**Comment by s5bug** [comment]
@alexarchambault Should I open issues for these two things?
1. The [documentation for `cs java`](https://get-coursier.io/docs/cli-java#managed-jvm-directory) and the [documentation for the caches](https://get-coursier.io/docs/cache) should be updated to mention arc.
2. The JDK index is no longer manually editable. This is really really important when using Coursier to
  a. Install JDKs that are otherwise not provided, or use a custom naming scheme
  b. _Use desktop applications that may require selecting a specific JDK_.

(b) is _very_ important to me. It is the #﻿1 reason I've recommended Coursier to people looking to have a way to easily manage JDKs. It's also the reason I'm able to recommend Coursier to people looking to play multiple versions of Minecraft (lower versions require JRE 8) as it's very easy to browse in that case.

**Comment by alexarchambault** [comment]
@s5bug About 1., sure!

About 2., I don't know if that can help in your case, but recent versions of the coursier CLI (since [`2.1.0-M6-26-gcec901e9a`](https://github.com/coursier/coursier/releases/tag/v2.1.0-M6-26-gcec901e9a) that has https://github.com/coursier/coursier/pull/2403) accept URLs as JVM ids. So one can request custom JVMs easily.
