### ISSUE TITLE
Remove scalaz dependency?

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#25]
It seems that coursier is only using `\/` and `Task` from scalaz - and only a very limited subset of the features of `Task`, to the point that the scalajs lib already has its own `Task` implementation...

And `\/` is just not a big enough incentive, the standard `Either` could replace it.

**Comment by alexarchambault** [comment]
A step toward (or tangent to) that in https://github.com/alexarchambault/coursier/commit/e20b93326d9a1beb8e0d7672c67e1cc4e47aee45... makes the `core` module depend only on `scalaz-core` (for `Monad`), no more on `scalaz-concurrent` (now depended upon by `coursier-files`, that supplies `Task` as `Monad` to core).

If :cat: had an equivalent of `scalaz.concurrent.Task`, it could just replace scalaz here.

**Comment by schrepfler** [comment]
Some library authors do copy-paste of external code to keep dependencies at minimum. Perhaps taking monix Task until cats get one.

**Comment by pjan** [comment]
monix & cats interoperate well. remove \/ in favor of either?

**Comment by fommil** [comment]
this is causing problems with sbt-ensime, I'll link in a moment

**Comment by lihaoyi** [comment]
I'm not sure if this is still happening at some point, but I'm still waiting on this to happen before including Coursier inside Ammonite.

**Comment by alexarchambault** [comment]
@lihaoyi I'll see if I can publish JARs of coursier that would shade scalaz. It's too slow to do with the current version of sbt-shading, but that could be circumvented I think.

Or maybe you could shade coursier plus its dependencies from Ammonite (provided that that can be done fast enough with sbt-shading). Could that be a solution for you? It's done in ensime-sbt [here](https://github.com/ensime/ensime-sbt/pull/312).

**Comment by fommil** [comment]
we leave our scalaz dependency transitive because it is too slow.

**Comment by lihaoyi** [comment]
A Coursier jar with a shaded version of Scalaz would be great, and I'd use it

**Comment by fommil** [comment]
vote to close, shading works great!

**Comment by olafurpg** [comment]
Is this fixed? coursier-cache doesn't bring in scalaz anymore

```
$ coursier fetch io.get-coursier:coursier-cache_2.12:1.1.0-M6
/Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.12.6/scala-library-2.12.6.jar
/Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/io/get-coursier/coursier_2.12/1.1.0-M6/coursier_2.12-1.1.0-M6.jar
/Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/io/get-coursier/coursier-cache_2.12/1.1.0-M6/coursier-cache_2.12-1.1.0-M6.jar
/Users/ollie/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.12/1.1.0/scala-xml_2.12-1.1.0.jar
```

**Comment by alexarchambault** [comment]
Yes, it's fixed. Closing!
