### ISSUE TITLE
Apple M1: different behavior using native and Java-based launcher

### ISSUE THREAD

**Issue by olafurpg** [coursier/coursier#2510]
On an Apple M1 chip, the native `cs` binary is able to fetch Java 8
```
❯ cs version
2.1.0-M6-53-gb4f448130
❯ cs java-home --jvm 8
/Users/olafurpg/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin8-binaries/releases/download/jdk8u332-b09/OpenJDK8U-jdk_x64_mac_hotspot_8u332b09.tar.gz/jdk8u332-b09/Contents/Home
```

When using the Java launcher with the exact same version, the same `java-home` command fails
```
❯ curl -fLo coursier https://github.com/coursier/launchers/raw/master/coursier && chmod +x coursier && ./coursier java-home --jvm 8
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  125k  100  125k    0     0   652k      0 --:--:-- --:--:-- --:--:--  652k
JVM 8 not found in index: No adoptium version matching '1.8+' found
❯ ./coursier version
2.1.0-M6-53-gb4f448130
```

I'm using the Java launcher in a project because it's a small cross-platform binary that I can check into a git repository.

**Comment by olafurpg** [comment]
A workaround is to use the `--architecture amd64` flag

```
❯ ./coursier java-home --jvm 8 --architecture amd64
/Users/olafurpg/Library/Caches/Coursier/arc/https/github.com/adoptium/temurin8-binaries/releases/download/jdk8u332-b09/OpenJDK8U-jdk_x64_mac_hotspot_8u332b09.tar.gz/jdk8u332-b09/Contents/Home
```

**Comment by keynmol** [comment]
The native binary seems to be running under Rosetta and fetching a x64 version of the temurin 8 jdk: `OpenJDK8U-jdk_x64_mac_hotspot`

AFAIR temurin doesn't have aarch64 builds for Java 8, only 11 and 17

**Comment by olafurpg** [comment]
I just tried the native M1 releases from https://github.com/VirtusLab/coursier-m1/releases and can confirm that I get the same error as the Java launcher 
```
❯ cs java-home --jvm 8
JVM 8 not found in index: No adoptium version matching '1.8+' found
```
Using `--jvm zulu:8` instead of `--jvm 8` solves the problem without using the `--architecture` flag. Closing this with "working as intended", but maybe these details will be helpful if somebody else hits on the same issue.
