### ISSUE TITLE
Memory usage of `coursier fetch --json-output-file ...`

### ISSUE THREAD

**Issue by jonshea** [coursier/coursier#2534]
I ran into an issue where `coursier fetch --json-output-file ...` was failing with `java.lang.OutOfMemoryError`. This failure persisted even with heap sizes or 8 GB. Analysis of a heap dump showed that 66% of the heap consisted of duplicate strings. In my particular case, 9% of the heap was taken up by 149,403 copies of the string `"org.scala-lang:scala-library:2.12.12"`, and another 9% was copies of the string `"org.scala-lang:scala-library:2.12.8"`. 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/1385/190451617-46938a95-b494-4283-a0f0-5da4c1d59c9d.png">

It appeared that most of these strings were held by the `reconciledVersionStr` and `requestedVersionStr` fields of `JsonElem`, for example:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/1385/190452293-8eaa8f32-3270-4d78-a113-a787700081cf.png">

I have prepared a PR adds `intern` calls to the allocations of `reconciledVersion`, `reconciledVersionStr`, and `requestedVersionStr` on `JsonElem`, causing these string allocations to be effectively deduplicated in to the JVM string pool. After this change, my same fetch command was able to complete
running with a much smaller heap, `-Xmx256m`. The PR is here: #2533 

There are likely further opportunities for improvement. For example, YourKit detects a similar number of duplicates of the `JsonElem` object itself.
<img width="780" alt="image" src="https://user-images.githubusercontent.com/1385/190453211-3b5f9667-ff84-4808-9289-7dab07d10cf2.png">
<img width="841" alt="image" src="https://user-images.githubusercontent.com/1385/190453350-f7350fda-b4c8-465d-95e4-f624d91561f0.png">

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/2533 (even though further optimizations are apparently possible)
