### ISSUE TITLE
org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over 1.0.6

### ISSUE THREAD

**Issue by raviteja-oops** [coursier/coursier#2543]
Getting below version conflict error

[error] 	* org.scala-lang.modules:scala-xml_2.12:2.1.0 (early-semver) is selected over 1.0.6
[error] 	    +- org.scoverage:scalac-scoverage-reporter_2.12:2.0.5 (depends on 2.1.0)
[error] 	    +- org.json4s:json4s-core_2.12:3.5.3                  (depends on 1.0.6)

**Comment by keynmol** [comment]
Try putting 

```scala
libraryDependencySchemes ++= Seq(
  "org.scala-lang.modules" %% "scala-xml" % VersionScheme.Always
)
```

into `project/plugins.sbt`. It's important that it goes under `project/` folder and **not** in the `build.sbt`

Also, this is not a coursier issue, it's a SBT issue.

**Comment by keynmol** [comment]
Does this happen during the loading of your project (i.e. somewhere after `loading project definition` when you start SBT), or when you invoke something like `compile` after the build has already loaded?

If it's the latter, then you'll need the snippet above in your `build.sbt` as well I think.

Either way, it's really not a coursier issue, it's a known, wider problem (with workaround): https://github.com/scala/bug/issues/12632

**Comment by raviteja-oops** [comment]
Yes, I removed that snippet from project/plugin.sbt and I placed it under build.sbt. Then it worked. Thank you
