### ISSUE TITLE
'cs' failes to execute with error message 'cs: cannot execute binary file', even after a reinstall

### ISSUE THREAD

**Issue by mtk** [coursier/coursier#2546]
'cs' failed to run.  worked two days ago.  removed it and re-installed with 'coursier install cs'.  still failed to run with the same error.  this is under fedora linux v36 (completely up-to-date).

**Comment by djneades** [comment]
I am also seeing this on an aarch64 Fedora VM.

```
# uname -a
Linux Fedora 5.18.15-200.fc36.aarch64 #1 SMP PREEMPT_DYNAMIC Sun Jul 31 21:12:19 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```

**Comment by schlawg** [comment]
Yeah, same for me on fedora x86 arch.

Both `cs` and `scala-cli` fail with **cannot execute binary file**.  Everything else in bin is fine (including `.cs.aux` and `.scala-cli.aux`).

Just in case the answer is something silly in the first few lines:

```
head cs | hexdump -C:

00000000  23 21 2f 75 73 72 2f 62  69 6e 2f 65 6e 76 20 73  |#!/usr/bin/env s|
00000010  68 0a 65 78 65 63 20 22  24 28 63 64 20 22 24 28  |h.exec "$(cd "$(|
00000020  64 69 72 6e 61 6d 65 20  22 24 30 22 29 22 3b 20  |dirname "$0")"; |
00000030  70 77 64 29 2f 2e 63 73  2e 61 75 78 22 20 22 24  |pwd)/.cs.aux" "$|
00000040  40 22 0a 50 4b 03 04 14  00 08 08 08 00 2c b9 4e  |@".PK........,.N|
00000050  55 00 00 00 00 00 00 00  00 00 00 00 00 1b 00 09  |U...............|
00000060  00 4d 45 54 41 2d 49 4e  46 2f 63 6f 75 72 73 69  |.META-INF/coursi|
00000070  65 72 2f 69 6e 66 6f 2e  6a 73 6f 6e 55 54 05 00  |er/info.jsonUT..|
00000080  01 75 32 4a 63 b5 93 cb  6a c3 30 10 45 f7 f9 8a  |.u2Jc...j.0.E...|
00000090  60 b2 28 b4 b2 9b b4 84  e2 65 d7 85 42 29 dd 94  |`.(......e..B)..|
000000a0  50 26 f2 c4 1e 90 25 21  c9 ce c3 f8 df 2b bf 9a  |P&....%!.....+..|
000000b0  34 6d 20 8b 64 65 79 34  be 67 ae 75 55 8d c6 e3  |4m .dey4.g.uU...|
000000c0  c0 a0 56 96 9c 32 84 36  88 c7 9f be e6 ab 1c a5  |..V..2.6........|
000000d0  33 20 82 bb ee d5 6d 35  5a 58 61 4c e5 96 19 14  |3 ....m5ZXaL....|
```

**Comment by akizminet** [comment]
I also have the same issue on Fedora 36. After updating fedora, `cs` failed to run.

**Comment by f-thiele** [comment]
Same here with
```
Linux fth-li 5.19.15-201.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Oct 13 18:58:38 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
the issue is though not just with `cs` but also with `bloop` and `scala-cli` (probably more but not installed on my system). In all those cases an additional `.name.aux` is provided e.g. `.bloop.aux` which do work to execute.

**Comment by rusty-snake** [comment]
`~/.local/share/coursier/bin/cs` starts with the actual shell script followed by a zipped META-INF directory. This is a problem if `sh` is `bash`. While `dash` or `zsh` (i.e. `dash ~/.local/share/coursier/bin/cs`) can start `cs`, `bash` can not because of the zipped META-INF directory blob.

Possible solution on coursier end for this would be to remove this binary blob as it seems unused to me.

All users here are running Fedora. This makes it look like the cause for this could be a Fedora patch to bash.

**Comment by schlawg** [comment]
>Possible solution on coursier end for this would be to remove this binary blob as it seems unused to me.
>All users here are running Fedora. This makes it look like the cause for this could be a Fedora patch to bash.

FWIW, I have been running with `cs` symlinked to `.cs.aux` (same for `scala-cli -> .scala-cli.aux` and `bloop` -> `.bloop.aux`) with no problems whatsoever.

**Comment by rusty-snake** [comment]
Because that what the script actually does:
```bash
#!/usr/bin/env sh
exec "$(cd "$(dirname "$0")"; pwd)/.cs.aux" "$@"
```
- shebang, obvious
- A compatible why to express `$(readlink "$(dirname "$0")")`, i.e. get the realpath of the directory containing `cs`, actually `~/.local/share/coursier/bin`.
- `exec ~/.local/share/coursier/bin/.cs.aux "$@"`

**Comment by schlawg** [comment]
Thanks for that, I meant to corroborate your suggestion that the blob can be removed.

If there is anything in `.cs.aux` internals that for some reason expects `cs` to contain that zip, I have not experienced any ill effects from it.

**Comment by schlawg** [comment]
It appears the zip in the shebang scripts is used by `cs update`.

If anyone applied the previously mentioned symlink workaround, they would need to do a fresh `cs install <package>` and then reapply the symlink hack to update those packages (such as bloop) that fail with `cannot execute binary file` on fedora.

**Comment by nafg** [comment]
I'm affected by this too, on Fedora. I discovered that if the script part is long enough then it works.

So this is okay (including a trailing newline):

```
#!/usr/bin/env sh

exec "$(cd "$(dirname "$0")"; pwd)/.cs.aux" "$@"
#######
```

But if you remove one `#` then it goes back to `cannot execute binary file`.

I figured this out (after a lot of digging, with help on Discord from Aly and @BalmungSan) by extracting the zip part with (slightly edited):

```
❯ tail -c +68 $(which cs)  > test
❯ file test
test: Zip archive data, at least v2.0 to extract, compression method=deflate
```

then experimenting with a `stub.sh` and doing `cat stub.sh test > test.run && sh test.run`

**Comment by nafg** [comment]
so I guess 75 bytes long is the magic number?

**Comment by julienrf** [comment]
@nafg Thank you for your investigation! The problem seems to be hard to reproduce outside of fedora. Did you find a fix that we could apply here? Is there a way to include a test for that in the CI?

**Comment by rusty-snake** [comment]
I would have played with an hexeditor to find out more but I'm no longer able to reproduce. Maybe the update to Fedora 37 fixed it for me.

**Comment by schlawg** [comment]
Fixed for me as well.  Coursier hasn't changed (at least it's still using zip manifest wrappers) so I do believe it was Fedora 37.

**Comment by nafg** [comment]
I am on fedora 37 and it's working now. But I think I already was when I last posted. So I don't think that's what changed.

In fact the files now have much longer headers. Before it was just something like

```
#!/usr/bin/env sh

exec "$(cd "$(dirname "$0")"; pwd)/.cs.aux" "$@"
```

but now it's a much longer script. It looks like this code: https://github.com/coursier/coursier/blob/main/modules/launcher/src/main/scala/coursier/launcher/Preamble.scala#L138-L160

That certainly puts it over 75 bytes!

**Comment by nafg** [comment]
> @nafg Thank you for your investigation! The problem seems to be hard to reproduce outside of fedora. Did you find a fix that we could apply here? Is there a way to include a test for that in the CI?

Not sure what wasn't clear. The fix is to make sure the preamble is more than 75 bytes. I don't know why the preamble changed for me though (see [my previous comment](https://github.com/coursier/coursier/issues/2546#issuecomment-1336311782))

**Comment by rusty-snake** [comment]
@nafg I still have the short script at the top.

**Comment by rusty-snake** [comment]
Also the file you linked hasn't changed since "Aug 16".

To me it seems the relevant code is [here](https://github.com/coursier/coursier/blob/de7ac23f7c2b896e6665658dab1437099a0a3fc0/modules/install/src/main/scala/coursier/install/InstallDir.scala#L398).

**Comment by rusty-snake** [comment]
> Re testing, I couldn't reproduce in Docker, so it would need a fedora VM.

Good idea. I can reproduce using `registry.fedoraproject.org/fedora:36`.

**Comment by rusty-snake** [comment]
Currently the problem seems to be a null-byte in the first 80-bytes.
