### ISSUE TITLE
'cs update' fails on scala-cli 0.1.16

### ISSUE THREAD

**Issue by mtk** [coursier/coursier#2559]
gets the error:

Error downloading gz+https://github.com/VirtusLab/scala-cli/releases/download/v0.1.16/scala-cli-x86_64-pc-linux.gz

**Comment by DEliasVCruz** [comment]
I'm having a similar error running `cs setup`
```sh
> cs setup
Checking if a JVM is installed
Found a JVM installed under /home/danielv/.local/share/sdkman/candidates/java/current.

Checking if ~/.local/share/coursier/bin is in PATH
  Should we add ~/.local/share/coursier/bin to your PATH via ~/.profile, ~/.config/zsh/.zprofile? [Y/n] n

Checking if the standard Scala applications are installed
  Installed ammonite
Error downloading gz+https://github.com/coursier/coursier/releases/download/v2.1.0-M7-18-g67daad6a9/cs-x86_64-pc-linux.gz
```

**Comment by mtk** [comment]
any update on this?  is it a real problem or something dumb on my part?  happy to wait if it is real.  just want to know if it is understood.

**Comment by mtk** [comment]
@alexarchambault i've heard you on chris kipp's podcast and while you have a french accent, i know you speak english better than 99% of most americans :-).  i hope you understand when i say i am *jonesing* for a coursier-delivered scala-cli!  i know you're busy doing great things.  just curious if there is a time frame for the fix?

**Comment by chungtc** [comment]
the culprit is unzip
sudo apt install unzip fixed my errors

**Comment by mtk** [comment]
there is certainly some kind of problem with the compression.  but unzip
can't be removed in general.  has to be fixable some other way?

**Comment by alexarchambault** [comment]
@mtk What `cs` version creates that error? (`cs version` should print the version - if it doesn't, it means it's too old ^^)

You might want to update `cs`, with either `cs update cs`, or `cs update coursier && coursier update cs`.

**Comment by julienrf** [comment]
@mtk @DEliasVCruz Is this issue still valid?

**Comment by mtk** [comment]
no, went away.  /mark

**Comment by DEliasVCruz** [comment]
I no longer use Scala nor coursier so I haven't checked

**Comment by julienrf** [comment]
Thank you for your response, I am closing this issue, feel free to comment on it if we should re-open it.
