### ISSUE TITLE
Public constructor of `core.Dependency` can't be called

### ISSUE THREAD

**Issue by lefou** [coursier/coursier#2560]
Since coursier 2.1.0-M7, the new parameter `minimizedExclusions` refers to a non-public type `MinimizedExclusions`.

This makes updating coursier to 2.1.0-M7 in Mill impossible, as JSON pickling (with upickle) no longer works.

**Comment by lefou** [comment]
`MinimizedExclusions` was introduced in this PR:

* https://github.com/coursier/coursier/pull/2442

Although I can imagine some motivation to hide `MinimizedExclusions` as implementation detail, with the current situation, we end up with a broken and unusable API.

I see two options:

__Option 1: Hide it completely__

Completely hide the `MinimizedExclusions` type, which also means, no public API should leak it. 

__Option 2: Make it public__

Make `MinimizedExclusions` public. This doesn't mean, all ways to efficiently construct a `MinimizedExclusions` need to be public, but at least there needs to be one way to create it. 

Also, as coursier is an widely used library in thirdparty tools, care should be taken, to easily support serialization or pickling of this type.

__Additional thoughts__

I can't understand how lightheaded (binary) compatiblity is handled in the above merged pull request. IMHO, ignoring (binary) compatibility is a major paint point in libraries and Scala has a huge track record in this regard. If there is really not enough development power or will  to keep compatibility, than at least prepare for a major version bump, so that downstream API consumers can deal with it. I'm shocked that courier, a library which is exactly about library and version management, is itself not following something like semantic versioning.

**Comment by alexarchambault** [comment]
About binary compatibility, I've somehow dropped it for now, as the version numbers tell (milestones). I'll definitely re-instate it later on though.

**Comment by lefou** [comment]
> About binary compatibility, I've somehow dropped it for now, as the version numbers tell (milestones). I'll definitely re-instate it later on though.

Do you mean, re-instate backward compatibility to 2.0 or just to 2.1? If only the latter, than I suggest to bump to 3.0 instead.

**Comment by alexarchambault** [comment]
> Do you mean, re-instate backward compatibility to 2.0 or just to 2.1? If only the latter, than I suggest to bump to 3.0 instead.

I'm not sure yet… I try to follow "package version policy" overall, so `2.1` would be fine. But depending on the scale of the API changes (to come), `3.0` might be a better choice.

**Comment by lefou** [comment]
Thank you for the fix. I'll test the latest pre-release and report back.

**Comment by lefou** [comment]
Unfortunately, in coursier `2.1.0-M7-34-gf519b50a3`, pickling `core.Dependency` with upickle is still not straightforward. The companions `apply`-method which accepts a `MinimizedExclusions` is still not public, only the one which accepts a `Set[(Organization, ModuleName)]`. But there is no accessor to such a set in `MinimizedExclusions`. Without any symmetric API, it is at least unnecessary hard to map a `core.Dependency`. 

What is the reasoning for keeping `MinimizedExclusions` private to `core`?

**Comment by lefou** [comment]
Also, `MinimizedExclusions` itself isn't symmetic, but I could work around that like this:

```scala
implicit lazy val minimizedExclusionsFormat: RW[coursier.core.MinimizedExclusions] =
    upickle.default
      .readwriter[coursier.core.MinimizedExclusions.ExclusionData].bimap[
        coursier.core.MinimizedExclusions
      ](
        me => me.data,
        ed => new MinimizedExclusions(ed)
      )
  implicit lazy val exclusionDataFormat: RW[coursier.core.MinimizedExclusions.ExclusionData] =
    RW.merge(
      upickle.default.macroRW[coursier.core.MinimizedExclusions.ExcludeNone.type],
      upickle.default.macroRW[coursier.core.MinimizedExclusions.ExcludeAll.type],
      upickle.default.macroRW[coursier.core.MinimizedExclusions.ExcludeSpecific]
    )
```

This could be easier, when `MinimizedExclusions` would have a companion-`apply` accepting a `ExclusionData`. Currently, I need to use the constructor, hence the `new` and the manual mapping.

**Comment by alexarchambault** [comment]
> The companions `apply`-method which accepts a `MinimizedExclusions` is still not public,

That's an overlook, but the constructor is public.

> But there is no accessor to such a set in `MinimizedExclusions`

That's what `MinimizedExclusions#toSet` does, if I'm not mistaken.

> What is the reasoning for keeping `MinimizedExclusions` private to `core`?

IIRC, this was supposed to be kind-of an implementation detail, but it ended up not really being one…

**Comment by alexarchambault** [comment]
I'm not excluding re-working a bit things around `MinimizedExclusions`, so that it's effectively purely internal. The optimizations of https://github.com/coursier/coursier/pull/2442 looked interesting, but it might have been merged prematurely…

> Also, `MinimizedExclusions` itself isn't symmetic, but I could work around that like this:

That looks correct. Alternatively, you could serialize it as a `Set[(String, String)]`, via `MinimizedExclusions#toSet` / `MinimizedExclusions.apply(exclusions: Set[(Organization, ModuleName)])`.

**Comment by lefou** [comment]
> > Do you mean, re-instate backward compatibility to 2.0 or just to 2.1? If only the latter, than I suggest to bump to 3.0 instead.
> 
> I'm not sure yet… I try to follow "package version policy" overall, so `2.1` would be fine. But depending on the scale of the API changes (to come), `3.0` might be a better choice.

I find "package version policy" (PVP) pretty unsuited in Java/Scala land. It makes the first segment of the version (which should be better part of the name instead) pretty useless. Also, with tools like Maven and even Coursier and their established default handling for versions, it's pretty unusable. Take Scala 2.x as an example. It forced even a new scheme to encode the compatibility into the artifact name, instead of just dropping the "epoch" from the version.

**Comment by lefou** [comment]
* https://github.com/coursier/coursier/pull/2564
