### ISSUE TITLE
Unable to locate dependency when jar name doesn't match dependency ID (works in Ivy)

### ISSUE THREAD

**Issue by danxmoran** [coursier/coursier#260]
(Possibly related to #258, but I'm not sure) I've been playing with integrating coursier into a project at work, but I can't get around an error with one dependency.  I can't link directly to the project as it's private, but the problem is reproducible from the CLI by running:

```
> coursier fetch -r http://cogcomp.cs.illinois.edu/m2repo edu.illinois.cs.cogcomp:illinois-common-resources:1.4
  Error:
http://cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-common-resources/1.4/illinois-common-resources-1.4.jar: NotFound(http://cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-common-resources/1.4/illinois-common-resources-1.4.jar,Some(true))
```

I took a look in [the repository](http://cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-common-resources/1.4/) and saw that while there is a `illinois-common-resources-1.4.pom`, there is indeed no `illinois-common-resources-1.4.jar`.  Instead, there's a `illinois-common-resources-1.4-illinoisSRL.jar`.

I'm pretty new to working with Maven / Ivy at anything deeper than a surface level so I'm not sure if the mismatch in naming between `.pom` and `.jar` files should be considered a bug on the library publisher's part, but on a practical level this dependency has been working in vanilla SBT w/ Ivy so the error is blocking any potential migration to coursier for us.  Do you know what the problem might be?

P.S. this project looks like it could help solve a lot of annoyances for us, thanks for putting all the effort into it :)

**Comment by alexarchambault** [comment]
Looks like the `illinoisSRL` classifier is needed somehow... This works:
```
coursier fetch edu.illinois.cs.cogcomp:illinois-common-resources:1.4 -r http://cogcomp.cs.illinois.edu/m2repo -C illinoisSRL
```

Do you have more details about the dependency that pulled this particular one? Classifiers should be handled by coursier, but it's possible that you're running into a bug related to them...

**Comment by danxmoran** [comment]
Sure! Our actual dependency is on `edu.illinois.cs.cogcomp:illinois-nlp-pipeline:0.1.21`.

**Comment by alexarchambault** [comment]
I looked a bit at the dependencies of `edu.illinois.cs.cogcomp:illinois-nlp-pipeline:0.1.21`.

At some point, it depends on `edu.illinois.cs.cogcomp:illinois-common-resources:1.1` (with no particular classifier, via `edu.illinois.cs.cogcomp:illinois-ner:3.0.33` or `edu.illinois.cs.cogcomp:illinois-nlp-pipeline:0.1.21`) and `edu.illinois.cs.cogcomp:illinois-common-resources:1.4` (with classifier `illinoisSRL`, via `edu.illinois.cs.cogcomp:illinois-srl:5.1.13`).

As both land in the same resolution, version 1.4 ends up being chosen. But the standard JAR with no classifier is not available in this version, which makes the first dependency fail when fetching JARs. Version 1.5 is fine on the other hand, as it has JARs both with no classifier and with classifier `illinoisSRL`.

Do you know what version ends up being chosen with Ivy? (I haven't had the patience to check :-)

Some basic checking of the availability of artifacts during resolution (when chosing the versions) may be added soon (https://github.com/alexarchambault/coursier/issues/200). That could address that.

As a workaround, adding a dependency towards `edu.illinois.cs.cogcomp:illinois-common-resources:1.5` addresses the problem.

**Comment by danxmoran** [comment]
I believe version 1.1 ends up being chosen by Ivy (it's what shows up under "External Libraries" in IntelliJ, with no sign of 1.4).

I tried adding an explicit dependency on 1.5, but that produces a new error:
```
$ coursier fetch -r http://cogcomp.cs.illinois.edu/m2repo edu.illinois.cs.cogcomp:illinois-nlp-pipeline:0.1.21 edu.illinois.cs.cogcomp:illinois-common-resources:1.5
  Error:
http://cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-common-resources/1.5/illinois-common-resources-1.5-illinoisSRL.jar: NotFound(http://cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-common-resources/1.5/illinois-common-resources-1.5-illinoisSRL.jar,Some(true))
```
This one is bizarre because that JAR does exist at the URL it's printing.

**Comment by alexarchambault** [comment]
```
$ coursier fetch \
    -r http://cogcomp.cs.illinois.edu/m2repo \
    edu.illinois.cs.cogcomp:illinois-nlp-pipeline:0.1.21 \
    edu.illinois.cs.cogcomp:illinois-common-resources:1.5
```
works for me on both filled and empty caches.

What does `ls -lha ~/.coursier/cache/v1/http/cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-common-resources/1.5/` say? You're maybe running into an issue with the cache.

You can try wiping the content of `~/.coursier/cache/v1/http/cogcomp.cs.illinois.edu/m2repo/edu/illinois/cs/cogcomp/illinois-common-resources/1.5` too, although this is not fully satisfying.

**Comment by danxmoran** [comment]
```
total 948648
drwxr-xr-x  7 dan  staff   238B May 31 07:33 .
drwxr-xr-x  7 dan  staff   238B May 26 19:59 ..
-rw-r--r--  1 dan  staff     0B May 25 10:12 .illinois-common-resources-1.5-illinoisSRL.jar.error
-rw-r--r--  1 dan  staff    40B May 25 19:32 illinois-common-resources-1.5-illinoisSRL.jar.sha1
-rw-r--r--  1 dan  staff   463M Apr 14 21:26 illinois-common-resources-1.5.jar
-rw-r--r--  1 dan  staff   419B Apr 14 21:26 illinois-common-resources-1.5.pom
-rw-r--r--  1 dan  staff    40B Apr 14 21:26 illinois-common-resources-1.5.pom.sha1
```
Removing `.illinois-common-resources-1.5-illinoisSRL.jar.error` fixed the problem!  I checked the file before deleting it, and it was empty.

**Comment by alexarchambault** [comment]
Closing this. Feel free to re-open if you still run into this.
