### ISSUE TITLE
Error when running coursier on Linux aarch64

### ISSUE THREAD

**Issue by mkurz** [coursier/coursier#2636]
```sh
$ curl -fL https://github.com/coursier/launchers/raw/master/cs-aarch64-pc-linux.gz | gzip -d > cs && chmod +x cs
...
$ ./cs 
Fatal error: Failed to create the main Isolate. (code 8)
```
I am running Asah Linux, which basically is Arch Linux ARM, on Apple Silicon (MacBook Pro M1):
```sh
$ uname -a
Linux mkurz-macbook-pro 6.1.0-asahi-2-1-edge-ARCH #2 SMP PREEMPT_DYNAMIC Wed, 14 Dec 2022 14:33:17 +0000 aarch64 GNU/Linux
```
The error message [originates in graal here](https://github.com/oracle/graal/blob/b6e1c8d0844c475c97ad7ef52796b192b59ef2fc/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/JavaMainWrapper.java#L386-L388).
However, I think you don't use latest graal for building the native images, maybe it would work with the latest one?

**Comment by mkurz** [comment]
Is it possible this is related to `sbtn` not having being available for aarch64 linux, like described here: #2358?

**Comment by lwronski** [comment]
> Is it possible this is related to `sbtn` not having being available for aarch64 linux, like described here: #2358?

Hi @mkurz, I don't think so, in this issue #2358 user be able to run corusier but fail when trying to download some apps, but in your case it throws error when starting cs.

I think a good test would be if you tried to build `cs` at Asah Linux. 
```
$ git clone --recursive https://github.com/coursier/coursier.git
$ cd coursier
$ ./mill -i show cli.nativeImage
```

If it works, it means that Scala CLI and Corusier have some misconfiguration during the building native launcher for aarch64 linux.

You can also update `graalVMVersion` to `22.3.0` and check what happen - [Deps.graalVmVersion](https://github.com/coursier/coursier/blob/f730535d8d9c8bdb885d353c5665a6785510cf7f/project/deps.sc#L74)

**Comment by mkurz** [comment]
So... I was able to build _and successfully run_ the cs binary on my machine, without changing anything. I just ran `./mill -i copyLauncher artifacts/` in a fresh clone (and git submodules initialized :wink:)

So that made me wonder what is going on. I tried to analyze my produced binary and compared it to the binary you provide... Because I am not an expert in that field, it took me quite a while to figure things out. First of all I thought it has something to do with the linked libraries (running `ldd ...` helped), because on my Arch linux, it does not link certain libraries, but it turned out that is because `gcc` does not do that for certain libs in newer version since glibc bundles them now, etc. (at least that is what I understood)...
Anyway, it turned out the problem is that the kernel of the OS I am running (Asahi Linux / Arch linux) on my machine (Apple M1 Pro) uses a page size of 16k (you can read more about that page size stuff [here](https://github.com/AsahiLinux/docs/wiki/Broken-Software)). As far as I understood most Linux kernels run with 4k page size, so does the GitHub actions VMs, and also the aarch64 virtual machine that is started within the workflow of this repo that produces the Linux aarch64 ELF binary.
The GraalVM's native image tool, by default tells the binary it produces that it will be run on a system with a page size that has the same value of the system it produced the binary. Since the binary is produced in a GHA vm with a pagesize of 4k and my system runs with 16k, this is the reason why it fails. When I build the binary myself, it of course worked because graal encodes in the binary the page size of the target system will be 16k, which of course is correct because I run it on the same machine :wink: 

Now, I figured out, that the native image tool as a options that helps here (`native-image --expert-options-all`):
```
  -H:PageSize=0                                Define PageSize of a machine that runs the image. The default = 0 (== same as host machine page size).
```
So I did some testing:
When I build an image **on my system** with `-H:PageSize=4096`, the binary fails with the exact same error message posted in my initial comment. That confirms what I described above, with this setting I basically emulated what happened on the GitHub vm.

So I wanted to be sure that my thoughts are correct, so I went ahead and produced a binary with a GitHub actions workflow, but using a page size of `-H:PageSize=16384`. So if I download that binary, it should then run on my machine. And it did! This was the workflow I was using: https://github.com/mkurz/coursier/actions/runs/3761717494
Here is the diff to the current main branch, the only relevant thing (besides removing lots of stuff from the GHA config), is the page size change: https://github.com/coursier/coursier/compare/main...mkurz:coursier:ubuntu_22.04_aarch_my_repo#diff-5e3e860f0a901409d66adfaf131a10d6a8e5d515df411940d1cb75e0ec2fa01f

Now, the question for me was, can we use a page size that fits both 4k and 16k kernels?
I gave it a try and when using `-H:PageSize=65536` or `-H:PageSize=16384` I could run the binary on my machine as well as on the GitHub vm. For that I did build the binaries locally and just pushed them and let the workflow execute them.
For 64k the workflow was: https://github.com/mkurz/coursier/actions/runs/3761943078/jobs/6394158112
For 16k the workflow was: https://github.com/mkurz/coursier/actions/runs/3761974693/jobs/6394216126
(Igorne that the workflow failed, that's is because by just calling `cs` the exit code is not 0)

So, I am wondering what to do now? Do you think it is possible that we just pass `-H:PageSize=16384` or `-H:PageSize=65536` when building the aarch64 linux binary? If think that should work. (I think actually we don't need to set the page size to be 64k, since i don't really think there are arm64 os out there with that kernel size.) 
Also https://github.com/AsahiLinux/docs/wiki/Broken-Software says: 
> Though the default for AArch64 compilers is to produce ELF files with sections aligned to 64K for compatibility with all AArch64 machines...

So it seems if graal handles everything correctly nothing should speak against that (?) However, even if that works, there may is a pull request that works against that idea, see https://github.com/oracle/graal/pull/5605 - see my comment there, my fear is that even if 4k kernels can run the 16k "graal native image" produced binary, that pr might makes it fail....

So what do you think? Maybe you guys know more about this stuff than I do.
(However, at least I know what's going on and can build my own binary for now)

**Comment by mkurz** [comment]
I also asked in the Asahi Linux chat:
```
<mkurz> If I produce a ELF binary with a page size of 64k, in theory that should run on all aarch64 machines, no matter if their kernel has a page size of 4k, 16k or 64k. Is that correct?
<tpw_rules> mkurz: that is a very vague question
<tpw_rules> the ELF section alignment has to be 64k for the program to load into memory
<tpw_rules> but once it loads, it can check the page size and do whatever it wants. or ignore it and hope page-size-dependent operations work
```
So not 100% sure, but if GraalVM does everything correct at runtime, we might be lucky and everything works by just passing `-H:PageSize=16384` or `-H:PageSize=65536`.
