### ISSUE TITLE
cs setup can't find a JVM

### ISSUE THREAD

**Issue by w-r-z-k** [coursier/coursier#2678]
When I run the setup process from the website:

```
$ curl -fL https://github.com/VirtusLab/coursier-m1/releases/latest/download/cs-aarch64-apple-darwin.gz | gzip -d > cs
$ chmod +x cs
$ ./cs setup
```

it says:

```
Checking if a JVM is installed
JVM adopt@1.8+ not found in index: JVM adopt not found
```

I thought the point of coursier was so that you didn't need to deal with setting up java.  The website says "They will also install a JVM if none is found on the system."

**Comment by tgodzik** [comment]
Thanks for reporting! Looks like we don't have adopt available in the indexes, we should most likely change the defaults there (I think Zulu should be present.)

**Comment by julienrf** [comment]
I agree with you Tomasz, is this something you could take care of?

**Comment by julienrf** [comment]
Possible workaround: run `cs setup --jvm 17`

**Comment by jpassaro** [comment]
bumping this, ran into it today and it's pretty confusing on its face. fortunately @julienrf's workaround was effective. I might suggest, if it's not too hard, special-casing the situation where the default can't be found and making some explicit user recommendations (e.g. explicit `--jvm`, check network connection, report as a bug, etc)
