### ISSUE TITLE
Retry when fetching artifact from remote resolver (maven for example)

### ISSUE THREAD

**Issue by hagay3** [coursier/coursier#2733]
Hi,
There is any retry mechanism built in for coursier?
also mentioned here #2217 
While coursier fetches artifacts from resolvers it fails on the first attempt and then fails the whole build:

[2023-04-04T12:37:08.627Z] 	Server access Error: Connection timed out (Connection timed out) url=https://XXXX.XXXX.XXXX/repository/maven-public/org/scala-sbt/sbt/1.6.2/sbt-1.6.2.pom

Gradle already doing retries automatically:
https://docs.gradle.org/current/userguide/dependency_resolution.html#sub:http-retries

Also, some tech notes might help and I'll be happy to add this feature myself.
Thanks

**Comment by adpi2** [comment]
Hi @hagay,

For the context, I think you should mention your original issue comes from sbt: https://github.com/sbt/sbt/issues/7200.

There already is a retry mechanism in Coursier CLI (see  [coursier.cli.resolve.ResolveParams](https://github.com/coursier/coursier/blob/33eac58f8a8695e47e4a1fe6d3a4c9951becc6b6/modules/cli/src/main/scala/coursier/cli/resolve/ResolveParams.scala#L21) and [coursier.cli.resolve.Resolve](https://github.com/coursier/coursier/blob/33eac58f8a8695e47e4a1fe6d3a4c9951becc6b6/modules/cli/src/main/scala/coursier/cli/resolve/Resolve.scala#L174-L220)) but not in `coursier.Resolve`, which is the core API of Coursier, used by `sbt-coursier`.

To solve this we can:
- Re-implement the retry mechanism in `sbt-coursier` somewhere around [here](https://github.com/coursier/sbt-coursier/blob/71d4f2c969a94f847ed3ca8e7e98c3bc71a28621/modules/lm-coursier/src/main/scala/lmcoursier/internal/ResolutionRun.scala#L82-L122),
- Add retry as a feature of the core API in `coursier.Resolve`.

WDYT @alexarchambault, Do you think `coursier.Resolve` should be able to retry on `ConnectException`?

**Comment by hagay3** [comment]
@alexarchambault @adpi2 
Hi, there are any more thoughts regarding the issue?

**Comment by eed3si9n** [comment]
For the record I wrote this 2 weeks ago in https://github.com/coursier/coursier/issues/2217#issuecomment-1496606522:

> As I commented in the sbt ticket Coursier already retries for some kind of error https://github.com/coursier/coursier/commit/869d7c628edcd9315a43f75d87614198146ce6bb, so I feel like this could be something a willing contributor could implement without knowing too much about the rest of Coursier code base.

We certainly can keep reimplementing retries outside of Coursier, but I feel like wider audience would benefit if this could be handled at the Downloader level.

https://github.com/coursier/coursier/blob/ddd165c54f366fc7a60379e31c6e7994399c84f3/modules/cache/jvm/src/main/scala/coursier/cache/internal/Downloader.scala#L774-L776
