### ISSUE TITLE
Versions from BOM pattern overrule those defined in the project or its parent. (Opposite of Maven)

### ISSUE THREAD

**Issue by gatisnolv** [coursier/coursier#2790]
I think I've stumbled on a bug. As the title says, versions for artifacts defined in a BOM source overrule those defined in the current projects pom (or its parent) which uses the BOM.
This is opposite to how Maven does it - i.e. the current project's or its parents versions take precedence.
Since this is the behavior irrespective of whether the project or the BOM has a higher version, it is clear that this is NOT an example of the difference in version handling between [Coursier](https://get-coursier.io/docs/other-version-handling) and [Maven](https://github.com/coursier/coursier/issues/418#issuecomment-487800709) (latest-wins vs nearest-wins), but a separate issue.

Setup: Maven 3.9.0, Coursier 2.1.4
Note: I couldn't figure out how to directly run `cs resolve` against the local Maven repository, so to serve it on localhost, from `~/.m2/repository` run something like `npx http-server` (or whatever web server you prefer), making it available on http://localhost:8080/

Minimal example: https://github.com/gatisnolv/coursier-bom-issue

Reproduction:
Run `mvn install` in each of `./BOM`, `./parent`, `./parent/child` directories to install the projects to the Maven local repository.
Observe the difference in result when running inside of the `./parent/child` directory `mvn dependency:tree` against the output of `cs resolve -q --cache "./" --repository "http://localhost:8080/" org.fake:child:1.0-SNAPSHOT; rm -rf http*`

Note: in the `cs resolve` command I specify to use as cache the current directory, and do an `rm -rf http*` after it's done to get updated results in the next run if I change something in the poms (and reinstall them again with `mvn install`).

**Comment by ppkarwasz** [comment]
We have a sligthly different problem, but it also affects the version resolution algorithm.
As reported by one of our users (cf. apache/logging-log4j2#2065) if the parent defines:


```xml
<properties>
  <slf4j.api>2.0.9</slf4j.api>
</properties>
<dependencies>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-api</artifactId>
      <version>${slf4j.version}</version>
    </dependency>
</dependencies>
```

and the child overwrites the property:

```xml
<properties>
  <slf4j.version>1.7.25</slf4j.version>
</properties>
```

then Maven with choose version `1.7.25` while Coursier will choose version `2.0.9`.

Coursier seems to resolve the `${slf4j.version}` placeholder **eagerly**, when computing the model of the parent POM, while Maven does it **lazily** after _"inheritance assembly"_ (cf. [Maven Model Builder](https://maven.apache.org/ref/3.9.6/maven-model-builder/)).

**Comment by lefou** [comment]
@ppkarwasz Please open a new separate issue, as it does not look like the same issue as the OP.

**Comment by ppkarwasz** [comment]
@lefou, I submitted #2906, thanks

**Comment by alexarchambault** [comment]
@gatisnolv FYI, it seems this is fixed on the current `main` branch (and in the upcoming coursier `2.1.17`).

Former coursier versions (up to `2.1.16`) used to give
```text
$ cs resolve -r m2Local org.fake:child:1.0-SNAPSHOT
org.fake:child:1.0-SNAPSHOT:default
org.slf4j:slf4j-api:2.0.5:default

$ cs resolve -r m2Local org.fake:child:1.1-SNAPSHOT
org.fake:child:1.1-SNAPSHOT:default
org.slf4j:slf4j-api:2.0.5:default
```

(`org.fake:child:1.1-SNAPSHOT` is the project under `parent/child` in your [repro repo](https://github.com/gatisnolv/coursier-bom-issue), with [this line](https://github.com/gatisnolv/coursier-bom-issue/blob/9a5238694f14ce88be627a5e5e16f2344f4d9c29/parent/child/pom.xml#L40) uncommented)

Current `main` and upcoming `2.1.17` give
```text
$ cs resolve -r m2Local org.fake:child:1.0-SNAPSHOT
org.fake:child:1.0-SNAPSHOT:default
org.slf4j:slf4j-api:2.0.6:default

$ cs resolve -r m2Local org.fake:child:1.1-SNAPSHOT
org.fake:child:1.1-SNAPSHOT:default
org.slf4j:slf4j-api:2.0.7:default
```
