### ISSUE TITLE
Can not find sisu-guice or jdeb in Play project created by Activator

### ISSUE THREAD

**Issue by mslinn** [coursier/coursier#282]
Just tried Coursier 1.0.0-M12 with the default project created by Activator 1.3.10. I created the project this way:

```
$ activator new test play-scala
```

Coursier could not find:

```
[error]   /opt/activator-dist-1.3.9/repository/org.sonatype.sisu/sisu-guice/3.1.0/jars/sisu-guice.jar
[error]   /opt/activator-dist-1.3.9/repository/org.vafer/jdeb/1.3/maven-plugins/jdeb.jar
```

I found `sisu-juice` in https://repo1.maven.org/maven2/org/sonatype/sisu/sisu-guice/3.1.0/sisu-guice-3.1.0.jar.

`default-test-build-compile-internal.xml` says `<metadata-artifact status="no" details="" size="4791" time="0" location="/home/mslinn/.ivy2/cache/org.vafer/jdeb/ivy-1.3.xml" searched="false" origin-is-local="true" origin-location="/opt/activator-dist-1.3.7/repository/org.vafer/jdeb/1.3/ivys/ivy.xml"/>`

After `rm -rf ~/.ivy2` and retrying, no change

**Comment by zoltanmaric** [comment]
To me this problem occurred because I had installed [Lightbend Activator](https://www.lightbend.com/activator/download) and I suppose it somehow messed up my `sbt` installation so it thought that its ivy cache was in the directory of `activator-dist`. I can see you're getting the same error messages pointing to your activator installation directory.

**Comment by mslinn** [comment]
Yes I noticed those error messages. My Ivy cache seems fine, because SBT is able to work with the same projects that coursier has problems with. Has anyone actually tried to duplicate this problem to see for themselves? It is a shame that Coursier still does not work with Activator projects.

**Comment by zoltanmaric** [comment]
I had the exact same messages (although the path was different, because my `activator-dist` folder was elsewhere). After removing the `activator-dist` folder entirely, everything worked.

**Comment by mkotsbak** [comment]
See https://github.com/alexarchambault/coursier/issues/271#issuecomment-239612692

**Comment by alexarchambault** [comment]
I haven't tried that again, but 1.0.0-M13 includes a better Ivy pattern handler, that should be fine with the repositories that activator globally adds.

**Comment by mslinn** [comment]
M13 fails exactly the same as M12.

**Comment by mslinn** [comment]
M15 fails exactly the same as previous versions

**Comment by hhandoko** [comment]
I experience the same problem:

- Activator `1.3.12`
- Coursier `1.0.0-M15`
- Play `2.5.10` project with SBT `0.13.13`

**Comment by alexarchambault** [comment]
The activator seems to be at the origin of this one (that's what I remember of my latest attempt to fix it, a few weeks ago). Disabling ought to make your projects work.

**Comment by hhandoko** [comment]
@alexarchambault how did you disable Activator? I've removed Play / Activator folder from PATH, but Coursier seems to keep a pointer to the Activator cache for some reason.

**Comment by alexarchambault** [comment]
It was something under `~/.sbt` IIRC... Maybe `~/.sbt/repositories`.

**Comment by hhandoko** [comment]
Just an update @alexarchambault ... You are correct, it is fixed after the Typesafe local repositories was commented out.

**Comment by alexarchambault** [comment]
Closing this. There were workarounds, and I'm not sure this is still an issue.
