### ISSUE TITLE
Request for clarification and to cut a new release

### ISSUE THREAD

**Issue by lefou** [coursier/coursier#2927]
Hi, I just stumbled over PR https://github.com/coursier/coursier/pull/2891 when I was in search for some way to check a set of dependencies for consistency, considering their transitive dependencies with `provided`-scope. 

My use case is to detect, whether a Mill plugin is compatible to the current Mill version. Mill plugins typically declare their Mill-dependencies with `provided`-scope.

In detail, I want to detect, that a plugin which was build against a newer version of the API (e.g. 0.11.6) might be in fact incompatible to the currently used API (e.g. 0.11.5). The idea was to add some version range for the currently running Mill API, e.g. `[0.11.0,0.11.5]` and also add the plugins. In case a plugin was build against a newer version, the version reconciliation process as outlined in https://get-coursier.io/docs/other-version-handling should fail due to the mismatch of the version range and the actual required API version. But the whole idea is only working if coursier also takes the `provided`-scoped dependencies into account.

So here are my two questions:

1. Is the idea from above already possible with PR #2891 ? If not, what else is missing? 

2. Can we get a new release including this PR?

Thank you!

_Originally posted by @lefou in https://github.com/coursier/coursier/issues/2891#issuecomment-1890989964_

**Comment by alexarchambault** [comment]
> 1. Is the idea from above already possible with PR https://github.com/coursier/coursier/pull/2891 ? If not, what else is missing?

It seems it should

> 2. Can we get a new release including this PR?

A release with that should have been cut a long time ago, that's an oversight, sorry about it

**Comment by alexarchambault** [comment]
`2.1.9` [is being built right now](https://github.com/coursier/coursier/actions/runs/7823126032)

**Comment by alexarchambault** [comment]
So [`2.1.9`](https://repo1.maven.org/maven2/io/get-coursier/coursier_2.13/2.1.9/) is out

**Comment by kubukoz** [comment]
Can this be closed?

**Comment by lefou** [comment]
Yeah.
