### ISSUE TITLE
`cs` command not available after `brew install`

### ISSUE THREAD

**Issue by mcanlas** [coursier/coursier#3063]
I feel like I’ve installed coursier before and this worked…

But when I do “brew install coursier”, it seems to install fine and symlink the file `coursier` but not `cs` as the docs would seem to imply

Should the brew formula be doing this or is something amiss??

**Comment by mcanlas** [comment]
I was mistaken. Apparently these two brew scripts are different

```
brew install coursier

brew install coursier/formulas/coursier
```

**Comment by tgodzik** [comment]
Looks like it install cs correctly now as recently tested.
