### ISSUE TITLE
Ban Scala 3.6.0 from `cs update`

### ISSUE THREAD

**Issue by s5bug** [coursier/coursier#3103]
From the Scala Discord:

> Hi all,
some of you might have seen that Scala 3.6.0 is available on Maven Central, however it was accidentally released (instead of 3.6.0-RC1) and should not be used by anyone and especially you should avoid releasing libraries with that version.
>
> We will fast-track 3.6.1 to replace it, and we'll also fast-track followup 3.6.x releases if needed to promptly address regressions.
>
> Scala Steward updates for both those versions has been disabled, so you should not get automatic updates for them.
>
> We will follow up with more information and a post mortem next week.

`cs update` currently updates to 3.6.0, which probably should be prevented.

**Comment by tgodzik** [comment]
Thanks for reporting! We don't have a way to blacklist releases, but once 3.6.1 is released (which is being worked on right now) the update will skip 3.6.0 which is broken.

Also, cs actually install Scala CLI underneath, which uses by default the current version of the Scala compiler, but it is not broken itself.
