### ISSUE TITLE
Coursier launcher for 2.1.15 requires Java 17

### ISSUE THREAD

**Issue by lefou** [coursier/coursier#3140]
The latest coursier launcher at https://github.com/coursier/launchers/raw/master/coursier, which is version 2.1.15, requires at least Java 17.

There is no mention of the change in minimal required Java version in the release info.

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/issues/3146 ought to fix that

**Comment by lefou** [comment]
Thank you!
