### ISSUE TITLE
Confused about installation versions

### ISSUE THREAD

**Issue by imdaveho** [coursier/coursier#3194]
Repro steps: (as of 12/19/2024)

install cs using official script
run `cs install mill`
run `mill --version`

Expected:
mill version 0.12.3 as per this PR: https://github.com/coursier/coursier/pull/3188

(edit: the PR did nothing but bump up the version in .mill-version; I could have sworn there was another update that was more meaningful than that but I could be thinking of something else)

Actual:
mill version 0.11.13

------------------------------------------
Background context:

I'm new to the java/scala ecosystem (honestly I tried circa 2012 but gave up because of the various forms of indirection). For one reason or another, I'm in a position to try again and hoping that the overall ecosystem has matured (which is a definite improvement over 2012). However, I also posted regarding `sbt` and the annoying warning regarding giter8 when running `sbt new` (https://github.com/coursier/coursier/issues/3045) so I decided to give `mill` a try especially because I like the fact that `build.sc` uses scala to build scala;  but that is neither here or there. I like the fact that `cs` is a standard in package mgmt for scala et al. but just like the whole dependency chain of ownership between `sbt`, `giter8`, `coursier`, `maven central`?, etc. I don't know how issues and updates get propagated.

Issue/question:

* How is it that `mill` is not the most up-to-date version after running `cs install mill`? 
* (possibly out of scope) What are the chains of propagation in order to keep things updated?

**Comment by lefou** [comment]
* #3188 updates the Mill version used to build coursier itself
* For Mill installation refer to https://mill-build.org/mill/cli/installation-ide.html
* Mill installed via `coursier` is not recommended (https://mill-build.org/mill/cli/installation-ide.html#_coursier_unsupported)
* To update your locally used Mill version, just bump the version in your local `.mill-version` file
