### ISSUE TITLE
Support for shorter dependency descriptors

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#324]
Briefly discussed at Scala Up North with @MasseGuillaume.

It would be cool to allow users to specify a dependency like `typelevel/cats`, for `"org.typelevel" %% "cats" % "latest.release"` (with support for `latest.release` to be added to coursier too). The [scala index](https://index.scala-lang.org/) could be used to get the module org and name `"org.typelevel" %% "cats"` from `typelevel/cats` - for public repositories at least (they need to be published on Central too, I guess).

In particular, that would allow to seamlessly launch applications like

```
$ coursier launch lihaoyi/Ammonite
```

Support for only the project name (just `cats` or `Ammonite`) could be added too, like

```
$ coursier launch Ammonite
```

Lastly, for projects publishing several modules, this kind of syntaxes could be supported:
- `http4s/http4s->http4s-circe` for `org.http4s:http4s-circe_2.11:latest.release` (`http4s/http4s` resolved to `"org.http4s" %% ...` with the scala index, and the part after `->` being interpreted as a specific module of it),
- or `http4s->http4s-circe` for `org.http4s:http4s-circe_2.11:latest.release` (like before, with just `http4s` resolved to `"org.http4s" %% ...` too),
  which would allow things like

```
$ coursier fetch http4s/http4s->http4s-circe
$ coursier fetch http4s->http4s-circe
```

**Comment by alexarchambault** [comment]
To handle the same syntax for private repositories (e.g. in corporate settings), we could either:
- get those infos directly from repositories (as suggested by @djspiewak), or
- crawl a repository and get those infos from its metadata.

Getting infos from repositories would require launching SBT, and have it output the relevant things (org / name for each published sub-project). Which may be a bit cumbersome, as it requires launching SBT for each project we want to index.

Crawling a repository may only work for Maven repos (via the SCM infos of the POMs), not for Ivy ones.

As getting those infos is a bit cumbersome no matter what, these could fetched only from time to time, and made available to possible users, by putting those in a single JAR and publishing it to a repository. That way, users would just have to reference the repository and module of the index. This could possibly be made so by some config files under `~/.coursier`. These JAR with the infos would be cached like any JAR, and could be updated from time-to-time via the already existing TTL mechanism say.

**Comment by olafurpg** [comment]
Instead of trying to automatically figure out maven coordinates with for example scaladex, would it be possible to support configuration for aliases? For example, 

```
$ cat ~/.coursier/coursier.conf
aliases = [
  {
    name = "scalafmt",
    groupId = "com.geirsson",
    artifactId = "scalafmt-cli",
    main = "org.scalafmt.cli.Cli",
    jvmOptions = "-Xss8m"
  }
]
```

Then you could run 

```
sudo coursier bootstrap --standalone scalafmt -o /usr/local/bin/scalafmt
# OR with hypothetical install/upgrade commands
coursier install scalafmt # puts it in ~/local/bin or wherever you want according to coursier.conf
coursier upgrade scalafmt # if artifact is on maven, use latest version in maven-metadata.xml
coursier upgrade scalafmt 1.0 # manually provide version, this is unnecessarily complex with homebrew
```

I imagine that it might be possible to create a decentralized system for sharing coursier.conf aliases in a similar way as homebrew works.
```
coursier add-alias olafurpg/scalafmt
# fetches from olafurpg/coursier-scalafmt,
# similar to homebrew tap olafurpg/scalafmt
```
There could be a centrally managed collection of aliases in `coursier/aliases`. However, I believe the decentralized model would more scalable. It's annoying to wait for PR approval when you're publishing your first cli app.

PS. I have given up on supporting homebrew for scalafmt https://github.com/scalameta/scalafmt/commit/0cf3b79be32ed084875e167a52af31272c577570 I really believe coursier offers a much more better way to share and consume cli apps on the JVM. I'm happy to help contribute on this front.

**Comment by alexarchambault** [comment]
Something along those lines should totally be done (after 1.0 final is out). This is the kind of things that were initially discussed at Scala Up North - @djspiewak was interested in that kind of way of handling aliases IIRC.

brew-like repositories look fine. This could also handle private repositories (both GitHub and Nexus ones, for the aliases and the artifacts).

The scaladex support could be given a lower priority and / or be triggered by a `--scaladex` flag. (The scaladex handler could also be made more interactive at the same time, like offering to choose among the scaladex search results...)

**Comment by olafurpg** [comment]
> The scaladex support could be given a lower priority and / or be triggered by a --scaladex flag. (The scaladex handler could also be made more interactive at the same time, like offering to choose among the scaladex search results...)

I agree. 

I was thinking about the syntax of the configuration. It might be beneficial to support something lightweight that handles the most common cases (published to maven, no custom jvm options) and something more verbose but flexible. Example 
```conf
aliases {
  scalafmt = "org:artifact:version@com.example.Main" # lightweight
  scalafmt-nightly { # verbose, but more flexible
    org = "com.foo"
    artifact = "bar"
    resolver = "bintray:scalameta/maven"
    password = ${?NEXUS_PW}
  }
}
```

**Comment by alexarchambault** [comment]
Initial issue fixed by https://github.com/coursier/coursier/pull/385.

**Comment by olafurpg** [comment]
Would it be possible to host the aliases/metadata in the original repo? That is, when users run `coursier install scalameta/scalafmt` that would fetch necessary metadata from a `.coursier` file in the scalameta/scalafmt repo. We are experimenting with a similar approach in https://github.com/densh/scala-native-cli (installing from [`.scalanative`](https://github.com/densh/scala-native-cli-test/blob/master/.scalanative) files)

**Comment by alexarchambault** [comment]
@olafurpg I guess that could be added, yeah. The scaladex support works this way (fetches / caches an intermediate file, that contains the coordinates of the actual dependency).

**Comment by olafurpg** [comment]
It would be nice as the tooling author to have the ability to specify the exact version, org, artifact, main class and optionally jvm options. `coursier install scalafmt` currently fetches scalafx and then fails to find a main class.

So far, however, it's been working fine to generate the full coordinates in CI and let users copy-paste the installation command from the docs http://scalameta.org/scalafmt/#Coursier

**Comment by alexarchambault** [comment]
`coursier launch scalafmt` fetches scalafx because it's the first entry that the scaladex returns:
```
$ curl https://index.scala-lang.org/api/search\?q\=scalafmt\&target\=JVM\&scalaVersion\=2.11.11
[{"organization":"scalafx","repository":"scalafx",
...
```

**Comment by olafurpg** [comment]
Yeah, I know 😞 The search relevance will hopefully get better soon https://github.com/scalacenter/scaladex/issues/389#issuecomment-308341744 

Even if scaladex search relevance improves, I'm not sure if it will be able to handle tricker cases like custom main like here http://scalameta.org/scalafmt/#Nailgun

**Comment by MasseGuillaume** [comment]
weird this was supposed to be fixed: https://index.scala-lang.org/search?q=scalafmt.

let me see what's wrong.

I like olaf's approach too. the only issue I see is this can get out of sync. one can release a new version an forget to update the meta file.

**Comment by olafurpg** [comment]
The meta file can be generated on sbt load to keep it in sync.

Automatically finding the right artifact from scaladex is quite challenging, for example in scalafmt it should be the `scalafmt-cli` module (out of ~3-4 modules) and main `org.scalafmt.cli.Cli` (out of two mains, can't be auto-detected). I admit it's a bad idea to have two mains, but it would be nice that if it wasn't a problem.

**Comment by dwijnand** [comment]
As described in Alex's ScalaDays talk this now exists, using as the central source of descriptors the https://github.com/coursier/apps repo but also the ability to add your own (ala "brew tap").
