### ISSUE TITLE
[help] How to skip or speed up sbt first boot phase?

### ISSUE THREAD

**Issue by xsy233** [coursier/coursier#344]
It seems sbt will take a long time to finish a fresh build without ~/.ivy2/cache

To my knowledge, sbt will first resolve and download scala and scala-sbt dependencies, then the plugins, then the other project dependencies.

Using coursier to resolve and fetch artifacts will be much fatser, but the sbt first boot phase sometimes takes more time than building the project.

I was wondering if you have any idea how to use some pre-built utils like a standalone coursier(generated by -s) to fetch scala and scala-sbt dependencies(with related scalaVersion and sbt.version respectively), then we can immediately use coursier for fetching.

**Comment by nartamonov** [comment]
It is well-known problem which (if I understand it correctly) have not effective solution yet. If you have multi-module project you may try cached resolutions as explained [here](https://github.com/sbt/sbt/issues/413).

**Comment by alexarchambault** [comment]
coursier now has a [custom sbt launcher](https://github.com/coursier/coursier/blob/master/csbt), which allows to handle all resolutions. It's quite underdocumented for now. Run `./csbt` from the [`demo-csb` branch](https://github.com/coursier/coursier/tree/demo-csbt) for an example (see the commit specific to this branch for the setup).

Beware that is still suffers [a few flaws](https://speakerdeck.com/alexarchambault/lightweight-data-ops-and-seamless-app-distribution-with-coursier?slide=15) though.
