### ISSUE TITLE
Support ConflictManager.strict similar to Ivy

### ISSUE THREAD

**Issue by ngbinh** [coursier/coursier#349]
We enforce explicit libraries override by having this setting in our sbt build.

``` scala
  private lazy val conflictMangerSettings: Seq[Setting[_]] = Seq(
    conflictManager := ConflictManager.strict.copy(organization = "^(?!org\\.scala-lang|org\\.scala-js).*$"),
    // scala library eviction
    ivyScala := ivyScala.value map {
      _.copy(overrideScalaVersion = true)
    },
    evictionWarningOptions in evicted := EvictionWarningOptions.default.withWarnScalaVersionEviction(false)
  )
```

Looks like `coursier` doesn't respect that. Is there a way to have the same behavior back?

**Comment by ngbinh** [comment]
is there anything I can do to help on this? I had to switch back to old ivy because of this. :(

**Comment by ngbinh** [comment]
Any updates on this issue?

**Comment by jon-morra-zefr** [comment]
+1

**Comment by alexarchambault** [comment]
This is fixed now. From the CLI, use the [`--strict`, `--strict-include`, and `--strict-exclude` options](https://github.com/coursier/coursier/blob/74617f052d126958d3e183a2f37572a595010308/doc/website/blog/2019-07-12-2.0.0-RC1.md#strict-conflict-manager).

With sbt-coursier, [enable the strict conflict manager](https://github.com/coursier/sbt-coursier/blob/7481329c8282a120903f9d07474c4b7ddda810e6/modules/sbt-coursier/src/sbt-test/shared-2/strict-conflict-manager/build.sbt#L8), and optionally force versions via `dependencyOverrides` to ignore conflicts for specific modules.

**Comment by ngbinh** [comment]
Awesome, thanks!
