### ISSUE TITLE
How to specify JVM options when using `coursier launch`?

### ISSUE THREAD

**Issue by nartamonov** [coursier/coursier#357]
I want to specify a few JVM options (like `-Xmx`, `-Xms`, `-Dprop=value`, and so on) to my app which launched by `coursier launch`. Is it possible?

**Comment by alexarchambault** [comment]
Not currently, but it shouldn't be hard to support (along the lines of https://github.com/lihaoyi/Ammonite/commit/7b0680036a99c75a16d2a460b5a5c5dbb61edc10 in Ammonite).

**Comment by alexarchambault** [comment]
One can pass Java options by prefixing them with `-J`. Also, `$JAVA_OPTS` is passed as is to `java`.

**Comment by alexander-myltsev** [comment]
> One can pass Java options by prefixing them with `-J`. Also, `$JAVA_OPTS` is passed as is to `java`.

Hi! @alexarchambault I'm trying to launch [`almond-spark`](https://almond.sh/docs/0.14.0-RC14/usage-spark). There is [a nasty workaround] to make `spark` work by adding Java opts. What parameters should I add to 

```bash
$ cs launch --use-bootstrap almond:0.14.0-RC15 --scala 3.3.3 -- --install
```

so Scala kernel hooks proper JAVA_OPTS?

**Comment by n0egen** [comment]
You can add `--java-opt` (after `--`) to pass Java options into almond, eg.

`./coursier launch --use-bootstrap sh.almond::launcher:0.14.0-RC15 -- --scala 3.3.3 --java-opt -Xmx64g --install`
