### ISSUE TITLE
Coursier does not resolve correctly sbt-plugins?

### ISSUE THREAD

**Issue by jvican** [coursier/coursier#370]
I have a custom sbt plugin which is _not_ uploaded to the official sbt repo. This plugin is available in a bintray organization. This plugin depends on other plugins, thus my build adds plugins both in `build.sbt` and `plugins.sbt`.

In both sbt files, I add the following line:

```
resolvers += Resolver.bintrayIvyRepo("scalaplatform", "tools")
```

Theoretically, coursier should able to resolve the sbt plugin. However, it doesn't. It looks for `https://dl.bintray.com/scalaplatform/tools/ch/epfl/scala/sbt-release_2.10_0.13/1.0.6/sbt-release-1.0.6.pom` instead of the correct url `https://dl.bintray.com/scalaplatform/tools/ch.epfl.scala/sbt-release_2.10_0.13/1.0.6/sbt-release-1.0.6.pom`. That is, the organization is not split into different folders. As a result, when coursier is enabled, the project fails. If I disable it, sbt successfully resolves it.

Am I doing something wrong or is this a known limitation of coursier? Let me know if I can provide more valuable information.

**Comment by oswaldo** [comment]
I see the same behaviour on 1.0.0-M14.
Had a build.sbt with the line `resolvers += Resolver.jcenterRepo`, which works with the default sbt/ivy but it only worked with coursier when I added `jcenter: http://jcenter.bintray.com/` to `~/.sbt/repositories`.

**Comment by jvican** [comment]
Do you have by any chance the sonatype sbt plugin enabled *globally*? I think this is also part of the problem.

**Comment by oswaldo** [comment]
Globally I have coursier, ensime, sbt-dependency-graph and sbteclipse-plugin. So maybe it is one of those interfering with it, so when I have some spare time I'll try again disabling them all to see what happens.

**Comment by ritschwumm** [comment]
can you try again with 1.0.0-RC12? at least in csbt it's looking better now.

**Comment by alexarchambault** [comment]
Seems that works now (just tried with sbt `0.13.18` and sbt-coursier `1.0.0-RC14`).
