### ISSUE TITLE
Source Dependencies Seem To Break Coursier

### ISSUE THREAD

**Issue by clhodapp** [coursier/coursier#388]
Coursier seems to break when asked to resolve sbt source dependencies:

Demo Build: https://github.com/clhodapp/breaking-coursier

Build Session:
```
[info] Loading global plugins from /Users/chodapp/.sbt/0.13/plugins
[info] Loading project definition from /Users/chodapp/breaking-coursier/project
[info] Loading project definition from /Users/chodapp/.sbt/0.13/staging/48a264571f657e256051/stubby/project
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Set current project to breaking-coursier (in build file:/Users/chodapp/breaking-coursier/)
> update
[info] Updating breaking-coursier
[trace] Stack trace suppressed: run last breaking-coursier/*:coursierResolution for the full output.
[error] (breaking-coursier/*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   org.scala_stubby:stubby_2.11:0.0.1-m1-1-gfb03336:
[error]     not found:
[error]       /Users/chodapp/.ivy2/local/org.scala_stubby/stubby_2.11/0.0.1-m1-1-gfb03336/ivys/ivy.xml
[error]       https://repo1.maven.org/maven2/org/scala_stubby/stubby_2.11/0.0.1-m1-1-gfb03336/stubby_2.11-0.0.1-m1-1-gfb03336.pom
[error] Total time: 2 s, completed Nov 12, 2016 7:28:55 AM
>
```

**Comment by clhodapp** [comment]
Neeever mind on this reproduction attempt. I forgot to set `scalaVersion` in my build. I still _do_ have issues with source dependencies, it just seems like more is needed to reproduce them.

**Comment by clhodapp** [comment]
OK. I fixed my silly mistakes and the build is in fact a reproduction now.

I'll update the original issue description.

**Comment by alexarchambault** [comment]
Nothing was done on the sbt-coursier side to support source repositories, so it possibly doesn't work, yeah :-|

**Comment by clhodapp** [comment]
Upate:

I believe the problem comes from the nature of a multi-build sbt context, which is how source dependencies work:

```
> plugins
In file:/Users/chodapp/breaking-coursier/
	sbt.plugins.IvyPlugin: enabled in breaking-coursier
	sbt.plugins.JvmPlugin: enabled in breaking-coursier
	sbt.plugins.CorePlugin: enabled in breaking-coursier
	sbt.plugins.JUnitXmlReportPlugin: enabled in breaking-coursier
	sbt.plugins.Giter8TemplatePlugin: enabled in breaking-coursier
	net.virtualvoid.sbt.graph.DependencyGraphPlugin: enabled in breaking-coursier
	org.ensime.EnsimeExtrasPlugin: enabled in breaking-coursier
	org.ensime.EnsimePlugin: enabled in breaking-coursier
	net.virtualvoid.optimizer.SbtOptimizerPlugin
	com.timushev.sbt.updates.UpdatesPlugin: enabled in breaking-coursier
	coursier.CoursierPlugin: enabled in breaking-coursier
In ssh://git@github.com:/scala-stubby/stubby.git#fb03336
	sbt.plugins.IvyPlugin: enabled in stubby
	sbt.plugins.JvmPlugin: enabled in stubby
	sbt.plugins.CorePlugin: enabled in stubby
	sbt.plugins.JUnitXmlReportPlugin: enabled in stubby
	sbt.plugins.Giter8TemplatePlugin: enabled in stubby
	net.virtualvoid.sbt.graph.DependencyGraphPlugin: enabled in stubby
	org.ensime.EnsimeExtrasPlugin: enabled in stubby
	org.ensime.EnsimePlugin: enabled in stubby
	net.virtualvoid.optimizer.SbtOptimizerPlugin
	com.timushev.sbt.updates.UpdatesPlugin: enabled in stubby
	com.typesafe.sbt.SbtPgp: enabled in stubby
	sbtrelease.ReleasePlugin: enabled in stubby
	com.typesafe.sbt.GitBranchPrompt
	com.typesafe.sbt.GitPlugin: enabled in stubby
	com.typesafe.sbt.GitVersioning: enabled in stubby
>
```

Basically, the project which we source-depend on doesn't end up getting the coursier plugin, which means that when we get to https://github.com/alexarchambault/coursier/blob/91ad7a8b56bfbfc2893f08a16a4f8150f3afd1ce/plugin/src/main/scala-2.10/coursier/Tasks.scala#L148, the project is left out of the `Vector` (since `coursierProject` isn't defined for it, since the coursier plugin hasn't been applied). Looking at workarounds...

**Comment by clhodapp** [comment]
One idea I've had is that perhaps there could be an `AutoPlugin` that you could drop into your global plugins directory that would enable most of the coursier tasks without enabling actual coursier resolution. That way, only projects that had opted into resolution with coursier would do so but everything would still work. Still trying to think of shorter-term hacks that don't involve chunking up the coursier plugin...

**Comment by clhodapp** [comment]
For now, I am just injecting the coursier settings into the upstream projects manually:
```
lazy val stubby = RootProject(uri("ssh://git@github.com:/scala-stubby/stubby.git#fb03336"))
inScope(Scope.GlobalScope in (stubby)(coursier.CoursierPlugin.projectSettings)
```

**Comment by alexarchambault** [comment]
Closing this. Ensuring coursier is around in the sourced projects works, and the upcoming sbt 1.3.0, with default coursier support, should help too.
