### ISSUE TITLE
support for typelevel scala (scalaOrganization)?

### ISSUE THREAD

**Issue by fommil** [coursier/coursier#391]
is there an easy way to redirect some ivy descriptors to a different organisation?

To support alternative scala versions, we will need to intercept many (but not all) `"org.scala-lang"` modules and replace them with the user's choice, e.g. `"org.typelevel"`

BTW, I don't mean in the sbt plugin, I mean with the raw coursier API..

@milessabin may be interested

**Comment by milessabin** [comment]
Unless I'm misunderstanding what you're asking for, this is already supported: see, eg., the `try-typelevel-scala` script [here](https://github.com/typelevel/scala/blob/typelevel-readme/try-typelevel-scala.sh).

**Comment by fommil** [comment]
that's a bit of a hack, since it's excluding specific ivy entries and explicitly replacing them. But I guess it's probably good enough.

**Comment by alexarchambault** [comment]
The "Allow to swap ..." commit of https://github.com/alexarchambault/coursier/pull/385 does that (which should do basically what the [script from the typelevel repo] does). Most of it is in the `cli` module, but maybe that should be all moved to `core` to allow re-use by the lib users.

**Comment by m4dc4p** [comment]
Would love to see this in the  SBT plugin, as I am using the typelevel compiler and hate waiting for slow downloads :)

**Comment by alexarchambault** [comment]
That should be fine now (since https://github.com/coursier/coursier/pull/541/commits/688e5342f1d8b94db76cc323462eca67e8744dd6, included in `1.0.0-RC3`).
