### ISSUE TITLE
Coursier causes build to fail, possible binary version mismatch

### ISSUE THREAD

**Issue by vossad01** [coursier/coursier#395]
If [hands-on-scala-js](https://github.com/lihaoyi/hands-on-scala-js) is built with `sbt` and coursier compilation fails with what appears to be a binary version mismatch (for details, see issue lihaoyi/hands-on-scala-js#42).  However, if coursier is disabled, compilation succeeds.

Looking at the output of `last book/compile:run`, the classpath lists all the same jars at the same version either way.

I enabled Coursier per the quick start:

`~/.sbt/0.13/plugins/build.sbt`
>addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-M14")

sbt: 0.13.13

**Comment by alexarchambault** [comment]
Seems to be fixed now (`1.0.0-RC3` works fine for me).
