### ISSUE TITLE
Should handle situation when dependency was relocated

### ISSUE THREAD

**Issue by mielientiev** [coursier/coursier#404]
This issue is related to https://github.com/alexarchambault/coursier/issues/323
When I'm trying to get the old version of bouncycastle, I've got:

coursier.ResolutionException: 1 not found https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/bctsp-jdk14-138.jar

Because bouncycastle/bctsp-jdk14/138 was relocated to org.bouncycastle/bctsp-jdk14/1.38

See: https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/bctsp-jdk14-138.pom 

SBT/Ivy resolves this.

I guess that coursier should look up to relocation tag

**Comment by RomanIakovlev** [comment]
Facing similar issue with a relocated artifact. Had to remove coursier SBT plugin from our project because of this, and now suffer long update times. :(

**Comment by hedefalk** [comment]
+1 Same problem with just the same bouncycastle version :(

**Comment by hedefalk** [comment]
Could I hijack just for advice? My dependency is a transitive one so I get this:

```~/d/p/uniply ❯❯❯ sbt                                                                                      ⏎ master ✱ ◼
[info] Loading global plugins from /Users/viktor/.sbt/0.13/plugins
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[info] Loading project definition from /Users/viktor/dev/projects/uniply/project
[info] Set current project to dfkka (in build file:/Users/viktor/dev/projects/uniply/)
[info] Updating uniply
https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/bctsp-jdk14-138.pom
  100.0% [##########] 363 B (1.3 KiB / s)
[info] Resolved uniply dependencies
coursier.ResolutionException: 1 not found
  https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/bctsp-jdk14-138.jar
[error] (*:update) coursier.ResolutionException: 1 not found
[error]   https://repo1.maven.org/maven2/bouncycastle/bctsp-jdk14/138/bctsp-jdk14-138.jar
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? ```

Problem is I can't even analyze what the path to this dependency is. dependency-tree plugin can't be run without loading project first, right? This problem I have had millions of times with sbt and makes it very broken for me. Like: http://stackoverflow.com/questions/24395307/working-offline-with-sbt-and-snapshot-dependencies

1) Is this something coursier could solve?
2) If not, how do I turn coursier off for a specific project (I enable it globally in user settings)

**Comment by hedefalk** [comment]
My only working workaround was to disable coursier temporarily to be able to use "what-depends-on" from sbt-dependency-graph to check what was using it and add exlusions and add the transitive dependency to bouncycastle manually. (I had two paths to the same relocated jar).

**Comment by jastice** [comment]
+1 for issue #404 involving a 404 status code
