### ISSUE TITLE
OSGi Versioning

### ISSUE THREAD

**Issue by briantopping** [coursier/coursier#416]
In https://github.com/sbt/sbt/issues/2873, I was told I should lobby here for OSGi compatible versioning. 

In short, SBT does not accept `major.minor.micro.qualifier` syntax for a version. https://www.infoq.com/news/2012/04/osgi-snapshot covers their resistance in some depth and I can't say I agree with everything in there, but there are a significant number of artifacts in the ecosystem that use this versioning and it should be possible to create in SBT.

The problem with not accepting this syntax is an OSGi version such as `0.1.0.SNAPSHOT` is considered a release version and SBT complains that overwriting release artifacts is deprecated and will be removed in SBT 1.0. 

I don't know exactly why this issue is related to Coursier, I assume it has something to do with Coursier making the determination of what is a snapshot in some future where SBT depends on it instead of Ivy.

Thanks for your consideration and apologies if this doesn't belong here.

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/commit/ab9341ac9bd12728a84667e9d72d88017e66442e should have fixed that.
