### ISSUE TITLE
`extension` from Ivy not correctly read

### ISSUE THREAD

**Issue by avdv** [coursier/coursier#419]
1. add an artifact with type = info, extension = csv

```scala
addArtifact(Artifact("test", "info", "csv"), makeLibraryList)
```

2. call publishLocal

3. in another project consume this artifact

```scala
allDependencies += organization.value %% "test" % "1.0.0" artifacts(Artifact("test", `type` = "info", extension = "csv")) intransitive()

lazy val checkCSV = taskKey[Boolean]("")

checkCSV := {
  val report = update.value
  val files = report.matching(artifactFilter(name = "test_2.*", `type` = "info", extension = "csv"))
  println("files: " + files.mkString(", "))

  files.nonEmpty
}
```

Now, running the `checkCSV` task in vanilla SBT yields:

```
files: /home/claudio/.ivy2/local/default/test_2.11/1.0.0/infos/test_2.11.csv
```

But, when using sbt-coursier version "1.0.0-M15-1" it fails:

```
files: 
```

The problem is that the `extension` is always set to the same value as the `type`:

```
Artifact(test_2.11,info,info,None,List(),Some(file:/home/claudio/.ivy2/local/default/test_2.11/1.0.0/infos/test_2.11.csv),Map())
```

whereas the relevant section from `ivy.xml` looks like this:

```xml
<artifact name="test_2.11" type="info" ext="csv" conf="compile,runtime,test,provided,optional,sources,pom">
</artifact>
```

**Comment by avdv** [comment]
I have looked into this a bit more, and AFAICS the ext is read correctly, but somehow is changed later on...

**Comment by alexarchambault** [comment]
@avdv Thanks for the report, a small repro would be helpful to help fix / speed fixing this.

**Comment by avdv** [comment]
[Here](https://github.com/avdv/coursier-issue308/tree/issue-419) is a small repro for this issue.

Hope this helps.

**Comment by avdv** [comment]
I have just realized that there are various problems with parsing the artifacts (or converting to/from Sbt internals).

In short, when printing `sbt.UpdateReport.toSeq`, the artifacts are almost completely different, not just the extension:

```scala
// vanilla
(compile,test:a_2.10:1.0.0,Artifact(test_2.10,info,csv,None,List(),None,Map()),/home/claudio/.ivy2/local/test/a_2.10/1.0.0/infos/test_2.10.csv)
```

```scala
// coursier
(compile,test:a_2.10:1.0.0:compile,Artifact(a_2.10,jar,jar,None,List(),Some(file:/home/claudio/.ivy2/local/test/a_2.10/1.0.0/jars/a_2.10.jar),Map()),/home/claudio/.ivy2/local/test/a_2.10/1.0.0/jars/a_2.10.jar)
(compile,test:a_2.10:1.0.0:compile,Artifact(a_2.10,info,info,None,List(),Some(file:/home/claudio/.ivy2/local/test/a_2.10/1.0.0/infos/test_2.10.csv),Map()),/home/claudio/.ivy2/local/test/a_2.10/1.0.0/infos/test_2.10.csv)
```

1. the artifact name is different
2. filtering the artifacts on `allDependencies` did not work since the jar is also listed
3. the extension is wrong

I will update the repro accordingly.
