### ISSUE TITLE
Support for dynamic revisions different from SBT / ivy

### ISSUE THREAD

**Issue by avdv** [coursier/coursier#424]
It seems coursier only supports dynamic revisions in major, minor and revision positions of a version, but not anywhere else.

For example `2.5.10-+` is correctly resolvable by vanilla SBT, but coursier spits out:

```
[error]   com.example:base_2.11:2.5.10-+:
[error]     not found:
[error]       /home/claudio/.ivy2/local/com.example/base_2.11/2.5.10-+/ivys/ivy.xml
[error]       https://jcenter.bintray.com/com/example/base_2.11/2.5.10-+/base_2.11-2.5.10-+.pom
[error]       https://repo1.maven.org/maven2/com/example/base_2.11/2.5.10-+/base_2.11-2.5.10-+.pom
```

For the following minimal build file:

```scala
scalaVersion := "2.11.8"
libraryDependencies += "com.example" %% "base" % "2.5.10-+" intransitive()
```

**Comment by jedesah** [comment]
This is probably related to this, `latest.integration` (as in `addSbtPlugin("organization" % "artifact" % "latest.integration")`) doesn't seem to work with coursier.
