### ISSUE TITLE
issues with spark-notebook

### ISSUE THREAD

**Issue by antonkulaga** [coursier/coursier#431]
I've made a PR to spark-notebook that adds coursier. Everyting builds fine but some new bugs emerged
https://github.com/andypetrella/spark-notebook/pull/799#issuecomment-277991174  
```
<console>:12: error: not found: value globalScope
       globalScope.sparkContext.setJobGroup("cell-CF7654DF29474E5384025A6F49FCCC95", "run-1485946611387: val sqlContext = new org.apache.spark.sql.SQLContext(sc)import sqlContext.implicits._")
```
Maybe you can help @vidma to figure out?

**Comment by PanAeon** [comment]
Hi, looks like this is not the coursier issue, see alexarchambault comment:
"globalScope missing seems to mean that your initialization script didn't run properly. There must have been errors prior to this one somewhere..."

**Comment by alexarchambault** [comment]
Seems ok since https://github.com/spark-notebook/spark-notebook/pull/873. Closing this.
