### ISSUE TITLE
The local cache issue.

### ISSUE THREAD

**Issue by wpc009** [coursier/coursier#440]
I use `coursier launch` to boot my application. The command is
```
coursier launch -r HTTP://<my-private-repo/ -i <some_dependency_A>  <my_prog_group>:<my_prog_name>:<version>
```
Coursier will download the dependency from `my-private-repo` without any problem. I use coursier API to resolve the same dependency `A` inside my program. But this time it can not find the dependency even the dependency is in the local cache because my prog does not know the private repo.

The coursier's cache the artifacts in folder structure like `<protocol>/<host_name>/<repo_path>/xxxxx`, if another program using coursier to resolve some artifact that already exists in local cache, if may fails. Because it has differrent resolver settings. It tries to find that artifact in cache but under some other repo.

Why to seperate each repo's artifact in the cache? Is there a way to orgnize local cache like ivy/maven does?

**Comment by alexarchambault** [comment]
Currently, there's no way to organize the cache the same way Maven or Ivy do. The cache is made this way so that a missing repo in one's build definition will always trigger an error, no matter the cache state. The required repositories should be specified wherever they are needed.

**Comment by pauldraper** [comment]
Likewise, if two repositories provide different artifacts (most likely in a SNAPSHOT scenario), you will get the same, consistent one.

It has some downsides, but the upsides much outweigh them IMO.
