### ISSUE TITLE
Azure and SSL

### ISSUE THREAD

**Issue by zifeo** [coursier/coursier#449]
While we moved our continuous integration services on Azure virtual machines, we started facing randomly some `SSLException`. It does not seem to depend on the resource download nor on the project. It occurs sometime 3x in a row or 1x during a day but was not there with our previous provider. Some similar issues suggest that it could be linked to a time-related cause. Is there a way to getting more info with coursier out of this?

```sbt
...
Downloaded https://repo1.maven.org/maven2/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
Downloaded https://repo1.maven.org/maven2/org/apache/ant/ant/1.9.6/ant-1.9.6.jar
Downloaded https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/io.spray/sbt-revolver/scala_2.10/sbt_0.13/0.8.0/jars/sbt-revolver.jar
Downloaded https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-js/sbt-scalajs/scala_2.10/sbt_0.13/0.6.13/jars/sbt-scalajs.jar
coursier.ResolutionException: 1 download error
  Caught javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: Tag mismatch! (Connection has been shutdown: javax.net.ssl.SSLException: Tag mismatch!)
[error] (*:update) coursier.ResolutionException: 1 download error
[error]   Caught javax.net.ssl.SSLException: Connection has been shutdown: javax.net.ssl.SSLException: Tag mismatch! (Connection has been shutdown: javax.net.ssl.SSLException: Tag mismatch!)
Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore?
```

**Comment by alexarchambault** [comment]
I also run into those on Travis CI from time to time (but I can't remember having run into those on Appveyor). Just re-running the corresponding job fixes it though.

I'm thinking about adding a retry when a `javax.net.ssl.SSLException` is caught.

When you see those in a row, do they all originate from the same URL?

**Comment by zifeo** [comment]
It is each time different whenever it happens in a row (max 3x). Retrying sounds good.
