### ISSUE TITLE
Retry if lock acquisition fails

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#459]
Currently, if two processes running coursier try to download the same file, one of them will be errored, because of the lock the other process acquires while downloading the file. Some wait / retry mechanism should be added to circumvent that.

**Comment by alexarchambault** [comment]
Locking is handled in [coursier.Cache](https://github.com/alexarchambault/coursier/blob/14f297b4f7ad8cf83abfe030825cd5b51bee64e3/cache/src/main/scala/coursier/Cache.scala), by the [`withLockFor` method](https://github.com/alexarchambault/coursier/blob/14f297b4f7ad8cf83abfe030825cd5b51bee64e3/cache/src/main/scala/coursier/Cache.scala#L158-L190). A way to implement that could roughly consist in defining a trait like
```scala
trait LockHandler { // I'm no good at naming things
  /**
   * @file: file being locked
   * @attemptId: opaque object, unique for a given attempt
   */
  def locked(file: File, attemptId: AnyRef): Option[Task[Unit]]
}
```
wrapping the return type of `withLockFor` in a `Task`, and passing it a `LockHandler`.

If a file is locked, `LockHandler.locked` would be called. If it returns `None`, we get the `Locked` error (as is the case currently). It it returns `Some(task)`, we map a new attempt on the returned `task`.

A `LockHandler` implementation could for example just wait a fix amount of time, or have its own thread pool and block on the lock until it gets freed, ...

**Comment by savulchik** [comment]
@alexarchambault Is the issue still relevant after https://github.com/coursier/coursier/commit/3ac230f0beaee00f72b57d8df04323b6c9b5070a ?

**Comment by alexarchambault** [comment]
@savulchik Thanks! This issue can closed, indeed.
