### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by hyunjun** [coursier/coursier#470]
Hi guys,
I tried to execute this behind the company proxy, however, got the error like below;
```
$ ./coursier --help
Error while downloading https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-M15/coursier-cli_2.11-1.0.0-M15-standalone.jar: Connection timed out, ignoring it
```
I got the same result when using `--proxy-all`.
Is there other ways?
Thanks,
Jun

**Comment by alexarchambault** [comment]
@hyunjun Are you able to download `https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-M15/coursier-cli_2.11-1.0.0-M15-standalone.jar` by other means? You can then run it via `java -cp coursier-cli_2.11-1.0.0-M15-standalone.jar coursier.cli.Coursier`.

**Comment by Lawiet** [comment]
java -cp coursier-cli_2.11-1.0.0-RC6-standalone.jar coursier.cli.Coursier
Error: no command specified

**Comment by Lawiet** [comment]
Hi, @alexarchambault i try but throw this error

> wget https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-RC1/coursier-cli_2.11-1.0.0-RC1-standalone.jar
--2017-07-18 15:07:21--  https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-RC1/coursier-cli_2.11-1.0.0-RC1-standalone.jar
Connecting to 106.31.63.70:80... connected.
Proxy request sent, awaiting response... 200 OK
Length: 2713992 (2.6M) [application/java-archive]
Saving to: ‘coursier-cli_2.11-1.0.0-RC1-standalone.jar’
100%[=================================================================================================>]
 2,713,992    887KB/s   in 3.0s
2017-07-18 15:07:24 (887 KB/s) - ‘coursier-cli_2.11-1.0.0-RC1-standalone.jar’ saved [2713992/2713992]
root:~/jupyter-scala # java -cp coursier-cli_2.11-1.0.0-M15-standalone.jar coursier.cli.Coursier                                      Error: Could not find or load main class coursier.cli.Coursier

**Comment by alexarchambault** [comment]
The "Error: no command specified" above is expected. Try adding `--help` or `fetch --help` as arguments.

**Comment by shengc** [comment]
if run by java command line, what the `coursier.mainJar` property should be set to ?

**Comment by alexarchambault** [comment]
Closing for now. Use of proxies is documented [here](https://get-coursier.io/docs/other-proxy).
