### ISSUE TITLE
ExclusionRule classifier is not honoured

### ISSUE THREAD

**Issue by caoilte** [coursier/coursier#482]
Just tried upgrading a project from Ivy to Coursier and it failed on a corner case. Specifcally an Exclusion rule applied to a classifier.

I have created an example project which demonstrates the problem. 

https://github.com/caoilte/coursier-issue-example

If you run it with Ivy you get Connection Refused (probably). If you run it with Ivy you get a 

`java.lang.NoClassDefFoundError: org/json/JSONException`

because of the way the sbt dependency is added. Specifically the `excludeAll(ExclusionRule("org.json", "json", "sources"))` in,

`libraryDependencies += "com.github.tomakehurst" % "wiremock" % "1.56" excludeAll(ExclusionRule("org.json", "json", "sources"))`

I am going to try and fix up my project to not require this Exclusion Rule, but it would be nice if coursier was a guaranteed drop in replacement for Ivy so I've raised this issue.

**Comment by alexarchambault** [comment]
I agree a warning about it should at least be emitted...

**Comment by alexarchambault** [comment]
Closing this. Warnings should now [be](https://github.com/coursier/sbt-coursier/blob/3987ba9af6136d20cd7da61b6e1e6f9afa68bf06/modules/lm-coursier/src/main/scala/coursier/lmcoursier/Inputs.scala#L107) [printed](https://github.com/coursier/sbt-coursier/blob/3987ba9af6136d20cd7da61b6e1e6f9afa68bf06/modules/lm-coursier/src/main/scala/coursier/lmcoursier/Inputs.scala#L118) if an exclusion rule has unsupported fields.
