### ISSUE TITLE
ForkMain failed with exit code 255

### ISSUE THREAD

**Issue by joan38** [coursier/coursier#495]
Hi,

I upgraded from `1.0.0-M15` to `1.0.0-RC1` and now we are getting the following when running the tests:
```
ForkMain 37823 failed with exit code 255
```

We are running SBT with 2G of ram: `sbt -mem 2048` and the fork with 4G `javaOptions in Test += "-Xmx4000m",` in a containerised env.

Cheers

**Comment by alexarchambault** [comment]
What sbt command was running when the process was killed? If the update triggered that, `1.0.0-RC2` about to be released should have a slightly lower memory load...

**Comment by joan38** [comment]
Hi @alexarchambault 
`1.0.0-RC2` solved the issue.
Merci
