### ISSUE TITLE
Regression in 1.0.0-RC1

### ISSUE THREAD

**Issue by scottcarey** [coursier/coursier#500]
Updating from M15, and removing the `coursierUseSbtCredentials := true` line in my build.sbt, results in many dependencies suddenly being unavailable resulting in compilation errors like "syntax not a member of scalaz".

Sequence of events so far:

Update to RC1, remove the `coursierUseSbtCredentials` line.  Everything works.
Change a dependency (In my case, an update of scalaz from 7.2.8 to 7.2.10, along with a few other dependencies).  Result: compilation errors mostly related to the changed artifacts, but some are related to unchanged artifacts.
I noticed #499, and tried the suggestion there -- brute force removal of the entire cache.  This did not work.
Reverting to M15 solved the problem.

Returning to RC1 now works, even if I nuke the entire cache directory, although I left `coursierUseSbtCredentials` in place.  It is unclear if the issue is related to that or not.

When it was in the bad state, 'sbt eclipse' also resulted in broken projects -- the project did not have scalaz-core as a dependency.  However, coursierDependencyTree shows scalaz-core.

I'm reverting to M15 for now.

A couple quirks in my config:  all public repositories are routed through a corporate repo, maven central is removed, and credentials are required for most artifacts.

**Comment by scottcarey** [comment]
Correction:  all of the compilation errors were related to dependencies that I updated.

**Comment by alexarchambault** [comment]
@scottcarey Is there still an issue? (Your latest comment seems to imply otherwise...)

**Comment by scottcarey** [comment]
I have abandoned RC1, the prior milestone is fine.

**Comment by alexarchambault** [comment]
Closing for now, re-open if you have more details and this is still a problem for you.
