### ISSUE TITLE
Jars not downloaded when using Nexus proxy repository

### ISSUE THREAD

**Issue by nigredo-tori** [coursier/coursier#505]
We're using Sonatype Nexus to provide a local proxy repository for Maven Central. It's lazy, meaning it only downloads files from Central when they are requested. E.g. if client requests a .pom, but not a .jar, then only a .pom will be added to cache. The problem is that attempting to index a directory returns the index of the corresponding directory in cache, not on remote.

Currently, as far as I can see from its log messages, Coursier does the following:
1. Download .pom file
2. Download directory listing
3. Download .jar only if it's present in the directory listing

This means that if a .jar for the artifact wasn't previously downloaded, Coursier won't attempt to download it!
An obvious workaround for this is querying required .jar manually when adding a new package, but this is extremely ugly and annoying.

Versions:
Coursier v1.0.0-RC1
Nexus v2.9.0

**Comment by alexarchambault** [comment]
I confirm that if the jar is missing from the directory listing, it won't be downloaded later on with the latest coursier versions...

Isn't there really no way to have the directory listings right, here? (by having the proxy return full listings...) I know Ivy relies on directory listings too, to list available versions on Ivy repositories AFAIK.

**Comment by backuitist** [comment]
Coursier does not seem to be warning about missing jars. I'm having this problem right now (testing https://github.com/scalameta/tutorial/blob/master/build.sbt with a Nexus repo missing scala 2.11.10):
```
[error] (tutorial/*:scalaInstance) Missing scala-compiler.jar
```
How can I ask coursier for the list of missing dependencies?
Once the jar has been added to Nexus, how should we tell coursier to go and fetch it again (via SBT)?

**Comment by nigredo-tori** [comment]
@backuitist, a superficial search yields a `coursierCachePolicies` setting, which seems to allow this. I'd say something like this would work (not as a permanent solution, obviously):
```scala
coursierCachePolicies := CachePolicy.ForceDownload
```
If this fails (I haven't tried it yet), there's always an option of nuking the coursier cache manually, either as a whole or just for select packages.

**Comment by backuitist** [comment]
What I've been doing, instead of querying the missing jar manually on Nexus, is to comment out coursier from the list of plugins and re-update, therefore going through the default ivy-based dependency fetcher.
Once all the jars have been fetched, I can revert back to coursier.

**Comment by nigredo-tori** [comment]
I finally got around to reproducing this problem on a more manageable project, and I found another workaround: **disabling file browsing for the repository** (in Nexus). This may be inconvenient if you have people who use this feature (e.g. for exploring the repository), but it the most simple and reliable way to circumvent this issue out of the ones mentioned here.

About updating:
- I've managed to reproduce the problem with Nexus 2.13 (couldn't get 2.14 to work from the docker image for some reason).
- Updating to 3.x fixes the issue since 3.x doesn't currently support file browsing (aka directory listings), but this is likely to change soon: https://issues.sonatype.org/browse/NEXUS-12531 .

**Comment by alexarchambault** [comment]
`1.0.0-RC4` should be fine with proxies out of the box. Feel free to re-open if that's not the case for you.

**Comment by nigredo-tori** [comment]
@alexchambault, it does seem to work for my toy example. Thank you.

**Comment by sideeffffect** [comment]
I was able to reproduce this with Scalafix `0.9.1` (see https://github.com/scalacenter/scalafix/issues/930) which uses `1.1.0-M4`
@alexarchambault could you please reopen this bug?
