### ISSUE TITLE
Custom cache directory for bootstrap launcher 

### ISSUE THREAD

**Issue by olafurpg** [coursier/coursier#511]
First of all, bootstrap scripts are amazing! Thank you for this feature.

I use a scalafmt bootstrap script in my CI and I noticed that it doesn't respect the COURSIER_CACHE environment variable,
```
$ export COURSIER_CACHE=foo/.coursier
$ coursier bootstrap com.geirsson:scalafmt-cli_2.11:0.6.8 --main org.scalafmt.cli.Cli -o scalafmt
$ ./scalafmt
$ ./scalafmt -Dbootstrap.jarDir
# obtained: downloads files to $HOME/.coursier/bootstrap
# expected: downloads files to foo/.coursier/bootstrap (or somewhere in foo/.coursier)
```

It seems this should be possible to fix by changing how `jarDir` is calculated here: https://github.com/coursier/coursier/blob/3c46f452ebe80bd0822b864a4675201cf900a6c6/bootstrap/src/main/java/coursier/Bootstrap.java#L348
However, that would mean that the bootstrap cache would inside `~/.coursier/cache`, which might cause problems since the bootstrap scripts and coursier core use different caching layouts.  Any pointers on what can be done?

Note.
This hasn't really bothered me so much that the CI redownloads everything on every run because the bootstrap script runs so fast that the download overhead is only 2-3 seconds. However, I feel it's a waste of resources to download the same artifacts over and over again and again.

**Comment by alexarchambault** [comment]
I was thinking about having bootstraps use the same cache layout as coursier itself (under `~/.coursier/cache/...` by default). After coursier 1.0 final is out I guess.

Some code could be shared between the `cache` and the `bootstrap` modules, via another Java module. This new module would handle calculating the path where a given URL would land in cache (currently done around [here](https://github.com/coursier/coursier/blob/6e79dcab9cc122ca43ca0134941799256ca2ee13/cache/src/main/scala/coursier/Cache.scala#L56-L92)), handling the `COURSIER_CACHE` env var (and the `coursier.cache` Java property). It shouldn't need to be aware of TTLs, to remain lightweight.

**Comment by fommil** [comment]
it would be very nice if they used the same cache. my OS cache dir is on RAM drive and I'm on mobile internet right now, so reboots mean starting again...
