### ISSUE TITLE
Build failure on missing SBT credentials file

### ISSUE THREAD

**Issue by alonsodomin** [coursier/coursier#514]
I have observed this when working on a contribution to `sbt-aspectj`, which adds the `bintray-sbt` plugin to the build, therefore adding some sort of support for Bintray repos, whilst having `sbt-coursier` as a global plugin.

SBT throws the error because it tries to find a `$HOME/.bintray/.credentials` file, which does not exist:

```
[trace] Stack trace suppressed: run last *:coursierResolution for the full output.
[error] (*:coursierResolution) Credentials file $HOME/.bintray/.credentials does not exist
[error] Total time: 0 s, completed 25-Apr-2017 09:26:43
```

After that SBT refuses to continue. Disabling the plugin makes that error a warning and SBT continues normally:

```
[warn] Credentials file $HOME/.bintray/.credentials does not exist
[info] Updating {file:$HOME/.../sbt-aspectj/}sbt-aspectj...
```

It would be great if the `sbt-coursier` could reproduce the same behaviour to avoid having to disable the plugin for this particular case...

**Comment by alexarchambault** [comment]
That looks like the same as https://github.com/coursier/coursier/issues/438. This is fixed in the current master. `1.0.0-RC2` will contain the fix.

**Comment by alonsodomin** [comment]
oh sorry, indeed looks like a clear duplicate, couldn't find that one before.

feel free to close this one then.

**Comment by alexarchambault** [comment]
Ok, closing then. Feel free to re-open it you still face this issue with `1.0.0-RC2`.
