### ISSUE TITLE
Using credentials on a public Nexus repository fails with 403 

### ISSUE THREAD

**Issue by backuitist** [coursier/coursier#519]
We have a Nexus enterprise repository with multiple repositories (same host, same realm). Some are read-only and do not require authentication, some are read/write and require authentication.
Starting with 1.0.0-M15-6, coursier uses the SBT credentials by default, which breaks artifact fetching (403) on the repositories that do not require authentication (but for which credentials are provided).

**Comment by alexarchambault** [comment]
sbt-coursier could possibly consider the credentials optional, so add repositories with credentials twice: a first time with auth, a second time with no auth, so that both would be tried. Don't know how sbt/Ivy manage this by default...

**Comment by ches** [comment]
Same problem with Artifactory. We worked around it by using two different CNAMEs for the same Artifactory host, using one for resolver and the other for `publishTo` and `Credentials` settings, but this is annoying 😕

**Comment by ches** [comment]
Interestingly, I just came across a note [in Artifactory documentation][1] that suggests Maven has this misbehavior too:

> #### Synchronizing authentication details for repositories with the same URL
> If you have repository definitions (either for deployment or download) that use _the same URL_, Maven takes the authentication details (from the corresponding server definition) of the first repository encountered and uses it for the life-time of the running build for all repositories with the same URL. This may cause authentication to fail (producing 401 errors for downloads or deployment) if you are using different authentication details for the respective repositories. This is inherent Maven behavior and can only be solved by using the same authentication details for all repository definitions with the same URL in your `settings.xml`.

[1]: https://www.jfrog.com/confluence/display/RTF/Maven+Repository#MavenRepository-ConfiguringAuthentication
