### ISSUE TITLE
raw api usage doesn't refresh SNAPSHOTs

### ISSUE THREAD

**Issue by fommil** [coursier/coursier#520]
A lot of ensime users have been reporting that their servers are not getting updated even after running `sbt ensimeConfig`. This is the other half of https://github.com/ensime/ensime-sbt/issues/321 and I'm very sorry that I don't have a reproduction for you to look at. I'm sure this used to work in earlier milestone releases.

Next time I am upgrading the server, I'll try to capture as much info as I can (e.g. timestamps before / after).

**Comment by alexarchambault** [comment]
Answered directly on https://github.com/ensime/ensime-sbt/issues/321.
