### ISSUE TITLE
Dependency tree from API?

### ISSUE THREAD

**Issue by captainju** [coursier/coursier#540]
Hello,
How can I get the dependency tree from the API?  
I would like data representing what we get from the sbt command `coursierDependencyTree`  

I've managed to get a successful `Resolution` for an Artifact, but I don't know what to do with it…

**Comment by alexarchambault** [comment]
The [`dependencyTree` method](https://github.com/coursier/coursier/blob/3c46f452ebe80bd0822b864a4675201cf900a6c6/core/shared/src/main/scala/coursier/util/Print.scala#L76-L82) should allow that.

**Comment by captainju** [comment]
Yes thank you, but it returns a `String` so I would need to parse it…  
Instead i'll try to develop a temporary data structure which contains all nodes with useful information for the resulting tree.
