### ISSUE TITLE
sbt-coursier forces scala-library version

### ISSUE THREAD

**Issue by pauldraper** [coursier/coursier#543]
```scala
autoScalaLibrary := false

libraryDependencies += "org.scala-lang" % "scala-library" % "2.11.7"
```

With vanilla SBT (0.13.15):

```
> show managedClasspath
[info] * Attributed(/home/paul/.ivy2/cache/org.scala-lang/scala-library/jars/scala-library-2.11.7.jar)
```

With sbt-coursier (1.0.0-RC3):

```
> show managedClasspath
[info] * Attributed(/home/paul/.sbt/boot/scala-2.10.6/lib/scala-library.jar)
```

Oddly, it seems sbt-coursier special cases scala-library.

I would just change `scalaVersion` but sometimes I need to have a different scala version for one config of a probject. E.g. this coursier bug was the cause for https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/1

**Comment by alexarchambault** [comment]
Kind of agree that `scalaVersion` shouldn't be enforced for the scala dependencies if `autoScalaLibrary` is `false` (or `ivyScala` says not to override the scala version). I have a fix for it locally, I'll push it after some clean-up.

About enforcing that, it's something that sbt now does too (which you prevent yourself from [here](https://github.com/lucidsoftware/neo-sbt-scalafmt/blob/master/sbt-scalafmt/src/main/scala/com/lucidchart/sbt/scalafmt/ScalafmtCorePlugin.scala#L205)). It did so after having seen that sbt-coursier did it IIRC (and it seemed a good idea to do that). That ensures no dependency bumps the version of the scala JARs.

But overall, that's a different issue than https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/1. The issue with https://github.com/lucidsoftware/neo-sbt-scalafmt/issues/1 is that it relies on the resolutions for disjoint Ivy configuration subgraphs to be independent from each other (versions one graph shouldn't bump versions in another graph). sbt-coursier doesn't support independent subgraphs for now. I was initially reluctant to support that not to add unnecessary complexity for a quite underused feature. That said, I quickly gave it a try and seem to have ended with a not too overweight support for it. I'm still pondering whether that should be merged before `1.0` final, if that doesn't break other things...

**Comment by dvic** [comment]
Is there any workaround for the time being? (especially for lucidsoftware/neo-sbt-scalafmt#1)

**Comment by alexarchambault** [comment]
@dvic None on the coursier side for now. If neo-sbt-scalafmt offered alternative ways of specifying the jars of scalafmt, there could have been some (one could then get this list of jar by other means - via the coursier cli for example... - and pass that to neo-sbt-scalafmt), but I don't think it allows that.

**Comment by pauldraper** [comment]
Don't have the code in front of me, but you can workaround it by overriding
scalafmt::managedClasspath

My two cents: I don't see why conflicting dependencies for other libs, e.g.
guava, isn't a problem too. Special casing scala-library is just weird. If
you really want to make sure you have a particular version of any
dependency, use dependencyOverrides.

**Comment by alexarchambault** [comment]
https://github.com/coursier/sbt-coursier/pull/2 should fix that.
