### ISSUE TITLE
Dep fetch fails due to locking in 1.0.0-RC3

### ISSUE THREAD

**Issue by ochrons** [coursier/coursier#547]
After I updated scalafiddle-core to use Coursier 1.0.0-RC3 (from M14), it started failing loading some dependencies with errors like:

```
ArrayBuffer((Dependency(org.scalaz:scalaz-core_sjs0.6_2.11,7.2.7,compile,
Set((org.scala-lang,scala-reflect), (org.scala-lang,scala-library), (org.scala-js,scalajs-library_2.11), (org.scala-js,scalajs-test-interface_2.11)),Attributes(,),false,true),
List(not found: C:\Users\oc\.ivy2\local\org.scalaz\scalaz-core_sjs0.6_2.11\7.2.7\ivys\ivy.xml, locked: C:\Users\oc\.coursier\cache\v1\https\repo1.maven.org\maven2\org\scalaz\scalaz-core_sjs0.6_2.11\7.2.7\scalaz-core_sjs0.6_2.11-7.2.7.pom)))
```

The [code in question](https://github.com/scalafiddle/scalafiddle-core/blob/master/compiler-server/src/main/scala/fiddle/compiler/LibraryManager.scala#L99-L111) loads libraries concurrently.

This is on Windows 10.

**Comment by alexarchambault** [comment]
If two different resolutions or artifact fetching try to download the file, one of them will fail with the error you're seeing (`locked: ...`). Once the file is downloaded (by the first resolution), retrying should just work.

Would simply retrying be an option for you?

**Comment by ochrons** [comment]
In my case it's ok if even one of the concurrent fetches succeeds, but it seems that with RC3 they all fail in some cases.

Optimally ScalaFiddle would build a flattened list of all dependencies and only then download the missing ones. Dunno if this is possible with Coursier.

**Comment by alexarchambault** [comment]
One of the downloads should succeed at least. If they all fail, this could be a bug.

**Comment by alexarchambault** [comment]
FYI, two downloads shouldn't conflict anymore with the current master - one will do the download, while the other will just watch it going (and could take over in case the download gets interrupted). `1.0.0-RC4` should be fine.

**Comment by ochrons** [comment]
Thanks! I'll update ScalaFiddle to use RC4 :)

**Comment by alexarchambault** [comment]
`1.0.0-RC4` is out since a few days (`RC5` is too, `RC6` about to). Feel free to re-open if that doesn't solve the problem for you.
