### ISSUE TITLE
Missing sbt-coursier for scala 2.11

### ISSUE THREAD

**Issue by krzkaczor** [coursier/coursier#555]
Hey!

I was following readme and I encountered error:
```
coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
  io.get-coursier:sbt-coursier;sbtVersion=0.13;scalaVersion=2.11:1.0.0-RC3:
    not found:
      /Users/x/.ivy2/local/io.get-coursier/sbt-coursier/scala_2.11/sbt_0.13/1.0.0-RC3/ivys/ivy.xml
      https://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.11_0.13/1.0.0-RC3/sbt-coursier-1.0.0-RC3.pom
```

It turns out that there is no sbt-courier released for scala 2.11. Any idea why is that?

**Comment by dwijnand** [comment]
All sbt 0.13 plugins are only built against Scala 2.11.

What you might have done is accidentally declared the `scalaVersion` in `project/plugins.sbt` (or `project/plugins.sbt`) to some version of Scala 2.11.x, e.g `scalaVersion := "2.11.8"`. Removing that will fix this issue.

**Comment by krzkaczor** [comment]
Thanks for the reply. I have specified scala version for the project in `build.sbt`:
```
scalaVersion := "2.11.11"
```
Now, somehow problem disappeared. Sorry for bothering you, I don't know what really "fixed" it.
