### ISSUE TITLE
Pre-existing ivy dependencies break coursier

### ISSUE THREAD

**Issue by thurstonsand** [coursier/coursier#561]
I'm trying out coursier on a project with repos
```scala
// artifactory needs credentials
credentials ++= Seq(Credentials(...))

resolvers ++= Seq(
  Resolver.mavenLocal,
  "Artifactory" at "https://private.artifactory.com"
)
```
And when simply adding the coursier sbt plugin and trying to recompile, compilation failed when it did not recognize `StrictLogging` from `"com.typesafe.scala-logging" %% "scala-logging"`. I had this dependency already downloaded in `~/.ivy2/cache/` (among every other dependency).
Commenting out `Resolver.mavenLocal` caused coursier to correctly download the dependency.

Then, it ran into the same issue with a dependency from my private artifactory, which has a username/password. Obviously I can't just comment this repo out... What am I doing wrong? I also tried simply deleting my ivy2 cache entirely, which did not fix the problem. If it helps at all, the dep from the private repo was classified as "tests", ie 

`"com.private" %% "dependency" % "1.0.0" % "test" classifier "tests"`

And just to ensure my own sanity, I then disabled coursier and the project compiled successfully. The most confusing part of it all is that coursier never once emitted a warning or error. It was the compiler that had to figure out that a dependency was missing

**Comment by alexarchambault** [comment]
`mavenLocal` shouldn't be used with coursier. It sometimes misses JARs (having only the POMs for some dependencies, not their JARs), which confuses coursier, that expects the repository having a POM to have the corresponding JAR.

I think it should emit a warning when `mavenLocal` is found in the repository list.

**Comment by thurstonsand** [comment]
ok, I can live with that. Any ideas on the problems I'm having after commenting that out?

**Comment by alexarchambault** [comment]
coursier doesn't rely on `~/.ivy2/cache`, it has its own cache under `~/.coursier/cache/v1`. You need to have all the right repositories that the dependencies can come from. From what I understand, either you don't have the repo for `"com.typesafe.scala-logging" %% "scala-logging"`, or a wrong version of it ends up included.

**Comment by thurstonsand** [comment]
the `scala-logging` issue was resolved after disabling the `mavenLocal` repo, which is fine. What about the follow-up problem with the dependency from my private repo? Does it have to do with the `classifier "tests"`, or is it possibly related to the repo itself?

The behavior I see is that coursier doesn't even attempt to download this dep, and does not emit any warning that it didn't try. The end result is that the dependency resolution step completes successfully without warnings, and then the compiler breaks when it does not recognize classes coming from the dep

**Comment by alexarchambault** [comment]
About the test stuff, you should add `classpathTypes += "test-jar"` for the test jars to be added to the classpath (like in https://github.com/coursier/coursier/issues/461).

**Comment by thurstonsand** [comment]
yep, that fixed it. everything works now, and definitely way faster
