### ISSUE TITLE
Server returned HTTP response code: 400 for URL

### ISSUE THREAD

**Issue by Enalmada** [coursier/coursier#563]
I am trying out coursier and getting a 400 error trying to download a private jar:
```
[error] (gell/*:coursierResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]   com.datomic:datomic-pro:0.9.5544:
[error]     download error: Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://deploy-a0dbc565-faf2-4760-9b7e-29a8e45f428e.s3.amazonaws.com/0.9.5544/datomic-pro-0.9.5544.pom?x-amz-security-token=<token>&AWSAccessKeyId=<id>&Expires=<expires>&Signature=<signature>
```

While I do have credentials setup and I see https://github.com/coursier/coursier/issues/358 about coursier not working with credentials, I feel this could be a different problem.  Normal sbt works, hitting url in browser works, curl -i "<url>" works with a 200 code.  Any reason why coursier would be getting a 400 when everything else I try to debug this works?

**Comment by alexarchambault** [comment]
Have you tried curl-ing with credentials? It might be the same issue as https://github.com/coursier/coursier/issues/519.

**Comment by Enalmada** [comment]
If I put the wrong credentials I get an "unauthorized" error, so I think credentials are working and this is something that happens after.   It is just so strange to me that the url that coursier says returns 400 works fine with curl or in browser.    It is almost like the private repo is angry at something coursier is passing to it.

You can get a free key to test here: https://my.datomic.com/account/create
```
libraryDependencies += "com.datomic" % "datomic-pro" % "0.9.5544"
credentials += Credentials("Datomic Maven Repo", "my.datomic.com", "<username>", "<key>")
resolvers += "my.datomic.com" at "https://my.datomic.com/repo"
```
(or if you want to ping me enalmada@gmail.com I can send you a small sample project showing normal sbt working but coursier failing)

**Comment by alexarchambault** [comment]
`1.1.0-M15` should support optional credentials (with requests attempted first without credentials, then with them in case of 4xx error). The doc should describe that in more details when `1.1.0-M15` is released.
