### ISSUE TITLE
Install specific version

### ISSUE THREAD

**Issue by annappropriate** [coursier/coursier#570]
Currently the only option is to install version from master, but I would love to be able to install a specific version.
I'm currently adding coursier to my work project to launch/bootstrap scalafmt. Having the same version installed at all developers' environments would be nice to have.

**Comment by alexarchambault** [comment]
You can get a specific version via the tags, like [`https://github.com/coursier/coursier/raw/v1.0.0-RC3/coursier`](https://github.com/coursier/coursier/raw/v1.0.0-RC3/coursier). It should work since `1.0.0-RC1` at least.

**Comment by anna-zzz** [comment]
Thanks, that works! Maybe worth mentioning in documentation?

**Comment by alexarchambault** [comment]
Yep, it could be added to the README. I'll keep this issue opened as a reminder.

**Comment by dwijnand** [comment]
Fixed in https://github.com/coursier/coursier/commit/ff83efade5fef34568244e4e42e5d8b963383f65
