### ISSUE TITLE
Support machine-readable output for coursierDependencyTree

### ISSUE THREAD

**Issue by sschuberth** [coursier/coursier#575]
It would be nice if the `coursierDependencyTree` task could be made to output to a machine-readable format, like JSON, for further analysis of the dependencies by some other tool.

**Comment by alexarchambault** [comment]
Note that trees can be obtained out of sbt via the CLI of coursier, like
```
$ coursier resolve org:name:ver -t
```

But some JSON would make it easier to analyze in external tools, yeah.

**Comment by sschuberth** [comment]
Let me add some more details about what I'm looking for: I need a tool with which I can programmatically query the dependencies of a Scala project, ideally without the need to make any changes to the project (like applying a plugin on the project level), and later on download these artifacts and / or their corresponding sources artifacts.

I though a way to do this would be by applying the plugin globally as part of `~/.sbt/0.13/plugins/build.sbt`, parsing the output of the `coursierDependencyTree` task, and then using `fetch` on all the reported dependencies.

Does that sound like a good plan and good reason to implement this feature, or would you recommend another approach?

**Comment by sschuberth** [comment]
I just realized that by now there is a `--json` argument to `coursier resolve`. So I could probably use the CLI instead of the plugin (via `coursierDependencyTree`) to get the information I want. If only I could find a way to tell `coursier resolve --tree --json` to list the trees for all project below the current directory. Is that possible?

**Comment by wisechengyi** [comment]
It's `--json-output-file` https://github.com/coursier/coursier/blob/c469899040ab37a222b477b50d8b081bac620c5b/cli/src/main/scala-2.12/coursier/cli/options/CommonOptions.scala#L93

> to list the trees for all project below the current directory

so like the following?
```
for p in projects:
  coursier <p's deps> --json-ouput-file a.json
```

**Comment by sschuberth** [comment]
> It's `--json-output-file`

Right, I've fixed that, thanks.

> so like the following?

I'd guess so, yes. I'm not sure if `--tree` would be needed there, too, to really get a tree / hierarchy of dependencies in JSON output, not just a flat list of all transitive dependencies. And of course dependencies should be grouped by project in the output.

**Comment by wisechengyi** [comment]
The json output has the dependency info, but you need to parse it into a tree structure. 
`--tree` only goes to stdout.

**Comment by sschuberth** [comment]
But is there enough information in the JSON output alone to reconstruct the tree?

**Comment by wisechengyi** [comment]
Probably? what do you want that is not in there?

**Comment by wisechengyi** [comment]
Ah json is only printed when using `fetch` (separate issue).

E.g. 
```
[tw-mbp-me coursier_dev (eg)]$ ./run fetch -t com.hannesdorfmann:httpkit-logansquare:1.5.6 --json-output-file x.out 
  Result:
└─ com.hannesdorfmann:httpkit-logansquare:1.5.6
   └─ com.bluelinelabs:logansquare:[1.0.0,1.1.0)
      └─ com.fasterxml.jackson.core:jackson-core:2.5.1
https://repo1.maven.org/maven2/com/bluelinelabs/logansquare/1.0.6/logansquare-1.0.6.jar
  100.0% [##########] 22.6 KiB (65.2 KiB / s)
https://repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.1/jackson-core-2.5.1.jar
  100.0% [##########] 224.5 KiB (646.9 KiB / s)
/Users/me/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/hannesdorfmann/httpkit-logansquare/1.5.6/httpkit-logansquare-1.5.6.jar
/Users/me/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/bluelinelabs/logansquare/1.0.6/logansquare-1.0.6.jar
/Users/me/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.1/jackson-core-2.5.1.jar

[tw-mbp-me coursier_dev (eg)]$ jq < x.out 
{
  "conflict_resolution": {},
  "dependencies": [
    {
      "coord": "com.bluelinelabs:logansquare:[1.0.0,1.1.0)",
      "file": "/Users/me/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/bluelinelabs/logansquare/1.0.6/logansquare-1.0.6.jar",
      "dependencies": [
        "com.fasterxml.jackson.core:jackson-core:2.5.1"
      ]
    },
    {
      "coord": "com.fasterxml.jackson.core:jackson-core:2.5.1",
      "file": "/Users/me/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/fasterxml/jackson/core/jackson-core/2.5.1/jackson-core-2.5.1.jar",
      "dependencies": []
    },
    {
      "coord": "com.hannesdorfmann:httpkit-logansquare:1.5.6",
      "file": "/Users/me/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/com/hannesdorfmann/httpkit-logansquare/1.5.6/httpkit-logansquare-1.5.6.jar",
      "dependencies": [
        "com.fasterxml.jackson.core:jackson-core:2.5.1",
        "com.bluelinelabs:logansquare:[1.0.0,1.1.0)"
      ]
    }
  ],
  "version": "0.1.0"
}

```

**Comment by wisechengyi** [comment]
so to make it work on `resolve`, that'll most likely involve moving some code around and applying the same logic on `resolve` from `fetch`.

**Comment by sschuberth** [comment]
Sounds good.

I just realized that in the JSON output above version ranges like `[1.0.0,1.1.0)` are not resolved. For `resolve`, I'd expect them to *be* resolved, however. Other than that the JSON data seems to be usable for parsing it into a tree of dependencies.

**Comment by alexarchambault** [comment]
Closing this. Feel free to discuss that further, or to open related PRs.
