### ISSUE TITLE
Cut a stable release

### ISSUE THREAD

**Issue by apeschel** [coursier/coursier#578]
This project has existed for over two years, and every single release is marked as a "pre-release". Please cut and release a stable version.

**Comment by alexarchambault** [comment]
As soon as https://github.com/coursier/coursier/pull/579, https://github.com/coursier/coursier/pull/581, https://github.com/coursier/coursier/pull/567, and maybe https://github.com/coursier/coursier/pull/560, are merged, `1.0.0-RC4` will be released. `1.0.0` final should follow if no major issue arises in the mean time.
