### ISSUE TITLE
Duplicate mappings

### ISSUE THREAD

**Issue by rvangsgaard** [coursier/coursier#582]
Version 1.0.0-RC3

`[trace] Stack trace suppressed: run last elastic-beanstalk:stage for the full output.
[error] (elastic-beanstalk:stage) Duplicate mappings:
[error] 	/home/MYHOME/PROJECT_PATH/target/docker/stage/opt/docker/lib/jaxen.jaxen-1.1.6.jar
[error] from
[error] 	/home/MYHOME/.coursier/cache/v1/https/repo1.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.bundle
[error] 		/home/MYHOME/.coursier/cache/v1/https/repo1.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.jar
`

The culprit seem to be `"com.google.code.findbugs" % "findbugs" % "3.0.1"`

It works going back to Ivy resolver.

**Comment by alexarchambault** [comment]
Closing for now. `"com.google.code.findbugs" % "findbugs" % "3.0.1"` seems to be resolved fine with recent sbt-coursier versions (`1.1.0-M13-2` is fine in particular).
