### ISSUE TITLE
Release plugin for 1.0.0-M6

### ISSUE THREAD

**Issue by jvican** [coursier/coursier#583]

**Comment by alexarchambault** [comment]
I'm running into issues in https://github.com/coursier/coursier/pull/560, which adds support for it. Latest one: it keeps compiling "compiler bridges" during the scripted tests, each of them taking ~45s, which slows the CI considerably... (and makes Travis time out...)

**Comment by alexarchambault** [comment]
`1.0.0-RC4` with support for sbt `1.0.0-M6` is out (since a few days).
