### ISSUE TITLE
shading seems broken between 1.0.0-RC2 and RC3

### ISSUE THREAD

**Issue by fommil** [coursier/coursier#590]
I upgraded sbt-ensime to RC3 (you should be able to easily reproduce that) and got this in the scripted tests, despite not shading jsoup

```
[info] java.lang.NoClassDefFoundError: Could not initialize class ensime.shaded.coursier.shaded.org.jsoup.nodes.Entities$EscapeMode [info] at ensime.shaded.coursier.shaded.org.jsoup.nodes.Document$OutputSettings.<init>(Document.java:372)
```

I minimised it to an upgrade from RC2 to RC3, still borken in RC5

**Comment by alexarchambault** [comment]
I think it originates from jsoup being shaded in coursier since `1.0.0-RC3`...  Its resources themselves are moved, but the hard-coded paths towards them are not adjusted accordingly. This can be fixed by suggesting the shading plugin to shade whole namespaces, like done [here](https://github.com/alexarchambault/ammonium/blob/master/build.sbt#L194-L198) for example.

Supplying whole namespaces this way makes the shading itself faster, which (good news!) allows to shade scalaz along coursier too, if the `scalaz` namespace is provided (done in the example above).

**Comment by alexarchambault** [comment]
You shouldn't need to shade the `org.jsoup` namespace in your case, as jsoup is now already shaded in coursier. You would need to shade `coursier` at least, and optionally `scalaz`.

**Comment by fommil** [comment]
thanks! So I just don't depend on `jsoup` anymore?

**Comment by fommil** [comment]
hmm, that still causes the same problem. Also if I have a list of shaded namespaces (just coursier), I still get the error. I guess that's because it's shading your shaded jsoup.

Would it maybe be best if you just don't shade anything and let that be a downstream decision? If you were going to shade anything, I'd want you to shade scalaz, but then that forces me to shade it and that's a lot of time to shade.

**Comment by alexarchambault** [comment]
Huh, weird, do you an open PR with it somewhere? It works me in my [modified Ammonite](https://github.com/alexarchambault/ammonium/blob/master/build.sbt#L194-L198) (and was working in https://github.com/lihaoyi/Ammonite/pull/604).

**Comment by fommil** [comment]
I'll push a branch for you to try https://github.com/fommil/ensime-sbt/tree/coursier-bug

Try the fastest test, which is:

`scripted sbt-ensime/simple-build-sbt`

**Comment by alexarchambault** [comment]
`shadeNamespaces` seems to be overridden (reset) by `ShadingPlugin.projectSettings`... Putting the `shadeNamespaces  ++= ...` after it seems to work (I now get a ensime expect / diff error when running the scripted test, but that seems unrelated to shading proper).

**Comment by fommil** [comment]
Doh! Ok I'll try that. What setting did you use?

**Comment by alexarchambault** [comment]
I only used `shadeNamespaces += "coursier"`. You could shade scalaz too now, by adding `"scalaz"` there and not depending explicitly on it. It's fast enough thanks to `shadeNamespaces` now.

**Comment by alexarchambault** [comment]
(Closing the issue...)

**Comment by fommil** [comment]
nice this seems to be working, thanks for the help!

**Comment by fommil** [comment]
do I still need to transitively depend on quasiquotes?

**Comment by alexarchambault** [comment]
Not necessarily... you can try to shade it. (I don't think I tried to shade this one afaic, I only shaded coursier in 2.11.)
