### ISSUE TITLE
First `update` is 10x slower

### ISSUE THREAD

**Issue by dragos** [coursier/coursier#594]
I am not sure if this is normal:

```
> update
[info] Updating xxx
[info] Resolved xxx dependencies
...
[success] Total time: 104 s, completed Jun 28, 2017 8:08:23 PM
> clean
[success] Total time: 1 s, completed Jun 28, 2017 8:08:27 PM
> update
[success] Total time: 12 s, completed Jun 28, 2017 8:08:40 PM
```

There is no download in either of the cases. If I restart Sbt, it's exactly the same timings: first `update` takes 102-104s, and the next one is around 10s. Why could this be?

**Comment by alexarchambault** [comment]
@dragos Hard to tell with that level of details ;-) I never ran into that long resolutions (even in my biggest projects).

Is it happening since a particular RC? If it's only since `1.0.0-RC6`, it might get fixed soon (I'll rework a bit the changes from RC5 to RC6).

**Comment by dragos** [comment]
No, RC6 doesn't work on this project (see #593). This is RC2 but I noticed the same behavior in RC5.

**Comment by dragos** [comment]
It looks like a lot of time is spent in `HttpsUrlConnection.getLastModified` for the first run. The second `update` is much faster, but still around 20s. Some time is spent in fastparse.
<img width="915" alt="screen shot 2017-07-03 at 14 35 47" src="https://user-images.githubusercontent.com/133742/27793177-3dc60768-5ffd-11e7-8ac8-933f642bcb8c.png">

**Comment by dragos** [comment]
<img width="1204" alt="screen shot 2017-07-03 at 14 38 52" src="https://user-images.githubusercontent.com/133742/27793203-5f551270-5ffd-11e7-86d5-d87f0c5e7e0e.png">

**Comment by alexarchambault** [comment]
Closing for now. Please re-open if you have more details (maybe specificities of the underllying repository in particular).
