### ISSUE TITLE
Unable to resolve test-jar artifacts from local Ivy repository

### ISSUE THREAD

**Issue by mpilquist** [coursier/coursier#605]
I'm experiencing an issue with coursier 1.0.0-RC6 where it silently fails to add a test-jar to the classpath when the artifact is published in the local Ivy cache.

Specifically, consider a project like this:

```scala
classpathTypes += "test-jar"
libraryDependencies ++= Seq(
  "com.github.mpilquist" %% "coursier-test-a" % "0.1-SNAPSHOT",
  "com.github.mpilquist" %% "coursier-test-a" % "0.1-SNAPSHOT" % "test" classifier "tests"
)
```

If coursier finds the dependency in a remote repository, then the regular `jar` artifact is added to the compile classpath and both the regular `jar` and the `test-jar` are added to the test classpath. If instead coursier finds the dependency in the local ivy repository, the `test-jar` is not added to the test classpath.

I've posted a sample project setup that demonstrates this: https://github.com/mpilquist/coursier-local-test-jars

**Comment by durban** [comment]
Maybe related: #318.
