### ISSUE TITLE
Coursier not using SFTP resolver

### ISSUE THREAD

**Issue by zzvara** [coursier/coursier#607]
Added coursier to SBT as a plugin. Immediately resolving does not work for 3 libraries, which are supposed to be taken from an SFTP resolver. That resolver is not even tried.

Does Coursier support SFTP resolvers, or is this to be added?

**Comment by alexarchambault** [comment]
These aren't supported for now. coursier supports custom protocols via `java.net.URL`. E.g. fm-sbt-s3-resolver adds support for s3 this way (see https://github.com/frugalmechanic/fm-sbt-s3-resolver/blob/1aa10983e3ba70eefef014fbdd57fb6a66c0a47f/src/main/scala/fm/sbt/s3/Handler.scala).

**Comment by alexarchambault** [comment]
Closing this for now. Feel free to open a PR with support for that, or to discuss that further here.
