### ISSUE TITLE
Allow passing java properties after bootstraping

### ISSUE THREAD

**Issue by MasseGuillaume** [coursier/coursier#615]
I can use -J option during the bootstrapping I would like to pass option Java after bootstrapping. This could be via environment variable for example.

**Comment by dwijnand** [comment]
I agree: 

> I don't really want to regenerate my own CLI when I want to tweak a JVM option.

(from https://github.com/scalameta/scalafmt/issues/813#issuecomment-285885825.)

**Comment by alexarchambault** [comment]
That shouldn't be hard to add, [this line](https://github.com/coursier/coursier/blob/5a271fffc511d30749f36ea55ba20ecb55ae3733/cli/src/main/scala-2.11/coursier/cli/Bootstrap.scala#L215) should just have to be changed... PR? 🙂

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/852 partially fixes that. One can know pass arguments like `-Dfoo=b` to a bootstrap to adjust Java properties.

For other kind of Java arguments, one can always do
```
$ java -Xmx2g -jar bootstrap [args]
```
