### ISSUE TITLE
Get the path of artifact that has been resolved (and cached)

### ISSUE THREAD

**Issue by zzvara** [coursier/coursier#618]
I'd like to resolve artifacts and then retrieve the (download) path (for example `C:\Users\User\.coursier\cache\v1\http\repository\artifactory\sbt-dev-local\org\apache\spark\spark-core_2.11\2.3.0-SNAPSHOT`), to supply it to a deployment script.

How can one retrieve such a path using the API?

**Comment by alexarchambault** [comment]
Not sure I fully understand what you mean here, but `coursier.CachePath` has [a method](https://github.com/coursier/coursier/blob/master/paths/src/main/java/coursier/CachePath.java#L39) that translates a url to its local path. It is available via the `coursier-cache` module for example.

**Comment by zzvara** [comment]
Thanks!
