### ISSUE TITLE
support of SHA-256 checksums

### ISSUE THREAD

**Issue by gabor-aranyossy** [coursier/coursier#621]
I need to use SHA-256 hashes for checksums. Adding a custom `checksumURL` to `Artifact` would allow me to do this, but eventually the validation fails with a `ChecksumFormatError` as only md5 and sha1 hashes seem to be supported [here](https://github.com/coursier/coursier/blob/master/cache/src/main/scala/coursier/Cache.scala#L875).

Would it be possible to introduce support for this somehow?

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/issues/625.
