### ISSUE TITLE
csbt doesn't use resolver added in ~/.sbt/0.13/plugins/plugins.sbt

### ISSUE THREAD

**Issue by ritschwumm** [coursier/coursier#622]
to use one of my sbt plugins, i have added my private repository added to ```~/.sbt/0.13/plugins/plugins.sbt``` like this:
```
resolvers	+= "foobar" at "http://example.net/maven"
addSbtPlugin("example.net" % "sbt-custom-plugin" % "1.0.0")
```
now when i start csbt, i get an error:
```(*:coursierSbtClassifiersResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution```

 it seems sbt looks into these resolvers:
```
~/.ivy2/local/com.example/...
https://repo1.maven.org/maven2/com/example/...
https://repo.typesafe.com/typesafe/ivy-releases/com.example/xsbt-jedit-control/1.6.0/ivys/ivy.xml
https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.example/...
```

where it does _not_ look is ```http://example.net/maven``` - why?

this might be related to #370.

**Comment by alexarchambault** [comment]
I'm about to add a small README for csbt - it is highly experimental, and suffers a bunch of issues, like this one...

**Comment by ritschwumm** [comment]
thanks you very much, csbt is cool stuff and i really want to use it.

**Comment by ritschwumm** [comment]
just tried with RC12, and everything looks fine now
