### ISSUE TITLE
Classifiers still partially broken in RC8

### ISSUE THREAD

**Issue by agluszyk** [coursier/coursier#624]
Assets artifacts created with Play framework are ignored when Coursier SBT plugin is enabled, however "test" classifier works correctly.

Asset creation snippet:
```
packagedArtifacts in publishLocal := {
  val artifacts: Map[sbt.Artifact, java.io.File] = (packagedArtifacts in publishLocal).value
  val assets: java.io.File = (playPackageAssets in Compile).value
  artifacts + (Artifact(moduleName.value, "jar", "jar", "assets") -> assets)
}
```

Build.sbt snippet:
```
// works under plain sbt and coursier
 val tests = "org.example" % "library" % version % Test classifier "tests"
// works only under plain sbt 
 val assets = "org.example" % "library" % version % classifier "assets"
 libraryDependencies += Seq(tests, assets)
```
It looks like Coursier is either ignoring resolving such artifact or it fails to put it in classpath.

**Comment by alexarchambault** [comment]
A small self-contained repo would be helpful here, to help with this.

**Comment by agluszyk** [comment]
Done, repo:
[https://github.com/agluszyk/coursier_classifiers_issue/tree/master](url)

**Comment by alexarchambault** [comment]
Adding
```scala
artifacts += Artifact(moduleName.value, "jar", "jar", "assets")
```
to the `build.sbt` of the `A` project fixes this. That basically adds a line corresponding to the assets artifact in `~/.ivy2/local/com.example/coursier_classifiers_issue_a_2.12/1.0-SNAPSHOT/ivys/ivy.xml`. coursier can then find that artifact.

It could be possible to have coursier check for the artifact without that... But that workaround should work for now.

**Comment by alexarchambault** [comment]
Closing this for now. My understanding is that the published `ivy.xml` must contain a line for the `assets` artifact, for it to be subsequently picked. This can be achieved with the `artifacts += ` line above.
