### ISSUE TITLE
Global 1.0-RC9 SBT plugin fails to resolve global sbt-errors-summary plugin

### ISSUE THREAD

**Issue by danxmoran** [coursier/coursier#632]
If my `~/.sbt/0.13/plugins/plugins.sbt` has:
```SBT
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC9")
addSbtPlugin("org.duhemm" % "sbt-errors-summary" % "0.6.0")
```
Then when loading any project I get:
```
[trace] Stack trace suppressed: run last *:coursierSbtClassifiersResolution for the full output.
[error] (*:coursierSbtClassifiersResolution) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
[error]     org.duhemm:sbt-errors-summary;sbtVersion=0.13;scalaVersion=2.10:0.6.0:
[error]         not found:
[error]             /Users/danmoran/.ivy2/local/org.duhemm/sbt-errors-summary/scala_2.10/sbt_0.13/0.6.0/ivys/ivy.xml
[error]             /Users/danmoran/.sbt/preloaded/org.duhemm/sbt-errors-summary/0.6.0/ivys/ivy.xml
[error]             /Users/danmoran/.sbt/preloaded/org/duhemm/sbt-errors-summary_2.10_0.13/0.6.0/sbt-errors-summary-0.6.0.pom
[error]             https://repo1.maven.org/maven2/org/duhemm/sbt-errors-summary_2.10_0.13/0.6.0/sbt-errors-summary-0.6.0.pom
[error]             https://repo.typesafe.com/typesafe/ivy-releases/org.duhemm/sbt-errors-summary/0.6.0/ivys/ivy.xml
[error]             https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.duhemm/sbt-errors-summary/0.6.0/ivys/ivy.xml
```

Everything works fine if I add the plugins in `project/plugins.sbt` instead of the global plugins file.

**Comment by alexarchambault** [comment]
I was able to reproduce the error locally. Looks like the fix of `updateSbtClassifiers` in 1.0.0-RC9 unearthed some errors...

Something that bugs me is that the sbt plugins repo doesn't appear in the repositories that are checked (via `externalResolvers.in(updateSbtClassifiers)` - it should appear as a repository starting with `https://repo.scala-sbt.org/scalasbt/sbt-plugins-releases/` in the list above, the closest is only like `https://repo.scala-sbt.org/scalasbt/ivy-snapshots/...`)

The sbt plugin repository might just be missing from this initial repository list. Without sbt-coursier, things should be picked from `~/.ivy2/cache`. With it, an error happens as coursier doesn't mix things from  various repositories in its cache.

Not 100% sure, but it seems this repository list comes from [here](https://github.com/sbt/sbt/blob/b2b02a1dd7339bca4532d45f013172c6f0620da7/src/main/conscript/xsbt/launchconfig#L14-L19).

@dwijnand Does this ring a bell to you, the sbt plugins repository being missing initially in `externalResolvers.in(updateSbtClassifiers)` (itself set [here](https://github.com/sbt/sbt/blob/0.13/main/src/main/scala/sbt/Defaults.scala#L1393-L1396))?

**Comment by alexarchambault** [comment]
Maybe related:
- https://github.com/calvinlfer/free-monad-coproduct-example/issues/2
- https://github.com/sbt/sbt/issues/2243
- https://github.com/akka/akka-http/issues/1056
- https://github.com/akka/akka-http/issues/1057

**Comment by FranklinChen** [comment]
Similar happens when having global

```
addSbtPlugin("com.timushev.sbt" % "sbt-updates" % "0.3.1")
```

I got

```
coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
    com.timushev.sbt:sbt-updates;sbtVersion=0.13;scalaVersion=2.10:0.3.1:
        not found:
            /Users/chen/.ivy2/local/com.timushev.sbt/sbt-updates/scala_2.10/sbt_0.13/0.3.1/ivys/ivy.xml
            /Users/chen/.sbt/preloaded/com.timushev.sbt/sbt-updates/0.3.1/ivys/ivy.xml
            /Users/chen/.sbt/preloaded/com/timushev/sbt/sbt-updates_2.10_0.13/0.3.1/sbt-updates-0.3.1.pom
            https://repo1.maven.org/maven2/com/timushev/sbt/sbt-updates_2.10_0.13/0.3.1/sbt-updates-0.3.1.pom
            https://repo.typesafe.com/typesafe/ivy-releases/com.timushev.sbt/sbt-updates/0.3.1/ivys/ivy.xml
            https://repo.scala-sbt.org/scalasbt/ivy-snapshots/com.timushev.sbt/sbt-updates/0.3.1/ivys/ivy.xml
```
