### ISSUE TITLE
Unable to resolve sbt-core-next with RC10

### ISSUE THREAD

**Issue by 2m** [coursier/coursier#636]
I tried upgrading to RC10 but got the following error while loading the project:

```
coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
    org.scala-sbt:sbt-core-next;sbtVersion=0.13;scalaVersion=2.10:0.1.1:
        not found:
            /home/martynas/.ivy2/local/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
            https://repo1.maven.org/maven2/org/scala-sbt/sbt-core-next_2.10_0.13/0.1.1/sbt-core-next-0.1.1.pom
            https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-core-next/0.1.1/ivys/ivy.xml
            https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt-core-next/0.1.1/ivys/ivy.xml
            https://repo.scala-sbt.org/scalasbt/maven-snapshots/org/scala-sbt/sbt-core-next_2.10_0.13/0.1.1/sbt-core-next-0.1.1.pom
            https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
```

Tried with sbt 0.13.15 and 0.13.16

**Comment by dwijnand** [comment]
(Btw what depends on sbt-core-next?)

**Comment by alexarchambault** [comment]
Possibly an error (independent of sbt-coursier) at the definition of the ivy-releases repository used here. The url from it that should be checked should be `https://dl.bintray.com/typesafe/ivy-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml` instead of `https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-core-next/0.1.1/ivys/ivy.xml` (`scala_2.10/sbt_0.13` parts missing).

**Comment by alexarchambault** [comment]
Like in https://github.com/coursier/coursier/issues/632, I'm not 100% sure of where this repo is defined, this might [here](https://github.com/sbt/sbt/blob/b2b02a1dd7339bca4532d45f013172c6f0620da7/src/main/conscript/xsbt/launchconfig#L18).

**Comment by 2m** [comment]
As for more context, I noticed this error when trying to load [alpakka](https://github.com/akka/alpakka)'s master build with RC10. I am not sure what depends ` sbt-core-next`. I tried loading the project with RC8 and then running `dependencyBrowseGraph` after `reload plugins` but there was no `sbt-core-next`.

**Comment by rpiaggio** [comment]
I am having this issue too and unable to run coursier as a result of it. Is there any information I can provide to help iron it out?

```
coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
    org.scala-sbt:sbt-core-next;sbtVersion=0.13;scalaVersion=2.10:0.1.1:
        not found:
            C:\Users\rpiaggio\.ivy2\local\org.scala-sbt\sbt-core-next\scala_2.10\sbt_0.13\0.1.1\ivys\ivy.xml
            C:\Users\rpiaggio\.sbt\preloaded\org.scala-sbt\sbt-core-next\0.1.1\ivys\ivy.xml
            C:\Users\rpiaggio\.sbt\preloaded\org\scala-sbt\sbt-core-next_2.10_0.13\0.1.1\sbt-core-next-0.1.1.pom
            https://repo1.maven.org/maven2/org/scala-sbt/sbt-core-next_2.10_0.13/0.1.1/sbt-core-next-0.1.1.pom
            https://repo.typesafe.com/typesafe/ivy-releases/org.scala-sbt/sbt-core-next/0.1.1/ivys/ivy.xml
            https://repo.scala-sbt.org/scalasbt/ivy-snapshots/org.scala-sbt/sbt-core-next/0.1.1/ivys/ivy.xml
            https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/org.scala-sbt/sbt-core-next/scala_2.10/sbt_0.13/0.1.1/ivys/ivy.xml
```

BTW, our Scala version in `build.sbt` is 2.11.11, not sure why 2.10 libraries are being downloaded.

**Comment by alexarchambault** [comment]
The [current master](https://github.com/akka/alpakka/commit/618ebf0e843e2369ca095b598472dafa5e9a975b) of alpakka seems to work fine with sbt-coursier `1.0.0-RC12` (`update`, `updateClassifiers`, and `updateSbtClassifiers` are ok).

**Comment by alexarchambault** [comment]
Closing this. Re-open if ever that's not fixed for you.

**Comment by 2m** [comment]
Yes. It works great. Thanks!
