### ISSUE TITLE
Coursier fails when providing project reference to github

### ISSUE THREAD

**Issue by jmartinezseven** [coursier/coursier#639]
Hi, 
My problem is when I'm trying to add a project reference like this 

lazy val `some-lib` =
  ProjectRef(uri("ssh://git@github.com/aaa/project.git#sdaf"), "lib")

It doesn't resolve the dependency. I don't know if I need to set another configuration for that

**Comment by alexarchambault** [comment]
Yep, source repositories aren't supported by sbt-coursier for now (see https://github.com/coursier/coursier/issues/388).

Closing to keep the discussion in https://github.com/coursier/coursier/issues/388.
