### ISSUE TITLE
coursier renames a tar.gz artifact to jar, and put that on classpath instead of jar

### ISSUE THREAD

**Issue by hochgi** [coursier/coursier#644]
## reproduce:

The [project in question](https://github.com/thomsonreuters/CM-Well) is open source, so:

edit version to RC11:

https://github.com/thomsonreuters/CM-Well/blob/75a6090b8d5036436ff3990a464244015eefe8e0/server/project/cmwell-build-plugin/build.sbt#L8

1. `cd server`
2. `sbt -mem 2048 packageCmwell`
3. `cd cmwell-cons/app`
4. `./cmwell.sh`
    * `> :lo pe`
    * `> pe.install`

Then inspect classpath of `play.core.server.ProdServerStart` (the play webserver).
It depends on https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/1.7.4/elasticsearch-1.7.4.jar
And there a `elasticsearch-1.7.4.jar` on classpath. But it's not the jar. it's this:
https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/1.7.4/elasticsearch-1.7.4.tar.gz
renamed to jar.

App fails of course with `NoClassDefFoundError`of elasticsearch classes.

Instead of (4) running the project (pretty heavy) you can simply inspect `cmwell-cons/app/lib/elasticsearch-1.7.4.jar` and see it's actually the tar.gz renamed to jar.

## other versions:

* This behavior seems consistent in versions 1.0.0-RC3 - 1.0.0-RC11.  
* Versions 1.0.0-M15-2 - 1.0.0-RC2 has a similar error where the artifact being renamed is the `zip` artifact: https://repo1.maven.org/maven2/org/elasticsearch/elasticsearch/1.7.4/elasticsearch-1.7.4.zip  
* 1.0.0-M15-1 seems like the last version it worked as expected.

**Comment by hochgi** [comment]
a workaround to resolve this issue is to get the `ModuleID` forced to `jar()` explicitly.
the following:
https://github.com/thomsonreuters/CM-Well/commit/e23c61e1834106e5f76e5429fddd5e38959920d4#diff-dd2b5602b232a56e0bbd68b8b8839225R13
fixed the issue we had, and allowed us to upgrade coursier.

### NOTE:
This is just a workaround, not a fix. the bug still gets the wrong artifact when `type` isn't forced explicitly, and more than 1 type exist.

**Comment by alexarchambault** [comment]
@hochgi Is it still an issue? Seems the line modified by https://github.com/CM-Well/CM-Well/commit/e23c61e1834106e5f76e5429fddd5e38959920d4#diff-dd2b5602b232a56e0bbd68b8b8839225R13 isn't around anymore. And adding sbt-coursier to it seems to put only JARs in `server/cmwell-cons/app/cons-lib`.

**Comment by hochgi** [comment]
It's been a while, and I'm no longer maintaining CM-Well. I think @e-orz is the best person to ask that question.
Thank you for following up, and making sure coursier is awesome!

**Comment by e-orz** [comment]
Hi,
I recently changed the Elasticsearch fetching way to use the new higher lever fetch API of the newer coursier. I will check soon if the issue still exists (of if it still relevant).

Thanks!

**Comment by e-orz** [comment]
Hi,
I looked at the code again. The artefact got is the jar one.
Elasticsearch recently changed their client to not include all the libraries needed for the server side, that is the reason for removing the exclude lines. The artefact is now elasticsearc-client and the jar seems just fine.

This issue can be closed now.

**Comment by alexarchambault** [comment]
Cool, thanks @e-orz!
