### ISSUE TITLE
Error in IvyXml.dependencies() - via Toree spark kernel

### ISSUE THREAD

**Issue by bzamecnik** [coursier/coursier#649]
I'm trying to load dependencies in Toree via its [`%AddDeps`](https://github.com/apache/incubator-toree/blob/master/kernel/src/main/scala/org/apache/toree/magic/builtin/AddDeps.scala) keyword:

```
%%AddDeps org.clapper grizzled-slf4j_2.11 1.3.1
```

However it fails in `coursier` with only a terse error message:

```
Magic AddDeps failed to execute with error: 
coursier/ivy/IvyXml$$anonfun$coursier$ivy$IvyXml$$dependencies$2$$anonfun$apply$10$$anonfun$apply$11$$anonfun$apply$12$$anonfun$apply$13$$anonfun$apply$14
```
It points to the [`IvyXml` class](https://github.com/coursier/coursier/blob/master/core/shared/src/main/scala/coursier/ivy/IvyXml.scala) and some lambda function in its `dependencies()` method in particular.

The code and docs said that "Ivy support is poorly tested" and a lot of errors are not reported:

> `// FIXME Errors ignored as above - warnings should be reported at least for anything suspicious`

It failed also with other packages. In this installation I was not able to get any other result for any package. `%AddJar` keyword works. Also on `https://try.jupyter.org/` kernels it work OK, except for some DNS error.

Versions:

Toree 0.2.0.dev1 - Spark 2.1.0 - Scala 2.11

**Comment by alexarchambault** [comment]
It seems to be fine with `1.0.0-RC12`:
```
$ coursier fetch -t org.clapper:grizzled-slf4j_2.11:1.3.1
  Result:
└─ org.clapper:grizzled-slf4j_2.11:1.3.1
   ├─ org.scala-lang:scala-library:2.11.11
   └─ org.slf4j:slf4j-api:1.7.7
…/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.11/scala-library-2.11.11.jar
…/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar
…/https/repo1.maven.org/maven2/org/clapper/grizzled-slf4j_2.11/1.3.1/grizzled-slf4j_2.11-1.3.1.jar
```

Can you try switching to it? (Although I see you're currently on `1.0.0-RC10`, which seems to work fine for me too…)

**Comment by bzamecnik** [comment]
Probably it was a bad build. When I rebuilt it it was working well.
