### ISSUE TITLE
sbt-scripted fails when using sbt 1.0.1 and coursier

### ISSUE THREAD

**Issue by nrinaudo** [coursier/coursier#650]
I'm running:
- sbt 1.0.1
- coursier 1.0.0-RC11

When using sbt-scripted, I systematically get the following failure:

```
info] Error during sbt execution: Could not finder sbt launch configuration.  Searched classpath for:
[info] 	/sbt.boot.propertiesUnspecified
[info] 	/sbt/sbt.boot.propertiesUnspecified
[info] 	/sbt.boot.properties
[info] 	/sbt/sbt.boot.properties
```

When I remove coursier from my list of global plugins, everything seems to behave as it should.

[Here's a repository](https://github.com/nrinaudo/coursier-repro) containing the smallest reproduction I could make, and [there's the travis log](https://travis-ci.org/nrinaudo/coursier-repro) that shows the same failure.

By contrast, [this is the travis log](https://travis-ci.org/nrinaudo/coursier-repro/builds/271830758) when coursier is not enabled.

**Comment by alexarchambault** [comment]
Adding the [following lines](https://github.com/coursier/coursier/blob/8d584d9ae0bafe8b64d5f37042e94e63d35a4766/project/Settings.scala#L186-L211) to `build.sbt` solved the problem for me. There should be a (probably quite ad hoc) way to have sbt-coursier generate update reports that don't require that workaround, but for now, one has to add these lines.

**Comment by nrinaudo** [comment]
Jesus, SBT, why do you have to make it so hard to love you...

**Comment by dwijnand** [comment]
Any more info on what the root cause is, @alexarchambault?

**Comment by alexarchambault** [comment]
@dwijnand The default implementation of `sbtLauncher` makes assumptions about how the order of things in the update report - in particular, it seems to expect the jar of `org.scala-sbt:sbt-launch` upfront. sbt-coursier doesn't provide guarantees about the order of things in the update report (for now, at least).

**Comment by alexarchambault** [comment]
That should be fine in `1.0.0-RC12` (with or without the workaround). Re-open if ever you still run into this with it.

**Comment by nrinaudo** [comment]
Confirmed, at least for my user case.
