### ISSUE TITLE
How to change artifact type after resolution?

### ISSUE THREAD

**Issue by hnrklssn** [coursier/coursier#656]
I want to transitively download sources of all dependencies. I'm working with the Scala API. How do I take a resolved dependency and make it download the source artifact when fetched?

**Comment by alexarchambault** [comment]
Look for `val localArtifacts` in the README. That illustrates how to fetch artifacts after a resolution.

**Comment by alexarchambault** [comment]
Adjusting [classifiers](https://get-coursier.io/docs/api.html#classifiers) with the new [API](https://get-coursier.io/docs/api.html) allows that.
