### ISSUE TITLE
[feature request] fetch/resolve json report

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#659]
Hi,

I am trying to integrate coursier with [Pants](https://www.pantsbuild.org/) build tool as a replacement for the existing ivy resolver. The goal is to have Pants to hand off the 3rdparty resolution/fetch job to coursier, then parse its result. 

Currently the command line is great,
```
./coursier resolve -t (or -T) <artifacts ...>
```
but it is not machine friendly. To start with, essentially I would require, e.g. json representation of the tree, and potentially the reason for conflict resolution. 

I am not very familiar with code base or Scala, so is it something an existing contributor can achieve relatively quickly? If not, can someone kindly point me to the relevant code?

Thanks,
Yi

**Comment by alexarchambault** [comment]
One way of integrating coursier could be as a library, via its [API](https://github.com/coursier/coursier#api-1). A number of projects already do that ([Ammonite](https://github.com/lihaoyi/Ammonite/blob/79f3f8b32e70245842ffa8b12d9e5939d0cd286e/amm/runtime/src/main/scala/ammonite/runtime/tools/IvyThing.scala), [scalafiddle](https://github.com/scalafiddle/scalafiddle-core/blob/502933eefd324e8cd4bb447b7669f4e78f6c70ab/compiler-server/src/main/scala/scalafiddle/compiler/LibraryManager.scala#L84), …).

The CLI doesn't propose JSON output for now, but that could possibly be added (and it could also accept its options as JSON).

**Comment by wisechengyi** [comment]
Thanks. The reason that we cannot use the scala api is that Pants is not in scala, and ideally we would tend not to write another scala wrapper for it. 

Adding `--json` to cli sounds good. Would you kindly point me to the related code?

**Comment by alexarchambault** [comment]
One way of doing this could consist in:
- adding a `json: Option[String]` option in [`FetchOptions`](https://github.com/coursier/coursier/blob/b7c7d5f9e6b8c848a3205ba75dfcd331f4d7df01/cli/src/main/scala-2.11/coursier/cli/Options.scala#L201),
- then, [right after](https://github.com/coursier/coursier/blob/master/cli/src/main/scala-2.11/coursier/cli/Fetch.scala#L14) we get the `FetchOptions` from the command-line args, if a JSON file is specified, parse it, and create a new `FetchOptions` from the former one and from what's in the JSON. Then the new `FetchOptions` can be used instead of the former one.

To parse / process the JSON file, [argonaut](https://github.com/argonaut-io/argonaut/) 6.2 is already a dependency of the CLI of coursier, along with [argonaut-shapeless](https://github.com/alexarchambault/argonaut-shapeless).

**Comment by alexarchambault** [comment]
That's for the input part, then the output… 🤔

**Comment by wisechengyi** [comment]
I'm mostly concerned with the output first because pants can flat the
commands now but have difficulty parsing out the result.

**Comment by wisechengyi** [comment]
Hi @alexarchambault,

Would appreciate your thought on the following approach:
Pants currently uses ivy for resolution, so essentially it calls:
```
java <some ivy jars> org.apache.ivy.Main \
-settings <ivysettings.xml> \
-ivy <resolve-ivy.xml> \
-confs default -cachepath <cache dir>
```
`ivysettings.xml` specifies where the repos are, `resolve-ivy.xml` specifies what jars to resolve, and `cache dir` will have the final ivy report.

Is it how coursier's sbt plugin works? in that coursier gets `ivysettings.xml` and `resolve-ivy.xml` from sbt then return the ivy report back to sbt?

If so, it might be a lot easier for us to integrate coursier into Pants in the same way if coursier can speak ivy, that is Pants only have to care about these 3 xml files.

**Comment by alexarchambault** [comment]
sbt-coursier gets all the input parameters by directly evaluating sbt settings / tasks, it doesn't rely on these xml files.

If you're really only interested in the jar file list (without any configurations-and-the-like considerations), you can just adjust how the jar list is printed around [here](https://github.com/coursier/coursier/blob/9b018f6dbc8627569ede71d7be3e7425c3f2cf5e/cli/src/main/scala-2.11/coursier/cli/Fetch.scala#L39).

Note that the `fetch` command should only print the jar list in stdout (the rest goes to stderr), so if parsing these lines is fine for you (it's just one JAR per line), it should be possible to do what you want without any JSON output.

**Comment by Globegitter** [comment]
While https://github.com/coursier/coursier/commit/a4258f48ce7e9a3b432dc5227ab9cd2dfdc2471a did add a `--json-output-file` for the fetch command it did not add this for the `resolve` command - would it be trivial to also add it to `resolve` @wisechengyi ?

**Comment by jin** [comment]
+1 to @Globegitter - this is really useful for Bazel as we can leverage Coursier's resolution + Bazel's highly cacheable download mechanism, as long as we have a way to parse the JSON output reliably from `resolve`.
