### ISSUE TITLE
cli remove public repo

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#663]
On the cli, coursier will try a https://repo1.maven.org/ and local ivy. Is there a way to remove them and only use the one I specified?

```
$ ./coursier resolve -r https://123.com/ x:y:z
x:y:z:default(compile)

Error:
  x:y:z
    not found: /Users/yic/.ivy2/local/x/y/z/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/x/y/z/y-z.pom
    download error: Caught java.net.ConnectException: Connection refused (Connection refused) (Connection refused (Connection refused)) while downloading https://123.com/x/y/z/y-z.pom
```

**Comment by alexarchambault** [comment]
Extra repos can be specified via the `-r` option. The default ones (Central and Ivy local) can be removed via `--no-default`.

This is discussed around [around that point](https://github.com/coursier/coursier#command-line-1) in the README.

**Comment by wisechengyi** [comment]
ah ok. thanks! reading all the options is hard :D
