### ISSUE TITLE
Coursier not resilient to changing local ivy cache directory

### ISSUE THREAD

**Issue by Mocuto** [coursier/coursier#665]
For resolving local cached dependencies, Coursier assumes they're in the $user.home/.ivy directory, even though that is absolutely not guaranteed.

See the following lines in Cache.scala:
```

  private lazy val ivy2HomeUri = {

    // a bit touchy on Windows... - don't try to manually write down the URI with s"file://..."

    val str = new File(sys.props("user.home") + "/.ivy2/").toURI.toString

    if (str.endsWith("/"))

      str

    else

      str + "/"

  }
```
It's very likely that a user may change their ivy home location via the SBT options:

```

-Dsbt.ivy.home=D:/mocut/.ivy2/

-Divy.home=D:/mocut/.ivy2/

```

Thus, Coursier should try `sys.props("ivy.home")` or `sys.props("sbt.ivy.home")` before deferring to `sys.props("user.home")`

**Comment by alexarchambault** [comment]
It shouldn't be an issue when using coursier from sbt, as the ivy2 local repository comes from sbt itself, not from `coursier.Cache.ivy2Local`. The right Java properties should already be handled fine thanks to that.

It can only be a problem when using coursier via its API (and using directly `coursier.Cache.ivy2Local`), or from the CLI of coursier.

I'd be happy to merge a PR taking into account the `ivy.home` property for `coursier.Cache.ivy2*`.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/705.
