### ISSUE TITLE
Cannot resolve local Maven artefacts

### ISSUE THREAD

**Issue by mduerig** [coursier/coursier#667]
Resolving artefacts only published to the local Maven repository does not seem to be supported. Although I could do 

    coursier.MavenRepository("file://" + java.lang.System.getProperties.get("user.home") + "/.m2/repository/")

this was discouraged at https://github.com/lihaoyi/Ammonite/pull/612#issuecomment-303433642.

It would be nice to have an OOTB option e.g. `coursier.MavenRepository.m2Local` similar to `coursier.Cache.ivy2Local`.

**Comment by alexarchambault** [comment]
`m2Local` can be added, I'd be happy to merge a PR adding it. Although as discussed in https://github.com/lihaoyi/Ammonite/pull/612, I wouldn't recommend using it too much, as it sometimes has POMs without the corresponding JARs, which coursier doesn't support well for now.

**Comment by scottcarey** [comment]
I would love to be able to use coursier's command line tool to fetch / launch things that may be in the maven local repo.

As it stands, it only supports the local ivy cache.

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/868, which is included in the latest milestones (>= `1.1.0-M5`).
