### ISSUE TITLE
sbt ++2.11.11 cli/pack not picking up changes

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#668]
For example, 

1. `sbt ++2.11.11 cli/pack`
2.
```
diff --git a/cli/src/main/scala-2.11/coursier/cli/Options.scala b/cli/src/main/scala-2.11/coursier/cli/Options.scala
index 24c6c03..731cd01 100644
--- a/cli/src/main/scala-2.11/coursier/cli/Options.scala
+++ b/cli/src/main/scala-2.11/coursier/cli/Options.scala
@@ -83,6 +83,12 @@ final case class CommonOptions(
   @Value("profile")
   @Short("F")
     profile: List[String] = Nil,
+
+  @Help("Output format of the resolution")
+  @Value("json")
+  @Short("x")
+    outputFormat: String = "",
+
   @Help("Swap the mainline Scala JARs by Typelevel ones")
     typelevel: Boolean = false,
   @Recurse
```
3. `sbt ++2.11.11 cli/pack`

The changes are not getting picked up. Have to do a `sbt clean` as a workaround, so probably some dependencies are declared correctly.

**Comment by alexarchambault** [comment]
It seems to work fine for me… Starting from clean sources, I run a first `sbt ++2.11.11 cli/pack`, apply the diff, run `sbt ++2.11.11 cli/pack` again, and the changes get picked and the option is listed via `cli/target/pack/bin/coursier fetch --help`.

**Comment by alexarchambault** [comment]
Seems fine now (fixes in recent versions of sbt-pack should have helped).
