### ISSUE TITLE
Coursier doesn't download lwjgl dependencies specified by the sbt-lwjgl-plugin

### ISSUE THREAD

**Issue by bbarker** [coursier/coursier#669]
To try, download an example project (e.g. https://github.com/bbarker/SME), and make sure the coursier plugin is uncommented in plugins.sbt.

From sbt, do `runHelloSimpleApplication`.

At this point, I expect to see something like:

```
[info] Copying files for linux64
[trace] Stack trace suppressed: run last *:lwjglCopyNatives for the full output.
[error] (*:lwjglCopyNatives) java.io.FileNotFoundException: No Natives found in: /home/brandon/.ivy2/cache/org.lwjgl.lwjgl/lwjgl-platform/jars
[error] Total time: 1 s, completed Sep 30, 2017 12:48:47 PM
```

**Comment by alexarchambault** [comment]
@bbarker The problem doesn't seem to come from coursier here. sbt-lwjgl has the ivy2 cache hardcoded in its sources [here](https://github.com/philcali/sbt-lwjgl-plugin/blob/26e52af2dc25e14c4e76fc75dcf062a862daeb97/src/main/scala/Slick2D.scala#L22) or [there](https://github.com/philcali/sbt-lwjgl-plugin/blob/26e52af2dc25e14c4e76fc75dcf062a862daeb97/src/main/scala/LWJGLPlugin.scala#L126), which can't work with coursier. sbt-lwjgl should rely on more generic mechanisms for that (e.g. like sbt-scalafmt does afaik).

**Comment by bbarker** [comment]
Thanks for the feedback. I believe it has been abandoned, I really need to try to find the time to rewrite it at some point (though I keep hesitating in the hope of switching to CBT first :) ).

**Comment by alexarchambault** [comment]
Ok, closing this issue then.
