### ISSUE TITLE
Failing to resolve dependencies that my custom server is returning ERROR 403 (Unauthorized)

### ISSUE THREAD

**Issue by AlexITC** [coursier/coursier#670]
I'm using coursier "1.0.0-RC12", I have added credentials for our own server and I'm getting the following error:

```
error Caught java.io.IOException: Server returned HTTP response code: 403 for URL: https://<server>/artifactory/libs-release/org/scalactic/scalactic_2.11/3.0.1/scalactic_2.11-3.0.1.jar (Server returned HTTP response code: 403 for URL: https://<server>/artifactory/libs-release/org/scalactic/scalactic_2.11/3.0.1/scalactic_2.11-3.0.1.jar)
```

My understanding is that coursier is thinking that our server can provide this library (scalactic) but we are not authorized to retrieve it and stopped looking for it in another server.

Maybe there is something that I'm missing.

**Comment by AlexITC** [comment]
I've done some research, for some reason coursier is getting that most artifacts should be retrieved from my custom server (here: https://github.com/coursier/coursier/blob/master/sbt-coursier/src/main/scala/coursier/Tasks.scala#L964), I thought that it tried to retrieve an artifact from different servers until its found or there are no more servers.

**Comment by alexarchambault** [comment]
@AlexITC Once coursier finds the metadata (POMs for Maven repos), it "sticks" to that repo for JARs. So it doesn't try the other repos for now… This might change in the future, but that's how it works now.

**Comment by l15k4** [comment]
I've hit this problem a couple of times already. Sometimes the solution is deleting the pom from cache ...

**Comment by alexarchambault** [comment]
Closing for now. coursier only tries to get jars from the same repo it originally got metadata.
