### ISSUE TITLE
Ensure tasks that incur IO are properly cached

### ISSUE THREAD

**Issue by godenji** [coursier/coursier#682]
By default Coursier invokes both `coursierResolutions` and `coursierArtifacts` on every `compile`.

When the number of subprojects is small this is not an issue, but when dealing with 30+ subprojects the overhead adds to the already laggy sbt development experience.

Running `sbt -Dsbt.task.timings=true` shows Coursier right behind `compileIncremental` wrt the top time consumers. It doesn't matter how many compilation runs one performs in a warm jvm, these are the top 2 consumers by a wide margin.

I'd prefer to manually `update` dependencies vs. needlessly paying the update tax on every `compile`.

**Comment by alexarchambault** [comment]
I think that's an issue with the [in-memory cache of updates](https://github.com/coursier/coursier/blob/affc902de417f13e4fdbbc42e47ee46d2cc27da0/sbt-coursier/src/main/scala/coursier/Tasks.scala#L420) of sbt-coursier… The [final task](https://github.com/coursier/coursier/blob/affc902de417f13e4fdbbc42e47ee46d2cc27da0/sbt-coursier/src/main/scala/coursier/Tasks.scala#L1208) in the `update` implementation of sbt-coursier relies on this cache, but evaluates anyway the tasks it depends on (that's how `Def.task` works). Some smart use of `Def.taskDyn` should allow to circumvent that.

I might propose to fix that at the upcoming Scala Spree of scala.io (on the 11/3).

**Comment by godenji** [comment]
> I might propose to fix that at the upcoming Scala Spree of scala.io (on the 11/3)

Great, that would be good timing -- fix for slow `compileIncremental` may be making its way into Zinc in the not too distant future as well: https://github.com/sbt/zinc/pull/371

With those fixes in place many users in the Scala ecosystem will be happy 😄

**Comment by godenji** [comment]
@alexarchambault so I've been playing around with this in a local branch.

As a quick hack one can effectively remove the time cost of calculating `coursierArtifacts` by caching the result:
```
private val artifactsCache = new mutable.HashMap[sbt.ProjectRef, Map[Artifact, FileError \/ File]]

def artifactFilesOrErrors(...) = {
  ...
  Def.task {
    artifactsCache.find(_._1 == thisProjectRef.value).map(_._2).getOrElse {
      // determine artifacts and store result in cache
      ...
      artifactsCache.getOrElseUpdate(thisProjectRef.value, ...)
    }
}
```

I am unable to track down where `coursierResolutions` is being invoked on `compile`. I have tried caching the results of various methods (including `def updateTask(...)`) in `Tasks.scala` but `coursierResolutions` remains in the `sbt -Dsbt.task.timings=true` results.

Not sure what a principled solution to caching `coursierArtifacts` and `coursierResolutions` is, but removing the time tax of these lookups on `compile` would be most welcome.

**Comment by godenji** [comment]
Ok, can use same caching approach with `def resolutionsTask(...)` using `thisProjectRef` as the cache key.

In a simple giter8 play test app this results in the removal of the time cost associated with  `coursierArtifacts` and `coursierResolutions` lookup in `compile`.

Providing a proper cache key for multi-project builds is another matter.
