### ISSUE TITLE
Benchmark Dependency Resolution and Download Against sbt 1.0

### ISSUE THREAD

**Issue by omervk** [coursier/coursier#691]
sbt 1.0 features parallel download of artifacts. It would be a great tool (and its output a great addition to the documentation) to add a benchmark of the above.

It could serve as a:

1. Differentiator and "selling point" for newcomers
2. Point of reference for future performance improvements
3. Regression test in terms of speed

I would suggest this be tested with different limits on bandwidth and quality of connection.

**Comment by alexarchambault** [comment]
@omervk I pushed a benchmark project [here](https://github.com/alexarchambault/coursier-benchmark).

**Comment by omervk** [comment]
That's wonderful, thank you for letting me know! Do you have any central place to collect results?

**Comment by alexarchambault** [comment]
See the answers [there](https://twitter.com/alxarchambault/status/936218399746744320). It might be a good idea to collect them somewhere else, yes.

**Comment by omervk** [comment]
How about allowing pull requests into the repo with people's setup and results?

**Comment by alexarchambault** [comment]
Closing this. It could be cool to collect the benchmark results from the tweets though…
