### ISSUE TITLE
'tests' classifier jar not fetched

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#698]
```
$ coursier fetch -t org.apache.avro:trevni-avro:1.8.2 --classifier tests
└─ org.apache.avro:trevni-avro:1.8.2
   ├─ org.apache.avro:trevni-core:1.8.2
   │  ├─ org.apache.commons:commons-compress:1.8.1
   │  ├─ org.slf4j:slf4j-api:1.7.7
   │  └─ org.xerial.snappy:snappy-java:1.1.1.3
   └─ org.slf4j:slf4j-api:1.7.7
```
but no jars are fetched

Strangely classifier 'hadoop2', 'sources', or 'javadoc' works. 
```
$ coursier fetch -t org.apache.avro:trevni-avro:1.8.2 --classifier hadoop2
└─ org.apache.avro:trevni-avro:1.8.2
   ├─ org.apache.avro:trevni-core:1.8.2
   │  ├─ org.apache.commons:commons-compress:1.8.1
   │  ├─ org.slf4j:slf4j-api:1.7.7
   │  └─ org.xerial.snappy:snappy-java:1.1.1.3
   └─ org.slf4j:slf4j-api:1.7.7
/Users/yic/Library/Caches/Coursier/v1/https/repo1.maven.org/maven2/org/apache/avro/trevni-avro/1.8.2/trevni-avro-1.8.2-hadoop2.jar
```

@alexarchambault any insight what might be wrong there? https://search.maven.org/#search%7Cga%7C1%7Corg.apache.avro

**Comment by alexarchambault** [comment]
@wisechengyi Asking for artifact types `test-jar` makes it work:
```
$ coursier fetch -t org.apache.avro:trevni-avro:1.8.2 --classifier tests -A test-jar
```

Admittedly, that's not obvious at all :| `test-jar` artifacts are [automatically added](https://github.com/coursier/coursier/blob/06322622188f2e458b15204e05f4cefa99321df3/sbt-coursier/src/main/scala/coursier/CoursierPlugin.scala#L285) in the sbt plugin. Maybe they should too [in the cli tools](https://github.com/coursier/coursier/blob/06322622188f2e458b15204e05f4cefa99321df3/cli/src/main/scala-2.11/coursier/cli/Options.scala#L172).

**Comment by wisechengyi** [comment]
@alexarchambault Thanks. The command works. However I am perplexed why `test-jar` is an `artifactType`? Is the equivalent of `packaging` in POM? 
> packaging: Now that we have our address structure of groupId:artifactId:version, there is one more standard label to give us a really complete address. That is the project's artifact type. In our case, the example POM for org.codehaus.mojo:my-project:1.0 defined above will be packaged as a jar. We could make it into a war by declaring a different packaging:
https://maven.apache.org/pom.html

If so, the `packaging` should be still `jar`, right?

**Comment by wisechengyi** [comment]
Ah later it explained `test-jar` is a thing, and `type` does not necessarily corresponds to the file extension, so I will add it to the cli artifact type and call it a day.

**Comment by wisechengyi** [comment]
changes went into with https://github.com/coursier/coursier/pull/692
