### ISSUE TITLE
coursier fails to download a bundle snapshot dependecy

### ISSUE THREAD

**Issue by amarouni** [coursier/coursier#703]
Using the latest available version : 
`addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.0-RC13")`

we're trying to resolve the following dependency : https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot/org/talend/daikon/daikon/0.19.0-SNAPSHOT/daikon-0.19.0-20171201.100416-43.pom which is a bundle in snapshot version :
```
<parent>
<groupId>org.talend.daikon</groupId>
<artifactId>daikon-parent</artifactId>
<version>0.19.0-SNAPSHOT</version>
<relativePath>../pom.xml</relativePath>
</parent>
<artifactId>daikon</artifactId>
<packaging>bundle</packaging>
<name>Daikon main shared library</name>
<url>https://github.com/Talend/daikon</url>
```

coursier fails with : `Not Found 1`

Changing from snapshot to release version coursier can correctly resolve and download the dependency.

**Comment by wisechengyi** [comment]
@amarouni possible it's checking it's cached pom hence not seeing anything you updated there. There is a default TTL 24 hours I think. Could you verify the behavior by manually nuking it?

**Comment by amarouni** [comment]
@wisechengyi I'm starting with a brand new environment `rm -rf ~/.cache/coursier && rm -rf ~/.coursier && sbt clean`.
I'm using the scala API :
```
package fr.marouni

import java.io.File
import coursier._
import scalaz.\/
import scalaz.concurrent.Task

object Driver extends App{

  override def main(args: Array[String]): Unit = {

    val attr = Attributes(classifier = "talend")
    val start = Resolution(
      Set(
        Dependency(
          Module("org.talend.daikon","daikon"), "0.20.0-SNAPSHOT")
        )
    )

    val ARTIFACT_REPOSITORY_OSS = "https://artifacts-oss.talend.com/nexus"
    val repositories = Seq(
      MavenRepository("https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot"),
      MavenRepository("https://repo1.maven.org/maven2"),
      MavenRepository(ARTIFACT_REPOSITORY_OSS + "/content/repositories/TalendOpenSourceRelease")
    )

    val fetch = Fetch.from(repositories, Cache.fetch())
    val resolution = start.process.run(fetch).unsafePerformSync
    val errors: Seq[((Module, String), Seq[String])] = resolution.metadataErrors
   println(s"Errors : $errors")
    val localArtifacts: Seq[FileError \/ File] = Task.gatherUnordered(
      resolution.artifacts.map(Cache.file(_).run)
    ).unsafePerformSync
    println(s"Local artifacts : $localArtifacts")
  }

}

```

I always end up with some error message : 
```
Errors : Vector()
Local artifacts : List(..., -\/(NotFound(https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot/org/talend/daikon/daikon/0.20.0-SNAPSHOT/daikon-0.20.0-SNAPSHOT.jar,Some(true))), ...)

```

**Comment by wisechengyi** [comment]
looks like https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot/org/talend/daikon/daikon/0.20.0-SNAPSHOT/daikon-0.20.0-SNAPSHOT.jar does not exist. Do you not think it should resolve to this url?

**Comment by amarouni** [comment]
@wisechengyi It's a snapshot : https://artifacts-oss.talend.com/nexus/content/repositories/TalendOpenSourceSnapshot/org/talend/daikon/daikon/0.20.0-SNAPSHOT/daikon-0.20.0-20171201.142527-3.jar

**Comment by alexarchambault** [comment]
I think I found the origin of the problem here (it has to see with the way artifacts are handled with snapshot versioning), I'll push the fix after some clean up.
