### ISSUE TITLE
activation ignores system property 

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#704]
iiuc https://search.maven.org/remotecontent?filepath=org/apache/mahout/mahout-core/0.8/mahout-core-0.8.pom suggests the deps should be `hadoop-core` if there is no system property name provided instead of `hadoop-common`, `hadoop-mapreduce-client-common`, and `hadoop-mapreduce-client-core`
However
```
java <X> -jar coursier-cli.jar resolve -t org.apache.mahout:mahout-core:0.8
```
gives the same result regardless whether X is 
`-Dname=hadoop.version`, or `-Dhadoop.version`, or empty
```
Result:
└─ org.apache.mahout:mahout-core:0.8
   ├─ com.thoughtworks.xstream:xstream:1.4.4
   │  ├─ xmlpull:xmlpull:1.1.3.1
   │  └─ xpp3:xpp3_min:1.1.4c
   ├─ commons-io:commons-io:2.4
   ├─ org.apache.commons:commons-lang3:3.1
   ├─ org.apache.commons:commons-math3:3.2
   ├─ org.apache.hadoop:hadoop-common:1.1.2
   ├─ org.apache.hadoop:hadoop-mapreduce-client-common:1.1.2
   ├─ org.apache.hadoop:hadoop-mapreduce-client-core:1.1.2
   ├─ org.apache.lucene:lucene-analyzers-common:4.3.0
   │  └─ org.apache.lucene:lucene-core:4.3.0
   ├─ org.apache.lucene:lucene-core:4.3.0
   ├─ org.apache.mahout:mahout-math:0.8
   │  ├─ com.google.guava:guava:14.0.1
   │  ├─ org.apache.commons:commons-math3:3.2
   │  └─ org.slf4j:slf4j-api:1.7.5
   ├─ org.apache.mahout.commons:commons-cli:2.0-mahout
   ├─ org.apache.mrunit:mrunit:1.0.0
   │  ├─ commons-logging:commons-logging:1.1.1
   │  ├─ junit:junit:4.10
   │  │  └─ org.hamcrest:hamcrest-core:1.1
   │  └─ org.mockito:mockito-all:1.8.5
   ├─ org.codehaus.jackson:jackson-core-asl:1.9.12
   ├─ org.codehaus.jackson:jackson-mapper-asl:1.9.12
   │  └─ org.codehaus.jackson:jackson-core-asl:1.9.12
   └─ org.slf4j:slf4j-api:1.7.5
```

suspect: https://github.com/coursier/coursier/blob/0b864ddabf4674ebe673bb3a81e7d2c698cca49c/core/shared/src/main/scala/coursier/core/Activation.scala#L20-L33

Currently having the workaround to exclude them then specify what we exactly need. so not blocking.

**Comment by alexarchambault** [comment]
It would be cool to accept properties that would be taken into account for profile activation, on the command-line. I think I didn't just used the global ones to make resolutions more reproducible… and also to be sure we don't leak anything sensitive from them.

**Comment by alexarchambault** [comment]
`--property` should now allow to pass those on the command line (since `1.1.0-M14-3`).
