### ISSUE TITLE
Allow fetching sources and javadocs when artifact type is specified

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#723]
Filing for book keeping.

Conversation as reference:

Yi Cheng @wisechengyi 09:45
@alexarchambault https://github.com/coursier/coursier/blob/a4258f48ce7e9a3b432dc5227ab9cd2dfdc2471a/cli/src/main/scala-2.11/coursier/cli/Options.scala#L197-L213, --sources and --javadoc will be scraped off when —artifact-type is passed. is that intentional?
can we append “src”, “doc” to types0 instead?

Alexandre Archambault @alexarchambault 13:03
@wisechengyi It might have been intentional at some point, but… it looks like the types could be happened to types0 instead, yep.
what do you mean by "scoped options" for case-app? (if you're still interested in your question above)

Yi Cheng @wisechengyi 13:06
Could you be clear on if it is okay that I make a change to append “src”, “doc” to types0 if sources and javadoc are true respectively

Alexandre Archambault @alexarchambault 13:08
I meant, that would change the current behaviour, but in an acceptable way
So I don't mind either way (keeping the current behaviour, or changing it if it can be useful in some contexts)

**Comment by alexarchambault** [comment]
Should be fixed since the refacting of the fetch command some time ago (since `1.1.0-M11` at least).
