### ISSUE TITLE
Using coursier plugin causes jvm project resolved dependencies from javascript

### ISSUE THREAD

**Issue by buaya91** [coursier/coursier#733]
Coursier Version: 1.0.0

Problem descriptions:

With coursier is enabled on project level, `monix` is being resolved incorrectly in sbt session, the js version of monix is being use and causes runtime exception.

Sorry that I haven't got time to make a minimum reproducible project, but I can confirm the difference is cause by

`addSbtPlugin("io.get-coursier"  % "sbt-coursier"        % "1.0.0")`

**Comment by alexarchambault** [comment]
Trivial coursier command lines, like
```
$ coursier fetch io.monix::monix:2.3.2
$ coursier fetch io.monix::monix:3.0.0-M3
```
 don't seem to run into that…

So yeah, a small repro is needed here…

**Comment by buaya91** [comment]
@alexarchambault I'll try to reproduce in minimal repo this weekend

**Comment by buaya91** [comment]
Closing until I manage to do a reprod
