### ISSUE TITLE
refactor cli helper

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#737]
https://github.com/coursier/coursier/blob/ff65c9dbb161451e0c0dc8b4c2330b610e9fec0a/cli/src/main/scala-2.11/coursier/cli/Helper.scala#L78

One block of code for helper is ~900 lines, so need to have better abstractions. Currently it is hard to tell whether some method or variable at the beginning is used later.

will come back to this if there is no volunteer after I resolve some of my other issues.

**Comment by alexarchambault** [comment]
@wisechengyi I agree that that file needs some refactoring… Initially, I wanted to add a "porcelain" API to coursier (to do roughly the same as the cli, but via a Scala API), and the cli could then use that API instead of `Helper`.

**Comment by wisechengyi** [comment]
not sure if I follow on 'porcelain', is that a 3rdparty library or special term in scala?

**Comment by dwijnand** [comment]
Probably from git: https://git-scm.com/book/en/v2/Git-Internals-Plumbing-and-Porcelain

> This book covers primarily how to use Git with 30 or so subcommands such as checkout, branch, remote, and so on. But because Git was initially a toolkit for a version control system rather than a full user-friendly VCS, it has a number of subcommands that do low-level work and were designed to be chained together UNIX-style or called from scripts. These commands are generally referred to as Git’s “plumbing” commands, while the more user-friendly commands are called “porcelain” commands.

**Comment by alexarchambault** [comment]
Yep, that would be a "higher level" API, a bit like the porcelain commands of git.

**Comment by alexarchambault** [comment]
Closing this, as `Helper` is now (almost) gone. It's only used by the `spark-submit` command, to should be moved to its own repository sooner or later.
