### ISSUE TITLE
Bootstrap mixing artifacts and urls

### ISSUE THREAD

**Issue by bosyi** [coursier/coursier#739]
I encountered a problem when trying to bootstrap my own application, as NOT standalone.
My app was in local ivy2, and bootstrap warned about "non HTTP URLs", which i think should be error as in most cases you end up with broken jar.
Proposition:1) for not standalone bootstrap for urls which not HTTP or only file:// add files to zip
2) maybe make custom flag for this

I looked a bit at code.. but i can't compile it with sbt, error with deps occurred. How to recompile locally coursier executable ?

**Comment by ddigger** [comment]
I am looking at a similar issue. Can you try to compile with sbt after doing ```git submodule update --init --recursive``` ?

**Comment by alexarchambault** [comment]
@bosyi It's described in [DEVELOPMENT.md](https://github.com/coursier/coursier/blob/70fa5f13cb36b2e30bfdddbc76566cbf878bbd79/DEVELOPMENT.md#compile-and-run-the-cli). (Plus, as @ddigger said, this needs the submodules to be checked-out too.)

I agree it would be better to add the `file:/` artifacts to the bootstrap in non standalone mode, maybe keeping the former behaviour behind an option… PR welcome, yep!

**Comment by bosyi** [comment]
PR https://github.com/coursier/coursier/pull/742
