### ISSUE TITLE
Dependency in `exclude` is still being tried to resolve

### ISSUE THREAD

**Issue by 2m** [coursier/coursier#740]
Current [master of sbt-whitesource](https://github.com/lightbend/sbt-whitesource/blob/4b23863dea92ad22715045c9ac65fee47368c31a/build.sbt#L40) has a dependency:
```scala
libraryDependencies += "org.whitesource" % "wss-agent-api-client" % whitesourceVersion exclude("org.boris", "pecoff4j")
```
which excludes `"org.boris" "pecoff4j"` because that is not on Maven Central. However when loading the build with coursier, this dependency is still being resolved, and naturally fails loading the build.

**Comment by alexarchambault** [comment]
@2m `org.whitesource:wss-agent-report:2.4.9` also depends on `org.boris:pecoff4j`, so it should be excluded from it too.

**Comment by 2m** [comment]
Interesting. `sbt-dependency-graph` did not show the dependency to `pecoff4j` after adding the first exclude. Also, sbt without coursier did not try to resolve that artifact.

After adding the second exclude now everything is fine with coursier as well. This ticket can be closed then.

**Comment by dwijnand** [comment]
Interesting difference in semantics. I PR'd sbt-whitesource: https://github.com/lightbend/sbt-whitesource/pull/30.

**Comment by alexarchambault** [comment]
You should use `excludeDependencies` if you want an exclusion to apply everywhere. In `libraryDependencies += "org" % "name" % "ver"exclude("foo", "bar")`, the exclusion only applies to that particular dependency.

**Comment by dwijnand** [comment]
`excludeDependencies` doesn't result in excludes in the POM, IIRC.
