### ISSUE TITLE
CLI fetch command has two different `--sources` options

### ISSUE THREAD

**Issue by propensive** [coursier/coursier#744]
I'm not sure if it's intentional (or consistent) that there are two `--sources` options, but it's a little confusing.

Here are the relevant bits of the help for `fetch`:

```
Command: fetch
Usage: coursier fetch 
  --sources | -S  
        Fetch source artifacts
<snip>
  --sources | -R  <value>
        Source repository - for multiple repositories, separate with comma and/or add this option multiple times
<snip>
```

**Comment by wisechengyi** [comment]
Yeah that's confusing.

https://github.com/coursier/coursier/blob/master/cli/src/main/scala-2.11/coursier/cli/Options.scala#L218

https://github.com/coursier/coursier/blob/master/cli/src/main/scala-2.11/coursier/cli/Options.scala#L38

It's so good to rename one of those at least. Before doing so, @alexarchambault could you clarify the difference between `Repository` and `Source repository`?
```
  @Help("Repository - for multiple repositories, separate with comma and/or add this option multiple times (e.g. -r central,ivy2local -r sonatype-snapshots, or equivalently -r central,ivy2local,sonatype-snapshots)")
  @Value("maven|sonatype:$repo|ivy2local|bintray:$org/$repo|bintray-ivy:$org/$repo|typesafe:ivy-$repo|typesafe:$repo|sbt-plugin:$repo|ivy:$pattern")
  @Short("r")
    repository: List[String] = Nil,
  @Help("Source repository - for multiple repositories, separate with comma and/or add this option multiple times")
  @Short("R")
    sources: List[String] = Nil,
```

**Comment by alexarchambault** [comment]
It corresponds to a deprecated feature, that I though I had removed, but not entirely it seems. https://github.com/coursier/coursier/pull/747 fixes that.
