### ISSUE TITLE
coursier-shared depends on org.scala-sbt %% sbt

### ISSUE THREAD

**Issue by leonardehrenfried** [coursier/coursier#745]
As I was integrating coursier with sbt-librarymanagement, I noticed that `coursier-shared` depends on 
`org.scala-sbt %% sbt`, so the entirety of sbt.

This creates circular dependency as the dependency chain is:
```
sbt -> librarymanagement -> librarymanagement-coursier -> coursier-shared -> sbt ...
```
This creates (I think) a weird compilation issue: https://github.com/sbt/librarymanagement/pull/190#issuecomment-358897786

I believe a dependency on `librarymanagement` would be enough, however I'm unsure where exactly it is defined. Does it come from the recently added `sbt-compat`?

**Comment by alexarchambault** [comment]
@leonardehrenfried It seems `sbt-shared` in coursier doesn't depend on sbt itself:
```
$ coursier resolve -r sbt-plugin:releases -t 'io.get-coursier:sbt-shared;scalaVersion=2.12;sbtVersion=1.0:1.0.1-SNAPSHOT'
  Result:
└─ io.get-coursier:sbt-shared;sbtVersion=1.0;scalaVersion=2.12:1.0.1-SNAPSHOT
   ├─ com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.2.0
   ├─ io.get-coursier:coursier-cache_2.12:1.0.1-SNAPSHOT
   │  ├─ io.get-coursier:coursier_2.12:1.0.1-SNAPSHOT
   │  │  ├─ org.scala-lang:scala-library:2.12.4
   │  │  ├─ org.scala-lang.modules:scala-xml_2.12:1.0.6
   │  │  │  └─ org.scala-lang:scala-library:2.12.0 -> 2.12.4
   │  │  └─ org.scalaz:scalaz-core_2.12:7.2.16
   │  │     └─ org.scala-lang:scala-library:2.12.3 -> 2.12.4
   │  ├─ org.scala-lang:scala-library:2.12.4
   │  └─ org.scalaz:scalaz-concurrent_2.12:7.2.16
   │     ├─ org.scala-lang:scala-library:2.12.3 -> 2.12.4
   │     ├─ org.scalaz:scalaz-core_2.12:7.2.16
   │     │  └─ org.scala-lang:scala-library:2.12.3 -> 2.12.4
   │     └─ org.scalaz:scalaz-effect_2.12:7.2.16
   │        ├─ org.scala-lang:scala-library:2.12.3 -> 2.12.4
   │        └─ org.scalaz:scalaz-core_2.12:7.2.16
   │           └─ org.scala-lang:scala-library:2.12.3 -> 2.12.4
   └─ io.get-coursier:coursier_2.12:1.0.1-SNAPSHOT
      ├─ org.scala-lang:scala-library:2.12.4
      ├─ org.scala-lang.modules:scala-xml_2.12:1.0.6
      │  └─ org.scala-lang:scala-library:2.12.0 -> 2.12.4
      └─ org.scalaz:scalaz-core_2.12:7.2.16
         └─ org.scala-lang:scala-library:2.12.3 -> 2.12.4
```

**Comment by leonardehrenfried** [comment]
Take a look at the POM file on Maven Central: https://repo1.maven.org/maven2/io/get-coursier/sbt-shared_2.12_1.0/1.0.0/sbt-shared-1.0.0.pom

The full sbt artifact is listed as a dependency.

My suspicion is that it's because of `sbt-compat`. I've opened PR a there and I'm hoping that that will make my branch compile without too much include/exclude hackery, even though it doesn't resolve the actual dependency problem. Maybe that's already enough.

**Comment by leonardehrenfried** [comment]
Oh sorry, I've overlooked that.

If it's ok, I'm going to keep this ticket open until the next version of
coursier is released and see if my PR, if it is accepted, fixes my problem.

On 22 January 2018 at 19:26, Alexandre Archambault <notifications@github.com

**Comment by leonardehrenfried** [comment]
Ok, I think I've removed all the sbt._ types from coursier-shared.

After the next release, I'm going to try it out again. 1.0.1 didn't solve all of the compilation/linking problems.

**Comment by leonardehrenfried** [comment]
I've build sbt/librarymangement with 1.0.2 and I'm nearly there.

I missed a single sbt._ import it seems:
```
[error] java.lang.NoClassDefFoundError: sbt/package$
[error] 	at coursier.ToSbt$.$anonfun$updateReport$1(ToSbt.scala:253)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:234)
[error] 	at scala.collection.MapLike$MappedValues.$anonfun$foreach$3(MapLike.scala:253)
[error] 	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:789)
[error] 	at scala.collection.immutable.HashMap$HashMap1.foreach(HashMap.scala:231)
[error] 	at scala.collection.immutable.HashMap$HashTrieMap.foreach(HashMap.scala:462)
[error] 	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:788)
[error] 	at scala.collection.MapLike$MappedValues.foreach(MapLike.scala:253)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:227)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at coursier.ToSbt$.updateReport(ToSbt.scala:223)
```

I will open a PR in the next few days.

**Comment by dqdinh** [comment]
FWIW, I also ran into an issue resolving sbt-compat:

``` [error] (coursierResolutions) coursier.ResolutionException: Encountered 1 error(s) in dependency resolution:
 [error]     com.dwijnand:sbt-compat;sbtVersion=1.0;scalaVersion=2.12:1.2.5:
 [error]         not found:```

I downgraded to version 1.0.0 and the error went away. I saw the error with 1.0.1 and 1.0.2

Looking forward to your PR @leonardehrenfried !

**Comment by leonardehrenfried** [comment]
The repo where sbt-compat is hosted was down a few days ago: https://twitter.com/scala_sbt/status/960928916750917632

I guess this happend more recently, correct?

**Comment by leonardehrenfried** [comment]
Could you try to add `Resolver.sbtPluginRepo("releases")` to your resolvers?

**Comment by dqdinh** [comment]
Thanks @leonardehrenfried  -- I was able to use 1.0.2

**Comment by leonardehrenfried** [comment]
@dqdinh that should actually work out of the box. Are you overriding your resolver settings somewhere?

**Comment by dqdinh** [comment]
@leonardehrenfried - You're right. This works out of the box. I misread the README and put `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.2")` into .sbt/1.0/global.sbt instead of .sbt/1.0/plugins/plugins.sbt.

After resolve an error related to https://github.com/coursier/coursier/issues/450#issuecomment-334863786 I was able to run it out of the box. This was my mistake. Thanks for responding so quickly.

**Comment by leonardehrenfried** [comment]
The 1.1.0-M1 release can now be compiled with sbt/librarymanagement.

Thanks @alexarchambault!
