### ISSUE TITLE
master ci broken

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#752]
https://travis-ci.org/coursier/coursier/builds/331611470, with errors like:
```
----------------------------------- Failures -----------------------------------
X coursier.test.CentralNexus3ProxyTests.versionInterval 13195ms 
  utest.AssertionError: assert(result == expected)
  result: scala.collection.immutable.Vector[String] = Vector(org.webjars.bower:jquery:3.3.1:compile,
   org.webjars.bower:jquery-mousewheel:3.1.13:compile, org.webjars.bower:malihu-custom-scrollbar-plu
  gin:3.1.5:compile)
  expected: Seq[String] = WrappedArray(org.webjars.bower:jquery:3.2.1:compile, org.webjars.bower:jqu
  ery-mousewheel:3.1.13:compile, org.webjars.bower:malihu-custom-scrollbar-plugin:3.1.5:compile)
    utest.asserts.Asserts$.assertImpl(Asserts.scala:114)
    coursier.test.CentralTests$stateMachine$macro$28$1.apply(CentralTests.scala:122)
    coursier.test.CentralTests$stateMachine$macro$28$1.apply(CentralTests.scala:63)
    scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:1
    40)
    java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
    java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
    java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
    java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
X coursier.test.CentralNexus2ProxyTests.versionInterval 11528ms 
  utest.AssertionError: assert(result == expected)
  result: scala.collection.immutable.Vector[String] = Vector(org.webjars.bower:jquery:3.3.1:compile,
   org.webjars.bower:jquery-mousewheel:3.1.13:compile, org.webjars.bower:malihu-custom-scrollbar-plu
  gin:3.1.5:compile)
  expected: Seq[String] = WrappedArray(org.webjars.bower:jquery:3.2.1:compile, org.webjars.bower:jqu
  ery-mousewheel:3.1.13:compile, org.webjars.bower:malihu-custom-scrollbar-plugin:3.1.5:compile)
    utest.asserts.Asserts$.assertImpl(Asserts.scala:114)
    coursier.test.CentralTests$stateMachine$macro$28$1.apply(CentralTests.scala:122)
    coursier.test.CentralTests$stateMachine$macro$28$1.apply(CentralTests.scala:63)
    scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
    scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:1
    40)
    java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
    java.util.concurrent.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1021)
    java.util.concurrent.ForkJoinPool$WorkQueue.execLocalTasks(ForkJoinPool.java:1046)
    java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1058)
    java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
    java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Tests: 126, Passed: 124, Failed: 2
```

**Comment by leonardehrenfried** [comment]
To add to the discussion: The test checks that jquery 3.2.1 is resolved but 3.3.1 was released a couple of days ago. I saw the same error in my own PR: https://github.com/coursier/coursier/pull/746

@alexarchambault said that the failing test could be put behind an if condition.

**Comment by leonardehrenfried** [comment]
Would it not be smarter to update the test-metadata repository? I will make a PR for that.

**Comment by wisechengyi** [comment]
> Would it not be smarter to update the test-metadata repository? I will make a PR for that.
@leonardehrenfried, do you mean to fix the tests concerning jquery or the ones in the description of this issue?

**Comment by leonardehrenfried** [comment]
Aren't they the same problem?

I recently tried to land a PR (https://github.com/coursier/coursier/pull/746) but CI failed because of coursier resolving the wrong version for jquery. The version in the cache(test-metadata) and the version in maven central was different. (https://github.com/coursier/coursier/pull/746#issuecomment-359389059)

I made a PR on the test-metadata repo which I hope will fix this: https://github.com/coursier/test-metadata/pull/1

Do you also have merge permissions there?

**Comment by wisechengyi** [comment]
ah not an expert on js stuff. thanks for doing this!

**Comment by leonardehrenfried** [comment]
I'm also not super sure why this repo exists but I guess it's to speed up tests or alternatively to test coursier's integration with nexus.

**Comment by wisechengyi** [comment]
Would you be able to verify this by changing the sha in `tests/metadata/` to your PR branch and reverting 7a38d1de402000e2618c1736b8eb51f44d82c67b?

Hopefully that'll save some time when @alexarchambault comes back.

**Comment by leonardehrenfried** [comment]
I just ran it and the tests pass.

```
Tests: 235, Passed: 235, Failed: 0
```

I never merged https://github.com/coursier/coursier/commit/7a38d1de402000e2618c1736b8eb51f44d82c67b so there was nothing to revert.

So in order to resolve this ticket you'd need to:

- Merge https://github.com/coursier/test-metadata/pull/1
- Revert https://github.com/coursier/coursier/commit/7a38d1de402000e2618c1736b8eb51f44d82c67b
- Rerun tests

**Comment by wisechengyi** [comment]
Thanks @leonardehrenfried!
LGTM. Unfortunately I don't have merge rights for test-metadata, so will have to wait till alex comes around.

**Comment by DanielRuf** [comment]
Can anyone test with `git bisect` in jQuery which commit from jQuery caused this?

**Comment by leonardehrenfried** [comment]
It isn't any code in jQuery that caused this. jQuery simply released a new version, which leads to a difference resolution result. You have to adjust the expectation of the test to make it pass.

The situation is made a little more complicated by the existence of the test-metadate repo, which mirrors parts of Maven Central for a few tests.

**Comment by wisechengyi** [comment]
@leonardehrenfried Do you think we should pin the jQuery version to resolve against? because right now that means every time there's a jquery update, we need to update the test repo, which does not make sense.

**Comment by leonardehrenfried** [comment]
Hmm, the test specifically resolves something that has a transitive version range dependency on jQuery, basically saying "Use the newest version available." I think this is a useful edge case to test.

However, it is run both against Maven Central directly and the local mirror and expects the same result. I think the complicated edge case should be run only against the local one and maybe a more robust, less edge-casey test can be run against Central.

**Comment by wisechengyi** [comment]
I agree that we should have a test case to fetch the newest version available, but we can also achieve this by artificially telling coursier what the latest version is. In that case our tests would be more self contained and stable.

**Comment by alexarchambault** [comment]
I'll try to re-enable the Nexus proxy tests… The main `CentralTests` rely on the [test-metadata](https://github.com/coursier/test-metadata) repo, so don't download things, and can't get broken when the underlying dependencies are updated. The Nexus tests, otoh, download things (via the Nexus proxy), so can get broken. The tests that can get broken this way can be put behind the `isActualCentral` condition (like [here](https://github.com/coursier/coursier/blob/1ddfbed8a86bdfe289999f6ab8afbfe58d438f21/tests/shared/src/test/scala/coursier/test/CentralTests.scala#L466)), to prevent that.

**Comment by alexarchambault** [comment]
> I agree that we should have a test case to fetch the newest version available, but we can also achieve this by artificially telling coursier what the latest version is. In that case our tests would be more self contained and stable.
This is roughly what happens for the main `CentralTests`. But it's hard to enforce for the Nexus proxy based tests :|

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/753 and https://github.com/coursier/coursier/pull/805.
