### ISSUE TITLE
The way ivy.xml files are found is not robust

### ISSUE THREAD

**Issue by benjyw** [coursier/coursier#755]
Ivy URL/Filesystem repos have separate patterns for finding ivy.xml files vs. finding artifacts. 

E.g., 

```
<url>
  <ivy pattern="http://foo.com/[module]/[revision]/ivy.xml" />
  <artifact pattern="http://foo.com/[module]/[revision]/[artifact]-[revision].[ext]" />
</url>
```
Coursier, however, appears to expect to find an artifact and its accompanying ivy.xml using the same pattern (with artifact="ivy" and ext="xml"). This means that in practice all patterns must end with `/[artifact].[ext]`, or the ivy.xml files must have non-standard names.

This can lead to weird behavior, such as attempting to parse a .jar file as XML (e.g., if the pattern ends with `[module]-[revision].jar` because the author doesn't care about the ivy.xml at all, see https://github.com/coursier/coursier/issues/754)

Update: I guess my statement that Coursier "appears to expect to find an artifact and its accompanying ivy.xml using the same pattern" is inaccurate, since it can find each using a separate pattern, I think. But there still remains the problem that in some cases it can match on a file that isn't an ivy.xml file, but will still attempt to parse it as XML. That said, in practice, resolving https://github.com/coursier/coursier/issues/754 would solve the current issues I'm having. The rest could be worked around with careful use of patterns.

**Comment by alexarchambault** [comment]
Having different patterns for metadata and artifacts is supported when using coursier via its API or its sbt plugin, but not via the CLI. But that should easy to add, one has just to find a right syntax for that… (and handle it around [that line](https://github.com/coursier/coursier/blob/9c274c23d6626d4327e4778bdca6cd5149ca321b/core/shared/src/main/scala/coursier/util/Parse.scala#L319))
