### ISSUE TITLE
Resolution of jar-less modules fails with default Artifactory proxy setup

### ISSUE THREAD

**Issue by cunei** [coursier/coursier#770]
Some Maven/Ivy modules may only exist in order to pull in a set of transitive dependencies, but provide no jar on their own. For example: `"org.apache.maven.resolver" % "maven-resolver" % "1.1.0"` provides this pom, and no jar exists:
```
http://central.maven.org/maven2/org/apache/maven/resolver/maven-resolver/1.1.0/maven-resolver-1.1.0.pom
```
When Coursier is asked to resolved this module, it will attempt to fetch the jar regardless. Normally that will return a 404, which is then ignored; resolution then proceeds normally. For example:
```
[cats:error] Downloading https://artifactory.somedomain.com:8082/artifactory/repo/org/apache/maven/resolver/maven-resolver/1.1.0/maven-resolver-1.1.0.jar
[cats] [info] Compiling 2 Scala sources to /localhome/jenkinssbt/workspace/sbt-community/target-0.9.10-test23/extraction/71686757518411edb8fe5b9b874a24ccbe3740cd/projects/83669638e73164da1a68c364fc1adc0af8b0c86e/project/target/scala-2.12/sbt-1.0/classes ...
[...]
```

In order to speed up resolution, it is common to set up an Artifactory instance as a proxy resolver, configuring sbt so that only that resolver should be used. When Artifactory is asked for a non-existing resource, because of security reasons it will not make a distinction between artifacts that really do non exist, versus those artifacts that may exist, but which are protected and are not accessible by an anonymous user (or an authenticated user with insufficient permissions.) Therefore, Artifactory by default returns a `403 Forbidden` in both cases. When Coursier sees a 403, it prints "unauthorized", and resolution aborts, making it impossible to resolve the module:
```
[cats:error] Downloading https://artifactory.somedomain.com:8082/artifactory/repo/org/apache/maven/resolver/maven-resolver/1.1.0/maven-resolver-1.1.0.jar
[cats] [error] coursier.ResolutionException: 1 unauthorized
[cats] [error]     https://artifactory.somedomain.com:8082/artifactory/repo/org/apache/maven/resolver/maven-resolver/1.1.0/maven-resolver-1.1.0.jar (Artifactory Realm)
```
While it is possible to change the Artifactory setup so that a 404 is returned instead, this is not its default configuration, and the option may not even be viable for those users that need the default behavior for security reasons. Instead, Coursier should cope more gracefully with a 403 in this case, behaving in a similar manner as if a 404 were observed.

Related to https://github.com/coursier/coursier/issues/670

**Comment by alexarchambault** [comment]
I agree it might be a good idea to handle 403 [the same way as 404](https://github.com/coursier/coursier/blob/7b12da18b68731c3599d4e2ef841506a5df42bfa/cache/src/main/scala/coursier/Cache.scala#L589), when doing non authenticated requests. This code is a bit touchy though, there aren't that many non regression tests at that level for the cache…

We could also add a small docker-based test, with an artifactory launched via docker, if an image for it exists. There are already that kind of things in coursier with [Nexus repositories](https://github.com/coursier/coursier/blob/7b12da18b68731c3599d4e2ef841506a5df42bfa/scripts/launch-proxies.sh).

**Comment by alexarchambault** [comment]
Closing this, as 4xx errors should now be handled the same way wrt authentication.

If you test that with recent versions of coursier, beware of possible infinite redirection issues, that [will be fixed](https://github.com/coursier/coursier/issues/1179) in the upcoming release.
