### ISSUE TITLE
Is it possible to specify the coursier cache location from the sbt command line?

### ISSUE THREAD

**Issue by drewctaylor** [coursier/coursier#783]
The [code suggests this is possible](https://github.com/coursier/coursier/blob/master/paths/src/main/java/coursier/CoursierPaths.java#L27), but I haven't been able to make it work. I've tried

> `sbt -Dcoursier.cache=.coursier compile`

> `sbt -Dcoursier.cache=/absolute/path/to/.coursier compile`

> `sbt -Dcoursier.cache=/absolute/path/to/without/period/coursier compile`

> `sbt -Dcoursier.cache="/lets/try/quotation/marks/coursier" compile`

But the system always uses ~/.coursier instead.

Setting the coursier cache location via export (as per the README, `export COURSIER_CACHE="$(pwd)/.coursier-cache"`) works as expected. Is there a reason this doesn't?

**Comment by alexarchambault** [comment]
Things like
```
$ sbt -Dcoursier.cache="/path/to/cache"
```
seem to work for me.

**Comment by drewctaylor** [comment]
Doesn't work for me, with or without sbt-extras. I'm running off MacOS; perhaps that's the difference?

**Comment by alexarchambault** [comment]
@drewctaylor I'm on OS X too.

**Comment by michaelmoss** [comment]
Hi. I'm wondering if anyone has a definitive answer how to set the coursier cache directory? I'm trying to build docker containers with a populated coursier cache, but I'm having trouble overriding it. It seems like there might be different behavior on OS X vs Linux as well.

**Comment by alexarchambault** [comment]
There's not a [dedicated documentation page](https://github.com/coursier/coursier/blob/master/doc/docs/cache.md) about the cache. Re-open if you still run into this issue.

**Comment by tarsa** [comment]
@drewctaylor SBT actually uses different Java system property: `-Dsbt.coursier.home`. Look here https://github.com/sbt/sbt/blob/v1.3.1/main/src/main/scala/sbt/coursierint/LMCoursier.scala#L40-L44
```
  def defaultCacheLocation: File =
    sys.props.get("sbt.coursier.home") match {
      case Some(home) => new File(home).getAbsoluteFile / "cache"
      case _          => CoursierDependencyResolution.defaultCacheLocation
    }
```
`-Dcoursier.cache` somehow doesn't have any effect on SBT in my case too.

**Comment by davidmweber** [comment]
Coursier uses the COURSIER_CACHE environment variable to specify the cache. So:

`export` COURSIER_CACHE=some/dir sbt clean compile`

**Comment by polomarcus** [comment]
`COURSIER_CACHE` works perfectly, thanks @davidmweber :heart_eyes:
