### ISSUE TITLE
Feature request/advice on strategy for implementing

### ISSUE THREAD

**Issue by bmaso** [coursier/coursier#793]
I would love to have a new capability in the Bootstrap feature: the ability to pick-and-choose which artifacts are automatically bundled with the bootstrap JAR, and which would be downloaded from a public repository when the JAR is launched. Is this something the coursier bootstrap command already can do and I'm just missing it, or should I take a shot at adding this?

AFAICT, currently you can either have a _standalone_ JAR, or a _fully downloading_ JAR. With some tinkering of a coursier bootstrap .jar file I was able to create a bespoke JAR that downloaded some of its artifacts, and had others bundled with the JAR, so I know the coursier Bootstrap class can handle unpacking such a beast.

I'd like the ability in the `coursier bootstrap` command to identify some of the artifacts to be bundled with the JAR, while all others should be downloaded when the JAR is launched. The `--standalone` CLI option would be an extreme case of bundling every artifact with the JAR.

**Comment by alexarchambault** [comment]
I'm not against doing that, if anyone comes up with a not too heavyweight way of telling the `bootstrap` command what to do.

**Comment by alexarchambault** [comment]
Closing this. Feel free to send a PR implementing this.
