### ISSUE TITLE
Edge case with invalid partial downloads

### ISSUE THREAD

**Issue by rberenguel** [coursier/coursier#794]
Using coursier 1.0.1 under `sbt`.

If a partial download file (say, `.jar.part` somewhere in `v1/cache`) has invalid length (this can be longer than expected or exactly as expected), resolution fails with a 416 error return code: 

```
[error] coursier.ResolutionException: 1 download error
[error]     Caught java.io.IOException: Server returned HTTP response code: 416 for URL: [...]
```

To reproduce this, visit anywhere in your local coursier cache (`~/.coursier/cache/v1/path_to_some_jar`) and move any `file.jar` to `file.jar.part`. Run `sbt update` on any project requiring this `jar` to make it fail.

I suspect the problem is here: https://github.com/coursier/coursier/blob/834fbd598a38d4c8dccbecf47fcd986d213e1495/cache/src/main/scala/coursier/Cache.scala#L572

The logic is expecting for a 206 with a correct range in the header for a retry, but 416 (invalid range) is a valid response in this case, and should be handled separately.

I would like to help with this issue if possible, but don't know how I can get `sbt` to use a local build of coursier for this. Any tips?

**Comment by rberenguel** [comment]
PR https://github.com/coursier/coursier/pull/795 should fix it if I understood how this area works correctly

**Comment by wisechengyi** [comment]
unit tests may be a little tricky @alexarchambault may have better ideas. 
for integration tests you can put it in https://github.com/coursier/coursier/blob/master/tests/jvm/src/test/scala/coursier/test/CacheFetchTests.scala or https://github.com/coursier/coursier/blob/master/cli/src/test/scala-2.12/coursier/cli/CliFetchIntegrationTest.scala. Basically you can mimic the scenario in #795 and show it works.

**Comment by rberenguel** [comment]
Thanks for the pointers @wisechengyi that's what I needed. I'll get it tested ASAP

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/795.
