### ISSUE TITLE
Local artifact isn't being copied to coursier cache

### ISSUE THREAD

**Issue by dotordogh** [coursier/coursier#798]
Currently, if you resolve a dependency with a local artifact, the artifact will not be copied to the cache. This could be a problem if the artifact only exists temporarily, if it gets deleted, the resolve will fail if it is not in the cache.

**Comment by alexarchambault** [comment]
I confirm that things from `file://` URLs aren't copied to the cache (handled by [this method](https://github.com/coursier/coursier/blob/2747d1e55ab13ec998e1c1006a7546f03252fd17/paths/src/main/java/coursier/CachePath.java#L39)).

Maybe that could be changed… Like we could have a `local://` protocol for things that wouldn't be copied, and we could copy things from `file://` to the cache from now on (a bit like [spark-submit does](https://spark.apache.org/docs/2.3.0/submitting-applications.html#advanced-dependency-management), where things from `file://` are moved around, but those from `local://` aren't).
