### ISSUE TITLE
Shading plugin gets into deadlock while shading scalameta

### ISSUE THREAD

**Issue by pshirshov** [coursier/coursier#801]
Hi guys, 

I know it's strange though it happens. I have a multimodule project which I'm building with sbt 1.1.1

I'm trying to shade scalameta: 
```
    val scalameta = "org.scalameta" %% "scalameta" % "3.3.1" % "shaded"
```

specifying `org.scalameta` as `shadeNamespaces` entry. Though sbt hangs in 9 of 10 runs.

**Comment by alexarchambault** [comment]
@pshirshov Do you have a repository reproducing that? (to ease investigations)

**Comment by alexarchambault** [comment]
Closing for now. Please re-open with exact / reproducible commands allowing to reproduce this (and minimize the issue).
