### ISSUE TITLE
Non-optional direct dependency resolved as optional

### ISSUE THREAD

**Issue by francisdb** [coursier/coursier#802]
context: https://github.com/lihaoyi/mill/issues/185
coursier `1.0.2`

We have a private nexus repository
I try to look up the following:
```scala
val dep = Dependency(Module("my.company", "foo_2.12"), "6.1.1", optional = false)
```
But after resolution
```scala
resolution.artifacts(true).foreach{ a =>
    println(s"${a.url} optional=${a.isOptional}")
}
```
prints
```
https://nexus.company.com/repository/maven-releases/my/company/foo_2.12/6.1.1/foo_2.12-6.1.1.jar optional=true
```

I digged a bit deeper and it seems that coursier tries to do a dir listing on the maven repository, but nexus does not allow dir listings on `https://nexus.company.com/repository/maven-releases/my/company/foo_2.12/6.1.1`, you instead have to do to `https://nexus.company.com/service/rest/repository/browse/maven-releases/my/company/foo_2.12/6.1.1`
(also this listing might not be compatible with a maven central listing)

Because the listing fails, the publications for this project after resolution are empty, which in turn marks the jar dependency as optional.

Multiple solutions:
* Detect nexus and request / parse listing differently
* If listing request / parse fails make sure there is a default list of publications
* Don't mark dependencies optional when they are requested as non-optional but end up with empty publictations (why is this done?)

**Comment by alexarchambault** [comment]
@francisdb "Optional" artifacts doesn't mean that these can be safely ignored here. Users of coursier via its API *have to* try to download those. "Optional" just means that if one gets a not found error when trying to download one of them, then this artifact and its not found error can be ignored. Only not found error should be ignored. This was added late during the RC cycle while retaining binary compatiblity, so it doesn't appear clearly in the API (and all users don't handle them yet).

It was added precisely to handle private nexus repositories or nexus mirrors, that don't always list all the available artifacts.

**Comment by francisdb** [comment]
Ok, that clarifies things, are you interested in also parsing nexus listings correctly?

**Comment by alexarchambault** [comment]
I think parsing Nexus listings should actually be removed… It was added to handle POMs with defective `packaging` tags, but Nexus mirrors don't always list all the files (they typically only list the ones they have in cache). "Optional" artifacts solved the issue at the end. So Nexus listing handling is now unnecessary (it just flags some artifacts as non optional, but if users handle optionality fine, it's the same result at the end).
