### ISSUE TITLE
Interrupted downloads are not detected properly

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#804]
While downloading a file, if the connection gets interrupted, it seems that `java.net.HttpURLConnection` doesn't report an error (I'd like to come up with a reproducible test for that… - I consistently ran into that at work…). okhttp is fine on the other hand, throwing if it can't read the whole response body.

Incomplete files can end up in the cache because of that…

Enabling okhttp by default should address that (needs Java >= 7 IIRC).

**Comment by wisechengyi** [comment]
Thanks @alexarchambault. Mark as related to #780

**Comment by alexarchambault** [comment]
Now that Java 8 is required, the okhttp module could be added to the sbt plugin and the cli by default to address that (it wasn't because it needed Java >= 7).

**Comment by Atry** [comment]
Related to https://github.com/scalameta/metals/issues/647

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/coursier/pull/1273 (with a manual check of `Content-Length`).
