### ISSUE TITLE
parent pom not respected?

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#809]
```
$ resolve -t org.apache.httpcomponents:httpclient:4.2.5
  Result:
└─ org.apache.httpcomponents:httpclient:4.2.5
   ├─ commons-codec:commons-codec:1.6
   ├─ commons-logging:commons-logging:1.1.1
   └─ org.apache.httpcomponents:httpcore:4.2.4
```

https://search.maven.org/remotecontent?filepath=org/apache/httpcomponents/httpcomponents-client/4.2.5/httpcomponents-client-4.2.5.pom  `<parent>` entry points to https://search.maven.org/remotecontent?filepath=org/apache/httpcomponents/project/6/project-6.pom which has
```
<modules>
  <module>../httpcore</module>
  <module>../httpclient</module>
  <module>../httpasyncclient</module>
</modules>
```

so `org.apache.httpcomponents:httpcore` should also be 4.2.5?

**Comment by alexarchambault** [comment]
`<modules>` are ignored (I think these are only for local Maven projects). The parent POM sets the version via some dependency management, to `${httpcore.version}`, which itself evaluates to `4.2.4` (property set a bit above in the parent POM too).

**Comment by wisechengyi** [comment]
hmm are you referring to
```
<properties>
  <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
  <httpcore.version>4.2.4</httpcore.version>
...
```

then 
```
<dependency>
  <groupId>org.apache.httpcomponents</groupId>
  <artifactId>httpcore</artifactId>
  <version>${httpcore.version}</version>
</dependency>
```
in https://search.maven.org/remotecontent?filepath=org/apache/httpcomponents/httpcomponents-client/4.2.5/httpcomponents-client-4.2.5.pom?

**Comment by alexarchambault** [comment]
yep

**Comment by wisechengyi** [comment]
Thanks! false alarm then phew...

**Comment by baroquebobcat** [comment]
Thanks for the explanation!
