### ISSUE TITLE
remove scalaz from rest of the codebase

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#812]
https://github.com/coursier/coursier/pull/807#issuecomment-373023671

At least for cli, we can further reduce the binary size.

**Comment by alexarchambault** [comment]
If anyone wants to handle that (cli not depending anymore on scalaz), I won't oppose it. Same for the sbt plugins.

There's no reason to remove the scalaz-interop module though.

**Comment by alexarchambault** [comment]
Closing this, as the cli doesn't depend anymore on scalaz since https://github.com/coursier/coursier/commit/9e5e3cfa1574d06504c2411df2326ee55dbc0555. The scalaz-interop module is still there in case it can be useful, but not used from this repo.
