### ISSUE TITLE
tags/branches corresponding to Pants release

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#814]
Hi @alexarchambault,

Just wondering if you would be okay with the idea that we push tags and/or create branches corresponding to stable Pants release (https://pypi.python.org/pypi/pantsbuild.pants). Will also try to document that. 

Thanks,
Yi

**Comment by alexarchambault** [comment]
Why not… what would these tags look like?

**Comment by wisechengyi** [comment]
I am thinking `pants_<pants release tag>`, e.g. tag `pants_release_1.5.0` in coursier for pants' 1.5.0 release https://github.com/pantsbuild/pants/blob/release_1.5.0/src/python/pants/backend/jvm/tasks/coursier/coursier_subsystem.py#L39 at 3e4a65d5ee66f043c2467972bd6e29f48b570715

In case of we need to cherry pick, then we will create a branch, and tag the commit on a branch.

Thoughts?

**Comment by alexarchambault** [comment]
Ok then. They're clearly identifiable via the `pants_` prefix, so that's ok for me.

**Comment by wisechengyi** [comment]
Thanks. Pushed the first one here: https://github.com/coursier/coursier/releases/tag/pants_release_1.5.x
