### ISSUE TITLE
Force coursier to get latest artifact version

### ISSUE THREAD

**Issue by amarouni** [coursier/coursier#819]
I'm working on a use case where I have to fetch the latest version of an artifact, is there any guarantee that using :

```scala
val res = Resolution(
      Set(
        Dependency(
          Module("XXX", "YYY"), "[1.0, 100.0]"
        )
      )
    )
``` 
will always fetch the latest available version of YYY <= 100.0 ?

Is there any other way to tell coursier to fetch the latest version ?

**Comment by alexarchambault** [comment]
For Maven repositories, this is handled [around here](https://github.com/coursier/coursier/blob/c7dabdf19ad932e70c9359a3f8bd8b2ac0dbb76d/core/shared/src/main/scala/coursier/maven/MavenRepository.scala#L440-L468). If the version flagged as release is in the interval, it is picked. Else, the highest version among the available ones, in the interval, is chosen.

**Comment by amarouni** [comment]
@alexarchambault got it thanks.
