### ISSUE TITLE
API example code doesn't compile

### ISSUE THREAD

**Issue by amarouni** [coursier/coursier#820]
The API example code given in the main README.md using the following dependencies : 
```scala
libraryDependencies ++= Seq(
  "io.get-coursier" %% "coursier" % "1.0.1",
  "io.get-coursier" %% "coursier-cache" % "1.0.1"
)
```

```
import scalaz.concurrent.Task

object CoursierDriver extends App {

  override def main(args: Array[String]): Unit = {
    import coursier._

    val start = Resolution(
      Set(
        Dependency(
          Module("org.scalaz", "scalaz-core_2.11"), "7.2.3", transitive = false
        )
      )
    )

    val repositories = Seq(
      MavenRepository("https://repo1.maven.org/maven2")
    )

    val fetch = Fetch.from(repositories, Cache.fetch[Task]())
}
```

The line `Fetch.from(repositories, Cache.fetch[Task]())` doesn't compile `fetch does not take type parameters`.

Is there any up to date API example code that resolves and fetches dependencies ?

**Comment by alexarchambault** [comment]
Just realized the README is currently a bit b*rked, since the branching out `1.0` / `1.1`… The one on the [`1.0` branch](https://github.com/coursier/coursier/tree/series/1.0.x) seems fine (except the version it mentions, that should be `1.0.3`, but `1.0.1` should be ok with its examples too).

**Comment by dwijnand** [comment]
lol "borked" isn't a swear word 😆

**Comment by alexarchambault** [comment]
@dwijnand I find it cooler written this way! (I think I saw that elsewhere…)

**Comment by amarouni** [comment]
@alexarchambault Thanks got it to work with the branch doc. I'll try to do a PR to correct the master doc.
