### ISSUE TITLE
Upgrade to directories 10

### ISSUE THREAD

**Issue by soc** [coursier/coursier#821]
I fixed bugs where the paths were not correctly built on Linux if XDG environment variables were set and bugs that affected `ProjectDirectories` paths for `cacheDir`, `configDir` and `dataDir` on Windows.

I'll add CI to directories to prevent this from happening again in the future.

**Comment by soc** [comment]
CI for Linux and Windows has been added, macOS is pending.

**Comment by soc** [comment]
I improved performance on Windows, and added support for `UserDirs#downloadDir` and `UserDirs#publicDir`. Should be a smooth upgrade.

**Comment by alexarchambault** [comment]
Waiting for the few PRs that update things (https://github.com/coursier/coursier/pull/826, https://github.com/coursier/coursier/pull/824, https://github.com/coursier/coursier/pull/823) to be merged before bumping directories too.

**Comment by soc** [comment]
Thanks for the heads up, let me know if you have any questions!
