### ISSUE TITLE
Shaded distribution incompatible with Java 9: JarJar fork needs an update

### ISSUE THREAD

**Issue by retronym** [coursier/coursier#822]
We're getting a Scala community [build running with JDK9](https://github.com/scala/community-builds/issues/609) (and beyond).

One of the issues we've found is with coursier.

```
[argonaut-shapeless] [error] (coursierResolutions) java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class coursier/shaded/fastparse/core/LowestPriSequencer. Method $anonfun$Sequencer1$1(Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2; at index 39 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[argonaut-shapeless] [error] (coursierSbtClassifiersResolution) java.lang.IncompatibleClassChangeError: Inconsistent constant pool data in classfile for class coursier/shaded/fastparse/core/LowestPriSequencer. Method $anonfun$Sequencer1$1(Ljava/lang/Object;Ljava/lang/Object;)Lscala/Tuple2; at index 39 is CONSTANT_MethodRef and should be CONSTANT_InterfaceMethodRef
[argonaut-shapeless] Project loading failed: (r)etry, (q)uit, (l)ast, or (i)gnore? 
```

 I've seen this problem before elsewhere and fixed by [updating](https://github.com/playframework/play-ws/pull/176) to the latest sbt-assembly, which in turn updates JarJar from the [pantsbuild/jarjar](https://github.com/pantsbuild/jarjar/commits/master) fork, which includes fixes [from myself](https://github.com/pantsbuild/jarjar/commits?author=retronym) and [others](https://github.com/pantsbuild/jarjar/commits?author=bantonsson) for Java 9 support.

I see that you're using your own [fork of JarJar](https://github.com/coursier/jarjar) with different lineage.

**Comment by retronym** [comment]
We are able to work around this problem by using a fork of shapeless-argonaut that simply removes the coursier plugin: https://github.com/scala/community-builds/pull/700

**Comment by alexarchambault** [comment]
@retronym This issue was fixed some time ago. The error you were seeing originated from argonaut-shapeless depending on an old version of sbt-coursier (`1.0.0-RC11` in `project/project/plugins.sbt`, bumped to `1.0.3` by https://github.com/alexarchambault/argonaut-shapeless/pull/102). The 2.12 Travis CI job of argonaut-shapeless now runs (fine) on Java 9.

**Comment by retronym** [comment]
Great! Sorry for the noise.
