### ISSUE TITLE
Bad Version Resolution

### ISSUE THREAD

**Issue by darkfrog26** [coursier/coursier#827]
I'm trying to use Coursier to resolve dependencies published by SBT.  This mostly works fine, but Coursier seems to have a different algorithm for determination of version when there are conflicting versions referenced:

```
[warn]  * com.google.guava:guava:11.0.2 is selected over {12.0.1, 16.0.1}
[warn]      +- org.apache.hadoop:hadoop-yarn-api:2.6.5            (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-yarn-server-common:2.6.5  (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-hdfs:2.6.5                (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-yarn-client:2.6.5         (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-yarn-common:2.6.5         (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-yarn-server-nodemanager:2.6.5 (depends on 11.0.2)
[warn]      +- my.project:myproject_2.11:1.4.15 (depends on 11.0.2)
[warn]      +- org.apache.hadoop:hadoop-common:2.6.5              (depends on 11.0.2)
[warn]      +- my.project:myproject-core_2.11:1.4.15           (depends on 11.0.2)
[warn]      +- org.apache.curator:curator-framework:2.6.0         (depends on 16.0.1)
[warn]      +- org.apache.curator:curator-client:2.6.0            (depends on 16.0.1)
[warn]      +- org.apache.curator:curator-recipes:2.6.0           (depends on 16.0.1)
[warn]      +- org.htrace:htrace-core:3.0.4                       (depends on 12.0.1)
```

In SBT it properly resolves to use Guava 11.0.2 because I explicitly reference that version in my dependencies. However, in Coursier, it resolves to use version 16.0.1 instead.  Is there any way to force it to use the dependency defined by my project explicitly?

**Comment by alexarchambault** [comment]
@darkfrog26 This is expected. You can use [`dependencyOverrides`](https://stackoverflow.com/questions/36501352/recommended-way-to-force-a-specific-version-of-sbt-dependency/36501752#36501752) to force the version of a specific dependency.

**Comment by darkfrog26** [comment]
After adding:

`dependencyOverrides += "com.google.guava" % "guava" % "11.0.2"`

It is still resolving to 16.0.1.  I'm doing it on the main dependency.

**Comment by darkfrog26** [comment]
@alexarchambault based on what you've said, this should be working, but it's not.  I would call that a bug.
