### ISSUE TITLE
Publish an unproguarded cli standalone jar on maven

### ISSUE THREAD

**Issue by wisechengyi** [coursier/coursier#829]
Current published standalone version is proguarded https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.get-coursier%22%20AND%20a%3A%22coursier-cli_2.12%22 which is great for adhoc use, but comes with extra cost on maintenance, and sometimes it can get tricky on things using reflections.

Currently we can't fully justify the cost for tuning/maintaining the proguard config yet, hence seeking an easier solution to use a regular fat jar in additional to the proguarded one.

@alexarchambault Do you think this can be an relatively simple tweak in the sbt's publishing config?

**Comment by alexarchambault** [comment]
@wisechengyi https://github.com/coursier/coursier/pull/811 works locally, it should just be a matter of tweaking the CI…

**Comment by alexarchambault** [comment]
Closing this, as the CLI isn't proguarded anymore since https://github.com/coursier/coursier/commit/089d5520581663eed7b47dbcaadd72024716ac85. No fat jar or assembly replaced it, the CLI launcher now just downloads multiple JARs upon launch instead of one.
