### ISSUE TITLE
hadoop dependencies propagation issue

### ISSUE THREAD

**Issue by volth** [coursier/coursier#836]
```coursier resolve org.apache.hadoop:hadoop-client:2.7.4``` shows ```org.apache.hadoop:hadoop-common:2.7.4``` among the dependencies

```coursier resolve org.apache.hadoop:hadoop-common:2.7.4``` shows ```com.jcraft:jsch:0.1.54``` among the dependencies

But is ```coursier resolve org.apache.hadoop:hadoop-client:2.7.4``` does not show ```com.jcraft:jsch:0.1.54``` as a dependency

(I was using ```coursier``` version 1.0.1, not sure if it fixed in master, I see nothing relevant in the commit log since 1.0.1)

**Comment by alexarchambault** [comment]
@volth As the [POM of `org.apache.hadoop:hadoop-client:2.7.4`](https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-client/2.7.4/hadoop-client-2.7.4.pom) shows, its dependency on `org.apache.hadoop:hadoop-common:2.7.4` excludes a bunch of things, including `com.jcraft:jsch` (grep for `hadoop-common` or `jsch` in it…). So it doesn't pull all of `hadoop-common`, and it doesn't pull `com.jcraft:jsch` via it in particular…
