### ISSUE TITLE
sbt plugins jars are missing from maven central

### ISSUE THREAD

**Issue by prozz** [coursier/coursier#840]
When I try to run sbt with coursier freshly added as a plugin it cannot download it.
It indeed cannot download it when visiting maven repo manually too (try clicking 'download jar'): http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22io.get-coursier%22%20AND%20a%3A%22sbt-coursier%22

**Comment by alexarchambault** [comment]
@prozz We'd need more details here… [This setup](https://github.com/coursier/coursier#sbt-plugin) should work fine. The issue on search.maven.org should originate from the particular directory structure of sbt plugins on maven central. It's the same for example for [sbt-ensime](https://search.maven.org/#artifactdetails%7Corg.ensime%7Csbt-ensime%7C2.5.1%7Cjar).

**Comment by prozz** [comment]
this is exactly what i tried to do:
- read on webs that coursier is super fun
- took my project i work daily on
- added plugin to sbt as per setup page u mention above
- when i run sbt it failed to download coursier
- visited maven central and search for it manually
- failed to download (404 from server)

it looks like those artifacts are not uploaded correctly?

this issue may not affect most of you because of coursier being locally available in your repository.

**Comment by alexarchambault** [comment]
@prozz The plugin is published [here](http://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.10_0.13/1.0.3/) and [there](http://repo1.maven.org/maven2/io/get-coursier/sbt-coursier_2.12_1.0/1.0.3/) for sbt 0.13 and 1.0. Please ask on the gitter room if you run into more issues.
