### ISSUE TITLE
Coursier can't fetch artifact on private Nexus

### ISSUE THREAD

**Issue by denisgarci** [coursier/coursier#847]
I get the following error:
```
Caught java.net.SocketException: Connection reset (Connection reset) while downloading
```
I use sbt version 1.04 and the coursier plugin version 1.0.3. This issue doesn't show up when the plugin is disabled.
Also this error doesn't show up on CI (Jenkins).

**Comment by alexarchambault** [comment]
@denisgarci Private Nexus usually work (they do for me, and for other users according to what's discussed in other issues too…)

**Comment by alexarchambault** [comment]
Closing for now. Feel free to re-open with more details (detailed error messages, …)

**Comment by denisgarci** [comment]
It's working on the latest coursier version!
