### ISSUE TITLE
Check if calls to mkdirs succeed

### ISSUE THREAD

**Issue by alexarchambault** [coursier/coursier#857]
Most cache directories are created via `java.io.File.mkdirs()`. Not reporting if their creation failed sometimes leads to spurious errors like https://github.com/lihaoyi/Ammonite/issues/798.

**Comment by pmpfr** [comment]
From eyeballing the source, it's also perfectly possible for it to pick a directory which doesn't exist and yet not call `mkdirs()`: for example if `~/.coursier/` exists but is empty.  It seems to work fine despite not calling `mkdirs()`.

If it's important to call `mkdirs()` it should do all the time.  If it's not, it probably shouldn't do a seemingly arbitrary case.

**Comment by alexarchambault** [comment]
To be more specific: the calls to `mkdirs` here or there could be made from a new helper function, that could maybe: call `mkdirs` itself, check its return code, and check again if the directory exists (created by another process?) if `mkdirs` returned false. Maybe it could check for obvious error cases (permissions, …).

**Comment by alexarchambault** [comment]
N/A since https://github.com/coursier/coursier/pull/1186.
