### ISSUE TITLE
Coursier slowing down sbt?

### ISSUE THREAD

**Issue by Pitometsu** [coursier/coursier#863]
Without `coursier`:
```
rm -Rf ~/.{ivy2,sbt} &&  \
  time sbt "; project my-project-name; assembly"
...
[success] Total time: 159 s, completed May 29, 2018 5:27:11 PM

real	4m59,740s
user	2m20,172s
sys	0m6,888s
```

With only `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")` in `~/.sbt/1.0/plugins/build.sbt`:

```
rm -Rf ~/.{ivy2,sbt} &&  \
  time sbt "; project my-project-name; assembly"
...
[success] Total time: 353 s, completed May 29, 2018 5:37:28 PM

real	7m39,720s
user	11m8,399s
sys	0m7,151s
```

Why so? Shouldn't it speedup downloading? Did I get wrong the `coursier`'s purpose or setup it in wrong way?

**Comment by alexarchambault** [comment]
I'd expect the first startup of sbt to take longer when sbt-coursier is enabled, as sbt has to download sbt-coursier itself (with the default resolution mechanism of sbt, as sbt-coursier isn't loaded yet). To check that, maybe don't run an `assembly` task as you're doing… (run the `about` command of sbt instead)

Then, if after the first startup, `assembly` itself is slower, no idea, I don't use sbt-assembly much. You may get more help by pushing an actual self-contained repro…

**Comment by jvican** [comment]
@Pitometsu It may have to do with the fact that you're not caching the `.coursier` directory?

**Comment by Pitometsu** [comment]
What I need for that? I just put `addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")` into `build.sbt`. Is it correct way to setup coursier?

**Comment by jvican** [comment]
Yes, but if you try the slowdown in CI just make sure you cache `.coursier` too. Not sure I can help further. What I can tell you is that coursier **does** speed up my builds like crazy :smile:
