### ISSUE TITLE
Readme instructions for API are out of date and don't work as at 1.0.3

### ISSUE THREAD

**Issue by benhutchison** [coursier/coursier#881]
I tried to follow the [quickstart API](https://github.com/coursier/coursier#api) instructions but discovered they seems to be from an earlier version of Coursier, as they mention classes that (eg `cousier.util.Task`) that don't exist as at v `1.0.3`

**Comment by alexarchambault** [comment]
This should be fixed with the [new website](https://coursier.github.io/coursier/1.1.0-SNAPSHOT/docs/intro), using the latest milestone (`1.1.0-M8`) instead of `1.1.0-SNAPSHOT` in the docs.
