### ISSUE TITLE
webjars ResolutionException

### ISSUE THREAD

**Issue by zy4** [coursier/coursier#885]
`[error] coursier.ResolutionException: Conflict(s) in dependency resolution:
[error]   org.webjars.npm:jquery:3.0.0-rc1:default(compile)
[error] org.webjars.npm:jquery:3.3.1:default(compile)
`
Seems like I have these transitive dependencies in my webjars. Can I get around this somehow?

**Comment by alexarchambault** [comment]
Needs more details (reproduction, as CLI commands or an sbt project, if possible).
