### ISSUE TITLE
coursier-cli_2.11-1.0.0-RC1 is not proxy aware?

### ISSUE THREAD

**Issue by cequencer** [coursier/coursier#888]
I am behind a firewall that requires proxy for any HTTP/HTTPS connections.  
I have all the necessary Unix environment variables for the proxy settings.  
In this environment I managed to download "coursier-cli" via this command as a first time user of coursier-cli:

`curl --proxy <proxy.server.com:port> -s -L -o coursier https://github.com/coursier/coursier/raw/v1.0.0-RC1/coursier`

After obtaining the executable, coursier-cli, it times out when I either tries to 'launch' or 'bootstrap' as follows:

```
$ ./coursier launch --help
Error while downloading https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-RC1/coursier-cli_2.11-1.0.0-RC1-standalone.jar: Connecti
on timed out (Connection timed out), ignoring it

$ ./coursier bootstrap --help
Error while downloading https://oss.sonatype.org/content/repositories/releases/io/get-coursier/coursier-cli_2.11/1.0.0-RC1/coursier-cli_2.11-1.0.0-RC1-standalone.jar: Connecti
on timed out (Connection timed out), ignoring it
```

I want to a different machine that is not behind a firewall without any proxy, the coursier-cli is able to download all the dependencies and generate the --help information.  I scanned through this --help information and none of them provides any type of proxy configuration acceptance.  Is there a plan to support proxy?  

According to this project's README.md file, coursier-cli supports "passing proxy as an additional argument to the artifact being launched."  However, coursier-cli is not able to download the it's own dependencies jars into it's startup cache to get to that point.  

Maybe the documentation to support proxy is not documented yet?  

I am already seeing similar issues being posted in the wild without good resolution.  For example, 

1. StackOverflow question [here](https://stackoverflow.com/questions/44438610/jupyter-scala-install-behind-a-proxy)
1. Github coursier issue #425 

Thanks to the community's support in making this project possible.

**Comment by cequencer** [comment]
Another idea that can help people behind firewall to use coursier is the ability to define a custom Maven settings.xml file to define local repository that is already mirroring the public Nexus repositories or proxy settings to help coursier source the artifacts in this firewall environments for bootstrap and runtime situations.  If this idea should be extracted and become it's own issue, feel free to do so.

**Comment by alexarchambault** [comment]
I'm in the midst of adding a page about proxies on the coursier website (https://github.com/coursier/coursier/pull/970), it can already be seen at https://github.com/coursier/coursier/blob/94c30a320370da983e224067054b0bbaf2fcf2a5/doc/docs/other-proxy.md.

**Comment by alexarchambault** [comment]
The website now has [a page](https://get-coursier.io/docs/other-proxy) about proxies.
