### ISSUE TITLE
Resolution fails with an XML parsing error on a HTML redirect page

### ISSUE THREAD

**Issue by przemek-pokrywka** [coursier/coursier#889]
Whenever I try to fetch some artifact from my nexus using:
`fetch --checksum none --no-default --repository http://nexus.redacted.com com.redacted:redacted_2.11:1.0.0` the nexus serves a HTTP redirect with the following HTML page:
```html
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.12.1</center>
</body>
</html>
```
which confuses coursier so that it fails with:
```
Error:
  com.redacted:redacted_2.11:1.0.0
    No fallback URL found
    org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 3; The element type "hr" must be terminated by the matching end-tag "</hr>". (The element type "hr" must be terminated by the matching end-tag "</hr>".)
```

What would be needed for coursier to support redirects?

**Comment by przemek-pokrywka** [comment]
Update: I was able to solve the issue by specifying the correct repository address (with https prefix and with a proper path - https://nexus.redacted.com/repository/maven).

So what's left is possibility to have a more helpful error message in case one misspecifies the repo address (or when the repo breaks and serves HTML instead).

I'd propose to print out the complete URL along with the HTML received.

**Comment by alexarchambault** [comment]
I think some people already run into http -> https redirect issues, that should not have been addressed already… It seems you're running into another case of that (with the redirection to https not happenning, and the xml parser failing on the redirect page).

**Comment by alexarchambault** [comment]
Should be fixed by https://github.com/coursier/coursier/pull/976.

**Comment by lefou** [comment]
The solution in #976 is not quite fixing the parsing error when the HTML document is not proper XML. Instead it fixed the concrete error case, in which a redirection was not possible.

To date, coursier can't handle repository pages, which don't contain proper XHTML, e.g. no closing tags.
