### ISSUE TITLE
Stable library API for basic stuff

### ISSUE THREAD

**Issue by olafurpg** [coursier/coursier#892]
I'm using coursier as a library in sbt-scalafix and I would love it if coursier exposed a stable library API with long-term binary compatibility guarantees. So far, I've been copy-pasting the examples from the readme https://github.com/coursier/coursier#api-1. This has worked great so far but with the upcoming v1.1 I noticed the APIs have changed. To work around this problem I created the project coursier-small https://github.com/olafurpg/coursier-small that exposes coursier functionality through a small library API. The coursier-small library is designed so that it's possible to evolve the API without every breaking binary compatibility

- no case classes
- no default parameter values
- no public constructors for classes that are expected to evolve

Writing in this style is cumbersome and requires a decent amount of boilerplate, see https://github.com/olafurpg/coursier-small/blob/80245ef077d7ad7757ca449d793484ff196f1576/small/src/main/scala/com/geirsson/coursiersmall/Settings.scala The same pattern is used in the Scala.js project https://github.com/scala-js/scala-js/blob/bad76528021ee7489171e53fc36b4dff5a6b04a4/linker/shared/src/main/scala/org/scalajs/linker/backend/emitter/InternalOptions.scala The benefit however is that it's possible to remove, rename and add new fields without breaking existing clients.

**Comment by olafurpg** [comment]
I think it would be great if this library API exposed the same functionality as the cli

- `fetch(Settings): List[Path]`
- `bootstrap(Settings): Path`
- `launch(Settings): List[Error]`

It would be nice if `Settings` supported some slightly more advanced features like

- ttl for SNAPSHOT
- custom repositories (maybe with authentication too)
- custom cache location

but to begin with I think all you need is what coursier-small exposes

- dependencies
- repositories
- `java.util.Writer`, maybe even something slightly higher level like a custom logger for diagnostics. In sbt-scalafix I silence the "Downloading [...] jar.pom" logs since they appear even when artifacts are cached https://github.com/scalacenter/sbt-scalafix/blob/077c7bdfdd05b56dee4a19dc80a50e3f640ada65/src/main/scala/scalafix/sbt/ScalafixPlugin.scala#L365-L373

**Comment by alexarchambault** [comment]
Fixed by https://github.com/coursier/interface.
