### ISSUE TITLE
Error resolving dependencies with odd suffix "%3Aproperties" in message

### ISSUE THREAD

**Issue by kaesler** [coursier/coursier#900]
I have a project which fails to build with Coursier enabled. If I disable Coursier it builds ok.

The Coursier version is 1.0.3.

The suffix in that error message is the URL-encoded form of ":properties". Maybe this is a clue.

I have not been able yet to boil this down to an easily reproducible case, as it involved our in-house Artifactory repository.

Here is the failure message when updating in a Play project:

```
> update
[trace] Stack trace suppressed: run 'last play/*:update' for the full output.
[error] (play/*:update) coursier.ResolutionException: 1 not found
[error]     https://our-inhouse-artifactory-repo/mdrm-maven/javax/inject/javax.inject/1/javax.inject-1.jar%3Aproperties
[error] Total time: 3 s, completed Sep 19, 2018 8:49:20 AM
```

It seems to fail in this way even if I have the java.inject.jar in my Ivy cache and in that case does not appear to do any network I/O.

**Comment by pshirshov** [comment]
Related: #924

**Comment by alexarchambault** [comment]
@kaesler A repro (even one spawning artifactory or other though docker) would be helpful here.

**Comment by alexarchambault** [comment]
Closing this. Re-open if you have some kind of repro (running a docker-based repository for example).
