### ISSUE TITLE
Fails on pom packages

### ISSUE THREAD

**Issue by aherrmann** [coursier/coursier#923]
The Coursier cli utility fails on pom packages.

For example, `launch`, `fetch`, and `resolve` all fail on `org.monodb:casbah_2.12.0-RC1:3.1.1`:

```
$ coursier launch org.monodb:casbah_2.12.0-RC1:3.1.1
$ coursier fetch org.monodb:casbah_2.12.0-RC1:3.1.1
$ coursier resolve org.monodb:casbah_2.12.0-RC1:3.1.1
Error:
  org.monodb:casbah_2.12.0-RC1:3.1.1
    not found: /home/me/.ivy2/local/org.monodb/casbah_2.12.0-RC1/3.1.1/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/org/monodb/casbah_2.12.0-RC1/3.1.1/casbah_2.12.0-RC1-3.1.1.pom
```

This in turn seems to cause `bazel-deps` to fail to resolve dependencies when pom packages are among the direct or transitive dependencies.

See https://github.com/johnynek/bazel-deps/issues/208

**Comment by alexarchambault** [comment]
All 3 commands work fine for me if I fix the typo `org.monodb` -> `org.mongodb`.

**Comment by aherrmann** [comment]
Oh, sorry, I didn't notice the typo. Indeed, in that case they all succeed for me as well.
