### ISSUE TITLE
new test failures in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [coursier/coursier#926]
coursier was green as of 13d301da41cfabf7ffa03b3eaee380ecead3da18 at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3591/

but then since more recent commits there are failures at e.g. https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/3597/consoleFull

```
[coursier] [error] Failed tests:
[coursier] [error] 	coursier.test.CacheFetchTests
[coursier] [error] 	coursier.test.ChecksumTests
[coursier] [error] 	coursier.test.MavenTests
[coursier] [error] 	coursier.test.IvyTests
```

@alexarchambault any idea what this is about...?

**Comment by alexarchambault** [comment]
@SethTisue That must be because these tests rely on some data that were moved to a new git submodule. https://github.com/coursier/coursier/pull/927 should fix that.

**Comment by SethTisue** [comment]
yup, good now
