### ISSUE TITLE
Document cache location rules and overrides

### ISSUE THREAD

**Issue by pmpfr** [coursier/coursier#949]
Per the source code, the rules are quite complicated, but the (deprecated) docs suggest it is a simple matter of `~/.coursier/cache` unless overridden.

Eyeballing the source says there are 4 possibilities:
1/ wherever `$COURSIER_CACHE` says
2/ wherever `-Dcoursier.cache=...` says
3/ a platform specific place like `~/.cache/coursier` or `~/Library/Caches/coursier` or a Windows place I don't understand
4/ `~/.coursier/cache`

An added complication is when considering 3/ and 4/ the choice depends on whether a directory already exists.

**Comment by pmpfr** [comment]
Related issue: 
https://github.com/coursier/coursier/issues/783

**Comment by alexarchambault** [comment]
Just updated the [doc page about the cache](https://github.com/coursier/coursier/commit/862c977a9cfc59dc84743ac05863a454ed199860) with more details, closing this.

**Comment by pmpfr** [comment]
Great to have it written out in such detail - and with justification!
