### ISSUE TITLE
coursier breaks on usages of ${packaging.type}

### ISSUE THREAD

**Issue by vn971** [coursier/coursier#956]
Example of how it looks in the console:

```log
[error]     Caught java.io.IOException: Server returned HTTP response code: 400 for URL: MY_PRIVATE_REPO/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type} (Server returned HTTP response code: 400 for URL: MY_PRIVATE_REPO/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}) while downloading MY_PRIVATE_REPO/javax/ws/rs/javax.ws.rs-api/2.1/javax.ws.rs-api-2.1.${packaging.type}
[error] (update) coursier.ResolutionException: 1 download error
```

As clearly seen, coursier tries to actually use the "${packaging.type}" text in URL. I must acknowledge that the problem is indeed very ugly. It's present in sbt as well, though the following work-around works there: https://github.com/sbt/sbt/issues/3618#issuecomment-334896668
With coursier, it doesn't, at least in version 1.0.3.

Thoughts? Maybe coursier should resolve the ${} thing to a variable (sounds like a dangerous approach though). Maybe it should allow ${packaging.type} specifically, maybe falling back to "jar" as default value? The latter would be ideal of course, at least to users who do not fully understand wtf that is, like me. Thoughts?

**Comment by alexarchambault** [comment]
@vn971 Do you have a small reproduction? The examples of https://github.com/sbt/sbt/issues/3618 seems fine with sbt-coursier 1.1.0-M7.

**Comment by vn971** [comment]
@alexarchambault I'll look into it. Currently at work, but I'll try to look from home.

**Comment by alexarchambault** [comment]
Closing for now, re-open if you have a repro or consistently run into that with the latest version of coursier.

**Comment by alexmnyc** [comment]
I am getting the same issue

```
coursier.lmcoursier.ResolutionException: 1 download error
[error]     Caught java.io.IOException: Server returned HTTP response code: 400 for URL: https://artifactory/artifactory/libs-snapshot/org/reflections/reflections/0.9.11/reflections-0.9.11.${packaging.type} (Server returned HTTP response code: 400 for URL: https://artifactory/artifactory/libs-snapshot/org/reflections/reflections/0.9.11/reflections-0.9.11.${packaging.type}) while downloading https://artifactory/artifactory/libs-snapshot/org/reflections/reflections/0.9.11/reflections-0.9.11.${packaging.type}
```

using 1.1.0-M9
