### ISSUE TITLE
sbt: how to lookup the credential when a repo redirects?

### ISSUE THREAD

**Issue by raboof** [coursier/coursier#963]
When a repository is specified as `repo.foo.com`, but `repo.foo.com` redirects to `dl.bintray.com`, ivy looks for the credential for `host = dl.bintray.com` while e.g. coursier works with the credential for `host = repo.foo.com`.

It looks like this was a safety choice at the ivy/httpclient side, to avoid accidentally leaking credentials to the wrong server: it is the standard behavior of the [HttpClient](http://hc.apache.org/httpclient-3.x/userguide.html) APIs (https://github.com/sbt/ivy/blob/2.3.x-sbt/src/java/org/apache/ivy/util/url/HttpClientHandler.java#L303, also when used via `setCredentials` with an `AuthScope`).

Unfortunately, it looks like the connection returned by [`url.openConnection`](https://github.com/coursier/coursier/blob/84727d8883007cbd3abb25a3707841c5b4391e26/modules/cache/jvm/src/main/scala/coursier/Cache.scala#L290) does follow redirects, but doesn't provide access to the redirected hostname.

How could we make this consistent?

**Comment by raboof** [comment]
Sbt/ivy mirror issue at https://github.com/sbt/ivy/issues/30

**Comment by 2m** [comment]
Note that coursier looks up credentials by a resolver name: https://github.com/coursier/coursier/issues/358#issuecomment-259095880

**Comment by raboof** [comment]
Ah, indeed I was referring to picking up the SBT credentials via `coursierUseSbtCredentials` (which seems enabled by default and appeared to work fine for me, except that it expected the other domain name compared to ivy)

**Comment by mdedetrich** [comment]
I am getting this issue when using coursier combined with sbt-cinnammon and there doesn't seem to be a workaround for it apart from  temporarily disabling coursier to just let ivy fetch the credentials first.
