### ISSUE TITLE
shading plugin doesn't support scalajs

### ISSUE THREAD

**Issue by pshirshov** [coursier/coursier#964]

**Comment by alexarchambault** [comment]
Not sure what would be needed to support that… The plugin doesn't already support scala annotations (so that public classes referencing shaded ones can't be used in downstream dependencies…). I guess this might require adjusting Scala.js IR too…

**Comment by alexarchambault** [comment]
Closing this as I don't really intent to work on that. Feel free to discuss that further here, or to send a PR adding support for that.
