### ISSUE TITLE
class coursier.cli.Coursier not found

### ISSUE THREAD

**Issue by julienrf** [coursier/coursier#988]
I followed the installation instructions given [in the former readme](https://github.com/coursier/coursier/blob/master/doc/FORMER-README.md#command-line) and I get the following result:

~~~
$ ./coursier --help      
Error: class coursier.cli.Coursier not found
~~~

**Comment by alexarchambault** [comment]
The following works fine for me
```
$ curl -L -o coursier https://git.io/vgvpD && chmod +x coursier && ./coursier --help
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
…
Coursier 1.1.0-M9
Usage: coursier [options] [command] [command-options]

Available commands: bootstrap, fetch, launch, resolve, spark-submit

Type  coursier command --help  for help on an individual command
```

What do
```bash
$ ls -l coursier
$ unzip -l coursier
```
say on your machine?

**Comment by julienrf** [comment]
I tried the last release and the problem didn’t show up. I’m closing the issue.

**Comment by alexarchambault** [comment]
https://github.com/coursier/coursier/pull/1039 should have a proper fix for it (if the underlying issues is similar to https://github.com/coursier/coursier/issues/804, as it seems to be).
