### ISSUE TITLE
Invalid URL on windows when downloading scaladex

### ISSUE THREAD

**Issue by jctof** [coursier/coursier#989]
I have been trying to install almond using coursier on window. Below is the error I get when launch the script. It looks like the user is invalid there is a spurious ( after the q= command.
I will checkout the Helper.scala class in coursier to see if I can figure something out

`Downloading https://index.scala-lang.org/api/search?q=(&target=JVM&scalaVersion=2.12.7
Error getting scaladex infos:
  download error: Caught java.io.IOException: Server returned HTTP response code: 422 for URL: https://index.scala-lang.org/api/search?q=(&target=JVM&scalaVersion=2.12.7 (Server returned HTTP response code: 422 for URL: https://index.scala-lang.org/api/search?q=(&target=JVM&scalaVersion=2.12.7) while downloading https://index.scala-lang.org/api/search?q=(&target=JVM&scalaVersion=2.12.7
'-r' is not recognized as an internal or external command,
operable program or batch file.
'-i' is not recognized as an internal or external command,
operable program or batch file.
'--sources' is not recognized as an internal or external command,
operable program or batch file.
'-o' is not recognized as an internal or external command,
operable program or batch file.
Press any key to continue . . .`

run.bat

`@echo off
rem installing almond. Coursier.bat is a prerequisit
rem Set all variables

SET ERROR_CODE=0
SET SCALA_VERSION=2.12.8 
SET ALMOND_VERSION=0.2.0
SET USER_CMD=user:sh.almond:scala-kernel-api_%SCALA_VERSION%:%ALMOND_VERSION%
SET ALMD_CMD=sh.almond:scala-kernel_%SCALA_VERSION%:%ALMOND_VERSION%

CALL coursier.bat bootstrap (
	-r jitpack 
	-i user -I %USER_CMD% %ALMD_CMD% 
	--sources --default=true 
	-o almond
)

PAUSE`

**Comment by alexarchambault** [comment]
Closing this, as one should now get a slightly clearer error when passing invalid dependencies on the command-line, like
```
$ coursier fetch ''
Cannot find app  in channels io.get-coursier:apps
```
