### ISSUE TITLE
Please provide an option to share artifacts between different repo

### ISSUE THREAD

**Issue by zhengcan** [coursier/coursier#993]
Compare maven/ivy/gradle, coursier will store artifacts in different folder for each repo.
For example, coursier will use `CACHE_PATH/https/repo1.maven.org/maven2/` and `CACHE_PATH/https/jcenter.bintray.com/` in same time.
This behavior will cause the same artifacts to be stored several times if we switch repo proxy frequantly. It really waste time and disk space.

I wish coursier could provide an option to disable this feature.
`CACHE_PATH/shared` maybe a good choice for default cache folder.

**Comment by alexarchambault** [comment]
Closing this as I don't intend to fix / allow that in the short term.

Note that adding the two repositories in the same resolution will make coursier pick the one that already has the metadata in cache, limiting duplication in the cache.
